### ISSUE TITLE
Download-only switch

### ISSUE THREAD

**Issue by jelabarre59** [skilion/onedrive#100]
Would like to see a switch which does only a download sync from OneDrive.  Essentially I'm looking at using this to create a local backup/archive of whatever is on the OneDrive site, rather than a 2-way sync (I'm looking at deleting local files that are no longer at the server end, although if you're adding this functionality, you might as well make switches to keep or delete local files)

**Comment by steima** [comment]
I am considering to use my oneDrive account also for static files that are served from my webserver. Technically I can already use the current codebase. In general I would prefer if my Linux box would have download-only access. Just for the peace of mind.

**Comment by skilion** [comment]
Added in 764975e2247eae9a7b4b6ea13de21584bfa3beb1
