### ISSUE TITLE
High cpu Load

### ISSUE THREAD

**Issue by onichan88** [skilion/onedrive#101]
Hello, I like your onedrive client for linux and I want to use it for a long time.
The problem I have is when the daemon or onedrive -m is loaded and is in stand by (waiting for changes in the files) one of the two cpus is stuck at 100% load. If I stop the daemon or the onedrive -m, it lows to almost 0%.

I can put you any logs you demand, but you must tell me wich logs you want.

Thanks for all

**Comment by onichan88** [comment]
I was on lubuntu 16.04. Changed to manjaro linux and all OK

**Comment by ChrisLane** [comment]
I've also been having this problem. Removed onedrive because of it.

**Comment by onichan88** [comment]
Hello, I was testing more time with this client and I having the same problem with cpu at 100% in standby, with manjaro linux...

**Comment by onichan88** [comment]
@ChrisLane have you tried another client of onedrive with success?

**Comment by ChrisLane** [comment]
Not yet.

**Comment by onichan88** [comment]
Toay I tried to launch onedrive -m -v, and I was looking that onedrive is looking for changes ok files everyte, and it stucks the cpu at 100%.

Is there any way that onedrive waits to some program that notifies the changes? Or it must check all the time?

**Comment by mkutyba** [comment]
I have the same. 100% CPU load on 1 core. Ubuntu 16.04.

**Comment by skilion** [comment]
Not enough info for debugging

**Comment by yosider** [comment]
For now, I edited src/main.d line 158:
```d
    immutable auto checkInterval = dur!"seconds"(45);
```
to
```d
    // update at 30-min interval   
    immutable auto checkInterval = dur!"seconds"(1800);
```
and reinstalled it.
I don't use OneDrive so often :)

**Comment by agungl** [comment]
Any chance to make that value configurable at startup by an optional parameter?

I've got a lot of data in one drive and it takes a while for a roundtrip to check for changes on a HDD. Increasing the value in the source file and recompiling helped to lower the CPU load. 
But a parameter would make it much easier. And think of a Docker image where you could set an ENV variable and use that one a startup, instead of providing an image with a fixed build in value.

**Comment by abraunegg** [comment]
@agungl 
Your suggestion was already implemented many months ago in my fork of this client as a 'config' option:

>monitor_interval
>Example: monitor_interval = "300"
>The monitor interval is defined as the wait time 'between' sync's when running in monitor mode. By default without configuration, the monitor_interval is set to 45 seconds. Setting this value to 300 will run the sync process every 5 minutes.

Also the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by RAZORXKHARA33** [comment]
@abraunegg I have also switched to your fork and have noticed an improvement, but am still getting spikes (just not quite as severe). Is there a way to limit CPU usage for the program?

**Comment by abraunegg** [comment]
Please post questions and issues with my fork here: https://github.com/abraunegg/onedrive
