### ISSUE TITLE
can't sync files with filename has space and special characters

### ISSUE THREAD

**Issue by haowo** [skilion/onedrive#102]
**Failed case：**
onedrive --resync
Deleting the saved status ...
Uploading: ./UW/MATH 103/ Natural and Social Sciences-Pearson (2014).pdf
HTTP request returned status code 400 (Bad Request)
Uploading: ./UW/MATH 103/ Natural and Social Sciences-Pearson (2014).pdf
HTTP request returned status code 400 (Bad Request)
Uploading: ./UW/MATH 103/ Natural and Social Sciences-Pearson (2014).pdf
sync.SyncException@src/sync.d(350): HTTP request returned status code 400 (Bad Request)
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59e253]
??:? void main.performSync(sync.SyncEngine) [0x58c59e]
??:? _Dmain [0x58bdce]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a966e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a95b8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a962a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a95b8]
??:? _d_run_main [0x5a9529]
??:? main [0x58f5d5]
??:? __libc_start_main [0x4925182f]
onedrive.OneDriveException@src/onedrive.d(348): HTTP request returned status code 400 (Bad Request)
??:? std.json.JSONValue onedrive.OneDriveApi.uploadFragment(const(char)[], immutable(char)[], long, long, long) [0x592ee1]
??:? std.json.JSONValue upload.UploadSession.upload() [0x5a2d19]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x5a0b10]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5a026f]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5a00a8]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5a00a8]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5a00a8]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59e155]
??:? void main.performSync(sync.SyncEngine) [0x58c59e]
??:? _Dmain [0x58bdce]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a966e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a95b8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a962a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a95b8]
??:? _d_run_main [0x5a9529]
??:? main [0x58f5d5]
??:? __libc_start_main [0x4925182f]
段错误 (核心已转储)

**successful case：**
onedrive --resync
Deleting the saved status ...
Uploading: ./UW/MATH 103/Natural_and_Social Sciences_Pearson_2014.pdf
Creating remote directory: ./UW/CS100
Uploading: ./UW/CS100/Assignment 2 Part B.xlsx

**Comment by JunpeiAnzai** [comment]
I could reproduce this issue too.

``
$ ./onedrive -m -v
$ touch ~/OneDrive/" Natural and Social Sciences-Pearson (2014).pdf"
``

I think this problem caused by leading white space "[WHITE SPACE]Natural..."
