### ISSUE TITLE
Crash due to character - commas

### ISSUE THREAD

**Issue by h0wdyd3wdy** [skilion/onedrive#103]
std.json.JSONException@std/json.d(1203): Unexpected character '<'. (Line 1:1)

This happens when you have commas in filenames.  Once you remove them, the error goes away.

**Comment by h0wdyd3wdy** [comment]
Again, crashing with a different file.

BIA Egypt, religion (Christian), mixed motives -  need not prove
 exact motive, Remand  (2012).pdf
std.json.JSONException@std/json.d(1203): Unexpected character '<'. (Line 1:1)

**Comment by JunpeiAnzai** [comment]
hi.
Could you tell me complete filenames?
and when did this error occur?(when upload from local or when download)
I guess there is composite causes(not only commas issue).

**Comment by skilion** [comment]
Files with commas are uploading & downloading fine in my tests
