### ISSUE TITLE
Consider moving compiler to GDC

### ISSUE THREAD

**Issue by codepoet80** [skilion/onedrive#106]
DMD's cross platform support is not great. Would like to use this on Raspberry Pi, but DMD doesn't have an ARM distro. Will try making from source with GDC, but would be great to see you move there officially for more platform support.

http://stackoverflow.com/questions/6767065/dmd-vs-gdc-vs-ldc
http://dlang.org/download.html

**Comment by tronium** [comment]
I have a fork that can be compiled using gdc on arm. You can try this and let me know whether this works for you:
https://github.com/tronium/onedrive/commit/703c53b700500d46e73a9f00aae80ed438508e2f

**Comment by znmeb** [comment]
I'm on Fedora - they have a whole "D Development Tools and Libraries" package group you can install. It's using LDC (llvm-based D compiler). Is that available on Debian?

http://wiki.dlang.org/LDC

I'm going to attempt to build this on my Fedora box later in the week ... if it works, do you want a pull request?

**Comment by mittus** [comment]
root@local:/home/pi/onedrive# make
gdc -frelease -fno-bounds-check -o onedrive src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d patch/etc_c_curl.d patch/std_net_curl.d -lcurl -lsqlite3 -ldl
patch/std_net_curl.d:176: error: module cstring is in file 'std/internal/cstring.d' which cannot be read
import path[0] = /usr/include/d/4.9/arm-linux-gnueabihf
import path[1] = /usr/include/d/4.9
Makefile:35: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1

**Comment by norbusan** [comment]
I am facing the same problems. I am maintaining onedrive in Debian, and the latest git state is not compilable with ldc (version 1.1.0), nor with gdc (version 6.2.1), so I cannot update onedrive anymore.

It would be great if some open compiler would be supported.

Thanks a lot

Norbert

**Comment by norbusan** [comment]
I got onedrive to compile with ldmd2 (ldc) by applying the following patch:
`````
--- onedrive.git.orig/src/onedrive.d
+++ onedrive.git/src/onedrive.d
@@ -37,7 +37,7 @@
        {
                this.httpStatusCode = httpStatusCode;
                this.error = error;
-               string msg = format("HTTP request returned status code %d (%s)\n%s", httpStatusCode, reason, toJSON(error, true));
+               string msg = format("HTTP request returned status code %d (%s)\n%s", httpStatusCode, reason, toJSON(&error, true));
                super(msg, file, line, next);
        }
 }
`````
No idea if this creates a lot of problems, but at least it compiles and works on my side.

**Comment by skilion** [comment]
The reference compiler is DMD however as of 300b07df3b6e71f1b15751724c17b5e84fa53667 you can specify a custom compiler via the DC variable.

**Comment by abraunegg** [comment]
Whilst using the reference compiler (http://downloads.dlang.org/releases/2.x/2.078.3/dmd.2.078.3.linux.tar.xz) and the latest git master I always run into the following compile issue:

```src/onedrive.d(37): Error: function std.json.toJSON (const(JSONValue*) root, const(bool) pretty = false, const(JSONOptions) options = cast(JSONOptions)0) is not callable using argument types (const(JSONValue), bool)```

The 'fix' / 'workaround' here for me is as per @norbusan suggested change / patch.
