### ISSUE TITLE
Crash - Removing directory while it is being uploaded

### ISSUE THREAD

**Issue by clauderobi** [skilion/onedrive#107]
onedrive was upload a big directory to the cloud and I wanted it to stop so I deleted the directory. This caused onedrive to core dump. Here is the screen output

Creating directory: ./test/Tools/vnidAnalyzer-6.6.0-0110/jre1.7.0_17/lib/servicetag
## sync.SyncException@src/sync.d(104): ./test/Tools/vnidAnalyzer-6.6.0-0110/jre1.7.0_17/lib/servicetag: No such file or directory

??:? void sync.SyncEngine.applyDifferences() [0x59c3b7]
??:? void main.performSync(sync.SyncEngine) [0x58c5a3]
??:? _Dmain [0x58bde6]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a968e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a95d8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5a964a]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5a95d8]
??:? _d_run_main [0x5a9549]
??:? main [0x58f5ed]
??:? __libc_start_main [0xa6e95f44]
## std.file.FileException@/usr/include/dmd/phobos/std/file.d(2060): ./test/Tools/vnidAnalyzer-6.6.0-0110/jre1.7.0_17/lib/servicetag: No such file or directory

??:? @trusted bool std.file.cenforce!(bool).cenforce(bool, const(char)[], const(char)_, immutable(char)[], ulong) [0x5757de]
??:? @safe void std.file.mkdir!(immutable(char)[]).mkdir(immutable(char)[]) [0x57564c]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x59d758]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x59d0a8]
??:? void sync.SyncEngine.applyDifferences() [0x59c228]
??:? void main.performSync(sync.SyncEngine) [0x58c5a3]
??:? _Dmain [0x58bde6]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a968e]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5a95d8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a964a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a95d8]
??:? _d_run_main [0x5a9549]
??:? main [0x58f5ed]
??:? __libc_start_main [0xa6e95f44]
Segmentation fault (core dumped)

**Comment by clauderobi** [comment]
Forgot to indicate that I am using commit eb8d0fe

**Comment by thomasfedb** [comment]
@clauderobi does this issue occur with the latest codebase? If not, could you close this issue please.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
