### ISSUE TITLE
2 x Linux + Cloud - Deleted directories get redownloaded or reuploaded

### ISSUE THREAD

**Issue by clauderobi** [skilion/onedrive#108]
I have a setup with 2 Linux running each onedrive + (of course) the MS Cloud server.

If I delete a directory in 1 Linux, onedrive will remove it form the Cloud. But eventually the 2nd Linux will upload its own copy of the directory (and its subtree) instead of deleting it locally. Eventually, the 1st Linux download the directory tree, ending with the same content as before, including files that were present.

If I delete the directory directly in the Cloud via the Web page, eventually one of the 2 Linux will recreate it. 

Working with individual files works Ok.

**Comment by clauderobi** [comment]
Forgot to indicate that I am using commit eb8d0fe

**Comment by xupefei** [comment]
I can confirm this issue. To reproduce it you only need one client:

1) Run `onedrive -m` on your Linux PC.
2) Go to [https://onedrive.live.com/](https://onedrive.live.com/) and delete any file.
3) Wait for several seconds, you will find the `onedrive` on your Linux PC pops out `Uploading xxxx.xxx` (name of the deleted file)

Then the deleted file is re-uploaded by this client.

**Comment by tronium** [comment]
I have solved this here: https://github.com/skilion/onedrive/pull/119

**Comment by skilion** [comment]
Fixed in 3a10f0f4b587af1de29c3d3124788caca842fde7
