### ISSUE TITLE
Does not sync OneNote files

### ISSUE THREAD

**Issue by Nightshaxx** [skilion/onedrive#110]
I installed this to sync my OneNote files, since MS office 2013 doesn't work in WINE and OneNote 2010 doesn't have auto-sync to OneDrive features. The OneDrive client syncs the folder, but doesn't sync the books themselves. 

Manjaro 16.08
**Terminal output:** _(Note, my notebooks are saved in the documents folder. The parts where it says something is "neither a file or directory" is were it is skipping over my onenote files.)_

```
onedrive --resync -v
Deleting the saved status ...
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/matthewc/OneDrive
Initializing the Synchronization Engine ...
Applying differences ...
970772CA5BE91157!103 root
The item is already present
970772CA5BE91157!104 Pictures
The item is already present
970772CA5BE91157!105 Documents
The item is already present
970772CA5BE91157!152 SRA 111 dup
The item is neither a file nor a directory, skipping
970772CA5BE91157!106 Matthew's Notebook
The item is neither a file nor a directory, skipping
970772CA5BE91157!135 MIS - Management Information Systems
The item is neither a file nor a directory, skipping
970772CA5BE91157!176 SRA 111
The item is neither a file nor a directory, skipping
970772CA5BE91157!122 School
The item is neither a file nor a directory, skipping
970772CA5BE91157!144 ECON 104
The item is neither a file nor a directory, skipping
970772CA5BE91157!103 root
The item has not changed
Uploading differences ...
970772CA5BE91157!103 root
The directory has not changed
970772CA5BE91157!104 Pictures
The directory has not changed
970772CA5BE91157!105 Documents
The directory has not changed
Uploading new items ...

```

**Comment by abraunegg** [comment]
Can you provide an 'ls -la' on these files, and a 'file <filename>' ?

**Comment by Nightshaxx** [comment]
@abraunegg not sure what you mean, the sync program completely skips over the files and does not sync them, nor has it ever downloaded them. (Maybe I was not clear about that). None the less, here is my terminal oututput.
 _(The files should be in "~/OneDrive/Documents" , I ran a "--resync -v" right before this, and got the same output as above.)_

```
[matthewc@matthew-pc ~]$ cd OneDrive
[matthewc@matthew-pc OneDrive]$ ls -la
total 16
drwxr-xr-x  4 matthewc matthewc 4096 Aug 15 15:54 .
drwx------ 50 matthewc matthewc 4096 Oct 18 12:22 ..
drwxr-xr-x  2 matthewc matthewc 4096 Aug 15 15:54 Documents
drwxr-xr-x  2 matthewc matthewc 4096 Aug 15 15:54 Pictures
[matthewc@matthew-pc OneDrive]$ cd Documents
[matthewc@matthew-pc Documents]$ ls -la
total 8
drwxr-xr-x 2 matthewc matthewc 4096 Aug 15 15:54 .
drwxr-xr-x 4 matthewc matthewc 4096 Aug 15 15:54 ..
```

**Comment by abraunegg** [comment]
Ahh OK - I missed the part that they were not even syncing down from OneDrive itself - I was thinking if it was already local and skipping it could be something with the file format

Is there any way to look at what OneDrive is doing with the requests to sync those files by using https://apigee.com/console/OneDrive ?

**Comment by Nightshaxx** [comment]
​APIgee does not have OneDrive support, but it does have OneNote support. ​


-- Matthew Cherrey

"The easiest way to stop piracy is not by putting anti-piracy technology to
work. It's by giving those people a service that's better than what they're
receiving from the pirates."* - Gabe Newell, Valve CEO*

"I often compare open source to science. To where science took this whole
notion of developing ideas in the open and improving on other peoples'
ideas and making it into what science is today and the incredible advances
that we have had." *- Linus Torvalds, C**hief architect of the Linux kernel*

**Comment by abraunegg** [comment]
OK .. it used to !

I have also just tested this issue against by fork - and even in debug mode, a OneNote file does not appear in the file list of files or changed items 

I have opened up a ticked on the OneDrive API side of things: https://github.com/OneDrive/onedrive-api-docs/issues/462

**Comment by Nightshaxx** [comment]
I found this on the OneDrive dev center. I assume this means that I will have to find a different way to sync my notebooks.....

https://dev.onedrive.com/readme.htm#working-with-onenote-notebooks

**Comment by tvhong** [comment]
This is still the case as of Jan 2018. I've just installed OneNote 2010 and hoping I could use OneDrive to sync the notebooks. But looks like this is not supported from the link @Nightshaxx posted above.

**Comment by thomasfedb** [comment]
My understanding is that OneNote files on OneDrive are not really files, but rather links to get OneNote to load the corresponding Notebook.

**Comment by abraunegg** [comment]
@Nightshaxx 
Given that the onedrive client does not sync OneNote files can this issue be closed?

**Comment by Nightshaxx** [comment]
Yes. This seems like Microsoft's problem. In fact I wouldn't be surprised
if it is intentional behavior to prevent people from using oneDrive to sync
oneNote files while editing them with an older version, forcing them to
upgrade.

**Comment by abraunegg** [comment]
If you can close it that would be great.

**Comment by Nightshaxx** [comment]
Done

**Comment by FriedrichStein** [comment]
Hey, 
i'm currently looking for a way to Sync to OneNote2010 on Linux.
@MCherrey have you found a way to get it done? Or have you found a workaround?
Greetings Friedrich

**Comment by abraunegg** [comment]
@FriedrichStein 
The one drive client uses the OneDrive API, where as OneNote uses a totally different API as per https://docs.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online#working-with-onenote-notebooks - using the 'onedrive' client to sync OneNote files is not possible.

Also the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by FriedrichStein** [comment]
Thank you for the answer. 
I found a solution for me, by runnung the android version of OneNote with Anbox. It works and even syncs with onedrive. Anyone trying this should use an x86 apkfile of onenote, cause other versions won't run.
