### ISSUE TITLE
Can this be made to work on Mac OS X?

### ISSUE THREAD

**Issue by actuallymentor** [skilion/onedrive#111]
I'd love to be able to sync to an external drive from the command line to keep a cold backup.

**Comment by Scimmia22** [comment]
Unlikely. See #94

**Comment by actuallymentor** [comment]
Hmm, too bad. Maybe I'll write a node based api interactor. Thanks!

**Comment by andrebrait** [comment]
Why would you want to, in the first place? I get that this is free software, but you're already running OS X, so I guess you're comfortable with proprietary closed source software. Microsoft has an official OneDrive client for OS X, AFAIK.

**Comment by actuallymentor** [comment]
@andrebrait Not a particularly nice email to see fly by in my mail. You do realize OS X is basically Unix? It's closed on the front but deliciously like linux when you pop the hood.

Anyway, back to topic. I want this to be able to keep a cold backup on a harddrive that I can plug in once a month and run "onedrive --update". I already use the desktop client for regular use.

<img width="1004" alt="screen shot 2016-10-12 at 6 50 42 pm" src="https://cloud.githubusercontent.com/assets/9071382/19319337/d026adfe-90ac-11e6-8b28-324f6780aa84.png">

**Comment by andrebrait** [comment]
@actuallymentor Sorry about that. I sent it prematurely and I noticed how rude I had sounded the second I hit the Comment button. I edited it, but logically you received the original comment via email. While I was really genuinely curious as to why you'd like to make it work on OS X and I meant to express my wondering as to whether you cared about free software, I surely expressed myself in a rude way and I apologize for that.

As for the practical aspects, I see why you'd like to make it run on OS X. Is a small Linux VM with a shared folder an option? Running some lightweight terminal-only distro on a VM and share a folder between your OS X host and the VM might do. I understand that it might be too much work for such a simple task, but it might just work and wouldn't require coding, etc.

**Comment by actuallymentor** [comment]
@andrebrait Thanks for the consideration, you probably had a bad morning or something :)

As for the VM idea, while not an entirely clean solution it would circumvent the need for a while coding project indeed. I'll trial it this weekend, maybe make a vagrant/docker setup for it

**Comment by skilion** [comment]
It would be possible by removing all the references to `monitor.d` since it is the only module which depends on inotify and it is completely optional for syncing.

**Comment by maehne** [comment]
I would also be interested if skilion/onedrive could be made to work on macOS. Like in issue #94, compilation fails in `monitor.d`:
```
$ make
echo v1.1.1-2-gc231b13 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/monitor.d(11): Error: undefined identifier 'IN_ATTRIB'
src/monitor.d(11): Error: undefined identifier 'IN_CLOSE_WRITE'
src/monitor.d(11): Error: undefined identifier 'IN_CREATE'
src/monitor.d(12): Error: undefined identifier 'IN_DELETE'
src/monitor.d(12): Error: undefined identifier 'IN_MOVE'
src/monitor.d(12): Error: undefined identifier 'IN_IGNORED'
src/monitor.d(12): Error: undefined identifier 'IN_Q_OVERFLOW'
src/monitor.d(130): Error: undefined identifier 'inotify_event'
make: *** [onedrive] Error 1
```
due to the lack of the inotify API on macOS. The equivalent API would be [FSevents](https://developer.apple.com/library/content/documentation/Darwin/Conceptual/FSEvents_ProgGuide/UsingtheFSEventsFramework/UsingtheFSEventsFramework.html).

My use case is that the official OneDrive client for macOS does not support case-sensitives file systems so that I cannot use it to set up a sync folder.

Would it be possible to refactor the code so that the correct file systems events API is used depending on the targeted platform?
