### ISSUE TITLE
Ubuntu 16.10 Make failure

### ISSUE THREAD

**Issue by fiercebrake** [skilion/onedrive#112]
Hello friends,
I am getting teh following error while trying to build on ubuntu latest; is tehre any further information you need from me in order to troubleshoot ?

/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libphobos2.a(socket_17ba_7d4.o): relocation R_X86_64_32 against symbol `__dmd_personality_v0' can not be used when making a shared object; recompile with -fPIC

**Comment by Tustvold** [comment]
Adding '-fPIC -defaultlib=libphobos2.so' to the makefile's DFLAGS works for me

**Comment by fiercebrake** [comment]
Thank you for your reply friend! i shall try your solution!

**Comment by rayoplateado** [comment]
This works perfectly.
