### ISSUE TITLE
Crash after remove file

### ISSUE THREAD

**Issue by maxxvin** [skilion/onedrive#118]
Nov 04 23:53:29 owncloud.maxhope.in.ua onedrive[1654]: Uploading: ./test7
Nov 04 23:53:35 owncloud.maxhope.in.ua onedrive[1654]: Deleting remote item: ./test7
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: onedrive.OneDriveException@src/onedrive.d(348): HTTP request returned status code 412 (Precondition Failed)
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ----------------
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? void onedrive.OneDriveApi.del(const(char)[]) [0x59450b]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? void sync.SyncEngine.uploadDeleteItem(itemdb.Item, const(char)[]) [0x5a161e]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? void sync.SyncEngine.deleteByPath(const(char)[]) [0x5a2833]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? void main.main(immutable(char)[][]).__dgliteral4(immutable(char)[]) [0x58c9c1]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? void monitor.Monitor.update(bool) [0x59114e]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? _Dmain [0x58c646]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a9bce]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a9b18]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a9b8a]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a9b18]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? _d_run_main [0x5a9a89]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? main [0x58fb35]
Nov 04 23:53:36 owncloud.maxhope.in.ua onedrive[1654]: ??:? __libc_start_main [0xe5e17b44]
Nov 04 23:53:36 owncloud.maxhope.in.ua systemd[1]: onedrive-maxx.service: main process exited, code=killed, status=11/SEGV
Nov 04 23:53:36 owncloud.maxhope.in.ua systemd[1]: Unit onedrive-maxx.service entered failed state.

**Comment by maxxvin** [comment]
system Debian 8 (jessie) onedrive-master

owncloud ~ # ll onedrive-master/ | pastebinit 
http://paste.debian.net/892485/

**Comment by sunziping2016** [comment]
I've experienced quite the same issue.

**Comment by Zardoz89** [comment]
Same problem with Ubuntu 16.04.1
Perhaps a change on Microsfot API ? --> **HTTP request returned status code 412**

**Comment by Zardoz89** [comment]
Branch from https://github.com/abraunegg/onedrive have this issue fixed.

**Comment by ChrisLane** [comment]
I'm also having this issue with the latest version from git on Arch Linux 4.8.8-1.

**Comment by GrouchyGaijin** [comment]
Same problem, but it just started on my Ubuntu 16.04 machine:
`Today is Sat Dec 10 @ 19:08:56 ~ $ onedrive -m
Deleting remote item: ./VIPKID/IMG_20161210_160217.png
HTTP request returned status code 412 (Precondition Failed)
Deleting remote item: ./VIPKID/IMG_20161210_160217.png
HTTP request returned status code 412 (Precondition Failed)
Deleting remote item: ./VIPKID/IMG_20161210_160217.png
sync.SyncException@src/sync.d(352): HTTP request returned status code 412 (Precondition Failed)
----------------
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59a4ec]
??:? void main.performSync(sync.SyncEngine) [0x58aa9e]
??:? _Dmain [0x58a1f7]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a521e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a5168]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a51da]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a5168]
??:? _d_run_main [0x5a50d9]
??:? main [0x58c6f5]
??:? __libc_start_main [0x3013382f]
onedrive.OneDriveException@src/onedrive.d(337): HTTP request returned status code 412 (Precondition Failed)
----------------
??:? void onedrive.OneDriveApi.del(const(char)[]) [0x5909db]
??:? void sync.SyncEngine.uploadDeleteItem(itemdb.Item, const(char)[]) [0x59cea9]
??:? void sync.SyncEngine.uploadFileDifferences(itemdb.Item, immutable(char)[]) [0x59b944]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x59a8ed]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x59a7be]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x59a7be]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59a3ba]
??:? void main.performSync(sync.SyncEngine) [0x58aa9e]
??:? _Dmain [0x58a1f7]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a521e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a5168]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a51da]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a5168]
??:? _d_run_main [0x5a50d9]
??:? main [0x58c6f5]
??:? __libc_start_main [0x3013382f]
Segmentation fault (core dumped)
`

**Comment by GrouchyGaijin** [comment]
Has there been any development on this issue?

**Comment by skilion** [comment]
Fixed in 0afb6fa3923066f46c531f33e175011cd69e06a8

**Comment by GrouchyGaijin** [comment]
Sorry to be a dumb a**, but what should I do to add the fix to my system? Can I just download the zip file again and install over the existing installation?

**Comment by skilion** [comment]
Yeah, downloading the latest zip and running `sudo make install` is enough
