### ISSUE TITLE
Crash with File size > 10Gb

### ISSUE THREAD

**Issue by jprady** [skilion/onedrive#121]
OneDrive doesn't allow files greater than 10Gb in size, but when one is encountered, we get a crash. The crash was repeated, and it was only when I used the website to try and upload that I discovered this was the issue as the website highlights the file as a problem.

onedrive[25841]: onedrive.OneDriveException@src/onedrive.d(348): HTTP request returned status code 400 (Bad Request)
Nov 20 16:16:48 peanut onedrive[25841]: ----------------
Nov 20 16:16:48 peanut onedrive[25841]: ??:? std.json.JSONValue onedrive.OneDriveApi.uploadFragment(const(char)[], immutable(char)[], long, long, long) [0x592d99]
Nov 20 16:16:48 peanut onedrive[25841]: ??:? std.json.JSONValue upload.UploadSession.upload() [0x5a2b41]
Nov 20 16:16:48 peanut onedrive[25841]: ??:? void sync.SyncEngine.init() [0x59bc92]
Nov 20 16:16:48 peanut onedrive[25841]: ??:? _Dmain [0x58bcfa]
Nov 20 16:16:48 peanut onedrive[25841]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a949e]
Nov 20 16:16:48 peanut onedrive[25841]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a93e8]
Nov 20 16:16:48 peanut onedrive[25841]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a945a]
Nov 20 16:16:48 peanut onedrive[25841]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a93e8]
Nov 20 16:16:48 peanut onedrive[25841]: ??:? _d_run_main [0x5a9359]
Nov 20 16:16:48 peanut onedrive[25841]: ??:? main [0x58f48d]
Nov 20 16:16:48 peanut onedrive[25841]: ??:? __libc_start_main [0xe8f6582f]
Nov 20 16:16:48 peanut systemd[1466]: onedrive.service: Main process exited, code=dumped, status=11/SEGV
Nov 20 16:16:48 peanut systemd[1466]: onedrive.service: Unit entered failed state.
Nov 20 16:16:48 peanut systemd[1466]: onedrive.service: Failed with result 'core-dump'.

**Comment by thomasfedb** [comment]
@jprady does this issue occur with the latest codebase? If not, could you close this issue please.

**Comment by skilion** [comment]
Closed as duplicate

**Comment by abraunegg** [comment]
I have pushed a patch in #314 that resolves this issue
