### ISSUE TITLE
Onedrive daemon dies after a while with SEGV signal

### ISSUE THREAD

**Issue by sdkks** [skilion/onedrive#125]
Onedrive works after starting manually via systemctl , it will upload and download properly. After a while it will crash. 

```
● onedrive.service - OneDrive Free Client
   Loaded: loaded (/usr/lib/systemd/user/onedrive.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Wed 2016-11-23 01:56:03 SGT; 2 days ago
     Docs: https://github.com/skilion/onedrive
  Process: 24460 ExecStart=/usr/local/bin/onedrive -m (code=killed, signal=SEGV)
 Main PID: 24460 (code=killed, signal=SEGV)

Nov 23 01:56:03 sdkks-pc onedrive[24460]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a949e]
Nov 23 01:56:03 sdkks-pc onedrive[24460]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void dele
Nov 23 01:56:03 sdkks-pc onedrive[24460]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a945a]
Nov 23 01:56:03 sdkks-pc onedrive[24460]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void dele
Nov 23 01:56:03 sdkks-pc onedrive[24460]: ??:? _d_run_main [0x5a9359]
Nov 23 01:56:03 sdkks-pc onedrive[24460]: ??:? main [0x58f48d]
Nov 23 01:56:03 sdkks-pc onedrive[24460]: ??:? __libc_start_main [0x70efd82f]
Nov 23 01:56:03 sdkks-pc systemd[4372]: onedrive.service: Main process exited, code=killed, status=11/SEGV
Nov 23 01:56:03 sdkks-pc systemd[4372]: onedrive.service: Unit entered failed state.
Nov 23 01:56:03 sdkks-pc systemd[4372]: onedrive.service: Failed with result 'signal'.
```

**Comment by sdkks** [comment]
I have a new observation, if a file is big, i.e. 15GB which is more than supported Onedrive size, this service will crash immediately.

**Comment by ervion-n** [comment]
For me it crashes with segfault for a ton of different reasons: file deleted or modified locally during sync, file deleted or modified remotely during sync, temporary loss of internet connection etc.

Some kind of exception handling would be really helpful.

**Comment by thomasfedb** [comment]
@sdkks does this issue occur with the latest codebase? If not, could you close this issue please.

**Comment by abraunegg** [comment]
> I have a new observation, if a file is big, i.e. 15GB which is more than supported Onedrive size, this service will crash immediately.

In #314 I have added individual file size checking to ensure that files comply with OneDrive standards, and validating that there is space available to support the file to be uploaded.

Can you recheck with #314?

**Comment by abraunegg** [comment]
@sdkks 
Any update on this issue? If no longer relevant, please can you close this issue.

**Comment by sdkks** [comment]
@abraunegg I stopped using it, so I'm not sure if it is still existing. I will close it.
