### ISSUE TITLE
Newbie but managed to setup Onedrive on Zorin 12 / Ubuntu but it stopped working after syncing today 

### ISSUE THREAD

**Issue by chefboyct** [skilion/onedrive#126]
Hi Skillion,

Thanks for the great project and please regard me as a useless newbie as I even had to search on the internet to find a proper walk about to install the Onedrive Free. 

Everything worked fine and I managed to sync yesterday the entire Onedrive onto my system. (I struggled to even change the onedrive.conf to redirect it to different folder so I decided just let the system create a Default OneDrive under Home directory). However I have this error this morning and also after reboot and it is still the same. I have tried to ping api.onedrive.com and it is working. So please let me know what I have done wrong so I can fix it. Thanks! 

./OneDrive: No such file or directory
./OneDrive: No such file or directory
sync.SyncException@src/sync.d(104): ./OneDrive: No such file or directory
----------------
??:? void sync.SyncEngine.applyDifferences() [0x5bed06]
??:? void main.performSync(sync.SyncEngine) [0x5af303]
??:? _Dmain [0x5aeb32]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d546e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d53b8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d542a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d53b8]
??:? _d_run_main [0x5d5329]
??:? main [0x5b1bb5]
??:? __libc_start_main [0xd402f82f]
std.file.FileException@/usr/include/dmd/phobos/std/file.d(1538): ./OneDrive: No such file or directory
----------------
??:? @trusted bool std.file.cenforce!(bool).cenforce(bool, const(char)[], const(char)*, immutable(char)[], ulong) [0x59d54e]
??:? @safe uint std.file.getAttributes!(immutable(char)[]).getAttributes(immutable(char)[]) [0x59fe1e]
??:? bool sync.SyncEngine.isItemSynced(itemdb.Item, immutable(char)[]) [0x5c05a2]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5c0066]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5bfb14]
??:? void sync.SyncEngine.applyDifferences() [0x5beb70]
??:? void main.performSync(sync.SyncEngine) [0x5af303]
??:? _Dmain [0x5aeb32]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d546e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d53b8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d542a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d53b8]
??:? _d_run_main [0x5d5329]
??:? main [0x5b1bb5]
??:? __libc_start_main [0xd402f82f]
Segmentation fault (core dumped)

**Comment by chefboyct** [comment]
Update - 27/11 20:06 GMT+2 

I just ran OneDrive on Terminal and it worked... until the error message again. Please note I also have OneDrive Linked to my Windows 10 on the separate partition. Zorin / Ubuntu I use the default setting (so there are two copies of OneDrive - One for Windows and one for Ubuntu)

downloading: ./OneDrive
Creating directory: ./$RECYCLE.BIN
Creating directory: ./$RECYCLE.BIN/S-1-5-21-2526016852-304190558-2125144657-1001
Downloading: ./Temp/Elroy Shilling CV - Feb 2015.docx
Downloading: ./Pictures/Camera Roll/IMG_20161127_090640.jpg
Downloading: ./Pictures/Camera Roll/IMG_20161127_090649_2.jpg
Downloading: ./Pictures/Camera Roll/IMG_20161127_090649.jpg
Downloading: ./Pictures/Camera Roll/IMG_20161127_090647_1.jpg
Downloading: ./Pictures/Camera Roll/IMG_20161127_090646_1.jpg
Downloading: ./Pictures/Camera Roll/IMG_20161127_090645.jpg
Downloading: ./Pictures/Camera Roll/IMG_20161127_115329.jpg
Downloading: ./Pictures/Camera Roll/Screenshot_2016-11-27-12-31-31.png
Downloading: ./$RECYCLE.BIN/S-1-5-21-2526016852-304190558-2125144657-1001/$R2W8NUO
Downloading: ./$RECYCLE.BIN/S-1-5-21-2526016852-304190558-2125144657-1001/$I2W8NUO
Downloading: ./Pictures/Camera Roll/IMG_20160331_093254-DESKTOP-TR4D68R.jpg
Downloading: ./Pictures/Camera Roll/IMG_20161127_173257.jpg
Downloading: ./Pictures/Camera Roll/IMG_20161127_173307.jpg
Uploading: ./Pictures/Saved pictures/WP_20140318_12_10_58_Smart.jpg
std.json.JSONException@std/json.d(473): Key not found: cTag
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x62e469]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException, inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x62e4ce]
??:? std.json.JSONValue.opIndexinout(pure ref @safe inout(std.json.JSONValue) function(immutable(char)[])) [0x5ee523]
??:? void sync.SyncEngine.saveItem(std.json.JSONValue) [0x5c41fa]
??:? void sync.SyncEngine.uploadFileDifferences(itemdb.Item, immutable(char)[]) [0x5c1d4f]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5c1365]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5c117c]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5c117c]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5c117c]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5c0b99]
??:? void main.performSync(sync.SyncEngine) [0x5af316]
??:? _Dmain [0x5aeb32]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d546e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d53b8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d542a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d53b8]
??:? _d_run_main [0x5d5329]
??:? main [0x5b1bb5]
??:? __libc_start_main [0xc01682f]
Segmentation fault (core dumped)

**Comment by skilion** [comment]
The first exception is related to the missing sync directory, double check your config file if that happens again.
The second exception has been fixed in 9ad9394b9827ce3e2bd7ab290451b7959cfbad50
