### ISSUE TITLE
segfault when running $onedrive

### ISSUE THREAD

**Issue by rlowrance** [skilion/onedrive#128]
I've installed it and ran one sync.

Now I want to sync again, but I get a segfault (see below).

I also get a segfault on $onedrive -m

* * * terminal output follows

$onedrive
HTTP request returned status code 400 (Bad Request)
HTTP request returned status code 400 (Bad Request)
sync.SyncException@src/sync.d(106): HTTP request returned status code 400 (Bad Request)
----------------
??:? void sync.SyncEngine.applyDifferences() [0x5bed7b]
??:? void main.performSync(sync.SyncEngine) [0x5af333]
??:? _Dmain [0x5aeb62]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d549e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d53e8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d545a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d53e8]
??:? _d_run_main [0x5d5359]
??:? main [0x5b1be5]
??:? __libc_start_main [0x77efa82f]
onedrive.OneDriveException@src/onedrive.d(348): HTTP request returned status code 400 (Bad Request)
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x5ba315]
??:? void onedrive.OneDriveApi.newToken() [0x5b5e6f]
??:? void sync.SyncEngine.applyDifferences() [0x5be9f2]
??:? void main.performSync(sync.SyncEngine) [0x5af333]
??:? _Dmain [0x5aeb62]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d549e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d53e8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d545a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d53e8]
??:? _d_run_main [0x5d5359]
??:? main [0x5b1be5]
??:? __libc_start_main [0x77efa82f]
Segmentation fault (core dumped)

**Comment by skilion** [comment]
Looks like the app is not authorized to access your onedrive. Since ad4e910e5584f584e271e5ab6a52c9daacedb178 the app will ask you to be authorized it again.
