### ISSUE TITLE
[Enhancement] Slow Download Performance

### ISSUE THREAD

**Issue by sidhant** [skilion/onedrive#131]
I have noticed that I cannot get this to max out my bandwidth. I have a very large (~100GB) Onedrive to sync and when I am watching the network utilization, it appears to be sporadic. For lack of better analogy, it seems as if it is not a "multi-threaded download". Any ideas?

Edit: I am on a ~800 Mbps connection and it barely uses ~45Mbps.

**Comment by aryehbeitz** [comment]
@sidhant try syncing your files on the windows client and compare speeds. If it's still slow, it a problem with the Onedrive network

**Comment by thomasfedb** [comment]
@sidhant did you attempt the comparison with the Windows client as suggested by @aryehbeitz?

**Comment by sidhant** [comment]
@thomasfedb Yes. It was much slower than the native client running on my Windows machine. I gave up on using this solution to sync my files.

**Comment by thomasfedb** [comment]
@sidhant if you're no longer looking for this to be resolved, can you close the issue?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
