### ISSUE TITLE
Error when uploading file that already existis

### ISSUE THREAD

**Issue by hugomilan** [skilion/onedrive#133]
I'm trying to synchronize my files but I'm getting an error when the onedrive tries to upload a file from my computer that already exists on the server. Maybe onedrive couldn't figure out that both files are the same?

This is the log that I get.
onedrive --sync -V

Uploading new items ...
Uploading: ./Imagens/Imagens da Câmera/IMG_20161009_175051.jpg
sync.SyncException@src/sync.d(362): HTTP request returned status code 409 (Conflict)
{
    "error": {
        "code": "nameAlreadyExists",
        "message": "An item with the same name already exists under the parent"
    }
}
----------------
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xf7cee652]
??:? void main.performSync(sync.SyncEngine) [0xf7cdbf88]
??:? _Dmain [0xf7cdb74d]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x358bc387]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x358bc2b3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x358bc32c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x358bc2b3]
??:? _d_run_main [0x358bc217]
??:? main [0xf7cdea57]
??:? __libc_start_main [0x34a1b3f0]
onedrive.OneDriveException@src/onedrive.d(365): HTTP request returned status code 409 (Conflict)
{
    "error": {
        "code": "nameAlreadyExists",
        "message": "An item with the same name already exists under the parent"
    }
}
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0xf7ce4407]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0xf7cf0f0d]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf7cf08b4]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf7cf06a3]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf7cf06a3]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf7cf06a3]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xf7cee541]
??:? void main.performSync(sync.SyncEngine) [0xf7cdbf88]
??:? _Dmain [0xf7cdb74d]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x358bc387]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x358bc2b3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x358bc32c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x358bc2b3]
??:? _d_run_main [0x358bc217]
??:? main [0xf7cdea57]
??:? __libc_start_main [0x34a1b3f0]
Segmentation fault (core dumped)

**Comment by skilion** [comment]
It should be fixed in bbbfeb68f3a1b2e841636c6dd933b7a89c16bff1
Try `--resync`

**Comment by hugomilan** [comment]
Thanks! I could do `--resync` and it worked well!

I also tested what happens when I delete files on drive/computer and do `onedrive`. I found out that if I delete a file on the drive, it synchronize well. But, when I delete a file on my PC, it doesn't synchronize and I get:

onedrive
Downloading: ./backup (copy).sh
object.Exception@src/itemdb.d(237): Unknow item id
----------------
??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0xe9d65c61]
??:? immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[]) [0xe9d8e64f]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0xe9dabc7e]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0xe9dabfd3]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xe9dab9bb]
??:? void main.performSync(sync.SyncEngine) [0xe9d99210]
??:? _Dmain [0xe9d989d6]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0xc21dd387]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xc21dd2b3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xc21dd32c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xc21dd2b3]
??:? _d_run_main [0xc21dd217]
??:? main [0xe9d9bcdf]
??:? __libc_start_main [0xc133c3f0]

**Comment by skilion** [comment]
I cannot reproduce your error, what steps did you do to get it?
Anyway, I assume deleting files is currently broken. If I execute manually a REST call to delete a file with the If-Match header set, I **always** get "HTTP request returned status code 412 (Precondition Failed)".

**Comment by hugomilan** [comment]
That's what I did.

`onedrive --resync`
`onedrive`
Then I copied backup.sh to "backup (copy).sh"
`onedrive`
Uploading: ./backup (copy).sh
Then I deleted "backup (copy).sh".
`onedrive`
Then I get:
Downloading: ./backup (copy).sh
object.Exception@src/itemdb.d(237): Unknow item id
----------------
??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0xd5b29c61]
??:? immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[]) [0xd5b5264f]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0xd5b6fc7e]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0xd5b6ffd3]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xd5b6f9bb]
??:? void main.performSync(sync.SyncEngine) [0xd5b5d210]
??:? _Dmain [0xd5b5c9d6]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x614be387]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x614be2b3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x614be32c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x614be2b3]
??:? _d_run_main [0x614be217]
??:? main [0xd5b5fcdf]
??:? __libc_start_main [0x6061d3f0]

I noted that onedrive first downloads the file that I deleted and then it seems to try to delete it.

**Comment by skilion** [comment]
It should be fixed as well in 203062fc6b1416de4d9230b9401556641e2b0a24

**Comment by hugomilan** [comment]
It's working! Thanks!
