### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by GrouchyGaijin** [skilion/onedrive#135]
Hi!

It looks like an issue I have has been recently fixed.  The problem I have is that I do not know how to update the program on my computer.  I am running Ubuntu 16.04.  I initially downloaded and extracted the zip file and then went through the installation steps.  Do I do the same thing and install the latest version over the version I am currently using or do I need to uninstall the current version first? If so, is there a preferred way to uninstall the current version?
Sorry for being so stupid.

**Comment by skilion** [comment]
Downloading the latest zip and running `sudo make install` is enough. It will overwrite the old version.

**Comment by GrouchyGaijin** [comment]
hmmmm I get an error:

Today is Thu Dec 29 @ 18:07:05 ~/Downloads/onedrive-master $ sudo make install
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/onedrive.d(40): Error: function std.json.toJSON (const(JSONValue*) root, const(bool) pretty = false, const(JSONOptions) options = cast(JSONOptions)0) is not callable using argument types (const(JSONValue), bool)
Makefile:19: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1

**Comment by skilion** [comment]
You also need to update DMD

**Comment by GrouchyGaijin** [comment]
sudo apt install dmd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dmd is already the newest version (2.071.0-0)

**Comment by GrouchyGaijin** [comment]
Great - got it working.  THANK YOU!!  This does make my life much easier.
