### ISSUE TITLE
Latest build failed

### ISSUE THREAD

**Issue by StevenChenSE** [skilion/onedrive#136]
make shows the following error:

dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
 src/onedrive.d(40): Error: function std.json.toJSON (const(JSONValue*) root, const(bool) pretty = false, const(JSONOptions) options = cast(JSONOptions)0) is not callable using argument types (const(JSONValue), bool)
 Makefile:19: recipe for target 'onedrive' failed
 make: *** [onedrive] Error 1

**Comment by fiercebrake** [comment]
in my case it shows:

dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
/usr/bin/ld: onedrive.o: relocation R_X86_64_32 against symbol `_D6object9Throwable7__ClassZ' can not be used when making a shared object; recompile with -fPIC

**Comment by skilion** [comment]
@StevenChenSE update DMD to the latest version
@fiercebrake https://github.com/skilion/onedrive/issues/112 may help

**Comment by plembo** [comment]
Same here on Fedora 24, latest packages. Just did a git pull and tried make. Result:

```
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl -fPIC -defaultlib=libphobos2.so src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/onedrive.d(40): Error: function std.json.toJSON (const(JSONValue*) root, const(bool) pretty = false, const(JSONOptions) options = cast(JSONOptions)0) is not callable using argument types (const(JSONValue), bool)
Makefile:19: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
```
Have added the fPIC param as in #112 and installed the latest dmd globally.

```
DMD64 D Compiler v2.071.1
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright
```

Before building stopped onedrive as a service and ensured no onedrive process was running. Previous version of onedrive still working.

**Comment by maizesix92** [comment]
Hi I am having an issue performing the 'make' command

This is the message printed in my terminal:
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
Error: Error writing file 'onedrive.o'
Makefile:19: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1

My dmd version is as such:
DMD64 D Compiler v2.073.0

any suggestions?

**Comment by skilion** [comment]
The error does not seem to be related to the code

**Comment by danbri** [comment]
I ran into this trying to hand-build @kukki 's docker image at https://hub.docker.com/r/kukki/docker-onedrive/ via this command: docker build -t "onedrivetest1:dockerfile" .

> Step 9/14 : RUN cd onedrive-master && make && make install
 ---> Running in 79aa602c63e7
dmd -g -inline -O -release -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/onedrive.d(41): Error: function std.json.toJSON (const(JSONValue*) root, const(bool) pretty = false, const(JSONOptions) options = cast(JSONOptions)0) is not callable using argument types (const(JSONValue), bool)
make: *** [onedrive] Error 1

disclaimer: docker *and* onedrive newbie

Per @skilion  & @plembo 's comments, I changed one line in the dockerfile and it builds:

> RUN wget http://downloads.dlang.org/releases/2017/dmd_2.073.2-0_amd64.deb -O dmd.deb && dpkg -i dmd.deb
