### ISSUE TITLE
Cannot get URI for first use

### ISSUE THREAD

**Issue by majonathany** [skilion/onedrive#137]
Hi,

I'm trying to use onedrive for the first time, but once I give permission in the browser by clicking yes, I am taken to a blank screen with no URI, and I have nothing to input into the console when prompted for the URI. Do you know the solution?

Thanks!

**Comment by st1618** [comment]
you should have a response URL in the address bar of your browser, copy and paste this

Kind regards

**Comment by itpastorn** [comment]
I've got the same problem. This is my response URL:

  https://login.live.com/oauth20_desktop.srf?error=invalid_request&error_description=The%20provided%20value%20for%20the%20input%20parameter%20%27redirect_uri%27%20is%20not%20valid.%20The%20client%20application%20must%20be%20marked%20as%20%27mobile%27%2c%20or%20the%20value%20must%20be%20an%20absolute%20URL%20which%20matches%20the%20registered%20redirect%20URI.&lc=1033

I've tried to manually change the response-URL parameter to the one provided by Microsoft. Then I get this:

  https://login.live.com/oauth20_desktop.srf?error=invalid_request&error_description=The%20provided%20value%20for%20the%20input%20parameter%20%27redirect_uri%27%20is%20not%20valid.%20The%20client%20application%20must%20be%20marked%20as%20%27mobile%27%2c%20or%20the%20value%20must%20be%20an%20absolute%20URL%20which%20matches%20the%20registered%20redirect%20URI.&lc=1033
