### ISSUE TITLE
Cannot install Ubuntu 15.10

### ISSUE THREAD

**Issue by jrock2004** [skilion/onedrive#14]
Trying to install and getting errors during make

```
❯ make                                                             
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl patch/etc_c_curl.d patch/std_net_curl.d src/config.d src/itemdb.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
--- errorlevel 1
Makefile:20: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1

```

**Comment by xied75** [comment]
Looks like you don't have libcurl installed? How did you install dmd then?

I got totally different error msg:
```
root@cdbb63e030ed:~/onedrive# make
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl patch/etc_c_curl.d patch/std_net_curl.d src/config.d src/itemdb.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/util.d
patch/std_net_curl.d(1851): Error: semicolon expected following function declaration
patch/std_net_curl.d(1851): Error: Declaration expected, not 'return'
patch/std_net_curl.d(2159): Error: unrecognized declaration
Makefile:19: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
```

**Comment by sollie78** [comment]
I got the same on 14.04:
sollie@Sollie-Laptop ~/onedrive-master $ make
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl patch/etc_c_curl.d patch/std_net_curl.d src/config.d src/itemdb.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
patch/std_net_curl.d(1851): Error: semicolon expected following function declaration
patch/std_net_curl.d(1851): Error: Declaration expected, not 'return'
patch/std_net_curl.d(2159): Error: unrecognized declaration
make: *** [onedrive] Fout 1

**Comment by sollie78** [comment]
I got it: http://d-apt.sourceforge.net/

1: 
sudo wget http://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list

2: 
sudo apt-get update && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring && sudo apt-get update

3:
sudo apt-get install dmd-bin

4: 
Try to make and install again

**Comment by noahruss** [comment]
sudo apt-get install libcurl3-dev

you have to install libcurl dev package

**Comment by skilion** [comment]
Added commands to README in bfb2419
