### ISSUE TITLE
Sync exception

### ISSUE THREAD

**Issue by marliwd** [skilion/onedrive#142]
I received the following error while attempting to sync onedrive. What happened and how can I fix it?

object.Exception@src/itemdb.d(237): Unknow item id
----------------
??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x584419]
??:? immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[]) [0x5acea7]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5c88d4]
??:? void sync.SyncEngine.applyDifferences() [0x5c819a]
??:? void main.performSync(sync.SyncEngine) [0x5b7a53]
??:? _Dmain [0x5b722e]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dfc97]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dfbc3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5dfc3c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dfbc3]
??:? _d_run_main [0x5dfb27]
??:? main [0x5ba537]
??:? __libc_start_main [0xef93082f]

**Comment by danielasun** [comment]
I also have this problem currently. I have multiple Linux systems running the onedrive client and this error prevents the files from syncing, most likely completely.

**Comment by chakkerz** [comment]
Same here, persists through reboots and restarts, though sometimes it will work and sync some more.

**Comment by jmayday** [comment]
Same problem here. Fedora 24 with following deps installed:

```
dmd-2.073.1-0.x86_64
libsqlite3x-devel-20071018-19.fc24.x86_64
libcurl-devel-7.51.0-4.fc25.x86_64
```

```
[~]─(139)-> onedrive -m
object.Exception@src/itemdb.d(237): Unknow item id
----------------
??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x5858a5]
??:? immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[]) [0x5ad455]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5c8dac]
??:? void sync.SyncEngine.applyDifferences() [0x5c86aa]
??:? void main.performSync(sync.SyncEngine) [0x5b7c5b]
??:? _Dmain [0x5b7432]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dea13]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5de93b]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5de9b8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5de93b]
??:? _d_run_main [0x5de8a7]
??:? main [0x5bac67]
??:? __libc_start_main [0x3cd4b400]
fish: 'onedrive -m' zakończony sygnałem SIGSEGV (Address boundary error)
```

**Comment by skilion** [comment]
The item database is in an inconsistent state, run `onedrive --resync`
I pushed a few commits meanwhile, if you update you need to reauth the app because of the switch to the new Microsoft Graph API: `onedrive --logout`
