### ISSUE TITLE
case sensitivity

### ISSUE THREAD

**Issue by hugomilan** [skilion/onedrive#145]
We know that in Linux the file names are case sensitivity but they are not in Windows (therefore, also in OneDrive). I copied some files and renamed it by only changing the case of the files' name. Of course, it had problems when uploading because, for Windows, the files had the same name. I think onedrive should have a flag to rename the file when uploading IF the only thing different between them is the file's name case (much like what it does when it sees files with the same name on server and local).

**Comment by thomasfedb** [comment]
@hugomilan does this error still occur with the latest commit? If so, can you describe more clearly what "had problems" means?

**Comment by abraunegg** [comment]
@hugomilan 

Can you re-test with the latest #314 branch?

**Comment by abraunegg** [comment]
@hugomilan 
Any update on this issue? If this is no longer relevant, please can you close this case.

**Comment by abraunegg** [comment]
@hugomilan 
Thanks for reporting that - it is a similar issue being reported in #341. I have updated the code to query the database before computing the path - commit 9520fe771687e1f8ee13f8ebe97cd88bba8195d7 if you can download the latest #314 branch & retry that would be greatly appreciated.

When running through the same steps as you with the updated code - this is what I get:

```
Loading config ...
Using Config Dir: /root/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 1095072441102
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from this selected path: TestFolder
Syncing changes from selected OneDrive path first before uploading local changes ...
ERROR: The requested single directory to sync was not found on OneDrive
Uploading differences of TestFolder
Uploading new items of TestFolder
OneDrive Client requested to create remote path: TestFolder
The requested directory to create was not found on OneDrive - creating remote directory: TestFolder
Sucessfully created the remote directory TestFolder on OneDrive
Uploading file TestFolder/test.txt ... done.
Remaining free space: 1095072441097
Requested file to upload exists on OneDrive - local database is out of sync for this file: TestFolder/Test.txt
Requested file to upload is newer than existing file on OneDrive
Uploading file TestFolder/Test.txt ... done.
Remaining free space: 1095072441091
```

Correct conflict resolution handling is what #343 is all about - once all these other issues are sorted, that is the next piece to work on.

**Comment by abraunegg** [comment]
@hugomilan
Any update?

**Comment by hugomilan** [comment]
I'll check it soon.
