### ISSUE TITLE
stuck in loop

### ISSUE THREAD

**Issue by mpede** [skilion/onedrive#146]
Hello there,

many thanks first of all for this project! I managed to get it to run on my RasPi, authenticate etc, and it downloaded the one folder I didn't include in the 'skip' variable successfully. However, and without specifying the -m parameter, the tool just seems to hang now while constantly maxing out the available download bandwidth. A -v parameter shows that it seems to be stuck in some kind of loop. Or is it maybe going through all items in the skipped folders here? Again, this folder is in the skip list as it has a couple of 100,000 files in it - even just checking them would probably take days. I thought of a loop as the ids seem to be the same (I let it run for an hour or so, producing 100s of these log lines, always repeating the four lines as shown below)

```
pi@raspberrypi:~ $ ./onedrive.bin -v 
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/pi/OneDrive
Initializing the Synchronization Engine ...
Applying differences ...
54D9DB42511EFD19!107 root
The item has not changed
54D9DB42511EFD19!107251 Juan
Filtered out
54D9DB42511EFD19!107 root
The item has not changed
54D9DB42511EFD19!107251 Juan
Filtered out
54D9DB42511EFD19!107 root
The item has not changed
54D9DB42511EFD19!107251 Juan
Filtered out
54D9DB42511EFD19!107 root
The item has not changed
54D9DB42511EFD19!107251 Juan
Filtered out
54D9DB42511EFD19!107 root
The item has not changed
54D9DB42511EFD19!107251 Juan
Filtered out
```

kind regards,
Christian

**Comment by skilion** [comment]
All the files in the folder must be enumerated, even if the folder is skipped. However the IDs should change.
Can you debug the issue by uncommenting `//http.verbose = true` at line 58 of `onedrive.d`?

**Comment by skilion** [comment]
Closed for inactivity
