### ISSUE TITLE
git clone in README.md

### ISSUE THREAD

**Issue by colemar** [skilion/onedrive#149]
```
$ git clone git@github.com:skilion/onedrive.git
Cloning into 'onedrive'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

```
$ git clone https://github.com/skilion/onedrive.git
Cloning into 'onedrive'...
remote: Counting objects: 540, done.
remote: Total 540 (delta 0), reused 0 (delta 0), pack-reused 540
Receiving objects: 100% (540/540), 178.81 KiB | 0 bytes/s, done.
Resolving deltas: 100% (371/371), done.
Checking connectivity... done.

```

**Comment by geraldo22** [comment]
> happened the same with me so I downloaded as a zip file. But once I got in the folder and typed 'make', it spitted an error:
> 
> $ make
> dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
> make: dmd: Command not found
> Makefile:19: recipe for target 'onedrive' failed
> make: *** [onedrive] Error 127

**Comment by HoneyFoxx** [comment]
Yeah i'm having the same issue with the git clone, and i get the same problem when i try to use the *"make"* command.

I hope this gets fixed soon....

**Comment by Scimmia22** [comment]
The problem with "make" is simple missing dependencies.

**Comment by jmayday** [comment]
> make: dmd: Command not found

go to https://dlang.org/download.html and install package for your system. For Fedora it's http://downloads.dlang.org/releases/2.x/2.073.1/dmd-2.073.1-0.fedora.x86_64.rpm
