### ISSUE TITLE
Build error on ArchLinux

### ISSUE THREAD

**Issue by yunake** [skilion/onedrive#15]
I've got the following error when building 1.0 from AUR:

```
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl patch/etc_c_curl.d patch/std_net_curl.d src/config.d src/itemdb.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/util.d
/usr/bin/ld: onedrive.o: relocation R_X86_64_32 against `_D17TypeInfo_xHAyaAya6__initZ' can not be used when making a shared object; recompile with -fPIC
onedrive.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
--- errorlevel 1
Makefile:19: recipe for target 'onedrive' failed
```

**Comment by skilion** [comment]
Maybe the AUR package is outdated. Try to make it manually.

**Comment by yunake** [comment]
i'm sorry, what do you mean by the package is outdated? it just pulls off of github and runs make. it goes for 1.0 release archive, but i've just ran a build manually with HEAD checkout and i'm getting the same error. this is with dmd v2.069. i'm not sure why it's failing to link though. adding fpic to dflags does nothing (is it even a valid flag for dmd? i'm not a d guy). how can i help you debug this?

**Comment by skilion** [comment]
On a clean 64 bit Arch Linux machine the app compiles without errors.
Since I am not able to reproduce your environment I can't really help you. Anyway a quick search on google of your error gives a few things to try.
You can find the DMD flags [here](http://dlang.org/dmd-linux.html)

**Comment by Scimmia22** [comment]
I'm pretty sure this is invalid.
