### ISSUE TITLE
How to configure skip_dir to exclude root folders?

### ISSUE THREAD

**Issue by shijistar** [skilion/onedrive#152]
I have several folders in my onedrive repository, e.g. A, B, C. I just want to synchronize the C directory. How do I set the `skip_dir` option? I tried "A|B", but the folder A/B was also excluded. I also tried "/A|/B" and "./A|./B" which didn't work neither.

**Comment by dhcmega** [comment]
You try to exclude /A but not /A/B ? Maybe you can exclude /A/* but except B ~/A/B
Maybe skip all together but then exclude the ones you want to sync.

**Comment by skilion** [comment]
Since March, you can use selective sync to achieve a reliable exclusion of files and directories
https://github.com/skilion/onedrive#selective-sync

**Comment by abraunegg** [comment]
@shijistar, @dhcmega 
This feature (skip_dir) is now available in my fork. Refer to https://github.com/abraunegg/onedrive/issues/123#issuecomment-466696653 for further details
