### ISSUE TITLE
Service crashed when network timeout happens

### ISSUE THREAD

**Issue by shijistar** [skilion/onedrive#153]
I started onedrive as service, but it silent stopped when a network timeout error occurred. Would it be possible to retry or skip that file in background? I don't want the process crashed and I don't know that.
---------------------------------------------------------------------------------
2月 04 22:16:57 lifengbao-pc onedrive[12122]: std.net.curl.CurlTimeoutException@std/net/curl.d(4094): Timeout was reached on handle 207EB60
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ----------------
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlTimeoutException).bailOut(immutable(char)[], ulong, const(char[])) [0x648034]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlTimeoutException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x647fa9]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? void std.net.curl.Curl._check(int) [0x61cea9]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x61d328]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x619f4b]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5c7553]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x5c51e8]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5d1124]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5d0b5a]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? void sync.SyncEngine.applyDifferences() [0x5cfba2]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? void main.performSync(sync.SyncEngine) [0x5bf163]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? _Dmain [0x5be93a]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5e609f]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e5fc7]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5e6044]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e5fc7]
2月 04 22:16:57 lifengbao-pc onedrive[12122]: ??:? _d_run_main [0x5e5f33]
2月 04 22:16:57 lifengbao-pc systemd[4584]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
2月 04 22:16:57 lifengbao-pc systemd[4584]: onedrive.service: Unit entered failed state.
2月 04 22:16:57 lifengbao-pc systemd[4584]: onedrive.service: Failed with result 'exit-code'.

**Comment by skilion** [comment]
Fixed in 1beadf25779a4395e993636486a01793d1afcac3. Run `onedrive --logout` after updating because there has been the switch to the new Microsoft Graph API.
