### ISSUE TITLE
Key not found: fileSystemInfo

### ISSUE THREAD

**Issue by thomasfedb** [skilion/onedrive#157]
This error is occuring immediately after starting `onedrive -m`:

```
std.json.JSONException@std/json.d(473): Key not found: fileSystemInfo
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x641951]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException, inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x6419b6]
??:? std.json.JSONValue.opIndexinout(pure ref @safe inout(std.json.JSONValue) function(immutable(char)[])) [0x5fdd9d]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5c9661]
??:? void sync.SyncEngine.applyDifferences() [0x5c86fa]
??:? void main.performSync(sync.SyncEngine) [0x5b7fb3]
??:? _Dmain [0x5b778e]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5e01f7]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e0123]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5e019c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e0123]
??:? _d_run_main [0x5e0087]
??:? main [0x5baa97]
??:? __libc_start_main [0xcb40d400]
```

If I run `onedrive --resync` then the error doesn't immediately reoccur, but occurs again a little later.

**Comment by thomasfedb** [comment]
@skilion are you still maintaining this repo? If not, are you looking for maintainers?

**Comment by jomoore** [comment]
I get this when the application tries to sync an item which has been deleted online but not locally. For some reason the JSON fetched for the deleted item doesn't contain the "deleted" key, so applyDifference() goes looking for its last modification time and falls over.

**Comment by Tekki** [comment]
Seems a deleted item no longer contains a 'deleted' property, instead the 'cTag' is missing. This isn't documented anywhere.

**Comment by thomasfedb** [comment]
To clarify, is this an API change from Microsoft or in this software package?

**Comment by Tekki** [comment]
It's on the side of Microsoft. I just noticed the same issue while I was testing my own library.

**Comment by thomasfedb** [comment]
That explains the regression when things were previously fine on my machine. How extensive would the changes required to this project be?

**Comment by Tekki** [comment]
If it's just about this issue, you can make a change at https://github.com/skilion/onedrive/blob/master/src/sync.d#L22. I just don't know what to think of an undocumented change on the API.
But we have 10 more issues here that all turn around the point that the point that the code doesn't react robust enough to errors on the side of OneDrive (timeouts, random error responses...). I'm not a D programmer, so I don't think that I can help a lot.

**Comment by Tekki** [comment]
As always, it's not as simple... There are other reasons why a delta of a file can contain no cTag. I found some deltas of photos with missing cTag that were probably accessed by OCR on OneDrive.
Another difference of deleted files is that their 'file' property is empty and contains no 'hashes'. Maybe this is the main difference. It's difficult to figure out.

**Comment by thomasfedb** [comment]
Might be time to move to the MS Graph API perhaps.

**Comment by Tekki** [comment]
Time for me, for you, or for @skilion? ;)
My impression is that things are changing a lot in these days. For example the whole explanation about how to register an app for OneDrive for Business has disappeared. On the other hand the new authentication flow doesn't work as described. At least last weekend it didn't.
The question remains if this repo is still maintained.

**Comment by thomasfedb** [comment]
Time for people who want to use OneDrive on Linux, although that most likely means somebody has to write a new daemon. There are official MS libraries for Python, Ruby, JS, which might be better than handling the REST API itself directly.

**Comment by skilion** [comment]
A workaround has been introduced in 1beadf25779a4395e993636486a01793d1afcac3
Since it contains also the switch to the new Microsoft Graph API, run `onedrive --logout`

**Comment by Tekki** [comment]
Thanks, and welcome back.

**Comment by thomasfedb** [comment]
Issues seems to be resolved on `master`. @skilion you can close this if you like.
