### ISSUE TITLE
Selective Syncing Functionality?

### ISSUE THREAD

**Issue by nbromhead** [skilion/onedrive#158]
I have been using OneDrive for a few years now on windows, and I've switched over to Ubuntu for my laptop. I am pretty new to linux but I'm loving it so far.

Is there a way to only sync certain files/directories such that I can store them locally, while still being able to see the other file names/directories on OneDrive? I have a lot of data stored on OneDrive, and I'd like to selectively download/sync things so I don't fill my ssd. This is supported on windows however I am not sure how to go about solving this on Linux. Thanks.

**Comment by skilion** [comment]
Feature added in 9dd944286f381b30b0fe656e66d69900782732a2
