### ISSUE TITLE
OneDrive not skipping directory

### ISSUE THREAD

**Issue by drdoran** [skilion/onedrive#16]
When run, the program is trying to download my entire OneDrive library, though in my config file I have it set to skip my music folder. In my config file I have:

```
skip_dir = "./Music/"
```

I have also tried some other variations but all have failed. I apologize if this is an error on my part. If so, it would be appreciated if you could direct me. Thank you for your time.

**Comment by skilion** [comment]
It should be correct to set it like this `skip_dir = ".*|Music"`. The correct path separators are added automatically.
`.*` is not needed but skipping hidden directories is a good practice under Linux.
Remember to run `onedrive --resync` whenever you change the configuration.
Also any files already downloaded in the Music folder won't be touched so you need to remove them manually.

**Comment by GrouchyGaijin** [comment]
I have tried three different ways of writing the skip directory command in the config file, but none of them are working for me.  The latest attempt was using `skip_dir = "Documents/Electronic Arts | Documents/My Games"`, but this did not work. When I run `onedrive --resync` any new files in both the Electronic Arts directory or the My Games directory are downloaded to the Linux machine.
(I don't really want a copy of all my kid's saved game data on this machine - LOL)

**Comment by drdoran** [comment]
Have you tried ``skip_dir = "Electronic Arts | My Games" `` ?

**Comment by GrouchyGaijin** [comment]
I have tried `skip_dir = "./Documents/Electronic Arts/* | ./Documents/My Games/*"`
and
`skip_dir =  "./Documents/'Electronic Arts'/*  | ./Documents/'My Games'/*" `
and
`skip_dir = "Documents/Electronic Arts | Documents/My Games"`

**Comment by GrouchyGaijin** [comment]
Does anyone else have any ideas of how to skip subdirectories?
My son plays games on a Windows machine and for some reason (OK, there is a setting specifying this, but I cannot find that setting to change it.) Steam keeps saving his game data to the My Games directory which is a subdirectory of Documents.
I have tried multiple times to tell OneDrive on the Windows machine to **not** include this folder in the sync, yet each time he plays a game the offending folder is, once again listed in OneDrive.  Once listed in OneDrive it is synced to the OneDrive online and from there downloaded onto my Linux machine.

What is the correct syntax to skip the directories which are located at:

`OneDrive/Documents/Electronic Arts`
`OneDrive/Documents/My Games`

Thank you,

GG

**Comment by drdoran** [comment]
GrouchGaijin,
I tested my previous suggestion of naming the subdirectories you wish to skip in the configuration file. It worded for me. Perhaps your problem is with the spaces in the folder name. Try using an backslash.

To clarify, I skipped the following subdirectory
``~/Directory/Skip_Me``

with the following in my configuration file
``skip_dir = "Skip_Me"``

and then ran.
``onedrive --resync``

I have a lot in my OneDrive so resyncing takes a long time, therefore, I'm not going to play around with spaces in my file names. I'm sure if you mess around some more you can get this working.

**Comment by GrouchyGaijin** [comment]
Hmmmm do I understand that you did **not** list the entire path of the subdirectory?
That is, in my case, instead of:

`skip_dir = "Documents/Electronic Arts | Documents/My Games"

I would just use:

``skip_dir = "My Games"`

I do appreciate the help!

**Comment by drdoran** [comment]
Correct! And you may also need to use an escape character for the spaces in your folder names.
First try ``skip_dir = "My Games" `` and run ``onedrive --resync``. 
If that does not work than try ``skip_dir = "My\ Games"`` and again run ``onedrive --resync``.
Hopefully this will solve your problem. Good luck!

**Comment by GrouchyGaijin** [comment]
Well the good news is that 
`skip_dir = "My Games"`
seems to work.  The problem now is getting the program to skip multiple directories.

Getting closer though!!

**Comment by drdoran** [comment]
Glad to hear that! You should be able to skip other directories by using the ``|`` key. To skip your Electronic Arts folder as well, you should be able to set your file to:
``skip_dir = "My Games | Electronic Arts"``

For further example, take a look at my configuration. I have OneDrive sync to my home folder, so I skip Desktop, Downloads and a folder called lmms.
``sync_dir = "~/"``
``skip_file = ".*|~*"``
``skip_dir = ".*|Desktop|Downloads|lmms"``

**Comment by GrouchyGaijin** [comment]
And we have a winner!!
Perhaps this is in the read me and I simply missed it, but this is working for me.
In order to skip two subdirectories of the Documents directory, in my config file I have:

`skip_dir = ".*|Electronic Arts|My Games"`

**Note: There is no space between the name of the directory and the |  On my system the directories were not skipped when I had a space.**

In other words on my system `skip_dir = ".* | Electronic Arts | My Games"` does not work, but
`skip_dir = ".*|Electronic Arts|My Games"` **does** work.

**Comment by charles-david** [comment]
Hi, I have installed your program. As mentioned above, the program was not skipping the "skip_dir" given in the config file of the user account. Whatever I did, the directories were not skipped, even if i did a "onedrive --resyn".
However, when I edited the /usr/local/etc/onedrive.conf and performed a "onedrive --resync", then the directories were correctly skipped.... I can only point the issue, don't really know where this is coming from, but maybe as it is installed as root, the config file used is the root one?

System: Opensuse 42.1 

Thanks for the good and hard work!

**Comment by leostrakosch** [comment]
> However, when I edited the /usr/local/etc/onedrive.conf and performed a "onedrive --resync", then the directories were correctly skipped....

Same problem here, on Ubuntu Mate 16.04 . Took me quite some time and I didn't think of that, thanks @charles-david !

**Comment by skilion** [comment]
Since 9dd944286f381b30b0fe656e66d69900782732a2 you can use selective sync

**Comment by speedster-pta** [comment]
I'm also struggling to get skip_dir to work. I've tried adding "skip_dir = ".*|FolderName"" to the config file but no luck with that. I can't find a onedrive.conf file anywhere on my machine, so I'm not able to edit that. Any suggestions?

**Comment by abraunegg** [comment]
The default configuration file for your user should be:
```
~/.config/onedrive/config
```
In that file, you should put:
```
skip_dir = "<dir_name>|<dir_name>|..."
```

example: To skip ~/OneDrive/blah/

```
skip_dir = "blah"
```

Once configured, then resync:

```
onedrive --resync
```
I do not know how robust the skip_dir code is however

**Comment by abraunegg** [comment]
Will have to add this to the list of things to fix

**Comment by ppreshant** [comment]
I think it is supposed to be `skip_file` instead.

From the README.md file
Available options:

    `sync_dir`: directory where the files will be synced
    `skip_file`: any files or directories that match this pattern will be skipped during sync.

**Comment by malanb5** [comment]
Yes, thanks @ppreshant.  Listing the directories (not paths to the directories) in the skip_file line is what fixed this for me.  Got to read the fine print!

**Comment by abraunegg** [comment]
@malanb5 
This feature (skip_dir) is now available in my fork. Refer to abraunegg#123 (comment) for further details

**Comment by limesqueezy** [comment]
@abraunegg 

I still cannot make it skip the whole directory. Instead it skips every single file of the directory and if a directory has `n` files you will actually get `n` lil _Skipping item - excluded by skip_dir config_ on your terminal, slowing the process extremely.

**Comment by abraunegg** [comment]
@arisioz 
Raise your query in the right location - https://github.com/abraunegg/onedrive/
