### ISSUE TITLE
Also got 404 error!

### ISSUE THREAD

**Issue by PterX** [skilion/onedrive#162]
Forget my poor english!

when i do it step by step acording #156 ,it can sync exist files.
but when is modify or add a new file,it alse post an 404 error.

watch this log.
![image](https://cloud.githubusercontent.com/assets/1871048/23830339/7810a4e0-0743-11e7-80ba-c40f74305fbe.png)

**Comment by skilion** [comment]
Try to apply the solutions of #159

**Comment by PterX** [comment]
@skilion i get the same error.

![image](https://cloud.githubusercontent.com/assets/1871048/23830623/3124e724-074a-11e7-8edc-a735dd5a5a82.png)

**Comment by skilion** [comment]
Can you post the full output after recompiling the app, uncommenting `//http.verbose = true` at line 58 of `src/onedrive.d`?

**Comment by PterX** [comment]
ok ,wait a moment.

**Comment by PterX** [comment]
This is th full output
[onedrive.log.txt](https://github.com/skilion/onedrive/files/836419/onedrive.log.txt)

**Comment by skilion** [comment]
Try to update the app. I just pushed a commit that changes how paths are handled and it may fix your error.

**Comment by PterX** [comment]
@skilion I am sorry, I have got the same error with new update.

**Comment by PterX** [comment]
@skilion this issue could be closed.

**Comment by jprady** [comment]
I have the latest version of the code, have made the client_id changes suggested in the other thread, and I'm seeing pretty much exactly the same issues.  It always happens on the same file. I can upload the logs if necessary.
