### ISSUE TITLE
Path ... contains invalid trailing character.

### ISSUE THREAD

**Issue by RJaBi** [skilion/onedrive#167]
Hi, I'm using 88d2a940782813253ea6a0581267d836a8f90a4e and getting errors that seem to be related to the folder names. Specifically I get the error messages.

>`C0514881CDD03160!128769 CorrPlots.pdf
>The file last modified time has changed
The file content has changed
Uploading: Folder/sm/300/1x1/proton+/LP/d32u32/plots/t017dt3p100/CorrPlots.pdf
sync.SyncException@src/sync.d(379): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "innerError": {
            "date": "2017-03-15T06:09:56",
            "request-id": "4b390598-efb9-488b-a313-1a9f411fcb69"
        },
        "message": "Path (\/LiveFolders\/Folder\/sm\/300\/1x1\/proton \/LP\/d32u32\/plots\/t017dt3p100\/CorrPlots.pdf) contains invalid trailing character."
    }
}
>----------------
>??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5d6c02]
??:? void main.performSync(sync.SyncEngine) [0x5c3e58]
??:? _Dmain [0x5c361c]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5ec617]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ec543]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5ec5bc]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ec543]
??:? _d_run_main [0x5ec4a7]
??:? main [0x5c6927]
??:? __libc_start_main [0xc9be4fdf]
onedrive.OneDriveException@src/onedrive.d(394): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "innerError": {
            "date": "2017-03-15T06:09:56",
            "request-id": "4b390598-efb9-488b-a313-1a9f411fcb69"
        },
        "message": "Path (\/LiveFolders\/Folder\/sm\/300\/1x1\/proton \/LP\/d32u32\/plots\/t017dt3p100\/CorrPlots.pdf) contains invalid trailing character."
    }
}
>----------------
>??:? std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0x5cc1a7]
??:? void sync.SyncEngine.uploadFileDifferences(itemdb.Item, immutable(char)[]) [0x5d78e6]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d722b]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x5d7161]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5d6a7b]
??:? void main.performSync(sync.SyncEngine) [0x5c3e58]
??:? _Dmain [0x5c361c]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5ec617]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ec543]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5ec5bc]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ec543]
??:? _d_run_main [0x5ec4a7]
??:? main [0x5c6927]
??:? __libc_start_main [0xc9be4fdf]
Segmentation fault (core dumped)
`

This is an ordianry file. Looking at this output I think the issue is likely in that the folder `proton` is actually `proton+` and it doesn't like that. Previous versions (before the API change to Graph) had no issue with folders ending with a +. Uploading folders ending with a + works fine in the official Windows 10 onedrive client and I can't find a source online anywhere saying that folder names with a + are no longer allowed. The source I can find is: https://support.office.com/en-us/article/Invalid-characters-in-file-or-folder-names-or-invalid-file-types-in-OneDrive-for-Business-64883a5d-228e-48f5-b3d2-eb39e07630fa

Is this just an issue of the path not being accurately converted? Though somewhat experienced with other languages a C style similar to dlang isn't the clearest to me so i'm not sure where to look.
Cheers

**Comment by PterX** [comment]
#166 i got the same error

**Comment by RJaBi** [comment]
Right so after far too many log statements I've determined where the issue is. Following on from the traceback in the opening post,

uploadFileDifferences -> onedrive.simpleUpload -> upload(localPath, url)

As far as I can tell the error involves the encoding of the url. This can be see in
>Folder/sm/300/1x1/proton+/LP/d32u32/plots/t017dt3p100/CorrPlots.pdf
where the encoded url is
>https://graph.microsoft.com/v1.0/me/drive/root:/Folder%2Fsm%2F300%2F1x1%2Fproton%2B%2FLP%2Fd32u32%2Fplots%2Ft017dt3p100%2FCorrPlots.pdf:/content
as generated by simpleUpload. This to my admittedly unknowledgeable eyes looks fine. The `%2F` are the URL encoding for the `/` while `%2B` is for the `+` in proton+ .

However the exception has a URL of:
>"message": "Path (\/LiveFolders\/sm\/300\/1x1\/proton \/LP\/d32u32\/plots\/t017dt3p100\/CorrPlots.pdf) contains invalid trailing character."
The `+` in proton+ is missing and instead there is a ` `. (I should note that on my terminal each `/` in that last is actually `\/` but markdown kills it.

I believe that this is the problem but I'm not sure how to go about fixing it. Would it work if I somehow coded my own `encodeComponent` which didn't encode `+`'s and just left them there? I don't know. 

If anyone else has any thoughts, i'd love to hear them.

**Comment by PterX** [comment]
@RJaBi https://dev.onedrive.com/misc/path-encoding.htm look this.
Maybe ms think '+' as space.lol

**Comment by RJaBi** [comment]
Yeah I saw that one

>When constructing the path segment of a URL for the OneDrive API, the following characters are allowed for path names, based on the URI RFC.


>  pchar       = unreserved / pct-encoded / sub-delims / ":" / "@"
  pct-encoded = "%" HEXDIG HEXDIG
  unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
  sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
              / "*" / "+" / "," / ";" / "="

>Item name characters, which are not included in the pchar group, such as # and (space), must be percent encoded.

If i'm reading this correctly, it means that onedrive doesn't need `+` to be encoded as `%2B`. I have no experience with URL encoding though.

**Comment by PterX** [comment]
@RJaBi but i'm replace %2b with + direct ,it's also get the same error.

**Comment by Tekki** [comment]
What happens if you encode the + twice, (%252b)?

**Comment by RJaBi** [comment]
I can confirm @PterX 's comment that replacing `%2b` with `+` directly doesn't work and gets the same error. Curiously in the "message" of the exception the path is still missing the + from proton despite it being there before the perform() call.

I've attached the output from both the above test (replacing with a `+` directly) and from @Tekki 's suggestion.

In Tekki's suggestion `%2B` is replaced with `%252B`. I do this using this code in simpleUpload():
>                string url = itemByPathUrl ~ encodeComponent(remotePath) ~ ":/content";
>                log.vlog("simpleUpload url: ", url);
 >               if ( url == "https://graph.microsoft.com/v1.0/me/drive/root:/Folder%2Fsm%2F300%2F1x1%2Fproton2B%2FLP%2Fd32u32%2Fplots%2Ft017dt3p100%2FCorrPlots.pdf:/content" ) {
>                  log.vlog("URL MATCH");
 >                 url = "https://graph.microsoft.com/v1.0/me/drive/root:/Folder%2Fsm%2F300%2F1x1%2Fproton%252B%2FLP%2Fd32u32%2Fplots%2Ft017dt3p100%2FCorrPlots.pdf:/content";
>                  log.vlog("decoded new url: ", decodeComponent( url ) );
>                }
>                if (eTag) {

This causes a different error. Instead we get:
>sync.SyncException@src/sync.d(379): HTTP request returned status code 412 (Precondition Failed)
{
    "error": {
        "code": "resourceModified",
        "innerError": {
            "date": "2017-03-16T23:28:16",
            "request-id": "36e350cb-446a-45de-87ce-9365e5027f10"
        },
        "message": "ETag does not match current item's value"
    }
}
I had a quick look at eTag but don't really know what it means.

The error messages in closer to full are in the below file:
[forissue.txt](https://github.com/skilion/onedrive/files/849273/forissue.txt)

Thanks for your interest.

**Comment by Tekki** [comment]
This last message means you have a sync conflict.

Many things are wrong here, on both sides.
It is not necessary to encode the whole file path, as you can see in the examples at the bottom of https://dev.onedrive.com/misc/path-encoding.htm. This only causes troubles.
On the other hand, the documentation is wrong when it lists the '+' under the characters that don't have to be encoded (and lists the ':' too, which is the sign for the end of the path). The API follows a process similar to the one described in https://url.spec.whatwg.org/#urlencoded-parsing, this means '+' is interpreted as an encoded space. The same happens on the old api.onedrive.com/v1.0, that I use since a long time. I'm not sure if this is a recent change. Probably I never tried to upload a file or folder with '+'.
What we can do in this project is not to use 'encodeComponent', but to write a function that only encodes the parts of the path between the slashes. In Perl, I would use a regex like:
`$path =~ s/([^A-Za-z0-9\-._~/])/sprintf '%%%02X', ord $1/ge`
I'm sure somebody can translate this into D.
Another possibility would be to split the path at '/', call encodeComponent on this array and then join it again.

**Comment by PterX** [comment]
@Tekki I try it ,but didn't work,mostly likely ms's api error.

**Comment by PterX** [comment]
@RJaBi pls create an issues here, https://github.com/OneDrive/onedrive-api-docs/issues

**Comment by Tekki** [comment]
@PterX It's definitely not an issue on the side of Microsoft (besides the unclear documentation). If you make correct requests, you can create folders with trailing '+'. What works on Perl, has to work on D too. ;)
For example, to ceate a 'Tekki Testfolder+' inside 'Documents', the path in the request has to look like this:
`root:/Documents/Tekki%20Testfolder%2B:`

**Comment by PterX** [comment]
Just look my log output,ths post url look like correct.
![111](https://cloud.githubusercontent.com/assets/1871048/24081958/9bb00aac-0cf8-11e7-81e0-7d689c4beab4.png)
![12](https://cloud.githubusercontent.com/assets/1871048/24081959/9be6cc4a-0cf8-11e7-929a-0d465af8ef25.png)

**Comment by Tekki** [comment]
You're correct, it's 'definitely' getting strange...

![skilion-onedrive-167](https://cloud.githubusercontent.com/assets/466122/24082370/c0e64c02-0cc4-11e7-9c24-3051a25df4d3.png)

**Comment by Tekki** [comment]
I've opened an issue at OneDrive API Docs: https://github.com/OneDrive/onedrive-api-docs/issues/555
@PterX please add more information if I've forgotten something.

**Comment by Tekki** [comment]
We have an answer from Microsoft and they confirm it is a bug (as @PterX said from beginning): _"We actually have a fix for this rolling out soon."_
I'll keep you informed when things work as expected.

**Comment by PterX** [comment]
@Tekki  OK, thanks for your help.

**Comment by Tekki** [comment]
Microsoft has deployed a patch today. In my tests it works now.

**Comment by PterX** [comment]
In my tests it work yet.

**Comment by RJaBi** [comment]
Also in mine it works.

Thanks for all your help @Tekki and @PterX
