### ISSUE TITLE
Authorization page not found

### ISSUE THREAD

**Issue by GrouchyGaijin** [skilion/onedrive#17]
I can almost get the program to run.  I get to the part where I open the link to authorize the program to access my onedrive.  The link I am given to click is:

https://login.live.com/oauth20_authorize.srf?client_id=000000004C15842F&scope=wl.offline_access%20onedrive.readwrite&response_type=code&redirect_url=https://login.live.com/oauth20_desktop.srf

 and when I click that link I get this:

Firefox can't find the server at bd504287-a598-4f00-a88d-8028e217e2de.apps.dev.live.com.

**Comment by stz184** [comment]
It is normal, I got confused too. 
Just copy/paste the link back to the terminal and you will be ok.

**Comment by GrouchyGaijin** [comment]
Thanks!  It seems to be downloading everything in my OneDrive now.
So it looks like if I set the command onedrive -m to run as startup item the program should monitor the OneDrive directory on my Linux machine for any changes and then upload new files to OneDrive automatically.  Is that correct?

**Comment by skilion** [comment]
Yes, check the README for how to install it as a service.
