### ISSUE TITLE
Incorrect README

### ISSUE THREAD

**Issue by jeanlucthumm** [skilion/onedrive#170]
Under "**Configuration**" in `README.md`, the instructions to copy the default config file are incorrect. The instructions should be as follows:
```
mkdir -p ~/.config/onedrive
cp /usr/share/onedrive/config.default ~/.config/onedrive/config
```

**Comment by Scimmia22** [comment]
No, it shouldn't. It's instructions are for installing directly from source, and the default config isn't installed.

**Comment by jeanlucthumm** [comment]
Oh I see, in that case I do apologize. I came across the README after installing from the AUR and was looking for setup instruction. Perhaps there should be a mention of  `/usr/share` for those who installed it, however, since there is no man page and GitHub seems to be the only place where `onedrive` is documented. Or maybe the PKGBUILD should output a reference to it?

**Comment by Scimmia22** [comment]
It's in the sticky comments in the AUR, that's about all the documentation you're going to get with AUR packages.
