### ISSUE TITLE
Shared Folders Not Included?

### ISSUE THREAD

**Issue by benyanke** [skilion/onedrive#173]
Most of my OneDrive folders for work are owned by another user, and then shared to me. The web interface and official client include these in the sync, but this one does.

I assume this is a known issue, and is there any timeline for resolution on this?

**Comment by beffardo** [comment]
In the readme.md it is written that Shared Folders are not supported, but if you take a look in here https://github.com/skilion/onedrive/issues/8, it seems that works are in progress.

**Comment by skilion** [comment]
Experimental support for shared folders added with ab592f1
