### ISSUE TITLE
Bandwidth Throttling

### ISSUE THREAD

**Issue by ghost** [skilion/onedrive#174]
Any chance I can make a request for bandwidth throttling to be included?

Great job on this mate, and very glad to see there's active development happenning! :) 👍

**Comment by thomasfedb** [comment]
@kpirnie this might be able to be done using iptables? Otherwise, it shouldn't be two difficult to offer a `--limit-rate` argument and pass through to libcurl, would you be keen to attempt a PR?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
