### ISSUE TITLE
No network connection

### ISSUE THREAD

**Issue by mikelovesthai** [skilion/onedrive#175]
Help. I was getting the 404 error so removed the whole onedrive installation plus config files and started again with the latest version. All installed fine but now I get "No network connection" when I run onedrive:

mike@server:~/serverE/onedrive-master$ sudo make
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
mike@server:~/serverE/onedrive-master$ sudo make install
install onedrive /usr/local/bin/onedrive
install -m 644 onedrive.service /usr/lib/systemd/user
mike@server:~/serverE/onedrive-master$ ./onedrive
No network connection

**Comment by tanpro260196** [comment]
Same issue here, Ubuntu 16.10.

**Comment by fiercebrake** [comment]
Same issue, latest build, ubuntu 17

**Comment by mikelovesthai** [comment]
Thanks. Reinstalling the dependencies fixed the issue for me too.

**Comment by varunagrawal** [comment]
I am currently facing this issue and the above mentioned fix doesn't seem to work for me.
