### ISSUE TITLE
skip_file/skip_dir configuration changed?

### ISSUE THREAD

**Issue by hugomilan** [skilion/onedrive#176]
I realized that in a recent update the skip_dir configuration was removed and that I should just put the folders I want to ignore in the skip_file (such as skip_file = "....|folder|folder1/something else|..."). However, these folders are being synchronized (even if I use skip_dir = "..." for the folder paths). (Yes, I do --resync after changing config). What am I missing?

**Comment by skilion** [comment]
[Selective sync](https://github.com/skilion/onedrive#selective-sync) was introduced for syncing only specific files.
So now `skip_file` just is just a mask for particular file names (and directory names) to skip (ex. hidden files).
Something like `skip_file = "folder1/fileX"` won't work anymore

**Comment by hugomilan** [comment]
Thanks. Is there any other way to set what folder to skip as before (i.e., when we set up skip_dir)? Or should I write the sync_list to tell exactly what I want to synchronize?

**Comment by skilion** [comment]
The two things are mutually exclusive and selective sync seemed to me the most reasonable thing to implement. So now you have to tell exactly what you want to synchronize in `sync_list`.

**Comment by hugomilan** [comment]
Alright, thanks for clarifying!

**Comment by abraunegg** [comment]
@hugomilan 
This feature (skip_dir) is now available in my fork. Refer to https://github.com/abraunegg/onedrive/issues/123#issuecomment-466696653 for further details
