### ISSUE TITLE
README: libcurl-dev is a "virtual package" on Ubuntu 16.04

### ISSUE THREAD

**Issue by knjmooney** [skilion/onedrive#177]
This is only an issue with the README.
```
 -> sudo apt install libcurl-dev
[sudo] password for knjmooney: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libcurl-dev is a virtual package provided by:
  libcurl4-openssl-dev 7.47.0-1ubuntu2.2
  libcurl4-nss-dev 7.47.0-1ubuntu2.2
  libcurl4-gnutls-dev 7.47.0-1ubuntu2.2
You should explicitly select one to install.

E: Package 'libcurl-dev' has no installation candidate
```
I installed `libcurl4-gnutls-dev` and the installation worked ok from there.

**Comment by mikeholler** [comment]
I also had this issue and this fixed it. I'm on Ubuntu 16.04, Gnome variant.

**Comment by obrobertsen** [comment]
Solution also working on Ubuntu 16.10, 
Thx. to knjmooney.

**Comment by skilion** [comment]
The README has been improved

**Comment by JordanPerezM** [comment]
Solution to  install
source("http://bioconductor.org/biocLite.R")
biocLite("biomaRt")

Problem:
 In install.packages(pkgs = pkgs, repos = repos, dependencies = dependencies, : installation of package 'RCurl' had non-zero exit status

Thanks a lot

**Comment by MKHDNP** [comment]
Thank you #knjmooney support
