### ISSUE TITLE
Seg fault - Problem with the SSL CA cert 

### ISSUE THREAD

**Issue by baja0006** [skilion/onedrive#178]
onedrive.OneDriveException@src/onedrive.d(371): Problem with the SSL CA cert (pa                                                                                        th? access rights?) on handle 55713AFAAAF0
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0x3a35e931]
??:? std.json.JSONValue onedrive.OneDriveApi.perform(const(void)[]) [0x3a35e58f]
??:? std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], con                                                                                        st(char)[]) [0x3a361502]
??:? bool onedrive.OneDriveApi.authorize() [0x3a35afe2]
??:? bool onedrive.OneDriveApi.init() [0x3a35aa9e]
??:? _Dmain [0x3a35562f]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x3a37e593]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*)                                                                                        .tryExec(scope void delegate()) [0x3a37e4bb]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*)                                                                                        .runAll() [0x3a37e538]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*)                                                                                        .tryExec(scope void delegate()) [0x3a37e4bb]
??:? _d_run_main [0x3a37e427]
??:? main [0x3a35914f]
??:? __libc_start_main [0xedf5e3f0]
std.net.curl.CurlException@std/net/curl.d(4097): Problem with the SSL CA cert (p                                                                                        ath? access rights?) on handle 55713AFAAAF0
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(                                                                                        immutable(char)[], ulong, const(char[])) [0x3a3df968]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).en                                                                                        force(bool, lazy const(char)[], immutable(char)[], ulong) [0x3a3df8dd]
??:? void std.net.curl.Curl._check(int) [0x3a3b52b4]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x3                                                                                        a3b5708]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x3                                                                                        a3b232b]
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0x3a35e8c6]
??:? std.json.JSONValue onedrive.OneDriveApi.perform(const(void)[]) [0x3a35e58f]
??:? std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], con                                                                                        st(char)[]) [0x3a361502]
??:? bool onedrive.OneDriveApi.authorize() [0x3a35afe2]
??:? bool onedrive.OneDriveApi.init() [0x3a35aa9e]
??:? _Dmain [0x3a35562f]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x3a37e593]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*)                                                                                        .tryExec(scope void delegate()) [0x3a37e4bb]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*)                                                                                        .runAll() [0x3a37e538]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*)                                                                                        .tryExec(scope void delegate()) [0x3a37e4bb]
??:? _d_run_main [0x3a37e427]
??:? main [0x3a35914f]
??:? __libc_start_main [0xedf5e3f0]
Segmentation fault (core dumped)

**Comment by skilion** [comment]
This error is related to your SSL certificates and it is not a problem of the app itself

**Comment by stockbsd** [comment]
how to solve this problem?
when I upgrade my ubuntu's some packages, the onedrive reports the sanme error:  Problem with the SSL CA cert

**Comment by abraunegg** [comment]
@stockbsd 
The 'skilion' github site is defunct. The code in this repository appears to have been abandoned and contains many other issues that have not been fixed. It contains defects that put you at risk of data loss and corruption.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone & build from here: https://github.com/abraunegg/onedrive

Specific to your issue - your Ubuntu OS is most likely missing CA certs. You need to fix that yourself.
