### ISSUE TITLE
Curl Exception...

### ISSUE THREAD

**Issue by softwareuser99** [skilion/onedrive#180]
Hi there, first of all a massive thank you for working on this sync client, it's a stellar piece of software, ottimo lavoro :-)

On LinuxMint with all updates installed, I get the following error around CURL, not sure whether this is something you are aware of...

Cheers!

`Apr 09 10:24:31 xxxxx onedrive[32247]: std.net.curl.CurlException@std/net/curl.d(4097): Failure when receiving data from the peer on handle 2007C00
Apr 09 10:24:31 xxxxx onedrive[32247]: ----------------
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, const(char[])) [0x64a268]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x64a1dd]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? void std.net.curl.Curl._check(int) [0x61fbb4]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x620008]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x61cc2b]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5c81ab]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x5c5f4c]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5d4a24]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5d4465]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? void sync.SyncEngine.applyDifferences() [0x5d3213]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? void main.performSync(sync.SyncEngine) [0x5c0a3b]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? _Dmain [0x5c0268]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5e8e93]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e8dbb]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5e8e38]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e8dbb]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? _d_run_main [0x5e8d27]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? main [0x5c3a47]
Apr 09 10:24:31 xxxxx onedrive[32247]: ??:? __libc_start_main [0x21e0c82f]
Apr 09 10:24:31 xxxxx systemd[1845]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Apr 09 10:24:31 xxxxx systemd[1845]: onedrive.service: Unit entered failed state.
Apr 09 10:24:31 xxxxx systemd[1845]: onedrive.service: Failed with result 'exit-code'.
`

**Comment by softwareuser99** [comment]
Maybe just to add, this happens after syncing successfully for 5-10 minutes or so... Attached the log in txt given linebreaks above.

[curl-exception.txt](https://github.com/skilion/onedrive/files/908070/curl-exception.txt)


My system info:
System:    Host: laptop Kernel: 4.4.0-72-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.2) dm: mdm Distro: Linux Mint 18.1 Serena
Machine:   System: LENOVO (portable) product: 20CLS0DE00 v: ThinkPad X250 Chassis: type: 10
           Mobo: LENOVO model: 20CLS0DE00 Bios: LENOVO v: N10ET46W (1.25 ) date: 11/28/2016
CPU:       Dual core Intel Core i5-5300U (-HT-MCP-) cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 9179
           clock speeds: min/max: 500/2900 MHz 1: 2300 MHz 2: 2300 MHz 3: 2300 MHz 4: 2300 MHz
Graphics:  Card: Intel Broadwell-U Integrated Graphics bus-ID: 00:02.0 chip-ID: 8086:1616
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.04hz, 1600x900@60.01hz
           GLX Renderer: Mesa DRI Intel HD Graphics 5500 (Broadwell GT2)
           GLX Version: 3.0 Mesa 12.0.6 Direct Rendering: Yes
Audio:     Card-1 Intel Wildcat Point-LP High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0 chip-ID: 8086:9ca0
           Card-2 Intel Broadwell-U Audio Controller
           driver: snd_hda_intel bus-ID: 00:03.0 chip-ID: 8086:160c
           Sound: Advanced Linux Sound Architecture v: k4.4.0-72-generic
Network:   Card-1: Intel Ethernet Connection (3) I218-LM
           driver: e1000e v: 3.2.6-k port: 3080 bus-ID: 00:19.0 chip-ID: 8086:15a2
           IF: enp0s25 state: down mac: <filter>
           Card-2: Intel Wireless 7265 driver: iwlwifi bus-ID: 03:00.0 chip-ID: 8086:095b
           IF: wlp3s0 state: up mac: <filter>
Drives:    HDD Total Size: 1000.2GB (55.2% used)
           ID-1: /dev/sda model: Samsung_SSD_850 size: 1000.2GB serial: S2RFNX0J208246L
Partition: ID-1: / size: 909G used: 507G (59%) fs: ext4 dev: /dev/dm-1
           ID-2: /boot size: 473M used: 269M (60%) fs: ext2 dev: /dev/sda2
           ID-3: swap-1 size: 8.46GB used: 0.12GB (1%) fs: swap dev: /dev/dm-3
RAID:      System: supported: N/A
           No RAID devices: /proc/mdstat, md_mod kernel module present
           Unused Devices: none
Sensors:   System Temperatures: cpu: 54.0C mobo: N/A
           Fan Speeds (in rpm): cpu: 3668
Repos:     Active apt sources in file: /etc/apt/sources.list.d/d-apt.list
           deb http: //master.dl.sourceforge.net/project/d-apt/ d-apt main #APT repository for D
           Active apt sources in file: /etc/apt/sources.list.d/graysky-utils-xenial.list
           deb http: //ppa.launchpad.net/graysky/utils/ubuntu xenial main
           deb-src http: //ppa.launchpad.net/graysky/utils/ubuntu xenial main
           Active apt sources in file: /etc/apt/sources.list.d/megasync.list
           deb https: //mega.nz/linux/MEGAsync/xUbuntu_16.04/ ./
           Active apt sources in file: /etc/apt/sources.list.d/nathan-renniewaldock-flux-xenial.list
           deb http: //ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu xenial main
           deb-src http: //ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu xenial main
           Active apt sources in file: /etc/apt/sources.list.d/nextcloud-devs-client-xenial.list
           deb http: //ppa.launchpad.net/nextcloud-devs/client/ubuntu xenial main
           deb-src http: //ppa.launchpad.net/nextcloud-devs/client/ubuntu xenial main
           Active apt sources in file: /etc/apt/sources.list.d/official-package-repositories.list
           deb http: //linuxmintpkg.efemef.ovh serena main upstream import backport
           deb http: //archive.ubuntu.com/ubuntu xenial main restricted universe multiverse
           deb http: //archive.ubuntu.com/ubuntu xenial-updates main restricted universe multiverse
           deb http: //archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse
           deb http: //security.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse
           deb http: //archive.canonical.com/ubuntu/ xenial partner
           Active apt sources in file: /etc/apt/sources.list.d/sebastian-stenzel-cryptomator-xenial.list
           deb http: //ppa.launchpad.net/sebastian-stenzel/cryptomator/ubuntu xenial main
           deb-src http: //ppa.launchpad.net/sebastian-stenzel/cryptomator/ubuntu xenial main
           Active apt sources in file: /etc/apt/sources.list.d/spotify.list
           deb http: //repository.spotify.com stable non-free
           Active apt sources in file: /etc/apt/sources.list.d/teejee2008-ppa-xenial.list
           deb http: //ppa.launchpad.net/teejee2008/ppa/ubuntu xenial main
           deb-src http: //ppa.launchpad.net/teejee2008/ppa/ubuntu xenial main
           Active apt sources in file: /etc/apt/sources.list.d/unit193-encryption-xenial.list
           deb http: //ppa.launchpad.net/unit193/encryption/ubuntu xenial main
           deb-src http: //ppa.launchpad.net/unit193/encryption/ubuntu xenial main
Info:      Processes: 229 Uptime: 22:47 Memory: 3251.5/7853.5MB
           Init: systemd v: 229 runlevel: 5 default: 2 Gcc sys: 5.4.0
           Client: Unknown python2.7 client inxi: 2.2.35

**Comment by softwareuser99** [comment]
possibly related threadç https://github.com/skilion/onedrive/issues/11

**Comment by thomasfedb** [comment]
@softwareuser99 does this issue occur with the latest codebase? If not, could you close this issue please.

**Comment by abraunegg** [comment]
@softwareuser99 
Can you please provide an update on this issue. If this is no longer valid, please can you close this case.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
