### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by dylanjewel** [skilion/onedrive#183]
Am having several problems, want to just wipe it all & reinstall see what that does. How do I do this?

**Comment by maunmaun** [comment]
navigate to wherever you saved your source (something like ~/onedrive_code) then
sudo make uninstall

To remove config files:
rm -rf ~/.config/onedrive

**Comment by julian-0** [comment]
Hi, I tried to uninstall following the steps, but when I run `onedrive --version` I still getting `onedrive v2.3.13-1build2` as a response.

Also the folder onedrive and all my files still there, am I missing something?

Thanks

**Comment by abraunegg** [comment]
@julian-0 
Any version < 1.1.4 is the code from this repo.

Any version > 2.0.0 is *not* associated with this GitHub repo. Please redirect yourself to: https://github.com/abraunegg/onedrive

To solve your question - you are running a Ubuntu package version, also, a version that contains bugs. You need to remove the package to remove the client.
