### ISSUE TITLE
OneDriveException@src/onedrive.d(387): HTTP request returned status code 416 

### ISSUE THREAD

**Issue by softwareuser99** [skilion/onedrive#186]
Hi there,

first of all, thank you so much for working on this project, it's a great little tool and I really appreciate the time and effort you are putting into this for all of us!

I have a little problem and I was wondering if you could help me. Below some system specs:

OS:
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

Onedrive client latest version as per your git

Below is the error message I am getting when turning on the verbose option. I have tried the "resync" option, however I keep getting the below message. It may be worth noting that I sync over 500 GB of data this way.

Would you have any suggestion as to how I can further debug this issue?

Thanks!

```
user@laptop ~ $ onedrive -v
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/user/XXXXXXXXXXXXX
Initializing the Synchronization Engine ...
Trying to restore the upload session ...
Continuing the upload session ...
Uploading fragment: 838860800-849346560/21357384104
onedrive.OneDriveException@src/onedrive.d(387): HTTP request returned status code 416 (Requested Range Not Satisfiable)
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.uploadFragment(const(char)[], immutable(char)[], long, long, long) [0x5c6aa5]
??:? std.json.JSONValue upload.UploadSession.upload() [0x5d9afc]
??:? void sync.SyncEngine.init() [0x5d2e35]
??:? _Dmain [0x5c0258]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5e8e93]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e8dbb]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5e8e38]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e8dbb]
??:? _d_run_main [0x5e8d27]
??:? main [0x5c3a47]
??:? __libc_start_main [0xeeec882f]
Segmentation fault
user@laptop ~ $ 
```

**Comment by dephekt** [comment]
Steps to repro:
* OAuth local onedrive client to Microsoft account
* Run ``onedrive`` and it downloads everything to /home/OneDrive
* Add a new directory, i.e. ``Movies``
* Add a folder inside ``Movies`` i.e. /home/OneDrive/Movies/Something
* Add video file and some images to the ``Something`` directory
* Execute onedrive -m to upload the changes
* Segmentation fault is encountered. Some files uploaded, some not.

```
$ onedrive -m
Continuing the upload session ...
onedrive.OneDriveException@src/onedrive.d(387): HTTP request returned status code 416 (Requested Range Not Satisfiable)
----------------
??:? std.json.JSONValue onedrive.OneDriveApi.uploadFragment(const(char)[], immutable(char)[], long, long, long) [0x5c5de9]
??:? std.json.JSONValue upload.UploadSession.upload() [0x5d5f70]
??:? void sync.SyncEngine.init() [0x5cf345]
??:? _Dmain [0x5bf5ac]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x5e4d0b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e4c3b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5e4cb4]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e4c3b]
??:? _d_run_main [0x5e4bab]
??:? main [0x5c2e3f]
??:? __libc_start_main [0x4075082f]
Segmentation fault (core dumped)
```

**Comment by thomasfedb** [comment]
@softwareuser99 @dephekt does this issue occur with the latest codebase? If not, could you close this issue please.

**Comment by dephekt** [comment]
I couldn't say, I started using rclone.

**Comment by evencarmer** [comment]
It's happening with me too. Latest version in Debian Sid 1.1.20170919-2
Continuing the upload session ...
`onedrive.OneDriveException@src/onedrive.d(396):` HTTP request returned status code 416 (Requested Range Not Satisfiable)
----------------
0x556d491908b3 ???
	???:0
0x556d4918f3da ???
	???:0
0x556d4919af36 ???
	???:0
0x556d4919604b ???
	???:0
0x556d4918b957 ???
	???:0
0x556d492df74e ???
	???:0
0x556d492df8be ???
	???:0
0x556d492dfc7a ???
	???:0
0x556d492df8be ???
	???:0
0x556d492dfa50 ???
	???:0
0x556d4918ada3 ???
	???:0
0x7fe4fadfff29 __libc_start_main
	???:0
0x556d49182b99 ???
	???:0
0xffffffffffffffff ???
	???:0
Segmentation fault (core `dumped)`
After adding folders locally then adding movies etc...

**Comment by evencarmer** [comment]
sorry about the bold formatting- unsure why it happened..?

**Comment by thomasfedb** [comment]
You need to wrap your logs in a code block. The Markdown documention is linked in the UI. Just put a triple backtick before and after.

**Comment by evencarmer** [comment]
yeah thanks sorry, I just deleted the post. Same thing is happening to me anyway with 1.1.20170919-2 from Debian Sid repository. The error was pretty much as posted above. I created a folder locally then added files to it. I think I'll stick to a browser upload for now, thanks :)

**Comment by abraunegg** [comment]
@softwareuser99 @evencarmer 

Does the issue still occur with all the changes posted in #314 ?

**Comment by abraunegg** [comment]
@softwareuser99 @evencarmer
Can you please provide an update. If this is no longer an issue, please close this case.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
