### ISSUE TITLE
running onedrive from cron job not working

### ISSUE THREAD

**Issue by donerler** [skilion/onedrive#187]
Hi,

I use the onedrive -v command from a bash script using cron jobs in Ubuntu. When I run the script from the terminal, the sync with onedrive works as expected. But running the same script using cron job, it doesn't do anything. After outputting the result to a log file, onedrive -v does not output anything. What am I doing wrong (I'm not a linux guru)?

Thank you.

**Comment by Tekki** [comment]
Maybe you forgot to write the full path to onedrive into the cronjob?

**Comment by donerler** [comment]
@Tekki Thanks. That seems to heve solved the issue
