### ISSUE TITLE
x86_64-suse-linux/bin/ld: cannot find -lphobos2

### ISSUE THREAD

**Issue by colourful-land** [skilion/onedrive#19]
Behaviour:

    > make
    dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl patch/etc_c_curl.d patch/std_net_curl.d src/config.d src/itemdb.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
    /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lphobos2
    collect2: error: ld returned 1 exit status
    --- errorlevel 1
    Makefile:20: recipe for target 'onedrive' failed
    make: *** [onedrive] Error 1

What I did check:

Check1: libphobos is mentioned in DFLAGS and the paths exists
```
$ cat /etc/dmd.conf
[Environment64]
DFLAGS=-I/usr/include/dlang/dmd-2.069.2/phobos -I/usr/include/dlang/dmd-2.069.2/druntime -L-L/usr/lib64 -L--export-dynamic
```
Check2: the .so files exists and in the right place:

```
$ ls /usr/lib64/*phobos*
/usr/lib64/libphobos2-ldc-debug.so.2.0.67  /usr/lib64/libphobos2-ldc.so.67  /usr/lib64/libphobos2.so.0.69.2
/usr/lib64/libphobos2-ldc-debug.so.67      /usr/lib64/libphobos2.so
/usr/lib64/libphobos2-ldc.so.2.0.67        /usr/lib64/libphobos2.so.0.69
```
Check3: changed Makefile from
```
DFLAGS = -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl
```
to:
```
DFLAGS = -v -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl
```
Run make again to observe that the linker commandline is:
```
gcc onedrive.o -o onedrive -m64 -lcurl -lsqlite3 -ldl -L/usr/lib64 -Xlinker --export-dynamic -Xlinker -Bstatic -lphobos2 -Xlinker -Bdynamic -lpthread -lm -lrt -ldl
```
This is to confirm that -L/usr/lib64 is used in linker.

Any hint? Strange enough, there was no error about not finding -lcurl or -lsqlite3, but curl/sqlite3 libraries are in /usr/lib64 just like -lphobos2

**Comment by zhangweiwu** [comment]
I don't know why lphobos2 should be statically linked, so I removed -Bstatic for it. Then I can obtain an executable successfully but it won't run.
```
$ gcc onedrive.o -o onedrive -m64 -lsqlite3 -ldl -L/usr/lib64 -Xlinker --export-dynamic -Xlinker  -lphobos2 -Xlinker -Bdynamic -lpthread -lm -lrt -ldl
$ ./onedrive 
Fatal Error while loading '/usr/lib64/libphobos2.so.0.69':
	The module 'std.net.curl' is already defined in './onedrive'.

```

**Comment by skilion** [comment]
Should not be a problem anymore since 9a9137e
