### ISSUE TITLE
bash: /usr/bin/onedrive: No such file or directory

### ISSUE THREAD

**Issue by 243750496** [skilion/onedrive#193]
Q1:what happed why can not git
```
git clone git@github.com:skilion/onedrive.git
Cloning into 'onedrive'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Q2:if i type the command one drive , it said no such file or directory,  but it's certain that i do installed.
![onedrive](https://user-images.githubusercontent.com/6311930/26913897-89c92034-4c50-11e7-9cf0-1889393d1d13.png)

`atc@ATC:~/onedrive$ onedrive
bash: /usr/bin/onedrive: No such file or directory
`

**Comment by papachaotica** [comment]
@1: you are not allowed to connet git@github.com:skilion/onedrive.git, this
is a ssh connection. try https://github.com/skilion/onedrive.git

@2: try apt-get reinstall onedrive

2017-06-08 7:44 GMT+02:00 243750496 <notifications@github.com>:

**Comment by skilion** [comment]
To install the application follow [this](https://github.com/skilion/onedrive#setup)
