### ISSUE TITLE
Couldn't resolve host name on handle 

### ISSUE THREAD

**Issue by obrobertsen** [skilion/onedrive#195]
Have this on a ubuntu 16.10 laptop, and it's working after installing.
But when rebooting my WLAN is not connecting to SSID before 2-3 seconds later.

Tried this but still not working:
https://unix.stackexchange.com/questions/126009/cause-a-script-to-execute-after-networking-has-started

Here are the error log:
june 15 07:47:55 mylaptop onedrive[1756]: onedrive.OneDriveException@src/onedrive.d(375): Couldn't resolve host name on handle BB38E0

**I think the program should handle program exception, and retry and handle network/suspend**

**Comment by skilion** [comment]
Fixed in 9e2123249aa9db794327871d3a48a5e543ed63e5
