### ISSUE TITLE
Not a Issues - nice to know

### ISSUE THREAD

**Issue by papachaotica** [skilion/onedrive#197]
http://ftp.papachaotica.de/debian/pool/onedrive
you can donwload builded packages for debian/ubuntu
on the direktory strukture you can see, setup a repository for is in progress

**Comment by leonardoteck** [comment]
@papachaotica It was of great help! I wasn't able to compile. Thanks

**Comment by papachaotica** [comment]
The packages are now available, directly with apt-get.

Install the Reprositoy key install:
apt-key adv --recv -keys --keyserver keyserver.ubuntu.com 54C878E9
or:
wget -O - http://ftp.papachaotica.de/debian/apt-key.gpg | apt-key add -

Then the entry into the sources.list:
deb http://ftp.papachaotica.de/debian experimental onedrive


I have rebuilt the packages, with the version number 0.0.0.2017xxxx
To ensure better handling with future versions

To get automatic updates from this repository in the future, you must
uninstall the onedrive package manually and re-install it via apt-get

2017-06-18 3:23 GMT+02:00 Leonardo Costa <notifications@github.com>:

**Comment by skilion** [comment]
not an issue
