### ISSUE TITLE
Segfault w/ latest code

### ISSUE THREAD

**Issue by snhirsch** [skilion/onedrive#198]
I was pleased to see that OneDrive for business is supported and decided to give it a try.  Everything went fine for a while during initial sync, but then it blew up with:

core.exception.RangeError@src/qxor.d(30): Range violation
----------------
??:? _d_arrayboundsp [0x5ed51e]
src/qxor.d:30 nothrow @safe void qxor.QuickXor.put(scope const(ubyte)[]...) [0x5d4bb4]
src/util.d:72 nothrow @safe int util.computeQuickXorHash(immutable(char)[]).__foreachbody2(ref ubyte[]) [0x5e0f7c]
/usr/include/dmd/phobos/std/stdio.d:4400 int std.stdio.ChunksImpl.opApply!(nothrow @safe int delegate(ref ubyte[])).opApply(scope nothrow @safe int delegate(ref ubyte[])) [0x5c240e]
src/util.d:71 immutable(char)[] util.computeQuickXorHash(immutable(char)[]) [0x5e0e41]
src/sync.d:90 bool sync.testFileHash(immutable(char)[], ref const(itemdb.Item)) [0x5d98fb]
src/sync.d:335 bool sync.SyncEngine.isItemSynced(itemdb.Item, immutable(char)[]) [0x5db68f]
src/sync.d:267 void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5db027]
src/sync.d:251 void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5dabae]
src/sync.d:169 void sync.SyncEngine.applyDifferences() [0x5d9dd7]
src/main.d:169 void main.performSync(sync.SyncEngine) [0x5c86af]
src/main.d:99 _Dmain [0x5c7ed0]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x5f0b7b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5f0aab]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5f0b24]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5f0aab]
??:? _d_run_main [0x5f0a1b]
??:? main [0x5cc08b]
??:? __libc_start_main [0x22299b34]
Segmentation fault (core dumped)

This happens on all operations now:  Simple sync, attempted resync, etc.

Let me know if you need any more information to troubleshoot?

Update:  I moved the sqlite file aside and ran --resync.  It blew up with the same error with the sqlite file growing to exactly the same size.  So, 100% repeatable.

**Comment by skilion** [comment]
Fixed in 1581c6989aff571b694473c3e24e4438db9675e1, thanks for reporting this
