### ISSUE TITLE
sync.SyncException@src/sync.d(182): HTTP request returned status code 500 (Internal Server Error)

### ISSUE THREAD

**Issue by papachaotica** [skilion/onedrive#199]
sync.SyncException@src/sync.d(182): HTTP request returned status code 500 (Internal Server Error)
----------------
??:? void sync.SyncEngine.applyDifferences() [0x5efeed]
??:? void main.performSync(sync.SyncEngine) [0x5e10cb]
??:? _Dmain [0x5e0c81]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x60620f]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x60613f]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x6061b8]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x60613f]
??:? _d_run_main [0x6060af]
??:? main [0x5e4a59]
??:? __libc_start_main [0x62055b44]
onedrive.OneDriveException@src/onedrive.d(392): HTTP request returned status code 500 (Internal Server Error)
----------------
??:? void onedrive.OneDriveApi.checkHttpCode() [0x5e7fff]
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5e778f]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x5e6513]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5f0728]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5f0548]
??:? void sync.SyncEngine.applyDifferences() [0x5efc85]
??:? void main.performSync(sync.SyncEngine) [0x5e10cb]
??:? _Dmain [0x5e0c81]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x60620f]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x60613f]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x6061b8]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x60613f]
??:? _d_run_main [0x6060af]
??:? main [0x5e4a59]
??:? __libc_start_main [0x62055b44]

**Comment by skilion** [comment]
Error 500 is difficult to debug because is an internal server error of OneDrive. It usually go away after a while. If it is recurrent please describe the steps to reproduce it.
