### ISSUE TITLE
onedrive authentication broken link...

### ISSUE THREAD

**Issue by murrayf** [skilion/onedrive#2]
Hi,

  Yesterday a tried your first release but I got an error in the first run... When authenticating program shows a broken link, there is a blank space aproximately in the middle of the link making the authentication not possible. I tried an "&" for this blank space but microsoft did not indicated me any url link to provide to onedrive.

Thanks,

Alberto.

**Comment by skilion** [comment]
The space in that link is correct, most browser should encode it automatically to `%20`. To be safe I've changed it in the code anyway.
After you give the permission, you get redirected to a new URL (which finishes with `?code=xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`) that, at least for now, points to broken/empty web page. That URL is the response that the app expects.

**Comment by murrayf** [comment]
Hi again skilion,

Thanks for your "%20" fix, until that point everything goes ok except 
the last part you mention regarding to the microsoft back url which is 
broken for me too...

Anyway, I'd notice you didn't mention in the README repo file that 
onedrive's Makefile needs D lang compiler dmd to complie correctly 
which can be downloaded from here: http://dlang.org/download.html

Maybe it could be useful for someone.

Thanks a lot for your help,

Alberto.

:)
