### ISSUE TITLE
onedrive daemon service failed

### ISSUE THREAD

**Issue by incomingstick** [skilion/onedrive#20]
Terminal ouput:
[user@localhost ~]$ systemctl --user enable onedrive
Failed to execute operation: No such file or directory

this seems like a simple fix, I will look at helping if I can find time.

**Comment by incomingstick** [comment]
This is happening because the onedrive service was never created. Upon creating the service base on the one here on git it failed because onedrive is saved to /usr/bin/onedrive not /usr/bin/locale/onedrive like the one her eon github. I suggest making that change in the service file. However once that service is enabled it fails with the following:

```
[user@localhost ~]$ systemctl --user status onedrive
* onedrive.service - OneDrive Free Client
   Loaded: loaded (/usr/lib/systemd/user/onedrive.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2016-01-17 15:21:15 UTC; 4min 31s ago
     Docs: https://github.com/skilion/onedrive
 Main PID: 735 (code=exited, status=1/FAILURE)

Jan 17 15:21:15 localhost onedrive[735]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d12a2]
Jan 17 15:21:15 localhost onedrive[735]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d11f8]
Jan 17 15:21:15 localhost onedrive[735]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d125e]
Jan 17 15:21:15 localhost onedrive[735]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d11f8]
Jan 17 15:21:15 localhost onedrive[735]: ??:? _d_run_main [0x5d1155]
Jan 17 15:21:15 localhost onedrive[735]: ??:? main [0x5b8915]
Jan 17 15:21:15 localhost onedrive[735]: ??:? __libc_start_main [0xf58f960f]
Jan 17 15:21:15 localhost systemd[728]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Jan 17 15:21:15 localhost systemd[728]: onedrive.service: Unit entered failed state.
Jan 17 15:21:15 localhost systemd[728]: onedrive.service: Failed with result 'exit-code'.
```

as I have not had the time to look through the source code I do not understand this output.

**Comment by skilion** [comment]
Did you compile/install the app using `sudo make install` ?
With that all the files will be in the correct locations.

**Comment by sollie78** [comment]
I like to run it as deamon. But i use linux mint 17.3. It doensnt ave systemd. Whats the best way to use your app.

**Comment by incomingstick** [comment]
It was installing from the AUR using yaourt. My guess then would be that the AUR package is outdated compared to this git repo.

**Comment by awesomehaircut** [comment]
I had the same problem on arch
Just copy or make the service file and it should be fine. 
Or even better use the source here

In any case this is an aur issue
