### ISSUE TITLE
Problem with filenames

### ISSUE THREAD

**Issue by xcffl** [skilion/onedrive#201]
It seems that this program cannot deal with files with names containing some special signals. For example:

```
Uploading: xxxxxx/read()if v == -1:break.md
HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "BadRequest",
        "innerError": {
            "date": "2017-06-18T02:21:59",
            "request-id": "1da2458c-61d8-46d1-847d-d1a6bd3adb94"
        },
        "message": "Only one path can be specified in the URL."
    }
}
```

**Comment by skilion** [comment]
As specified [here](https://github.com/skilion/onedrive#file-naming), filenames must be valid according to Windows conventions. Remove the colon and the file should upload just fine.

**Comment by erenoglu** [comment]
Yes, but can't Onedrive at least "not crash", skip the file, send a notification to the system of the problem? I just noticed that I've been running since 2 weeks w/o noticing that sync was failing due to this.
