### ISSUE TITLE
segfault on JSON exception (Key not found: name)

### ISSUE THREAD

**Issue by shrike92** [skilion/onedrive#202]
Pastebin of the verbose output:
**https://pastebin.com/k6E9LYEi**

Tried running as root and non-root.  I can consistently reproduce the error by attempting to force a manual sync.

Ubuntu 16.04 LTS, x86

edit: originally it was uploading, but that no longer works either.

**Comment by shrike92** [comment]
Of course!  I appreciate you writing this so if there's anything I can do to help just let me know.

It's a mess!  Is there any way I can format it better for you?  I went ahead and anyonymized everything as well:
https://pastebin.com/NK8DCL8m

**Comment by skilion** [comment]
The items in the log you posted all contain the 'name' property so no problem there. Let's do another test.

Run `onedrive` and ensure you still see the error you posted before: `... Key not found: name`
Then run the following command (again substitute XXXXXX as before) and post the output.
```
curl -H "Authorization:bearer XXXXXX" $(cat .config/onedrive/delta_link)
```

**Comment by shrike92** [comment]
No problem.  I ran it again and got the same error.  I then ran the command you listed below and got the following output:

https://pastebin.com/U3b89aYu

Also, I just realized something.  We use two factor authentication, could that be affecting it? It was able to sync initially when I first installed, but maybe it's lost authorization since then?

**Comment by skilion** [comment]
The error is caused by OneDrive not returning the name of a deleted file. OneDrive for Business is full of this small quirks that do not respect the specifications.
I pushed a workaround that handles the issue a61abc4e1569121b14886de2d3904ebf7d74a4d3

**Comment by shrike92** [comment]
Thanks a ton!
