### ISSUE TITLE
if uploaded file changes in the later time, the newly changed file is not reuploaded

### ISSUE THREAD

**Issue by binghesam** [skilion/onedrive#205]
At this stage, i find a problem, 
when one file has been uploaded to the onedrive.com
then , i chnage the contents like adding some lines in the txt.file
but i use the commend line 
onedrive

the newly changed txt.file is not uploaded, the onedrive.com just keep the 
past first-time uploaded files.

Dose anyone find this problem? is there any solution. Or,I  miss something?

Thanks for your viewing, hope to get some response or suggestions.

**Comment by skilion** [comment]
You can use the `--verbose` switch to see explicitly how the application is handling your files

**Comment by fabienpe** [comment]
Same problem here since I upgraded to the latest version. Verbose does not show anything:
```
xxx@xxx:~$ onedrive --verbose
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/xxx/OneDrive
Initializing the Synchronization Engine ...
Applying differences ...
Uploading differences ...
E1A52AAF3FE37C9!144 root
The directory has not changed
Uploading new items ...
```

**Comment by ddss** [comment]
Same problem here. It is the first time that I'm using this application:

```
onedrive --verbose
Loading config ...
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/xxx/OneDrive
Initializing the Synchronization Engine ...
Applying differences ...
Uploading differences ...
36F938EF4A43DFDD!105 root
The directory has not changed
Uploading new items ...
 ```

The file changed was a pdf (comments in it).

I´m currently running Fedora 24. 
DMD64 D Compiler v2.076.0-dirty

**Comment by binghesam** [comment]
In fact, there will finally be two double-copied files.

**Comment by David-Byrne** [comment]
Same issue as the above reports, with the same terminal output.

Any modifications to a previously added file aren't applied when I run `onedrive`. If I run `onedrive --resync` it results in a duplicate copy and `file-computerName.txt` contains the newer change.

If there's any more information I can give let me know, I'll be happy to help :smile:

**Comment by David-Byrne** [comment]
I've done a bit of investigating and the bug seems to have been added in commit 35f81b21158932cd3051ddcb845c61afa63a191b. Hopefully someone with more knowledge of the code base can find it from there, I'm definitely out of my depth at this point. 

As an aside I see some of the code changes are for computing the path; I have my home directory set as my onedrive sync directory which might be an edge case... Maybe someone else with this issue could mention if they have the same setup?

As a temporary workaround reverting to 74c931cdba09a7a70dd216e433e45abb7ea6e70e works for now.

**Comment by razimantv** [comment]
@David-Byrne 's solution worked for me. I have reverted to https://github.com/skilion/onedrive/commit/74c931cdba09a7a70dd216e433e45abb7ea6e70e too to be able to continue syncing updated files.

**Comment by skilion** [comment]
This should not be a problem anymore after ab592f134e63edae8ee3bed64f7ec9351183e431
