### ISSUE TITLE
Question: Not download all files

### ISSUE THREAD

**Issue by Ntweat** [skilion/onedrive#206]
How to sync only one remote director which is shared with me?

**Comment by skilion** [comment]
As of ab592f134e63edae8ee3bed64f7ec9351183e431 you can sync shared folders. To sync only a specific folder use [Selective Sync](https://github.com/skilion/onedrive#selective-sync).

**Comment by Iambecomeroot** [comment]
@skilion Can you provide more information on how to sync shared folders? I con't figure it out.
