### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by lucasrhb** [skilion/onedrive#208]
It's 100% ok while adding new files, but seg fault while deleting files from the cloud. That happens only with "-m". Also not deleting any files when doing sync/resync. OneDrive for Business, Fedora 24.

[M] Item deleted: dupa/dupka.txt
Deleting remote item: dupa/dupka.txt
Applying differences ...
01DTRG7VV6Y2GOVW7725BZO354PWSELRRZ root
The item has not changed
01DTRG7VUP64BDLTUWWFFKJUSR4VV4ZWJR 
The item is marked for deletion
Deleting files ...
object.Exception@src/itemdb.d(231): Unknow item id
----------------
/home/lucas/dlang/dmd-2.074.1/linux/bin64/../../src/phobos/std/exception.d:388

 pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x590201]
src/itemdb.d:231 immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x5c6d6b]
src/sync.d:362 void sync.SyncEngine.deleteItems() [0x5dbef7]
src/sync.d:185 void sync.SyncEngine.applyDifferences() [0x5da5a3]
src/main.d:169 void main.performSync(sync.SyncEngine) [0x5c89f7]
src/main.d:147 _Dmain [0x5c8662]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x5f117b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5f10ab]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5f1124]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5f10ab]
??:? _d_run_main [0x5f101b]
??:? main [0x5cc3d3]
??:? __libc_start_main [0x7b5ed730]
Segmentation fault (core dumped)_

**Comment by skilion** [comment]
Fixed in 849dd36276f99af87b36d7541bba79ba314d5b93
