### ISSUE TITLE
"Unknow item id" unavoidable crash introduced in 35f81b2

### ISSUE THREAD

**Issue by davegregg** [skilion/onedrive#214]
Several users have posted error messages already #(207), so far only Ubuntu users have reported (inconclusive).

# The Error
```D
~ $ onedrive --monitor                                                                                                                       4s 498ms
object.Exception@src/itemdb.d(231): Unknow item id
----------------
??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x2f8f21d9]
??:? immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x2f928d43]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x2f93c869]
??:? void sync.SyncEngine.applyDifferences() [0x2f93c257]
??:? void main.performSync(sync.SyncEngine) [0x2f92a9cf]
??:? _Dmain [0x2f92a1f0]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x2f95314b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x2f95307b]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x2f9530f4]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x2f95307b]
??:? _d_run_main [0x2f952feb]
??:? main [0x2f92e3ab]
??:? __libc_start_main [0x4f8c83f0]
fish: “onedrive --monitor” terminated by signal SIGSEGV (Address boundary error)
```

# Where it breaks (`enforce(selectById(...))`)
In `itemdb.d`, at `enforce`:
```D
	string computePath(const(char)[] driveId, const(char)[] id)
	{
		string path;
		Item item;
		while (true) {
			enforce(selectById(driveId, id, item), "Unknow item id");
			if (item.type == ItemType.remote) {
				// substitute the last name with the current
				path = item.name ~ path[indexOf(path, '/') .. $];
			} else if (item.parentId) {
				if (path) path = item.name ~ "/" ~ path;
				else path = item.name;
			} else {
				// root
				if (!path) path = ".";
				break;
			}
			driveId = item.parentDriveId;
			id = item.parentId;
		}
		return path;
	}
```

# The immediate problem
The value of `selectById()` is being cast as false at some point in the loop.

# When the bug was introduced
This bug seems to have been introduced a month ago in @skilion's commit ["itemdb support for remote items"](https://github.com/skilion/onedrive/commit/35f81b21158932cd3051ddcb845c61afa63a191b#diff-df48cccab2346d845f24b2131b335c5a).

The latest OneDrive build has been unusable for those of us affected since then. And since this service runs in the background it is plausible that many users are affected and haven't yet noticed that their cloud service crashes on launch and so fails to sync.

**Comment by davegregg** [comment]
(minor text change needed as well: `Unknow item id` to `Unknown item ID`)

**Comment by davegregg** [comment]
I've compiled with `make debug` and run verbosely. The usual syncing operations begin but there is one oddity which appears relevant:

I have an item marked for deletion (in my case a folder called "OldNewExplorer"). I can confirm via onedrive.com that this folder occurs only in my Recycle Bin. 

*But then, later, look where the exception occurs:*

```D
9B171F9828CF895E!125475 Butterfly Assassins - Sylvia - 09 Turn It Off.mp3
Filtered out
9B171F9828CF895E!125452 Ladder Song.mp3
Filtered out
9B171F9828CF895E!128103 OldNewExplorer32.dll
object.Exception@src/itemdb.d(231): Unknown item id
----------------
??:? pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, const(char[])) [0xe2d486c2]
??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0xe2d48732]
??:? immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0xe2d89969]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0xe2d99b09]
??:? void sync.SyncEngine.applyDifferences() [0xe2d9969d]
??:? void main.performSync(sync.SyncEngine) [0xe2d8aa53]
??:? _Dmain [0xe2d8a609]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0xe2dafcf7]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xe2dafc27]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xe2dafca0]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xe2dafc27]
??:? _d_run_main [0xe2dafb97]
??:? main [0xe2d8e3e1]
??:? __libc_start_main [0x9d59d3f0]
fish: “onedrive --verbose” terminated by signal SIGSEGV (Address boundary error)
```

That file `OldNewExplorer32.dll` was in the marked-for-deletion `OldNewExplorer` folder and should no longer exist anywhere in the drive except the Recycle Bin. It is _then_ apparently the selectById() cannot resolve an item ID. This is repeatable.

**Comment by davegregg** [comment]
Just more behavioral data. I cleared the Recycle Bin and ran onedrive verbosely again:

```
Filtered out
9B171F9828CF895E!128099 OldNewExplorer
The item is marked for deletion
9B171F9828CF895E!128374 Screenshots
Filtered out
9B171F9828CF895E!127575 machines
Filtered out
9B171F9828CF895E!126866 0a18f58bf8855c2642f2d9886cf07a67.jpg
The item is marked for deletion
9B171F9828CF895E!128100 readme.txt
object.Exception@src/itemdb.d(231): Unknown item id
```
You'll notice it is throwing an exception at readme.txt here, which now occurs in neither by now-empty Recycle Bin nor anywhere in my local onedrive folder (currently--though several readme.txt files occur on my remote drive).

**Comment by skilion** [comment]
1. Can you confirm that you are using the latest commit 849dd36276f99af87b36d7541bba79ba314d5b93
2. Can you provide the steps to reproduce the error? (ex. create folder X, create file Y in X, delete X)

**Comment by davegregg** [comment]
@skilion 
1. Yes, I'm on 849dd36276f99af87b36d7541bba79ba314d5b93.
2. All I know is it started happening I think about a month ago _every_ time onedrive runs, and I can't get it to *stop* happening in order to reproduce steps from a bug-free state. I'm close to rolling back to before the breaking change, which I _think_ is 35f81b21158932cd3051ddcb845c61afa63a191b. Actually, let me test that. I'll roll back and see if it will start working.

**Comment by davegregg** [comment]
@skilion Okay, so here's what I've done. 
1. Rolled back my local repo to 74c931cdba09a7a70dd216e433e45abb7ea6e70e.
2. `$ make debug`
3. `$ sudo make install`
4. `$ onedrive --verbose`
5. Output:
```D
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
object.Exception@src/itemdb.d(55): The item database is incompatible, please resync manually
----------------
??:? itemdb.ItemDatabase itemdb.ItemDatabase.__ctor(const(char)[]) [0x8bb25d79]
??:? _Dmain [0x8bb27e71]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x8bb4d227]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x8bb4d157]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x8bb4d1d0]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x8bb4d157]
??:? _d_run_main [0x8bb4d0c7]
??:? main [0x8bb2bd99]
??:? __libc_start_main [0x7611d3f0]
fish: “onedrive --verbose” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by davegregg** [comment]
Oh, I see -- that is throwing at:
```D
else if (db.getVersion() != itemDatabaseVersion) {
```

So I guess I'll have to resync to roll back the database version?

**Comment by skilion** [comment]
Yes, run `onedrive --resync`

**Comment by davegregg** [comment]
Update: After rolling back to 74c931cdba09a7a70dd216e433e45abb7ea6e70e and *resyncing*, I get no errors.

**Comment by davegregg** [comment]
Okay, for testing, I rolled forward to the latest master head and ran *resync* again. Now no error. Seems there is a breaking change for at least some people when upgrading between versions without resyncing.
