### ISSUE TITLE
onedrive, too many requests and exit

### ISSUE THREAD

**Issue by timoleh** [skilion/onedrive#215]
=nedrive reports "sync.SyncException@src/sync.d(182): HTTP request returned status code 429 (Too Many Requests)" and after awhile enters fail-state.
Log messages in "https://pastebin.com/SUv2AU5t".

Timo

**Comment by thomasfedb** [comment]
@timoleh does this issue occur with the latest codebase? If not, could you close this issue please.

**Comment by timoleh** [comment]
It seems to work after some updates.
