### ISSUE TITLE
File deleted locally is not deleted remotely

### ISSUE THREAD

**Issue by hugomilan** [skilion/onedrive#217]
Tested with committee 7fae9c1. Ubuntu 16.04. libcurl4-openssl-dev, libsqlite3-dev, and inotify-tools installed.

I created a new file, "backup (copy).sh" and run onedrive ("onedrive -v"). Then I deleted that file locally and run onedrive again ("onedrive -v"). The file is not downloaded to my PC and it is not deleted remotely either.

See log in https://pastebin.com/af9a03MK

**Comment by eakbas** [comment]
I experience the same problem. My setup is the same as @hugomilan 's.

**Comment by nogu3ira** [comment]
Did you allow the service to run when you're not logged in?

https://github.com/skilion/onedrive/wiki/Managing-the-onedrive-service

> Note that by default systemd will only keep user services running when a user has at least one active session open. To allow the service to run when you're not logged in, use:
> 
> `# loginctl enable-linger YOURUSERNAME`

**Comment by skilion** [comment]
Can't reproduce on the latest commit (c7e09304a6e5777702bb928e2cdb76f2cead87d7). The issue should have been fixed.
