### ISSUE TITLE
Skip files that it doesn't have permission to access

### ISSUE THREAD

**Issue by xcffl** [skilion/onedrive#219]
Some files that onedrive doesn't have permission to access contain in the folders to sync. They will cause onedrive to crash. Is it possible to skip them and sync all the other files?

**Comment by thomasfedb** [comment]
@xcffl does this issue occur with the latest codebase? If yes, please provide the error logged. If not, could you close this issue please.

**Comment by abraunegg** [comment]
@xcffl 
Can you provide an update. If this is no longer an issue, please close this case.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
