### ISSUE TITLE
Failure when not syncing photos

### ISSUE THREAD

**Issue by Gerharddc** [skilion/onedrive#22]
When I try to avoid syncing my "Pictures" folder then I get the following crash:

std.json.JSONException@std/json.d(443): Key not found: cTag
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x629e7a]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException, inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x629ede]
??:? std.json.JSONValue.opIndexinout(pure ref inout(std.json.JSONValue) function(immutable(char)[])) [0x5fc22a]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5cfc2e]
??:? void sync.SyncEngine.applyDifferences() [0x5cf001]
??:? void main.performSync(sync.SyncEngine) [0x5c0f97]
??:? _Dmain [0x5c08ba]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5dc12e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dc084]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5dc0ea]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5dc084]
??:? _d_run_main [0x5dbfe1]
??:? main [0x5c2c6d]
??:? __libc_start_main [0xee656b04]

Even if I rename the folder, this happens. My conf is now:

sync_dir = "~/OneDrive"
skip_file = ".*|~*"
skip_dir = ".*|Videos|Music|Pictures-old"

**Comment by skilion** [comment]
Fixed since 5ed7dfc
