### ISSUE TITLE
It ignores delete operations using "Shift + delete" in ubuntu

### ISSUE THREAD

**Issue by micdoug** [skilion/onedrive#220]
I have this problem. When I delete files using "Shift + Delete", the program doesn't recognize the operation, and it doesn't report the operation to onedrive's service. When I delete using just "Delete" it recognizes it and reports.

**Comment by thomasfedb** [comment]
@micdoug what is the behaviour of <kbd>Shift</kbd> + <kbd>Del</kbd>, and how does it differ from <kbd>Del</kbd>?

**Comment by micdoug** [comment]
When you use Shift + Del, the target (file or folder) are permanent removed. The target is not moved to the trash. In this case the delete operation is not reported to onedrive service.

**Comment by abraunegg** [comment]
@micdoug 
Can you retry & report back when using the #314 branch of code?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
