### ISSUE TITLE
Won't build on arm as DMD not available for arm

### ISSUE THREAD

**Issue by nwaltham** [skilion/onedrive#221]
It would be nice to have this run on a raspberry pi, which uses a flavour of debian. Unfortunately DMD is not available on arm. Other D compilers are..

**Comment by NiklasOlofsson** [comment]
I just noticed... to bad.

**Comment by skilion** [comment]
As of ab592f134e63edae8ee3bed64f7ec9351183e431 you can specify the compiler via the DC variable. For example with [LDC](https://wiki.dlang.org/LDC): `make DC=ldmd`
