### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by songsen** [skilion/onedrive#222]
ThinkPad-X200:~$ onedrive  --syncdir ~/OneDrive/upload
sqlite.SqliteException@src/sqlite.d(147): attempt to write a readonly database
----------------
src/sqlite.d:22 ref sqlite.Statement.Result sqlite.Statement.Result.__ctor(etc.c.sqlite3.sqlite3_stmt*) [0x5ed0d1]
src/sqlite.d:173 sqlite.Statement.Result sqlite.Statement.exec() [0x5ed47e]
src/sync.d:266 void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5efb62]
src/sync.d:169 void sync.SyncEngine.applyDifferences() [0x5ee825]
src/main.d:184 void main.performSync(sync.SyncEngine) [0x5da8d7]
src/main.d:114 _Dmain [0x5da0ff]
Segmentation fault (core dumped)

**Comment by chase9** [comment]
Could this issue be related to #207? Both are seg faults but it's hard to see the problem with the other one. I mentioned there that my seg fault went away when running with sudo, does that also happen with you?

**Comment by thomasfedb** [comment]
@songsen I'd suggest you try `--resync`. Please let us know if this is still an issue, or otherwise close this issue.

**Comment by abraunegg** [comment]
@songsen 
Does this issue still occur with #314 ?

**Comment by abraunegg** [comment]
@songsen 
Can you provide an update. If this is no longer an issue, please can you close this case.

**Comment by Hikikomono** [comment]
I have the same Issue,  `--resync` helps once, but after creating some files in my onedrive folder and trying if both sides work (upload / download) i get the same Error

**Comment by abraunegg** [comment]
@Hikikomono 

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by Hikikomono** [comment]
@abraunegg 

Thanks for the quick Reply!
I'll give it a try.
