### ISSUE TITLE
Feature Request: Ability to forfeit local state and update local mirror based on server state

### ISSUE THREAD

**Issue by hachre** [skilion/onedrive#223]
Hi,

I'd really love to see a feature that allows me to do essentially what `--resync` does, while also deleting all local files that exist additionally to whatever files the server has. Similar to what `git pull` and `git reset --hard` would do to a git tree. 

Currently `--resync` only forgets the local sync state, but later attempts to upload additional files that exist locally but not on the server. I want those files to be deleted so that the local side fully represents what's currently going on on the server side.

I hope I was able to convey what I mean.
Would it be possible to consider such a feature?

Thanks

**Comment by thomasfedb** [comment]
@hachre does the `--download` flag meet your needs? If so, please close.

**Comment by agrigorev** [comment]
Hello,
I suppose, I have encountered this behaviour (deleted files are getting re-uploaded) last days. Is --download the proper flag? What does it do?

Thanbks in advance,
Andrey

**Comment by thomasfedb** [comment]
As per `--help`:

```
-d    --download Only download remote changes
```

**Comment by hachre** [comment]
@thomasfedb Sorry it took me so long to respond! **Yes, the `-d` option is doing exactly what I want.** Is this something that has been added since my initial post or did I manage to overlook that? Thank you very much!

**Comment by thomasfedb** [comment]
It was added in https://github.com/skilion/onedrive/commit/764975e2247eae9a7b4b6ea13de21584bfa3beb1 it seems.

**Comment by agrigorev** [comment]
Hello @thomasfedb 
I will definitelly try -d-option (today I started my laptop again, and it uploaded again deleted files to the server). But I have another question: how can I update the client? Should I go through the whole process again (download - build - reconfigure)? Does any shorter/less complex way exist?

Thanks,
Andrey

**Comment by thomasfedb** [comment]
The same way as you installed it, yes.
