### ISSUE TITLE
Randomly stopped without an error

### ISSUE THREAD

**Issue by gigaSproule** [skilion/onedrive#225]
I ran this with `onedrive --verbose` after making with debug and installing and it's randomly stopped syncing. There are no errors, but running `$?` shows code 141.

This keeps happening on different files. I'm trying to get more information, but not sure how.

**Comment by thomasfedb** [comment]
Is this still happening @gigaSproule?

**Comment by gigaSproule** [comment]
Not been using it. I usually end up reformtting my laptop every so often. If i get some time, I'll try it again.

**Comment by thomasfedb** [comment]
Okay @gigaSproule. If the issue no longer needs to be looked into could you close the issue please.

**Comment by gigaSproule** [comment]
I've not been able to get round to this, so I'll close it
