### ISSUE TITLE
recipe for target 'onedrive' failed

### ISSUE THREAD

**Issue by vood8D** [skilion/onedrive#227]
Hello, 

I have issue with the makefile. I installed dependecy for my ubuntu server, 
The command make return : 
`dmd -g -inline -O -release -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:31: recipe for target 'onedrive' failed
` 

Thank for your help,

**Comment by alinuxfan** [comment]
Make sure you install the dmd dependency. 

From the readme:
curl -fsS https://dlang.org/install.sh | bash -s dmd

**Comment by gifthlong** [comment]
After the above command i.e. `curl -fsS https://dlang.org/install.sh | bash -s dmd`

You may need to run `source ~/dlang/dmd-2.077.1/activate` to use

**Comment by pureair** [comment]
After run source ~/dlang/dmd-2.077.1/activate, still get error as reported in https://github.com/skilion/onedrive/issues/259

**Comment by thomasfedb** [comment]
Can this issue be closed @vood8D?

**Comment by abraunegg** [comment]
@vood8D 
Do you have at least 1GB of memory for your build environment? To build using DMD you need at least 1GB of memory on the build server.

If this issue is no longer an issue for you, please can you close this case.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
