### ISSUE TITLE
First run Authorization failed due to: invalid uri

### ISSUE THREAD

**Issue by hanzi4389604** [skilion/onedrive#229]
I am a green hand in linux world. I don't know how to initialize this on my ubuntu14.

Msg:
onedrive --version
onedrive v1.0.1
onedrive 
Authorize this app visiting: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
Enter the response uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
Invalid uri
Could not initialize the OneDrive API

**Comment by skilion** [comment]
The response uri you pasted is the same as the one you visited. Clearly the page did not load correctly.
