### ISSUE TITLE
Question about running as a service

### ISSUE THREAD

**Issue by GrouchyGaijin** [skilion/onedrive#23]
Forgive my slowness to comprehend what may be clear to everyone else.
I am running Ubuntu 14.04 64 bit.  I installed OneDrive using make and sudo make install.
Things are now working fine as long as I run onedrive -m when I logon to the computer and keep a terminal open.

I see that to run onedrive as a service I am supposed to enable and start the systemd service:
systemctl --user enable onedrive
systemctl --user start onedrive

When I type systemctl --user enable onedrive in the terminal I get a message that the command is not found. When I check Synaptic I see that systemd-services is installed.

What am I missing and how can I fix this?

Thank you

GG

**Comment by GrouchyGaijin** [comment]
orgive my slowness to comprehend what may be clear to everyone else.
I am running Ubuntu 14.04 64 bit. I installed OneDrive using make and sudo make install.
Things are now working fine as long as I run onedrive -m when I logon to the computer and keep a terminal open.

I see that to run onedrive as a service I am supposed to:
If you want to sync your files automatically, enable and start the systemd service:

systemctl --user enable onedrive
systemctl --user start onedrive

When I type systemctl --user enable onedrive in the terminal I get a message that the command is not found.  When I check Synaptic I see that systemd-services is installed.

What am I missing and how can I fix this?

Thank you

GG

**Comment by xied75** [comment]
@GrouchyGaijin systemctl is a cli for linux with systemd, that is not enabled for Ubuntu 14.04. The document needs to be more clear on this.

**Comment by telmer6** [comment]
You could try running it at boot as a scheduled task.

**Comment by GrouchyGaijin** [comment]
Firstly, thank you for writing this really useful program, it has made my life easier.
Now, because I am forgetful, twice I have edited a presentation at home and then when I get to work realize I forgot to manually sync OneDrive from the Linux machine.

I have tried running the commands onedrive and onedrive -m as scheduled tasks and I have tried running a script that runs onedrive and onedrive -m as scheduled tasks.

I cannot get the onedrive (or onedrive -m) commands to run unless I manually invoke them.

I am running Ubuntu 14.04 64bit and would **really really** appreciate being able to run this as a service.

**Comment by skilion** [comment]
Ubuntu 14 uses **Upstart** to manage services. The commands in the readme are for **systemd** which is used in Ubuntu 15 and other Linux distros. If you want to run onedrive as a service with Upstart you should look up the [documentation](http://upstart.ubuntu.com/getting-started.html) and write a custom job.
