### ISSUE TITLE
Cannot install on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by onlize** [skilion/onedrive#231]
Hello, I am trying to install it, but have an error when I try to run make command:
`
ubuntu@user:~/onedrive$ make`
`dmd -g -inline -O -release -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d`
`make: dmd: Command not found`
`Makefile:31: recipe for target 'onedrive' failed`
`make: *** [onedrive] Error 127`
`ubuntu@user:~/onedrive$ 
`
Can you help?

**Comment by Scimmia22** [comment]
Did you read the output you pasted? "dmd: Command not found" is very clear

**Comment by onlize** [comment]
Yes, I saw it. Sorry, I am very new to Ubuntu, so maybe it is basic, but when I google it, I cannot find anything useful. I tried to install dmd and receive an error:
`ubuntu@user:~/onedrive$sudo apt install dmd`
`[sudo] password for user:` 
`Reading package lists... Done`
`Building dependency tree`       
`Reading state information... Done`
`E: Unable to locate package dmd`
`ubuntu@user:~/onedrive$`

**Comment by muffledSheep** [comment]
Might help: http://d-apt.sourceforge.net/

**Comment by onlize** [comment]
It helped, thank you.
