### ISSUE TITLE
wish: specify target folder in OneDrive

### ISSUE THREAD

**Issue by thegreyshadow** [skilion/onedrive#232]
This is a wish.

Thanks for the onedrive client.

I would like, if possible, to be able to specify not only the local directory to sync with OneDrive; but also, the target OneDrive folder. That is, I'm not interested in syncing the whole OneDrive contents into my hard drive, but only a particular folder.

Thanks again for all your great work.

**Comment by skilion** [comment]
This is already possible with [Selective sync](https://github.com/skilion/onedrive#selective-sync).
