### ISSUE TITLE
Sync with for Business

### ISSUE THREAD

**Issue by avihuh** [skilion/onedrive#238]
Hi,
I succeed to configure for person One Drive, but how can I do it for business, please advise :)

**Comment by docsmooth** [comment]
If you log into your One Drive for business account instead, it will sync that automatically.  That's what I'm syncing with on Kubuntu 17 right now.  Follow the instructions for having multiple sycs set up.

**Comment by avihuh** [comment]
Thanks for replying, but I need to enter the URL, and the URL redirect me to OneDrive personal, how to sign in to for business?

**Comment by docsmooth** [comment]
You have to log out of one drive personal, then log in with your one drive business account on the web browser, first.

https://www.office.com
Sign in with business account, click OneDrive link.

**Comment by avihuh** [comment]
@docsmooth Hi, sorry for the delay, I didnt understand, I logged out my personal on the web and sign in to ODFB on the web what do i need to do now?

**Comment by skilion** [comment]
Then you need to lunch the application and authorize it with your OneDrive Business account. If you already authorized it with another account you need to logout `onedrive --logout`
