### ISSUE TITLE
Request: Ensure compatibility with GCC's new D front-end

### ISSUE THREAD

**Issue by andrebrait** [skilion/onedrive#239]
This is a request for the near or not-so-near-but-still-less-than-a-year-away term.

So, GNU's GCC is finally getting a front-end for D >=2.0. Since GCC is a much, much more widespread compiler suite than DMD and it will probably even be available on ARM platforms, it would be a good idea to make this software compatible with it as soon as the front-end officially lands on GCC and/or is released on a final version of GCC.

**Comment by thomasfedb** [comment]
@andrebrait is this something you'd be able to test out? Perhaps a pull request?

**Comment by andrebrait** [comment]
@thomasfedb When it lands on GCC, sure (or when I get the opportunity to compile GCC with D support)

**Comment by thomasfedb** [comment]
@andrebrait do you have a good link to track progress of D in GCC?

**Comment by thomasfedb** [comment]
Given that this compiles find with LDC (which is what's used to compile this for Fedora) I think we can be fairly confident for this one. @andrebrait would you be happy to close this issue until there's actually something to fix?

**Comment by andrebrait** [comment]
Sure thing. Closing this up.
