### ISSUE TITLE
Crash on sync

### ISSUE THREAD

**Issue by GrouchyGaijin** [skilion/onedrive#24]
This morning I started getting this error message when I run onedrive -m
Does anyone know what I can do to fix this?

Today is Thu Jan 21 @ 07:47:44 ~ $ onedrive -m
std.json.JSONException@std/json.d(443): Key not found: cTag
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x6134c2]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException, inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x613526]
??:? std.json.JSONValue.opIndexinout(pure ref inout(std.json.JSONValue) function(immutable(char)[])) [0x5e6fce]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5be4fe]
??:? void sync.SyncEngine.applyDifferences() [0x5bd8d1]
??:? void main.performSync(sync.SyncEngine) [0x5af867]
??:? _Dmain [0x5af18a]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5ca9fe]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ca954]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5ca9ba]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ca954]
??:? _d_run_main [0x5ca8b1]
??:? main [0x5b153d]
??:? __libc_start_main [0xf436cec4]

**Comment by GrouchyGaijin** [comment]
Update:

I completely uninstalled everything connected to onedrive and started from scratch.
At first the sync seemed to be working, as files were downloading from Microsoft's server to my Ubuntu machine, then all of a sudden I got the same error listed above.

This is such a drag.  I work with some Windows-centric folks and this program made it so much easier to work from home.

**Comment by GrouchyGaijin** [comment]
So, does anyone have an idea what is causing this crash or how to fix it?  I would be grateful for some help.

**Comment by sollie78** [comment]
feb 02 20:56:44 Sollie-Laptop systemd[1007]: Starting OneDrive Free Client...
feb 02 20:56:44 Sollie-Laptop systemd[1007]: Started OneDrive Free Client.
feb 02 20:57:30 Sollie-Laptop onedrive[2434]: Downloading: ./Pictures/2003/Gourmetten 28-12-2003/dcp_0050.jpg
feb 02 20:57:31 Sollie-Laptop onedrive[2434]: HTTP request returned status code 403 (Forbidden)
feb 02 20:58:09 Sollie-Laptop onedrive[2434]: Downloading: ./Pictures/2003/Gourmetten 28-12-2003/dcp_0050.jpg
feb 02 20:58:10 Sollie-Laptop onedrive[2434]: HTTP request returned status code 403 (Forbidden)
feb 02 20:58:50 Sollie-Laptop onedrive[2434]: Downloading: ./Pictures/2003/Gourmetten 28-12-2003/dcp_0050.jpg
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: sync.SyncException@src/sync.d(106): HTTP request returned status code 403 (Forbidden)
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ----------------
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void sync.SyncEngine.applyDifferences() [0x5cc36f]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void main.performSync(sync.SyncEngine) [0x5be16f]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? _Dmain [0x5bda12]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d8f9a]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d8ed8]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d8f56]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d8ed8]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? _d_run_main [0x5d8e35]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? main [0x5bfe6d]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? __libc_start_main [0x5d877b44]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: onedrive.OneDriveException@src/onedrive.d(337): HTTP request returned status code 403 (Forbidden)
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ----------------
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void onedrive.OneDriveApi.checkHttpCode() [0x5c5358]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5c4684]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x5c23ec]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5cd551]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5cd088]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void sync.SyncEngine.applyDifferences() [0x5cc1f1]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void main.performSync(sync.SyncEngine) [0x5be16f]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? _Dmain [0x5bda12]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d8f9a]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d8ed8]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d8f56]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d8ed8]
feb 02 20:58:51 Sollie-Laptop onedrive[2434]: ??:? _d_run_main [0x5d8e35]
feb 02 20:58:51 Sollie-Laptop systemd[1007]: onedrive.service: main process exited, code=exited, status=1/FAILURE
feb 02 20:58:51 Sollie-Laptop systemd[1007]: Unit onedrive.service entered failed state.

**Comment by GrouchyGaijin** [comment]
This seems to be a different error from the one I get.

**Comment by GrouchyGaijin** [comment]
Thank you!  It seems to be working now.  I'll know if it worked all the way through when the sync is done.

**Comment by sollie78** [comment]
Mine works ok now. Seems te be a perfect fix :)

**Comment by GrouchyGaijin** [comment]
Mine works now as well.  THANK YOU

I have a question about skipping folders though.  I have tried:
`skip_dir = ".Documents/Electronic Arts/ *| .Documents/My Games/*"`
and
`skip_dir = ".Documents/'Electronic Arts'/ *| .Documents/'My Games'/*"`

But both of these folders are still being downloaded to my Linux machine.  How should I write this to ignore the Electronic Arts and My Games folders?

Thank you

**Comment by drdoran** [comment]
I don't know about sub directories, but for your Documents folder you would do:
``
skip_dir = "Documents"
``
So I don't know, give this a try:
``
skip_dir = "Documents/Electronic Arts | Documents/My Games
``

[https://github.com/skilion/onedrive/issues/16](url)

**Comment by GrouchyGaijin** [comment]
Thank you for the reply.  Unfortunatly skip_dir = "Documents/Electronic Arts | Documents/My Games" did not work.  When I run onedrive --resync any new files in both the Electronic Arts directory or the My Games directory are downloaded to the Linux machine.
(I don't really want a copy of all my kid's saved game data on this machine - LOL)

**Comment by lepennec** [comment]
astanin commit solved the issue for me...

**Comment by CBTyrone** [comment]
Try changing src/sync.d at roughly 115 to the following (this worked for me): 


string name;

		if(auto ntest = "name" in item) {
		
			name = item["name"].str;
		} else {

			skippedItems ~= id;
			return; // Clearly this isn't working out
		}
