### ISSUE TITLE
Wpm

### ISSUE THREAD

**Issue by mtwb47** [skilion/onedrive#240]
I have it installed, and the initial sync was successful. but starting the service daemon failed. This is the output:
```
sudo systemctl --user  enable onedrive
Failed to connect to bus: No such file or directory

```

Obviously, it won't sync without the service enabled or started. I tried adding .service to the onedrive (so onedrive.service), but that obviously wasn't the right way to do it.

Any help would be appreciated. I'm using arch, and this was downloaded through the AUR not through git, as I couldn't get it to make through git.

**Comment by Scimmia22** [comment]
That's a dbus issue, not a onedrive issue. Try the Arch forums/IRC/mailing list.
