### ISSUE TITLE
Failing to update/remove files, when changes pushed from other source (Web/Windows PC)

### ISSUE THREAD

**Issue by gtsotsos** [skilion/onedrive#241]
Hello,

Thanks for this awesome tool. 

I think i came across a bug or I am doing something wrong. 

When a new file file is pushed to OneDrive via either web interface or Windows PC, tool picks up changes and updates corresponding folder/s. On the other hand, when file gets updated or deleted on Web/Windows PC, changes are not reflected to ~/OneDrive directory.

Thank you,
Georgios

**Comment by thomasfedb** [comment]
@gtsotsos remote changes are not reflected immediately, they should sync after a short delay. Can you confirm if this is still an issue?

**Comment by abraunegg** [comment]
@gtsotsos 
Can you provide an update here?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
