### ISSUE TITLE
When files are shared in the web interface, they get duplicated on the client

### ISSUE THREAD

**Issue by docsmooth** [skilion/onedrive#243]
When I share a file in OneDrive with co-workers (click "Share" and then choose their names and send the email from the interface), the onedrive client immediately starts duplicating all files in the folder structure to a "folder-`hostname`" folder.  It's done this twice, so now I have:
/folder
/folder-`hostname`
/folder-`hostname`-`hostname`

A "diff -r" on the 2 folders shows no difference until I start changing files.

**Comment by docsmooth** [comment]
The folllowing logs are created:
Oct 23 04:12:37 kubuntu10 onedrive[22572]: Moving: Process-kubuntu10 -> ./Process-kubuntu10                                                                                                                                                        
Oct 23 04:12:37 kubuntu10 onedrive[22572]: ./Process-kubuntu10: No such file or directory                                               
Oct 23 04:12:37 kubuntu10 onedrive[22572]: Creating directory: ./Process-kubuntu10                                                                                                                               
Oct 23 04:12:37 kubuntu10 onedrive[22572]: Creating remote directory: ./Process-kubuntu10-kubuntu10                                     
Oct 23 04:12:38 kubuntu10 onedrive[22572]: Uploading: ./Process-kubuntu10-kubuntu10/<redacted file name>

**Comment by thomasfedb** [comment]
Sounds like the metadata on the remove version is being modified in a way that leads to a mismatch, the remote version is then downloaded and the local version renamed.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
