### ISSUE TITLE
Onedrive for Business

### ISSUE THREAD

**Issue by zuruikyubi** [skilion/onedrive#244]
I have setup onedrive for personal, but when I go to do the auth for onedrive for business I can not get the URI link to come up.... am I doing something wrong?

**Comment by olorin37** [comment]
Any details? For me is working both personal and business version.

**Comment by Eddles999** [comment]
Hello good afternoon, I'm having the same problem, I have OneDrive for Business, but not OneDrive for Personal.  I'm fully logged into my browser and can access everything in my OneDrive.  So when I install onedrive-d, and run "onedrive-pref" - the first step is to authorise onedrive-d, so "onedrive-pref" gives me an URL to authorise.  However, when I copy & paste the URL in my browser, it takes me to the personal log-in page.  When I try to enter my password, it says "You cannot use your work or school account, you need to make a personal account".  As a test, I tried to make a personal account with my work email address, and it refuses to do so as there's an existing account connected to the email address already.  

How can I get my Business OneDrive account to authorise onedrive-d to access it, the URL generated by onedrive-pref doesn't work.

Any help would be greatly appreciated.  Thank you!

**Comment by Tekki** [comment]
Open the link in a private window.

**Comment by Eddles999** [comment]
Same thing.  It pops up a login page, which I type in the email address, then I get:

"That Microsoft account doesn't exist. Enter a different account or get a new one."

I click on "No account?  Create one!", then it pops up:

"You can't sign up here with a work or school email address. Use a personal email, such as Gmail or Yahoo!, or get a new Outlook email."

It's still going to the Onedrive Personal log-in page, it's not going to the OneDrive for Business log-in page.

Thank you for your speedy response!

**Comment by Eddles999** [comment]
Anyone?

**Comment by Modelmat** [comment]
It works for me.

**Comment by luodaoyi** [comment]
我也一样的问题

**Comment by yosoufe** [comment]
Same here. Personal is working but the school account doesn't work. I need onedrive for my school account while I have 1 TB capacity there. The error I get in the address bar is the following, after turning plus characters to space.

```

**Comment by thomasfedb** [comment]
@yosoufe sounds like an issue for your administrator. @zuruikyubi what do you mean by "can not get the URI link to come up" and is this still an issue?

**Comment by bugzy** [comment]
@Eddles999 onedrive-d (https://github.com/xybu/onedrived-dev) is different from this onedrive client. I hope than no one else has the two clients confused.

**Comment by redog** [comment]
I'm using this on onedrive for business with MFA enforced ( since about february) and it's working ok. Initial sync works well and monitor works well while it's running but gives me issues when it's stopped for any significant amount of time.  It might matter that our setup is a federated domain(not sure). The same #334 bug is causing me some issues though.

**Comment by abraunegg** [comment]
@redog 

To resolve that issue you need to use the code from #314:

There are 2 ways to get the latest code:

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
make install
```

Option 2:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

**Comment by abraunegg** [comment]
@zuruikyubi 
Can you provide an update please, if not close this case
