### ISSUE TITLE
With "OneDrive Files-on-Demand" enabled, onedrive creates a copy of any file downloaded by a client.

### ISSUE THREAD

**Issue by theColourSpace** [skilion/onedrive#247]
From the logs it seems as though, the remote side pushes the download as a copy operation with the same source and destination. onedrive seems to interpret this as a conflict and duplicates the file with that copy getting synced as well.

Logs:
Nov 06 22:32:03 ubuntu onedrive[8997]: Uploading: ./JD_COMP_injected copy.mp4
Nov 06 22:33:35 ubuntu onedrive[8997]: Moving: JD_COMP_injected copy.mp4 -> ./JD_COMP_injected copy.mp4
Nov 06 22:33:35 ubuntu onedrive[8997]: ./JD_COMP_injected copy.mp4: No such file or directory
Nov 06 22:33:35 ubuntu onedrive[8997]: Downloading: ./JD_COMP_injected copy.mp4
Nov 06 22:35:31 ubuntu onedrive[8997]: Uploading: ./JD_COMP_injected copy-ubuntu.mp4

First I uploaded "JD_COMP" then I downloaded it on a windows clients at "22:33:35" when I did that it saw it as move operation, and duplicated the file. Downloading "JD_COMP" again and uploading it as "copy-Ubuntu" duplicate.

Bug, no?

**Comment by thomasfedb** [comment]
Does still still occur @theColourSpace? If so I will attempt to replicate the issue.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
