### ISSUE TITLE
working behind proxy and no proxy

### ISSUE THREAD

**Issue by djvujke** [skilion/onedrive#248]
Hi, 
I'm on KDE and frequently on and off proxy. 
Proxy settings in KDE are via autoconfiguration URL.
So onedrive isn't aware of this proxy settings and can't work when behind proxy.
I've edited onedrive.service and added in service section Restart=always and RestartSec=3 as i've noticed that service fails sometimes. I'm not sure if it fails if its not able to reach destination
How to make onedrive aware whether i'm behind/or not proxy?

Thanks,
djole

**Comment by thomasfedb** [comment]
@djvujke could you provide some more details as to the type/manner of the proxy you're using? It it for all HTTP/S traffic?

**Comment by skilion** [comment]
The app uses the libcurl library to manage all connections. Libcurl respects the proxy environment variables named http_proxy, ftp_proxy, sftp_proxy, etc.

Read [here](https://stackoverflow.com/a/9447493) for an example.

**Comment by Rondom** [comment]
Well, but it's still a valid feature-request, isn't it. I think libproxy would support proxy-configs.
