### ISSUE TITLE
[Feature Request] Syncing Status Indicator.

### ISSUE THREAD

**Issue by Modelmat** [skilion/onedrive#249]
While doing the initial `onedrive` sync, is it possible to have an indicator like `apt-get` or `pacman` does when installing programs. This would help give us the size to download, as well as time remaining and similar.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by Modelmat** [comment]
Uh I don't think you own this??? Why is this being "closed"?

**Comment by abraunegg** [comment]
Because I am not going to look at it ... I am considering it defunct as the 'skilion' repository appears to have been abandoned by the original author. If you want this - close this case, open a new one under by branch where I can track it correctly.
