### ISSUE TITLE
Slow When Syncing Lots of Files

### ISSUE THREAD

**Issue by Modelmat** [skilion/onedrive#250]
I have some node_modules directories, and there are thousands upon thousands of small files. This takes forever - it's downloading at around 10Kb/s  when large files do about 1000Kb/s or more.

I would recommend adding a download manager that downloads everything at once, like the windows one does, - atleast for small files.

**Comment by webermarcolivier** [comment]
Same problem here. I am uploading tens of thousands of files and it is darn slow (average ~3 KB/s), while transfer of large files is fast (~1 MB/s). This reduces a lot the usability of the client, almost to unusable.

**Comment by Modelmat** [comment]
The use of asynchronous code might also be good. Or multi-threaded downloading!

**Comment by thomasfedb** [comment]
@Modelmat sounds like you should be using a different solution for this sort of data, aka git. OneDrive is meant for documents, not for code.

**Comment by Modelmat** [comment]
I know, but it's my backup solution so I can access files. Much easier than git, and my school blocks git (but not Onedrive for School)

**Comment by thomasfedb** [comment]
Git works over HTTP/S as well as SSH.

**Comment by webermarcolivier** [comment]
In my case, files are not source code, but a variety of formats (images, data files, etc). The initial synchronization (upload) took approx. 20 hours for 20k files. However, the client currently running works smoothly, detecting and synchronizing only changed files.

**Comment by abraunegg** [comment]
@Modelmat @webermarcolivier 
There are some DB performance enhancements in #314 - can you retry with that & report back?

**Comment by Modelmat** [comment]
Not really sure how to compile it... is there prebuilt binary for it yet?

**Comment by abraunegg** [comment]
You need to have an environment to 'build' binaries. The dependencies can be found here under Setup:

https://github.com/skilion/onedrive

You need mainly:
* libcurl-devel
* sqlite-devel

Then install DMD using `curl -fsS https://dlang.org/install.sh | bash -s dmd`

There are 2 ways to get the latest code:

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
make install
```

Option 2:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by Modelmat** [comment]
Sorry, I haven't had time to actually run this. I will be able to do it in one week (I am busy with tests for school)
