### ISSUE TITLE
make: dmd: Command not found - dmd is installed though

### ISSUE THREAD

**Issue by appleton252** [skilion/onedrive#251]
Hi,

I'm having a problem installing onedrive on ubuntu. I try to hit the command make and get this. However, dmd is installed. 

```
`dmd -g -inline -O -release -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:31: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127`

```
DMD is installed.

```

dmd -g -inline -O -release -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:31: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127
```
Is there something I'm missing? Would be grateful for any assistance here. 

Thank you,

**Comment by andrebrait** [comment]
Is is installed AND it's in your path? Can you post the output of `which dmd` or `whereis dmd`?

**Comment by appleton252** [comment]
It's definitely installed. How do I check the path? Where it should be installed

There is no output from both commands. Sorry for the questions, new to ubuntu.

Thank you for your assistance

**Comment by andrebrait** [comment]
@appleton252 It's okay. Newbies are always welcome. How did you install it?

If there's no output for these commands it means the executable for dmd is not in the PATH. Which means it hasn't been installed in a way the installation scripts expect it to or you might need to add it to the PATH.

**Comment by appleton252** [comment]
Thank you, I ran the command in the readme. 

`curl -fsS https://dlang.org/install.sh | bash -s dmd`

Output:

`dmd-2.077.0 already installed
dub-1.6.0 already installed

Run `source ~/dlang/dmd-2.077.0/activate` in your shell to use dmd-2.077.0.
This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
Run `deactivate` later on to restore your environment.`

Thank you,

**Comment by andrebrait** [comment]
When you run `source ~/dlang/dmd-2.077.0/activate` you need to compile onedrive in the same terminal window (the same bash process, but I'm assuming you're using a terminal emulator) you used the source command. If you close it or somehow restart bash the variables will reset to their default value.

Can you attach the file `~/dlang/dmd-2.077.0/activate`?
After you run `source ~/dlang/dmd-2.077.0/activate`, what's the value of the PATH variable? You can check it by running `echo "$PATH"` (with the quotes and the $, exactly as it's written here).

You can check if it has changed by running `echo "$PATH"` before and after running the `source` command.

**Comment by felipem775** [comment]
Could be `sudo` the problem?

I try install but I have the error when I run `sudo make install`

```
(dmd-2.077.0)➜  onedrive git:(master) make
dmd -g -inline -O -release -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
(dmd-2.077.0)➜  onedrive git:(master) sudo make install
install -D onedrive /usr/local/bin/onedrive
install -D -m 644 onedrive.service /usr/lib/systemd/user/onedrive.service
```

**Comment by sidster262** [comment]
There are actually a few more dependencies you haven't listed.
`sudo apt install git curl gcc make`
After installing those the install completed perfectly

**Comment by appleton252** [comment]
Hello,

I managed to get this working. Sorry for the delayed reply and thanks to the both of you :)

**Comment by ZhiyangLin** [comment]
How did you make it work?

**Comment by homerobse** [comment]
I managed to get rid of the dmd error by installing dmd [here](https://dlang.org/download.html), but then I got this error

`$ make
echo v1.1.1-2-gc231b13 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
/usr/bin/ld: cannot find -lcurl
/usr/bin/ld: cannot find -lsqlite3
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1`

**Comment by homerobse** [comment]
Found this: https://github.com/skilion/onedrive/issues/48

You just need to install the dev packages to get rid of the follow-up error on curl and sqlite3
```
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libsqlite3-dev
```
(There were three options of libcurl-dev, I just chose that one as it was the first of the list in apt-get output)

**Comment by tmunro55** [comment]
HI all,

I've been trying to install the onedrive sync app on Mint 19. I've gotten most of the way, but am encountering the following:

tim@gimly ~/onedrive $ source ~/dlang/dmd-2.081.1/activate
(dmd-2.081.1)tim@gimly ~/onedrive $ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/sqlite.d(71): **Error: module `stdlib` is in file 'std/c/stdlib.d' which cannot be read**
import path[0] = /home/tim/dlang/dmd-2.081.1/linux/bin64/../../src/phobos
import path[1] = /home/tim/dlang/dmd-2.081.1/linux/bin64/../../src/druntime/import
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1

Any help would be greatly appreciated.

--tim

**Comment by abraunegg** [comment]
Hi,

Your specific issue has been resolved in my branch / repository. The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by tmunro55** [comment]
Perfect. Compiled, installed and syncing.

Thank you very much.

--tim

**Comment by Rosein** [comment]
Hi, 
I have a problem with activate a specific version. When I run
`source ~/dlang/dmd-2.085.1/activate` 
bash says there is No such file or directory
I have installed dmd by zypper and command 
`whereis dmd` confirms it, because it outputs:
`dmd: /usr/bin/dmd /etc/dmd.conf /usr/share/dmd`
To be honest I am newbie and I am not sure that installing the dmd should make a new folder 'dlang' i my ~. 
Any suggestions how to activate it in another way?

**Comment by abraunegg** [comment]
If you have installed dmd via zypper there should be no need to activate .. however it should be noted that SuSE packages for dmd gave issues in the past and potentially should not be used .. ymmv

**Comment by Rosein** [comment]
You are right, it wasn't necessary. Thanks
