### ISSUE TITLE
Error when syncing (uploading)

### ISSUE THREAD

**Issue by piovisqui** [skilion/onedrive#253]
When I started syncing, an error occurred. I manually checked and all files were uploaded. Anyway, here is the log. I'm running Fedora 26.

HTTP request returned status code 412 (Precondition Failed)
{
    "error": {
        "code": "resourceModified",
        "innerError": {
            "date": "2017-11-21T20:46:57",
            "request-id": "96c7ea2b-e110-4a78-8140-cb9b32de6d8a"
        },
        "message": "ETag does not match current item's value"
    }
}

**Comment by piovisqui** [comment]
Posted that too soon. Then next error crashed the app. A path with special characters does not work.

src/sync.d:102 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x58669a]
src/main.d:184 void main.performSync(sync.SyncEngine) [0x570340]
src/main.d:162 _Dmain [0x56ff99]
onedrive.OneDriveException@src/onedrive.d(403): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "innerError": {
            "date": "2017-11-21T21:00:10",
            "request-id": "3a1c359a-6069-46d1-a9d3-3f1e25bdb0f5"
        },
        "message": "One or more invalid characters are present in the path (\/LiveFolders\/PERSONAL_PATH_WITH_?_Ç_~_ê_)."
    }
}
----------------
src/onedrive.d:38 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x57b31b]
src/sync.d:544 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x58824c]
src/sync.d:529 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5883f6]
src/sync.d:529 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5883f6]
src/sync.d:402 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x586589]
src/main.d:184 void main.performSync(sync.SyncEngine) [0x570340]
src/main.d:162 _Dmain [0x56ff99]

**Comment by RJaBi** [comment]
What file (filepath) is it? There are a number of characters which Onedrive itself doesn't allow
> " * : < > ? / \ | 
source: https://support.office.com/en-us/article/Invalid-file-names-and-file-types-in-OneDrive-OneDrive-for-Business-and-SharePoint-64883a5d-228e-48f5-b3d2-eb39e07630fa

This is the first place i'd look.

**Comment by piovisqui** [comment]
Yeah, the question mark is the problem.
