### ISSUE TITLE
How to skip folder from syncing? Regex issue

### ISSUE THREAD

**Issue by piovisqui** [skilion/onedrive#254]
I tried to skip the location "FOLDER1/FOLDER with spaces in name and big files/"
`skip_file = ".*|~*|FOLDER1/*.*"
skip_file = ".*|~*|FOLDER1/*"
skip_file = ".*|~*|FOLDER1/.*"
skip_file = ".*|~*|FOLDER1\/.*"
`
and many others, but it seems that when you add a slash / the regex after it are ignored. The option 
`skip_file = ".*|~*|FOLDER1*"`
without the slash works.

**Comment by skilion** [comment]
`skip_file` is used to filter file and directories according to their name. To skip a specific file or directory you need to use [Selective sync](https://github.com/skilion/onedrive#selective-sync).
