### ISSUE TITLE
No network connection

### ISSUE THREAD

**Issue by jarwinder** [skilion/onedrive#255]
For the past couple of days (maybe 3 or 4 days), whenever I try to sync, using "onedrive" or "onedrive -v", I get this:

Loading config ...
Initializing the OneDrive API ...
No network connection

My network works, I'm on a wired DHCP very plain and basic network, nothing out of the ordinary. It worked recently and I was able to upload all my files. Now, any time I try to sync, I get this "no network" message. Could it be caused by a change in the API? Am I missing something?

**Comment by GeraldScott** [comment]
I am having a similar problem when I run onedrive on a laptop with Fedora 27, but oddly enough, it works fine from my desktop with Centos 5 (I want two copies of the contents of my OneDrive). I installed onedrive in the same way on the same day.

I am going to try to fix it with a reinstallation, as per [this issue](https://github.com/skilion/onedrive/issues/175).

**Comment by thomasfedb** [comment]
@jarwinder @GeraldScott does this issue persist with the latest version?

**Comment by jarwinder** [comment]
@thomasfedb I just updated to the latest version, had to resync, but the issue seems to be gone. thanks!

**Comment by thomasfedb** [comment]
@jarwinder that's great. Could you close this issue then?

**Comment by GeraldScott** [comment]
It's working beautifully. Well done and many thanks.
