### ISSUE TITLE
Start up onedrive on boot

### ISSUE THREAD

**Issue by igunter** [skilion/onedrive#257]
I'm trying to get the onedrive to start up when the server is rebooted but cannot seem to get it working.

In my /etc/rc.local file I've added
`update -rc.d onedrive -m & defaults`

I've also tried by creating a scheduled task in my crontab file
`* * * * * onedrive -m`

and it doesn't seem to work. It only syncs when I specifically execute it in terminal.

I'm running Ubuntu Server 14.04 so I can't add it to the startup programs as I don't have a GUI installed.

Ideally I'd like it to turn on even before I log in.

**Comment by igunter** [comment]
Okay, I've finally got it attempting to start through the cron, but I'm getting this error in my log file.
`Authorize this app visiting:

Invalid uri
Could not initialize the OneDrive API
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri:`

My cron line looks like this:
`* * * * * /home/server/onedrive/onedrive >> /var/log/script_output.log 2>&1`

But, it works fine when I manually run onedrive -m from the prompt.

**Comment by marcusball** [comment]
Is your cron script running under your user account? Try specifying the `--confdir` option to make sure the cron script is finding the config directory.

**Comment by thomasfedb** [comment]
@igunter I'd say that @marcusball is correct, that you're not loading your config correctly.

**Comment by abraunegg** [comment]
@igunter 

Any update on this issue? #314 has updated service files for systemd & init.d file for non-systemd systems to allow service to start at boot.

In terms of your cron issue, the issue stems from the environment variables that cron inherits when starting. Additionally:

```
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=X 
MAILFROM=Y
HOME=/
```

These variables impact the environment variables crontab uses.

**Comment by abraunegg** [comment]
@igunter 
Any update from your side? If not, please can you close this case

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
