### ISSUE TITLE
Make fails on Ubuntu 16.04 even after following all the instructions

### ISSUE THREAD

**Issue by d1g33k** [skilion/onedrive#259]
I followed the guide to the tee, installed DMD and all its dependencies, but the make command still fails with the following output:

`make
dmd -g -inline -O -release -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
Makefile:31: recipe for target 'onedrive' failed
make: *** [onedrive] Killed`

`dmd --version
DMD32 D Compiler v2.077.0
Copyright (c) 1999-2017 by Digital Mars written by Walter Bright`

**Comment by OHNOSROFLCOPTER** [comment]
I use Ubuntu 16.04 as well but I was able to install it just fine. Were there any errors when you ran:
`curl -fsS https://dlang.org/install.sh | bash -s dmd`

**Comment by Nobiel** [comment]
some issue on CentOS6

**Comment by pureair** [comment]
same here ubuntu 16.04.

**Comment by skilion** [comment]
I tried on a VM with Ubuntu 16.04 and the app compiled successfully. I used DMD from the d-apt repository though. You can try it to see if it works for you, I put the steps in the [readme](https://github.com/skilion/onedrive#dependencies-ubuntudebian)
