### ISSUE TITLE
Failed to start onedrive.service: Unit onedrive.service not found.

### ISSUE THREAD

**Issue by b3b0** [skilion/onedrive#261]
Hey friend -

After following all instructions and installing, downloading files successfully, I wanted to make sure that the onedrive service is running. 

```
$ systemctl --user start onedrive
Failed to start onedrive.service: Unit onedrive.service not found.

$ systemctl --user enable onedrive
Failed to enable unit: Unit file onedrive.service does not exist.
```

Also tried:
```
$ systemctl --user start onedrive.service
$ systemctl --user enable onedrive.service
```

With no luck, even inside of the ~/onedrive/ directory.

Odd, since I installed this on Ubuntu Xenial and Manjaro earlier in the day and didn't encounter this issue. 

The machine with the issues is: 
- running Ubuntu Artful
- with all dependencies
- installed according to standard instructions
- downloading all files splendidly when running . ~/onedrive/onedrive

Any suggestions?

Much appreciated. Great work.

**Comment by thomasfedb** [comment]
Is `/usr/lib/systemd/user/onedrive.service` present?

**Comment by obrobertsen** [comment]
systemctl --user daemon-reload

**Comment by thomasfedb** [comment]
Looks like you can close this issue @skilion.

**Comment by b3b0** [comment]
I switched to a different solution after no reply. Sorry guys. Cannot confirm that this solved the issue.

**Comment by thomasfedb** [comment]
Please close this issue @b3b0 if you no longer require it looked into.

**Comment by gvegayon** [comment]
In my case, I had to create the service file by saving the file `/usr/lib/systemd/user/onedrive.service` with the following contents:

```
[Unit]
Description=OneDrive Free Client
Documentation=https://github.com/skilion/onedrive

[Service]
ExecStart=@PREFIX@/bin/onedrive -m
Restart=no

[Install]
WantedBy=default.target
```

And then type

```shell
$ systemctl --user start onedrive
$ systemctl --user enable onedrive
Created symlink from /home/vegayon/.config/systemd/user/default.target.wants/onedrive.service to /usr/lib/systemd/user/onedrive.service.
```

**Comment by abraunegg** [comment]
@gvegayon 

The original unit files also contain issues which are fixed in my fork. Additionally, the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by gvegayon** [comment]
Thanks for the heads up!
