### ISSUE TITLE
Automatically Start Onedrive sync Service

### ISSUE THREAD

**Issue by joseortiz3** [skilion/onedrive#263]
I didn't see this in the documentation, and am hesitant to try this project until I get a yes/no about this question:

The documentation shows [how to enable and start the Onedrive Sync service from command line](https://github.com/skilion/onedrive#onedrive-service), but it does not mention if this starts it only for the duration of the user session, or if this starts the service for all-time.

If this starts the service for all-time, please indicate this in the documentation. If it does not, and as-is the service must be restarted after every restart, etc, please also indicate this. If steps need to be taken to automatically start the one-drive service (such as edit .bashrc, etc), please post these steps here and in the documentation.

Hope to hear that there's a tested way to get this service to automatically start, as it does in windows.

**Comment by Scimmia22** [comment]
Read up on how systemd --user services work. Very little about your question makes sense, so I'm not sure how to answer it.

**Comment by joseortiz3** [comment]
@Scimmia22 I'm sorry my question didn't make sense to you, but I don't get the sense you are trying to be very helpful either. Without saying which parts you are having trouble understanding, and for what reasons, I can only try to reformat the issue in a clearer way:

If the two commands `systemctl --user enable onedrive`, `systemctl --user start onedrive` result in a configuration that auto-starts the service after every boot of the system
- say "Yes, the service will autostart on boot by default after running those two commands".
- consider the suggestion to add something like "Running these two commands will configure the service to be automatically started on reboot" to the [instructions](https://github.com/skilion/onedrive#onedrive-service)

If those two commands do not result in a configuration that starts the service on every system boot
- say "Those two commands will not result in a configuration that starts the service on reboot. You must do something else to configure the system to automatically start the Onedrive service on boot."
- consider the suggestion to add something like "These two commands will not result in a system configuration that restarts the service by default. Users may wish to do something else to get the service to automatically start after boot."

Certainly it's not expected that every person who uses this extension should need to understand the intricacies of `systemctl` and `systemd` to be able to understand what running these two commands does.

**Comment by Scimmia22** [comment]
It "enables" the daemon to start with the user session (not on boot), and starts it. This is systemd 101.

**Comment by joseortiz3** [comment]
Thanks.
