### ISSUE TITLE
CIFS mount

### ISSUE THREAD

**Issue by masterlog80** [skilion/onedrive#264]
Hello.
After the first sync completed successfully, I noticed that when changing a local file's content keeping the same name (e.g. file backup-monday.tgz is updated weekly), the new file is NOT uploaded over the old one, or neither uploaded with a different name.
After the new file's contend is saved, info on verbose mode does not shown anything special:

**onedrive --monitor --verbose**
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /media/OneDrive
Initializing the Synchronization Engine ...
Applying differences ...
Uploading differences ...
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX root
The directory has not changed
Uploading new items ...
Initializing monitor ...
Monitor directory: .
Monitor directory: ./TEMP
<...>
Applying differences ...
Uploading differences ...
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX root
The directory has not changed
<...>

Config files are as below:
**cat config**
#Directory where the files will be synced
sync_dir = "/media/OneDrive"
#Skip files and directories that match this pattern
skip_file = ".*|~*"

**cat sync_list**
TEMP
REMOTE_BACKUP

However, if I do add a new file into the folder it's uploaded correctly. Also, if I do remove files from the Web, those changes are not committed locally, like it works as one-way sync.

As the synced folder is located in a external NAS (using XFS FileSystem) mounted R/W by CIFS, can this be the reason? Does a local EXT4 filesystem is required?

Thanks

**Comment by masterlog80** [comment]
Hello,

After moving data to an EXT4 partition, it looks it's working.
So, I think this need a remote EXT4 partition on NAS storage to work, maybe using a NFS mount.
Is there anyone able to check, please?

Thanks

**Comment by skilion** [comment]
`--monitor` mode requires [inotify](https://en.wikipedia.org/wiki/Inotify) to work, which is a feature dependent on the filesystem. However this is only required for real-time tracking of local changes.

Every 45s remote changes are downloaded and a complete scan of the files is performed for detecting local changes to upload. This should work no problem on a CIFS mount.

You can try do debug the issue by forcing the download new changes only in verbose mode. `onedrive --download --verbose`. You will need at least commit ab592f134e63edae8ee3bed64f7ec9351183e431.

**Comment by masterlog80** [comment]
Hello,
Thank you for getting back. I confirm that at my side it does not work as explained one CIFS shares mount. Also, as per my understanding, inotify does not work on CIFS:
https://stackoverflow.com/questions/8124617/getting-file-create-notifications-for-cifs-mount-in-linux/16381209

I tried to debug the the issue with the command provided, but actually it does not work:
`# onedrive --download --verbose`
`Unrecognized option --download`
`Try 'onedrive -h' for more information`

But I should have the correct version, installed trough Armbian (debian) repo:
`# onedrive --version`
`onedrive v1.0.1`

Any idea?
Thanks

**Comment by skilion** [comment]
To use the `--download` switch you need the latest commit. It has not been released yet.

**Comment by masterlog80** [comment]
Ah, ok. Any ETA to be released?

**Comment by skilion** [comment]
After I will have tested the client with OneDrive for Business I will tag a new release. Meanwhile you can download the latest version from the home page with the green 'Clone or download' button.

**Comment by masterlog80** [comment]
Thanks, but I prefer using the repo. So, waiting for update, then... ;-)
Thank you

**Comment by thomasfedb** [comment]
@masterlog80 have you tried with the latest version yet?

**Comment by masterlog80** [comment]
Hello,
Thank you for getting back. As I installed "onedrive" using the repo, my version is still 1.0.1.
I tried to use GIT and MAKE to upgrade to 1.1.0, but I faced an error:

`# make`
`dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d`
`make: dmd: Command not found`
`Makefile:29: recipe for target 'onedrive' failed`
`make: *** [onedrive] Error 127`

So, I will check again once 1.1.0 is available trough the repo. :-)
Thanks~

**Comment by thomasfedb** [comment]
You'll need to install the DMD compiler. Instructions are in the README. If you're facing an issue with a previous version, I'd suggest you file a request with the repo maintainer. I don't think you can expect this issue to be looked into if you're not prepared to test on the latest revision.

**Comment by masterlog80** [comment]
Unfortunately I got an error:

''Fetched 303 kB in 23s (13.0 kB/s)''
''W: GPG error: http://master.dl.sourceforge.net d-apt InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBCF975E5BA24D5E''
''W: Failed to fetch http://master.dl.sourceforge.net/project/d-apt/dists/d-apt/main/binary-armhf/Packages  404  Not Found''
''E: Some index files failed to download. They have been ignored, or old ones used instead.''

Any ETA to put new version on REPO?

**Comment by thomasfedb** [comment]
Hard to tell what's happened there @masterlog80 without knowing what command that error was in response to. I'm not sure what repo you're referring to, you should contact whoever maintains that repo.

**Comment by masterlog80** [comment]
Sorry, I just updated my previous reply with the command I run there. 
About my repo where I installed "onedrive", this is "SID(Unstable):
https://packages.debian.org/search?lang=en&suite=default&arch=any&searchon=names&keywords=onedrive

Thanks

**Comment by thomasfedb** [comment]
@masterlog80 if you have a look at the [package page](https://packages.debian.org/en/sid/onedrive) you'll see that the package maintainer is Norbert Preining (preining@debian.org). You should contact them with regards to packaging the latest version. Nobody here has any control over that process.

**Comment by masterlog80** [comment]
@thomasfedb thank you very much!
Regards

**Comment by abraunegg** [comment]
@masterlog80 
Is this still an issue, if not please can you close this case

**Comment by masterlog80** [comment]
Thank, closing now.
