### ISSUE TITLE
Installation with LDC

### ISSUE THREAD

**Issue by jhcsu** [skilion/onedrive#266]
As of https://github.com/skilion/onedrive/commit/ab592f134e63edae8ee3bed64f7ec9351183e431 it is now possible to to specify a compiler in the Makefile via the DC variable.  As noted [elsewhere](https://github.com/skilion/onedrive/issues/49) it should be possible to use ldmd2, the wrapper for LDC, to compile the code.

This may be a naive question resulting from me not being particularly familiar with the D language... but when using `ldmd2` as noted above, I am getting the following:

```
> ldmd2 -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/qxor.d(8): Deprecation: variable qxor.QuickXor.widthInBits immutable field with initializer should be static, __gshared, or an enum
src/qxor.d(9): Deprecation: variable qxor.QuickXor.lengthInBytes immutable field with initializer should be static, __gshared, or an enum
src/qxor.d(10): Deprecation: variable qxor.QuickXor.lengthInQWords immutable field with initializer should be static, __gshared, or an enum
src/qxor.d(11): Deprecation: variable qxor.QuickXor.bitsInLastCell immutable field with initializer should be static, __gshared, or an enum
src/qxor.d(12): Deprecation: variable qxor.QuickXor.shift immutable field with initializer should be static, __gshared, or an enum
src/sqlite.d(4): Error: module std.string import 'fromStringz' not found
src/itemdb.d(32): Deprecation: variable itemdb.ItemDatabase.itemDatabaseVersion immutable field with initializer should be static, __gshared, or an enum
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
```

Does anyone have any suggestions that might help out with the import error?  Thanks.

(Incidentally, dependencies were successfully installed first...)
```
sudo apt install libcurl4-openssl-dev
sudo apt install libsqlite3-dev
```

**Comment by skilion** [comment]
Which version of LDC are you using? I just tested the 1.6.0 and it compiles fine.

**Comment by jhcsu** [comment]
`ldc2 -version` shows this:
```
LDC - the LLVM D compiler (0.14.0):
  based on DMD v2.065 and LLVM 3.5.0
  Default target: arm-unknown-linux-gnueabihf
```
(Nothing there looks anything close to 1.6.0.  `apt-cache show ldc` also references the 0.14.0, so I'm not sure where else to look!)

**Comment by jhcsu** [comment]
Instead of using the `apt`-provided installation of LDC, I have now downloaded the ARM binary version [directly](https://github.com/ldc-developers/ldc/releases).  I can compile without errors.  Will close this issue.  Thanks!
