### ISSUE TITLE
High CPU usage?

### ISSUE THREAD

**Issue by clemi2408** [skilion/onedrive#267]
Hey,
thanks for the best onedrive sync tool out there.
i've a big collection of files stored at onedrive.
After the first full sync, i noticed that high CPU usage.
Files still getting synced, so on a functional perspective all things do fine.
But on top i see:

458 system    20   0  202920  38808  10480 R 99,7  3,8  31:03.98 onedrive   

Can you give advice how to do further analysis?

Also started onedrive with --verbose, where i see onedrive loops over my files checking if there any changes...

Regards
clem

**Comment by clemi2408** [comment]
and suddenly:

Jan  3 12:03:52 share01 onedrive[458]: monitor.MonitorException@src/monitor.d(99): inotify_add_watch failed (No such file or directory)
Jan  3 12:03:52 share01 onedrive[458]: ----------------
Jan  3 12:03:52 share01 onedrive[458]: src/monitor.d:16 void monitor.Monitor.add(immutable(char)[]) [0x56271b]
Jan  3 12:03:52 share01 onedrive[458]: src/monitor.d:75 void monitor.Monitor.addRecursive(immutable(char)[]) [0x562494]
Jan  3 12:03:52 share01 onedrive[458]: src/monitor.d:193 void monitor.Monitor.update(bool) [0x562fe0]
Jan  3 12:03:52 share01 onedrive[458]: src/main.d:169 _Dmain [0x55cbba]
Jan  3 12:03:52 share01 onedrive[458]: Creating folder ./ABC
Jan  3 12:03:52 share01 systemd[1]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Jan  3 12:03:52 share01 systemd[1]: onedrive.service: Unit entered failed state.
Jan  3 12:03:52 share01 systemd[1]: onedrive.service: Failed with result 'exit-code'.

**Comment by clemi2408** [comment]
https://github.com/skilion/onedrive/issues/101

**Comment by Rondom** [comment]
Well #101 is a closed issue, so I suggest leaving at least this one open, so the problem does not get lost
