### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by onlize** [skilion/onedrive#268]
I am trying to install it on CentOS 7. I run the following:

sudo yum install libcurl-devel - Success
sudo yum install sqlite-devel - Success
curl -fsS https://dlang.org/install.sh | bash -s dmd - Success
sudo git clone https://github.com/skilion/onedrive.git - Success
cd /onedrive

I have a problem when I try to run make command

> [user@CentOS7 onedrive]$ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
make: *** [onedrive] Error 127
[user@CentOS7 onedrive]$

What can I do?

**Comment by fiercebrake** [comment]
I just download the rpm from their website. Seems to be working in my
case...


Shalom Aleichem !
David Valiente
Cel. 7737-0206
JesuCristo Dios y Salvador... Hechos 4:11-12
"...so wonderfully does God suit men to the work he designs them for."

**Comment by onlize** [comment]
Thank you for your reply. Sorry, I am new to Linux and possible does not do something right. I downloaded dmd-2.078.0-0.fedora.x86_64.rpm file and try to install it. At first, it tells me that I cannot install it because I am missing prerequisites. When I try to install prerequisites, it says that I already have them installed.

> [user@CentOS7 Downloads]$ sudo rpm -ivh dmd-2.078.0-0.fedora.x86_64.rpm
error: Failed dependencies:
	glibc-devel(x86-32) is needed by dmd-2.078.0-0.x86_64
	libcurl(x86-32) is needed by dmd-2.078.0-0.x86_64
	libgcc(x86-32) is needed by dmd-2.078.0-0.x86_64
[user@CentOS7 Downloads]$ sudo yum install glibc-devel libcurl libgcc
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.cogentco.com
 * epel: ftp.cse.buffalo.edu
 * extras: mirror.trouble-free.net
 * updates: mirrors.mit.edu
Package glibc-devel-2.17-196.el7_4.2.x86_64 already installed and latest version
Package libcurl-7.29.0-42.el7_4.1.x86_64 already installed and latest version
Package libgcc-4.8.5-16.el7_4.1.x86_64 already installed and latest version
Nothing to do
[user@CentOS7 Downloads]$

**Comment by onlize** [comment]
I was able to install it, but I cannot start or enable the service:

> [user@CentOS7 onedrive]$ sudo make install
install -D onedrive /usr/local/bin/onedrive
install -D -m 644 onedrive.service /usr/lib/systemd/user/onedrive.service
[user@CentOS7 onedrive]$ systemctl --user enable onedrive
Failed to execute operation: Process /bin/false exited with status 1
[user@CentOS7 onedrive]$ systemctl status onedrive.service
Unit onedrive.service could not be found.

Any ideas?

**Comment by onlize** [comment]
I found the way around. Thank you.

**Comment by onlize** [comment]
Sorry, I do not remember what I did.

In the end, I gave up. onedrive did not work. I do not use it.

**Comment by liger1978** [comment]
I've packaged skilion/onedrive for CentOS 7, try this:

```bash
yum -y install https://harbottle.gitlab.io/harbottle-main/7/x86_64/harbottle-main-release.rpm
yum -y install onedrive
```
