### ISSUE TITLE
Files/Folders created in Groups are not synced in client

### ISSUE THREAD

**Issue by zaahirlaher** [skilion/onedrive#270]
We have folders and files that are created within the "Groups" Sections of Outlook 365. There is a sync option which would sync the files with OneDrive, but this seems native for Windows. How can we get these files to sync with the client?

![1](https://user-images.githubusercontent.com/653578/34669112-dab59b14-f478-11e7-9b57-fd0fd6e3eef2.png)
![2](https://user-images.githubusercontent.com/653578/34669113-db00e8a8-f478-11e7-9f0e-d9180ff79041.png)

**Comment by thomasfedb** [comment]
Would be helpful if you could provide the URI that the link attempts to open.

**Comment by zaahirlaher** [comment]
@thomasfedb, if you are referring to the xdg-opne dialog, then there is no link displayed. I assume on windows, it would probably be opening the OS onedrive software to sync the group folder/files.

**Comment by thomasfedb** [comment]
The dialogue will be triggered by a URI that there browser cannot handle that the OneDrive software would normally handle on Windows. You should be able to capture the URI either within the browser or once xdg-open is run.

**Comment by zaahirlaher** [comment]
Is is this:

odopen://sync?userId=e7f1c304-a884-4889-83f7-d98192e209fa&siteId=%7B2354aab2-3b19-4b9c-a28c-eb0eba8a4671%7D&webId=%7B8268b628-b3e8-4de5-8b6f-f803557737aa%7D&webTitle=folderName&listId=%7BDFDFF3A0-41AA-4318-B503-495DF73C87CC%7D&listTitle=Documents&userEmail=myemail&listTemplateTypeId=101&webUrl=https%3A%2F%2Fa%2Esharepoint%2Ecom%2Fsites%2Fdsomename%2Eall&webLogoUrl=_layouts%2F15%2Fimages%2Fsiteicon%2Epng&isSiteAdmin=0&webTemplate=64&onPrem=0&scope=OPENLIST

**Comment by thomasfedb** [comment]
Yep, that's what I meant. Might also be useful to detail the behaviour on Windows, and/or the behaviour you're seeking this project to support.

**Comment by zaahirlaher** [comment]
Ok, so our company uses Office365 (https://outlook.office.com). From Outlook365 we can access (still using the browser) OneDrive via https://<companyname>.sharepoint.com/personal/<username with domain>/_layouts/15/onedrive.aspx If files/folders are create/uploaded here than the Skilion client 
synchronises the files.

The problem is, when we create groups in outlook365, these groups can also have their own folders/files. You can view these groups from The outlook mail page, in the left panel. When on the groups page, you will have a files link. If you click the files link, there will be a "Browse Library" link on the right side of the page.

When select the "Browse Library" link we are taken to https://<company>.sharepoint.com/sites/<folder name>/Shared%20Documents/Forms/AllItems.aspx

One this page there is a sync link. On windows, this link would invoke the OneDrive Client and sync respective group files and folder in the local OneDrive directory. This behaviour does not happen in Linux, presumably because the link is try to open the windows client. So because of this, the Linux client cannot sync folders/files that are created in groups.

**Comment by zaahirlaher** [comment]
Looks like #283 is requesting the same feature

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
