### ISSUE TITLE
cc: No such file or directory

### ISSUE THREAD

**Issue by onlize** [skilion/onedrive#271]
I had to reinstall my CentOS 7 server and having issues with setting up OneDrive.

I cloned "git clone https://github.com/skilion/onedrive.git"

After that, I try to run make:

> [user@CentOS7 onedrive]$ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
make: *** [onedrive] Error 127
[user@CentOS7 onedrive]$ 

I think last time I installed it, I had to to run: "source ~/dlang/dmd-2.078.0/activate" but this time it does not work:

> [user@CentOS7 onedrive]$ source ~/dlang/dmd-2.078.0/activate
(dmd-2.078.0)[user@CentOS7 onedrive]$ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
cc: No such file or directory
Error: linker exited with status 255
make: *** [onedrive] Error 255
(dmd-2.078.0)[user@CentOS7 onedrive]$ deactivate

Can you help?
Thank you.

**Comment by Rondom** [comment]
According to the error message, you are lacking gcc

**Comment by onlize** [comment]
yes, this was the problem. Thank you.
