### ISSUE TITLE
[Feature request] TeamSite syncing (OneDrive for Business)

### ISSUE THREAD

**Issue by liger1978** [skilion/onedrive#274]
In Windows OneDirve, one can sync an 0365 Team site document library.  It would be great if one could also do this with skilion/onedrive.

**Comment by wimpunk** [comment]
Are team sites the same as sharepoints?

**Comment by liger1978** [comment]
Could be a duplicate...No idea if an Office 365 SharePoint Team Site is the same as an on-site  SharePoint Team Site.

**Comment by bugzy** [comment]
Onedrive Team sites are Sharepoint document libraries. The solution being discussed in #283 will resolve this request.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
