### ISSUE TITLE
Error registering url

### ISSUE THREAD

**Issue by ppadial** [skilion/onedrive#277]
After copyintg the url after authorise the app, im getting

```std.net.curl.CurlException@std/net/curl.d(4392): Peer certificate cannot be authenticated with given CA certificates on handle 206B000
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, const(char[])) [0x5e4256]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x5e41c9]
??:? void std.net.curl.Curl._check(int) [0x5bed48]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x5bf17c]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x5bc308]
src/onedrive.d:386 std.json.JSONValue onedrive.OneDriveApi.perform() [0x571caf]
src/onedrive.d:375 std.json.JSONValue onedrive.OneDriveApi.perform(const(void)[]) [0x571ac1]
src/onedrive.d:332 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x572105]
src/onedrive.d:252 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x57130e]
src/onedrive.d:237 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x5711fb]
src/onedrive.d:84 bool onedrive.OneDriveApi.authorize() [0x570172]
src/onedrive.d:64 bool onedrive.OneDriveApi.init() [0x56ff96]
src/main.d:97 _Dmain [0x568bcd]
```

Im using latest master.

**Comment by skilion** [comment]
The error log is incomplete, please post also the text before "----------------".
Refer to [this](https://github.com/skilion/onedrive#reporting-issues) when posting issues.

**Comment by hughesjm80** [comment]
onedrive --verbose
Loading config ...
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: ----REMOVED----
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "c5e202c8-9fdd-4e52-8f1c-767984dd7f97",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: Transmission data parser failure: Authorization Code is malformed or invalid.\r\nTrace ID: b65377ec-1fb9-4d96-ad34-d240fb9b0f00\r\nCorrelation ID: c5e202c8-9fdd-4e52-8f1c-767984dd7f97\r\nTimestamp: 2018-01-20 19:25:01Z",
    "timestamp": "2018-01-20 19:25:01Z",
    "trace_id": "b65377ec-1fb9-4d96-ad34-d240fb9b0f00"
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x571ef0]
src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x572082]
src/onedrive.d:252 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x57127e]
src/onedrive.d:237 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x57116b]
src/onedrive.d:84 bool onedrive.OneDriveApi.authorize() [0x5700e2]
src/onedrive.d:64 bool onedrive.OneDriveApi.init() [0x56ff06]
src/main.d:97 _Dmain [0x568b3d]

**Comment by hughesjm80** [comment]
Tested latest commit d9a5d1b. Successfully entered response uri and completed full sync.

**Comment by ppadial** [comment]
I will check it, thanks @hughesjm80

**Comment by ppadial** [comment]
Yes, he made a commit fixing this issue, but now, when i run this app in a container, it simply doesn't not work :\ but it works with version 1.0.1.

:(

**Comment by skilion** [comment]
There are no significant changes that should prevent the app to work in a container.
Anyway the main issue is solved.

**Comment by ppadial** [comment]
Well, in a clean environment im having this error again
```
Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=Mcf92e0fb-f639-1c2b-cd15-e2d9b32b5907
std.net.curl.CurlException@std/net/curl.d(4392): Problem with the SSL CA cert (path? access rights?) on handle 1B32970
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, const(char[])) [0x5e4256]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x5e41c9]
??:? void std.net.curl.Curl._check(int) [0x5bed48]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x5bf17c]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x5bc308]
src/onedrive.d:386 std.json.JSONValue onedrive.OneDriveApi.perform() [0x571caf]
src/onedrive.d:375 std.json.JSONValue onedrive.OneDriveApi.perform(const(void)[]) [0x571ac1]
src/onedrive.d:332 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x572105]
src/onedrive.d:252 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x57130e]
src/onedrive.d:237 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x5711fb]
src/onedrive.d:84 bool onedrive.OneDriveApi.authorize() [0x570172]
src/onedrive.d:64 bool onedrive.OneDriveApi.init() [0x56ff96]
src/main.d:97 _Dmain [0x568bcd]
```
The version im running, is:
```
onedrive v1.1.1
```

Maybe im missing a dependency?

**Comment by skilion** [comment]
There is a problem with the SSL certificates of your environment, the issue it is not related to the app itself

**Comment by ppadial** [comment]
My environment? i don't have SSL certs, is a clean machine in a clean network...

**Comment by ppadial** [comment]
My host info: 
```ppadial@runa:$ nslookup
> google.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   google.com
Address: 216.58.214.174
```
So my DNS are the google ones, and i'm not using proxies. So, could be a connection from the curl lib when you query the url to get the token?

**Comment by skilion** [comment]
I cannot help on this issue but you can start to diagnose your problem from [here](https://duckduckgo.com/?q=curl+Problem+with+the+SSL+CA+cert)

**Comment by ppadial** [comment]
I'm reading thsi code

```conn.handle.set(CurlOption.ssl_verifypeer, 0);``` for HTTP
but it will disable the verification at all, i will use my GSM network to verify is nothing on my side.

**Comment by ppadial** [comment]
Well it failed also in the GSM network of my phone, so it should be an issue. I will check your code maybe tomorrow to debug your post command for redeem code in Onedrive file to see what happens.

**Comment by Scimmia22** [comment]
No SSL certs? So you cannot use HTTPS at all? Sounds like a faulty container

**Comment by ppadial** [comment]
Well, im using this dockerfile
```# Multi-stage build - See https://docs.docker.com/engine/userguide/eng-image/multistage-build
FROM dlanguage/dmd as dmd

ENV TOOL_VERSION v1.1.1

RUN apt-get update && \
    apt-get install -y git make libcurl4-openssl-dev libsqlite3-dev && \
    git clone https://github.com/skilion/onedrive.git && \
    cd onedrive && \
    git checkout ${TOOL_VERSION} && \
    make && make install


# Main Build
FROM ubuntu:latest

# Labels
LABEL maintainer="Paulino Padial <github.com/ppadial>"

# Packages installation
RUN apt-get update && apt-get upgrade -y && \
    apt-get install --no-install-recommends --no-install-suggests -y apt-utils locales tzdata openssl libcurl4-openssl-dev libsqlite3-dev curl && \
    apt-get purge -y --auto-remove && \
    rm -rf /var/lib/apt/lists/*
RUN locale-gen en_US.UTF-8

# Copy and configure app files
COPY --from=dmd /usr/local/bin/onedrive /usr/local/bin/onedrive
RUN chmod +x /usr/local/bin/onedrive
RUN mkdir /confdir /syncdir

# Configure entrypoint
ADD docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

VOLUME [ "/confdir", "/syncdir" ]
WORKDIR /onedrive

# Start the container process
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD []
```

The issue is when i build the ubuntu image, but using this image: https://github.com/oznu/docker-s6-debian it works... so i dunno which package or problems with the image are :\

**Comment by ppadial** [comment]
Found, removing `--no-install-recommends --no-install-suggests` fix the issue with the container...
