### ISSUE TITLE
JSONValue is not an object - What can i do?

### ISSUE THREAD

**Issue by clemi2408** [skilion/onedrive#278]
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /media/usb01/onedrive
Initializing the Synchronization Engine ...
Applying changes of 01UFQ6O2V6Y2GOVW7725BZO354PWSELRRZ
Delta link expired, resyncing...
JSONValue is not an object
Applying changes of 01UFQ6O2V6Y2GOVW7725BZO354PWSELRRZ
Delta link expired, resyncing...
JSONValue is not an object
Applying changes of 01UFQ6O2V6Y2GOVW7725BZO354PWSELRRZ
Delta link expired, resyncing...
std.json.JSONException@std/json.d(260): JSONValue is not an object
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x5dc7a9]
??:? pure @safe bool std.exception.enforce!(std.json.JSONException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x5dc725]
??:? inout pure @property @trusted inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.objectNoRef() [0x596f19]
/usr/include/dmd/phobos/std/json.d:599 const pure @safe const(std.json.JSONValue)* std.json.JSONValue.opBinaryRight!("in").opBinaryRight(immutable(char)[]) [0x56642b]
src/sync.d:182 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x56c107]
src/sync.d:145 void sync.SyncEngine.applyDifferences() [0x56bd59]
src/main.d:190 void main.performSync(sync.SyncEngine) [0x55ce0b]
src/main.d:118 _Dmain [0x55c988]

**Comment by skilion** [comment]
Does a resync solve the issue?

`onedrive --resync --verbose`

**Comment by thomasfedb** [comment]
@clemi2408 have you tried the solution offered above?

**Comment by skilion** [comment]
I managed to reproduce the issue, solved in 008a5756b343b6072e00b6bf032896bd464b745d

**Comment by mhannonj** [comment]
Awesome!  I had the same problem, and this fix resolved the issue.

**Comment by bredebal** [comment]
> Does a resync solve the issue?
> 
> `onedrive --resync --verbose`

thank you. This fixed my problem

**Comment by abraunegg** [comment]
@bredebal 
This is fixed in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
