### ISSUE TITLE
Restart using systemd

### ISSUE THREAD

**Issue by Guiguyguillaume** [skilion/onedrive#279]
Hi,

I'm getting a lot of interruptions when uploading, not sure what the problem is, and can't seem to find one solution that works in the listed issues.

But a simple way out for me would be for the onedrive process to restart, I've used the " 
systemctl --user enable onedrive
systemctl --user start onedrive
" and it works fine.

But what should I do with systemd to make onedrive restart after a crash? (HTTP 412 error f. ex.)

Thanks!

**Comment by obrobertsen** [comment]
sudo sed -i "s/^Restart=no/Restart=on-failure/g" /usr/lib/systemd/user/onedrive.service
# or
sudo sed -i "s/^Restart=no/Restart=always/g" /usr/lib/systemd/user/onedrive.service
sudo systemctl --user daemon-reload
sudo systemctl --user restart onedrive.service

**Comment by Guiguyguillaume** [comment]
Thank you for answering!

I'm getting the following when writing the last to lines:
Failed to connect to bus: No such file or directory

Thanks

**Comment by Guiguyguillaume** [comment]
Have been now using the new config with "always" for a couple of day. One of the new update from the script brought some stability, but this helped the most, keeping on after 401's and 504's. I get by some 412's, but not always.

Still not using the last two lines, as I get an error there.
sudo systemctl --user daemon-reload
sudo systemctl --user restart onedrive.service

**Comment by obrobertsen** [comment]
It depend on OS. I am running Ubuntu 16.10 
Have you tried full resync. And check for illegal filenames.

**Comment by Guiguyguillaume** [comment]
Mint 18.3

**Comment by thomasfedb** [comment]
You'd be better off using `systemctl --user edit onedrive` and then adding `Restart=always`. This will create a user-specific override for the current user to change the `Restart` behaviour. You might also want to add `RestartSec=60` to your unit file.

**Comment by Guiguyguillaume** [comment]
Thanks for the tip!

**Comment by thomasfedb** [comment]
@Guiguyguillaume if your issue is resolve you can close it.
