### ISSUE TITLE
It is in go-slow 

### ISSUE THREAD

**Issue by he852100** [skilion/onedrive#282]
I don't know what's wrong with it 
![sudu](https://user-images.githubusercontent.com/26913892/35291011-f21b861c-00a6-11e8-8bb8-4e0facb96f60.PNG)

**Comment by obrobertsen** [comment]
Try testing your internet provider speed from command line:
> wget -O - https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py |python

**Comment by he852100** [comment]
It's been a long time ,Then I met a mistake :)
![54](https://user-images.githubusercontent.com/26913892/35288017-aac3de0c-009e-11e8-9739-4f04c7013971.PNG)
I used the tools you recommend
![we](https://user-images.githubusercontent.com/26913892/35288248-1b3666be-009f-11e8-9e04-1d0bc8e2ac23.PNG)

**Comment by he852100** [comment]
I see。 The large volume of files will be very slow.
At first it's fast.

**Comment by obrobertsen** [comment]
Maybe change of user-agent-string will boost the performance?
https://www.theregister.co.uk/2017/03/23/microsoft_onedrive_linux_slow/

**Comment by obrobertsen** [comment]
https://redmondmag.com/articles/2017/03/23/onedrive-for-business-linux-problem.aspx?m=1

**Comment by abraunegg** [comment]
@he852100 @obrobertsen 
There are DB performance additions in #314 - Can you retry using that PR / branch?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
