### ISSUE TITLE
Syncing a sharepoint document library

### ISSUE THREAD

**Issue by m1kl** [skilion/onedrive#283]
Is there any way to sync a sharepoint document library?

**Comment by thomasfedb** [comment]
Is it accessible via OneDrive?

**Comment by mickael83** [comment]
Yes I can access it through online OneDrive as you can see in the screenshot.
![sharepoint_document_library](https://user-images.githubusercontent.com/2827671/35383205-83e55786-01b9-11e8-848e-2c041886732a.png)

**Comment by thomasfedb** [comment]
Unless you can mount it into your directory tree, I doubt it will be supported by this project. Haver you looked through the OneDrive API to see if these shares are mentioned?

**Comment by mickael83** [comment]
I am not familiarized with the OneDrive API however [this issue](https://github.com/OneDrive/onedrive-api-docs/issues/651) seems to be related.

In Windows 10, I used to sync this kind of document libraries. To do so, I would click on the sync option (represented on the screenshot of my earlier post) and it would open onedrive app to allow to sync the document library with explorer. That was the reason I asked if this project supported this feature.

**Comment by gustaflarsson** [comment]
+1 Would love support for this. Having the same issues within my company. We use OneDrive and shared folders (sharepoint i assume).

**Comment by thomasfedb** [comment]
@riversource thanks for looking into this. Perhaps the first step towards supporting this, for advanced users, is to allow the `driveUrl` and others to be customised in the config file? What do you think?

**Comment by riversource** [comment]
Yes, thats a goot idea.

Meanwhile I found out how to find the corresponding driveUrl for user created Sharepoints. It also works with the tool. The magic key is the drive URL. In case you have it, Sharepoint and Onedrive works flawlessly. Unfortunately finding this URL is sometimes not that easy.

**Comment by thomasfedb** [comment]
@riversource would you consider putting a PR together for this?

**Comment by riversource** [comment]
Hi,

I used the Graph Explorer and the Sharepoint API:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/sharepoint

There you can see, how to build the required URL in order to geht the drive ID:
GET https://graph.microsoft.com/v1.0/sites/[hostname]:/[PATH]:/drives

So what you need to know is the Hostname and the Path to the sharepoint website collection. Example:
GET https://graph.microsoft.com/v1.0/sites/contoso.sharepoint.com:/teams/hr:/drives

I created a Sharepoint website collection called "Backup" in the Sharepoint Admin Center. So the URL is:
GET https://graph.microsoft.com/v1.0/sites/myname.sharepoint.com:/sites/Backup:/drives

Unfortunately this URL cant be direclty used as "driveURL" in the sync client. But in the answer there is an entry called "id". Using this ID you can create the "driveURL":
https://graph.microsoft.com/v1.0/drives/[id]

Inserting this into driveUrl, itemByIdUrl and itemByPathUrl in the source code allows to use the sharepoint drives to be synced using this client.

**Comment by manuroc** [comment]
Until the dev implements OneDrive Groups to the app, I am following riversource's guide to modify the source code myself. However I cannot for the life of me find the Groups's [id]. I inputted the special URL into my browser (https://graph.microsoft.com/v1.0/sites/myname.sharepoint.com:/sites/Backup:/drives, but replaced with my shared drive name) but I get an "InvalidAuthenticationToken" error. Is there any way I can find out the [id] of my shared drive so that I can use it in the driveUrl etc fields? Thanks for the help!

**Comment by riversource** [comment]
Are you sure you have been logged in in the Graph browser (top left side)?

**Comment by manuroc** [comment]
Ah yeah, I made a slight mistake, works fine now thanks! I will use the id as riversource explained.

However, as I'd like to use more than 1 shared Group in the Onedrive client, I don't think it'll be possible without more major code changes. For now 1 Group is enough, though can't wait until Dev adds more complex functions!

**Comment by bugzy** [comment]
@thomasfedb @riversource it looks like someone else has made a pull request to sync libraries #302

**Comment by manuroc** [comment]
That's cool, thanks. Makes the process a tiny bit easier. 

Now next step would be to include more robust profiles management, which would allow us to add multiple personal accounts as well as Group accounts to be synced to several separate folders, like it's currently done on Windows. My knowledge isn't good enough to integrate this functionality but seems like a good feature for future versions!

**Comment by MPW1412** [comment]
Hello,

I tried to make this working building the provided PR. But I don't achieve to sync my sharepoint folder successfully:

git clone https://github.com/jorge-leon/onedrive.git
cd onedrive
checkout o365_business_group_drive_sync
make
sudo make install

Now I prepared the configuration file with the id from Microsoft's Graph Explorer and placed it in ~/.config/onedrive/config:

```
drive_url="https://graph.microsoft.com/v1.0/drives/b!ptxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxBl/root"
item_by_id_url="https://graph.microsoft.com/v1.0/drives/b!ptxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxBl/root"
item_by_path_url="https://graph.microsoft.com/v1.0/drives/b!ptxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxBl/root"
```

But when I launch onedrive now, it still doesn't try to sync the sharepoint site folder:

```
Opening the item database ...
All operations will be performed in: /home/mpw/Onedrive
Initializing the Synchronization Engine ...
Applying changes of XXXXXXXXXXXXXXXXXXXX
Processing XXXXXXXXXXXXXXXXXXXX root
Root
Processing XXXXXXXXXXXXXXXXXXXX YYYY @ ZZZZZ
The item type is not supported
Filtered out
Processing XXXXXXXXXXXXXXXXXXXX Notizbuch öffnen.onetoc2
Filtered out
Processing XXXXXXXXXXXXXXXXXXXX Schnelle Notizen.one
Filtered out
Processing XXXXXXXXXXXXXXXXXXXX Neuer Abschnitt 1.one
Filtered out
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of XXXXXXXXXXXXXXXXXXXX
```

Can someone give me a hint what's going wrong here?

Thanks.

Bye,
Matthias

**Comment by manuroc** [comment]
Hello,

Looks like OneDrive client is broken when syncing groups. Maybe a Microsoft API change?

I tried re-compiling and reinstalling both Skillion's and Jorge's versions but no change. This is after modifying the correct Group Graph IDs in the source.

Output looks like this:

`Key not found: lastModifiedDateTime
Key not found: lastModifiedDateTime
std.json.JSONException@std/json.d(494): Key not found: lastModifiedDateTime
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0xadab02e7]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0xadb3f3c6]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0xadaf5975]
??:? itemdb.Item sync.makeItem(ref const(std.json.JSONValue)) [0xadac6269]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0xadac711a]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0xadac6f8b]
??:? void sync.SyncEngine.applyDifferences() [0xadac6c69]
??:? void main.performSync(sync.SyncEngine) [0xadab5c0b]
??:? _Dmain [0xadab5767]`

**Comment by abraunegg** [comment]
There was an API change:

https://github.com/OneDrive/onedrive-api-docs/issues/834

Working on a fix at the moment

**Comment by jorge-leon** [comment]
Thanks for the pointer. I had this problem also since recently.  The following patch seems to work for me.

```
diff --git a/src/sync.d b/src/sync.d
index 775a7ba..66cc088 100644
--- a/src/sync.d
+++ b/src/sync.d
@@ -44,7 +44,7 @@ private Item makeItem(const ref JSONValue driveItem)
                name: "name" in driveItem ? driveItem["name"].str : null, // name may be missing for deleted files in OneDrive Biz
                eTag: "eTag" in driveItem ? driveItem["eTag"].str : null, // eTag is not returned for the root in OneDrive Biz
                cTag: "cTag" in driveItem ? driveItem["cTag"].str : null, // cTag is missing in old files (and all folders in OneDrive Biz)
-               mtime: "fileSystemInfo" in driveItem ? SysTime.fromISOExtString(driveItem["fileSystemInfo"]["lastModifiedDateTime"].str) : SysTime(0),
+               mtime: ("fileSystemInfo" in driveItem && "lastModifiedDateTime" in driveItem["fileSystemInfo"])? SysTime.fromISOExtString(driveItem["fileSystemInfo"]["lastModifiedDateTime"].str) : SysTime(0),
        };
 
        if (isItemFile(driveItem)) {

```

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
