### ISSUE TITLE
Do you support synching for OneDrive for Business?

### ISSUE THREAD

**Issue by passboltUser** [skilion/onedrive#284]
You say you support "Support OneDrive for Business (part of Office 365)". Does this mean I can synch like with https://github.com/xybu/onedrived-dev , which unfortunately doesn't support OneDrive for Business?

**Comment by he852100** [comment]
Full support

**Comment by passboltUser** [comment]
Thanks.
No, just asked if it can sync, because it doesn't explicitly mention that in the "Features:" points (maybe some point, like "Support OneDrive for Business", does imply that), but I wasn't sure and was looking for the "sync" word. 
But you may change "Support OneDrive for Business" to "Full sync support OneDrive for Business".
