### ISSUE TITLE
one drive for bussiness

### ISSUE THREAD

**Issue by xhudik** [skilion/onedrive#287]
Hi, i tried:

```
./onedrive -v
Loading config ...
No config file found, using defaults
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
```
I've put the URL into my web browser. It took me to Microsoft login page (i picked appropriate account). I got 
blank page with URL:`https://login.microsoftonline.com/common/oauth2/nativeclient?error=access_denied&error_description=AADSTS50005%3a+Device+platform+Unknown+used+by+the+user+is+an+unsupported+device+platform.+Supported+device+platforms+are%3a+iOS%2c+Android%2c+Mac%2c+and+Windows+flavors.%0d%0aTrace+ID%3a+c35660fc-6d86-418e-b055-0989efff0300%0d%0aCorrelation+ID%3a+c4e09138-1987-4210-82d6-480459df0020%0d%0aTimestamp%3a+2018-02-09+09%3a02%3a29Z` I put this URL back to `onedrive` command line and got the following error:
```
Enter the response uri:https://login.microsoftonline.com/common/oauth2/nativeclient?error=access_denied&error_description=AADSTS50005%3a+Device+platform+Unknown+used+by+the+user+is+an+unsupported+device+platform.+Supported+device+platforms+are%3a+iOS%2c+Android%2c+Mac%2c+and+Windows+flavors.%0d%0aTrace+ID%3a+c35660fc-6d86-418e-b055-0989efff0300%0d%0aCorrelation+ID%3a+c4e09138-1987-4210-82d6-480459df0020%0d%0aTimestamp%3a+2018-02-09+09%3a02%3a29Z
Invalid uri
Could not initialize the OneDrive API
```

If you take a closer look on the URL string - looks strange: `Device+platform+Unknown+used+by+the+user+is+an+unsupported+device+platform.+Supported+device+platforms+are%3a+iOS%2c+Android%2c+Mac%2c+and+Windows+flavors.`

Any idea how to overcome?

thank you

**Comment by thomasfedb** [comment]
What happens when you visit the authorization URL? Do you get prompted for a username and password? @skilion, you might need to look into this one.

**Comment by xhudik** [comment]
Hi @thomasfedb - I modify my original issue (was a bit messy and confusing). Does it make a bigger sense now? (i think there is also answer on your question)

**Comment by stevenkopite** [comment]
Any follow ups on this? i might have a similar issue..

**Comment by thomasfedb** [comment]
@stevenkopite best if you report your issue in full

**Comment by abraunegg** [comment]
@xhudik @stevenkopite @jlallet 

Any update on this issue? I have been testing #314 with 'personal' & 'business' accounts and have found no issue

**Comment by xhudik** [comment]
nope, still the same error ('Invalid uri. Could not initialize the OneDrive API') :(

**Comment by abraunegg** [comment]
Did you test with #314 ?

Can you provide --verbose output?

**Comment by jlallet** [comment]
Hi,
Just tested with pr/314. 
First, the application tries to access a sudo path:

std.exception.ErrnoException@std/stdio.d(423): Cannot open file `/var/log/onedrive/xxxxx.onedrive.log' in mode `a' (Permission denied)
----------------
??:? @safe shared(core.stdc.stdio._IO_FILE)* std.exception.errnoEnforce!(shared(core.stdc.stdio._IO_FILE)*, "std/stdio.d", 423uL).errnoEnforce(shared(core.stdc.stdio._IO_FILE)*, lazy immutable(char)[]) [0x615785]
??:? ref @safe std.stdio.File std.stdio.File.__ctor(immutable(char)[], const(char[])) [0x5cd814]
src/log.d:45 @safe void log.logfileWriteLine!(immutable(char)[]).logfileWriteLine(immutable(char)[]) [0x57fc97]
src/log.d:20 @safe void log.log!(immutable(char)[]).log(immutable(char)[]) [0x580137]
src/onedrive.d:77 bool onedrive.OneDriveApi.authorize() [0x58f163]
src/onedrive.d:67 bool onedrive.OneDriveApi.init() [0x58f05f]
src/main.d:144 _Dmain [0x581ba5]

I can go through this error if i run the app as sudo but not very far since the original error is still present:
https://login.microsoftonline.com/common/oauth2/nativeclient?error=access_denied&error_description=AADSTS50005%3a+Device+platform+Unknown+used+by+the+user+is+an+unsupported+device+platform.+Supported+device+platforms+are%3a+iOS%2c+Android%2c+Mac%2c+and+Windows+flavors.%0d%0aTrace+ID%3a+xxxxxxxxxxxxxxxxxx%0d%0aCorrelation+ID%3a+xxxxxxxxxxxxxxxx%0d%0aTimestamp%3a+2018-04-23+20%3a13%3a53Z

**Comment by abraunegg** [comment]
```
std.exception.ErrnoException@std/stdio.d(423): Cannot open file `/var/log/onedrive/xxxxx.onedrive.log' in mode `a' (Permission denied)
```

This issue - your user is not part of the 'users' group - GID 100 - this is why you get that error. `make install` sets the correct permissions, but if your user is not part of the standard user group this error will occur.

> I can go through this error if i run the app as sudo but not very far since the original error is still present

What OS / kernel / Linux flavour are you running? `uname -a` and release information would be helpful.

**Comment by xhudik** [comment]
hi there,
i tried:
```
sudo onedrive --verbose
```
but no `output` has been output. Where should I put `--verbose`?

Info on my system:
```
id
uid=1000(tomas) gid=1000(tomas) groups=1000(tomas),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),108(netdev),110(lpadmin),113(scanner),119(bluetooth),135(docker),136(vboxusers),1002(jupyter)

uname -a
Linux kovral 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
```
So you are right - my user has GID 1000 not 100

**Comment by abraunegg** [comment]
@jlallet @xhudik 

What you need to do is add your user to your 'users' group:

```
usermod -a -G users <username>
```

When using #314, provide the log for the following:

```
onedrive --synchronize --verbose --debug-https
```

If your still having issues - are you free to do a WebEx (will host & send you email) to help resolve.

**Comment by abraunegg** [comment]
@jlallet 

No worries - glad it is working for you

@xhudik 

Any update from your side?

**Comment by xhudik** [comment]
hmmm, no joy ;(

I changed to your branch.
```
make
sudo make install
uid=1000(tomas) gid=1000(tomas) groups=1000(tomas),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),100(users),108(netdev),110(lpadmin),113(scanner),119(bluetooth),135(docker),136(vboxusers),1002(jupyter)

onedrive --synchronize --verbose --debug-https
Loading config ...
Using Config Dir: /home/tomas/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?error=access_denied&error_description=AADSTS50005%3a+Device+platform+Unknown+used+by+the+user+is+an+unsupported+device+platform.+Supported+device+platforms+are%3a+iOS%2c+Android%2c+Mac%2c+and+Windows+flavors.%0d%0aTrace+ID%3a+e371db68-2241-4985-9d63-6a156bee4800%0d%0aCorrelation+ID%3a+97423a7b-0bee-4922-9f57-30792aae2ff8%0d%0aTimestamp%3a+2018-04-24+10%3a42%3a09Z
Invalid uri
Could not initialize the OneDrive API
```

**Comment by abraunegg** [comment]
@xhudik 

How are you obtaining the response URL?

With what browser?

**Comment by xhudik** [comment]
I have pasted it to Firefox and picked appropriate account (a list of 2 accounts was visible and I picked the one that is actual)

**Comment by abraunegg** [comment]
So for some reason the user agent your browser or proxy server is sending to OneDrive is what is generating that error as OneDrive cannot correctly detect what system your using.

Clear your browser cache, disable any browser plugins. If you are still getting that same `access_denied` auth URL open a case with the OneDrive API team.

**Comment by abraunegg** [comment]
@xhudik 

Any update from your side?

**Comment by abraunegg** [comment]
@xhudik

Any update from your side? If not, please can you close this case out.

**Comment by xhudik** [comment]
Hi @abraunegg , sorry for the delay!
unfortunately, it is still  the same:
```
...
error=access_denied&error_description=AADSTS50005%3a+Device+platform+Unknown+used+by+the+user+is+an+unsupported+device+platform.+Supported+device+platforms+are%3a+iOS%2c+Android%2c+Mac%2c+and+Windows+flavors.
...
```

it seems our corporate allows only these: `iOS%2c+Android%2c+Mac%2c+and+Windows`. So it is likely corporate issue. Thanks for trying. I think you can lose the issue.

thanks!

**Comment by abraunegg** [comment]
@xhudik 

As you opened the case you need to close it - I cannot do that

**Comment by tiagoliveira9** [comment]
I have the same problem; our company only allows iOS%2c+Android%2c+Mac%2c+and+Windows. Could it be possible to pose as a Mac to bypass the issue?

**Comment by abraunegg** [comment]
@tiagoliveira9
It might be possible to present a different user agent string that may get around this.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. It contains defects that put you at risk of data loss and corruption. If you wish to use the latest code which contains numerous fixes and enhancements you need clone & build from here: https://github.com/abraunegg/onedrive

**Comment by tiagoliveira9** [comment]
@abraunegg  I have used your repo to install onedrive. I commented here thinking that I was commenting on your repo. Where can I edit the construction of the user agent string?

**Comment by abraunegg** [comment]
@tiagoliveira9
Please open a new ticket to look into this

**Comment by abraunegg** [comment]
Future reference - refer to https://github.com/abraunegg/onedrive/issues/666
