### ISSUE TITLE
View folders and files - but not download them locally

### ISSUE THREAD

**Issue by StraightRage** [skilion/onedrive#289]
Hi there,

first of all thank you for this great project. It really is important for me as I have OneDrive and was a Win10 user before. 

Now to the issue: I do not want to have the files I have on OneDrive to be synced on my desktop. I have 1TB of storage on OneDrive for the sole reason of keeping my desktop environment as lean as possible. 

Ideally I want it to perform like this: 
- whenever I add files in the OneDrive-folder I can upload them to the cloud
- I can see the folders and files on my desktop linux but WITHOUT downloading them (ideally a thumbail preview but text would do it too I guess)
- the files are only downloaded if I want to work with them or specifically chose to have them on my desktop

Could you help me with this? On your page I can only find commands for syncing both ends etc. 

If I start filling up 1TB of cloud it's gonna kill my desktop eventually due to downloading it all.

I use latest linux mint with XFCE if it matters.

**Comment by thomasfedb** [comment]
Maybe you should use the web interface? How do you expect the files to be present on your local machine if they're not downloaded?

**Comment by obrobertsen** [comment]
Take a look at odrive.com

**Comment by thomasfedb** [comment]
Hmm, interesting, but likely well outside of the scope of this project at present. Would require a while additional system to handle requests for particular files/folders to be synced as well as integration with Nautilus.

**Comment by StraightRage** [comment]
Well I am expecting a usable substitute for the OneDrive client on win10. I mean I have literally no usage for a 1TB cloud if I have to keep it all on my system at the same time. 

Also odrive documentation is pure garbage I installed everything as the info says but there is no follow up to it. They focus on Mac and Win where they apparently have a flawless integration with menus and options. Literally nothing on linux without 10 lines of commands...

Anyway thanks. I understand what Linux and Opensource is about but god damn give me some user comfort for once. At some point I just want to be a normal user without looking up 2 hours for every problem. Sorry

**Comment by thomasfedb** [comment]
Wrong attitude.

**Comment by StraightRage** [comment]
I did not imply anything bad to you.

This is just another frustrated user that literally spend the last two weeks to understand and use linux only to see that nothing can be achieved for his mainstream use. 
I will not bend back: user comfort is literally 0 and the time investments I already took are ridiculous. However I see that I may not be the target group of Mint now. Anyway thank you for both for the replies. Except for the last one. Wrong attitude. ;)

**Comment by thomasfedb** [comment]
If you want to complain about Linux support for OneDrive you might consider contacting Microsoft. It is their product after all...

@skilion has built a very useful utility which meets the needs of many users. That they're happy to give away this software is something you should be appreciative of. If it doesn't meet your needs that's tough, but ultimately nobody's problem except your own.

**Comment by StraightRage** [comment]
It was a rather general complaint about Linux. Not this project. 
For what it is worth the people that get Linux recommended should be informed about the discrepency for everyday mainstream users. Honestly one of those rare moments where I see why some people buy overprices OSX products: comfortability.

I know it all comes with a price in transparency and security but at some point there's gotta be a cut. Just extremely frustrated with the hours I took for learning and giving it time and getting nothing in return from Linux. Looking back I would like to punch those people in the face that just blindly recommended me linux cause "dude muh opensource can do anything man".

That might change in the future though with more frequent use for me. I will use the shitty microsoft web-app for now. Thanks guys

**Comment by thomasfedb** [comment]
Please close this issue.
