### ISSUE TITLE
What are the correct permissions on the folder?

### ISSUE THREAD

**Issue by agrigorev** [skilion/onedrive#290]
Hello,

I'm just trying to eliminate possible reasons for my issue (files, deleted in the Windows Client or Browser, get uploaded again when Linux Laptop starts), and come to the idea of persmissions. Can it be that Service has no persmissions to sync changes locally? Or, better to say, what  are the correct persmissions on the working Folder?

Regards,
Andrey

**Comment by thomasfedb** [comment]
As long as you're running `onedrive` as your user, then you should be able to sync anywhere that you can read and write. I'd suggest somewhere inside your home folder.

If you can provide more details I'd be happy to help investigate.

**Comment by agrigorev** [comment]
Hello @thomasfedb,
thanks for your feedback. My local copy is in my home folder and I'm the only user on the laptop. So,  I suppose, I have proper permissions on the folder.

**Comment by thomasfedb** [comment]
@agrigorev What is the issue you're encountering?

**Comment by agrigorev** [comment]
Hello, my issue is re-uploading of the deleted files. I have 2 laptops - one runs Windows 7 and official MS client, another one is Ubuntu and runs yours. When I delete files in Windows client, and then start my Linux laptop, your client starts to upload deleted files and folders back to the server. So,  my idea was, that - perhaps - service has not enough permissions to remove/delete files, that's wy I asked about proper permissions.

In another ticket/thread you recommended to use flag "-d". I will try it. I will also update my version of the client. I hope, this will help. The only conciderations I have with flag "-d" - does it mean, that newly created local files will not be uploaded to the server?

Cheers,
Andrey

**Comment by thomasfedb** [comment]
@agrigorev the `-d` flag will disable uploads. Please close this issue and open a new issue that actually describes the problem you are encountering.

**Comment by agrigorev** [comment]
Hello
