### ISSUE TITLE
Installation: 

### ISSUE THREAD

**Issue by Sebl29** [skilion/onedrive#291]
Hi,
I just installed it successfully and when I start it, I see this prompt:
`Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri:`

When I visit this url in my browser (chromium, chrome, firefox; last two browsers in a clean way, without any addons) I see the MS dialog, enter my email and password and got redirected to https://login.microsoftonline.com/common/oauth2/nativeclient , where I see only a blank page. Should I see a proper url? I am guessing, that there should be some information with a proper url.

When I enter anything in this prompt dialog, the answer is always "Invalid uri
Could not initialize the OneDrive API".

Any help appreciated, thx in advance.

**Comment by thomasfedb** [comment]
@Sebl29 The URL you're redirected to should have a query string. You should then copy the whole URL, including query string, and paste at the prompt. Please let us know if that fixes your issue.

**Comment by Sebl29** [comment]
as I sayed, after putting in url and password in the 2 dialogs, there is only a white blank page and the url of that site is https://login.microsoftonline.com/common/oauth2/nativeclient

Do I need to activate anything in my office365 / onedrive preferences?

**Comment by thomasfedb** [comment]
It's this with the latest version compiled from this repo?

**Comment by Sebl29** [comment]
master, d9a5d1b3b961056f78fe07504f4cbcd42e76e1ae (from 20 January, checked out yesterday). But obviously it is just about the link or my browsers.

**Comment by skilion** [comment]
When you authorize the app, after loggin in in the browser, you get redirected to a blank page. The full url should contain someting like login.microsoftonline.com/common/oauth2/nativeclient?**code**=1234567...

If it does not contain **code** it may be a temporary service disruption. It has happened to me a few times. It should work again after a few hours.
