### ISSUE TITLE
RPM spec file for Fedora compilation

### ISSUE THREAD

**Issue by pipiche38** [skilion/onedrive#292]
Find here attached a Fedora .spec file in order to produce rpm package of onedrive.
[spec-file.zip](https://github.com/skilion/onedrive/files/1706915/spec-file.zip)

**Comment by thomasfedb** [comment]
Very keen for this, as a Fedora user. Have you got this on copr? What's the best way to set this up to build each new version in this repo?

Also, is it standard to include spaces around the `@` in the vendor email address?

**Comment by pipiche38** [comment]
Good catch for the email. I should remove the space. As Copr is concerned this is what I look for. I mainly need to see how to get DND compiler

**Comment by thomasfedb** [comment]
Try asking in #fedora-devel on Freenode

**Comment by pipiche38** [comment]
Here attached is the updated spec file. [spec-file.zip](https://github.com/skilion/onedrive/files/1710566/spec-file.zip)

I have created a Copr available here : https://copr.fedorainfracloud.org/coprs/pipiche/onedrive/
For now the binaries are produced out of a srpm I have created. 

I'm using ldc compiler which is available on standard repository for Fedora

**Comment by thomasfedb** [comment]
Do you have to zip it? Just paste the source in the comment... I'll check out the copr.

**Comment by pipiche38** [comment]
%define name onedrive
%define debug_package %{nil}
%define version 1.1.1
%define release 1

Summary: A complete tool to interact with OneDrive on Linux. Built following the UNIX philosophy.
Name: %{name}
Version: %{version}
Release: %{release}
Vendor: Patrick Pichon <patrick@pichon.me>
Source: https://github.com/skilion/onedrive.git
License: GPL
Group: System Environment/Daemons
Buildroot: /var/tmp/%{name}-%{version}-%{release}-root
Requires: libcurl sqlite
BuildRequires: ldc sqlite-devel libcurl-devel

%description
A complete tool to interact with OneDrive on Linux. Built following the UNIX philosophy.
Features:

    State caching
    Real-Time file monitoring with Inotify
    Resumable uploads
    Support OneDrive for Business (part of Office 365)
    Shared folders (not Business)

What's missing:

    While local changes are uploaded right away, remote changes are delayed
    No GUI



%prep
%setup -q

%build
make DC=ldc2 PREFIX=/usr/ DESTDIR=$RPM_BUILD_ROOT

%install
mkdir -p %{buildroot}/usr/bin
install -D onedrive %{buildroot}/usr/bin/onedrive
install -D -m 644 onedrive.service %{buildroot}/usr/lib/systemd/user/onedrive.service


%files
%doc CHANGELOG.md LICENSE README.md
%defattr(-,root,root)
%attr(555,bin,bin) /usr/bin/onedrive
%attr(555,bin,bin) /usr/lib/systemd/user/onedrive.service

%clean
rm -rf $RPM_BUILD_ROOT

%changelog
* Thu Feb 8 2018 Patrick Pichon <patrick@pichon.me>
initial version

* Fri Feb 9 2018 Patrick Pichon <patrick@pichon.me>
ready for Copr

**Comment by pipiche38** [comment]
When the .spec available on git, I'll see how to build Copr directly from your repository.

**Comment by pipiche38** [comment]
%define name onedrive
%define debug_package %{nil}
%define version 1.1.1
%define release 1

Summary: A complete tool to interact with OneDrive on Linux. Built following the UNIX philosophy.
Name: %{name}
Version: %{version}
Release: %{release}
Vendor: Patrick Pichon <patrick@pichon.me>
Source: https://github.com/skilion/onedrive.git
License: GPL
Group: System Environment/Daemons
Buildroot: /var/tmp/%{name}-%{version}-%{release}-root
Requires: libcurl sqlite
BuildRequires: ldc sqlite-devel libcurl-devel

%description
A complete tool to interact with OneDrive on Linux. Built following the UNIX philosophy.
Features:

    State caching
    Real-Time file monitoring with Inotify
    Resumable uploads
    Support OneDrive for Business (part of Office 365)
    Shared folders (not Business)

What's missing:

    While local changes are uploaded right away, remote changes are delayed
    No GUI



%prep
%setup -q

%build
make DC=ldc2 PREFIX=/usr/ DESTDIR=$RPM_BUILD_ROOT

%install
mkdir -p %{buildroot}/usr/bin
install -D onedrive %{buildroot}/usr/bin/onedrive
install -D -m 644 onedrive.service %{buildroot}/usr/lib/systemd/user/onedrive.service


%files
%doc CHANGELOG.md LICENSE README.md
%defattr(-,root,root)
%attr(555,bin,bin) /usr/bin/onedrive
%attr(555,bin,bin) /usr/lib/systemd/user/onedrive.service

%clean
rm -rf $RPM_BUILD_ROOT

%changelog
* Fri Feb 9 2018 Patrick Pichon <patrick@pichon.me>
ready for Copr

* Thu Feb 8 2018 Patrick Pichon <patrick@pichon.me>
initial version

**Comment by thomasfedb** [comment]
Can you enclose that in a code block? That is ` ``` ` on the line above and below? See https://guides.github.com/features/mastering-markdown/

**Comment by pipiche38** [comment]
```
%define name onedrive
%define debug_package %{nil}
%define version 1.1.1
%define release 1

Summary: A complete tool to interact with OneDrive on Linux. Built following the UNIX philosophy.
Name: %{name}
Version: %{version}
Release: %{release}
Vendor: Patrick Pichon <patrick@pichon.me>
Source: https://github.com/skilion/onedrive.git
License: GPL
Group: System Environment/Daemons
Buildroot: /var/tmp/%{name}-%{version}-%{release}-root
Requires: libcurl sqlite
BuildRequires: ldc sqlite-devel libcurl-devel

%description
A complete tool to interact with OneDrive on Linux. Built following the UNIX philosophy.
Features:

    State caching
    Real-Time file monitoring with Inotify
    Resumable uploads
    Support OneDrive for Business (part of Office 365)
    Shared folders (not Business)

What's missing:

    While local changes are uploaded right away, remote changes are delayed
    No GUI



%prep
%setup -q

%build
make DC=ldc2 PREFIX=/usr/ DESTDIR=$RPM_BUILD_ROOT all

%install
mkdir -p %{buildroot}/usr/bin
install -D onedrive %{buildroot}/usr/bin/onedrive
install -D -m 644 onedrive.service %{buildroot}/usr/lib/systemd/user/onedrive.service


%files
%doc CHANGELOG.md LICENSE README.md
%defattr(-,root,root)
%attr(555,bin,bin) /usr/bin/onedrive
%attr(555,bin,bin) /usr/lib/systemd/user/onedrive.service

%clean
rm -rf $RPM_BUILD_ROOT

%changelog
* Fri Feb 9 2018 Patrick Pichon <patrick@pichon.me>
ready for Copr

* Thu Feb 8 2018 Patrick Pichon <patrick@pichon.me>
initial version
```

**Comment by thomasfedb** [comment]
Rather than trying to get a `.spec` added to this repo, it might be better to seperately maintain a `onedrive-rpm` repo which you can then link to copr.

**Comment by pipiche38** [comment]
I'm not sure to understand what you mean by onedrive-rpm repo ?

**Comment by pipiche38** [comment]
That is fine, but in Copr you need one single Git source. It means that we need to have the Source code, Makefile and .spec in one git location.

**Comment by thomasfedb** [comment]
Are you sure @pipiche38, I thought that copr could download source tarballs. For example:

```
Source: https://github.com/skilion/onedrive/archive/v1.1.1.tar.gz
```

**Comment by pipiche38** [comment]
You right.

However I found an other issue, in the Makefile. 
Makefile refers to .git in order to get the version number. In the Copr-build process (using rpkg) the .git directory is removed and so is lacking the possibility to create version.
Same if we look to the tarball that you suggested. the Makefile doesn't work

**Comment by thomasfedb** [comment]
You can have a patch applied using the spec file:

```
Patch1: fix-version.patch

...

%prep
%autosetup
```

**Comment by pipiche38** [comment]
wprking on it. will find a suitable and nice solution.

**Comment by thomasfedb** [comment]
Excellent! 👍

**Comment by thomasfedb** [comment]
Happy to help out if need be. This is the one piece of software on my Fedora machine that I've not managed to get a package for,

**Comment by pipiche38** [comment]
I created a git repo to store the necessary stuff for Copr build. It includes:
.copr/makefile which is going to be used by Copr build process to generate the .srpm file for platform build

[https://github.com/pipiche38/onedrive-srpm](url)

[https://copr.fedorainfracloud.org/coprs/pipiche/onedrive-srpm/](url)

**Comment by pipiche38** [comment]
Next step, could be to add a webhooks that from your repository we trigger automatically the Build ;-)

**Comment by thomasfedb** [comment]
That link is broken @pipiche38

**Comment by pipiche38** [comment]
https://github.com/pipiche38/onedrive-srpm

https://copr.fedorainfracloud.org/coprs/pipiche/onedrive-srpm/

**Comment by thomasfedb** [comment]
Thanks @pipiche38! I'll try installing from your repo and see how I go!

**Comment by thomasfedb** [comment]
Also, @pipiche38, do you think it's worth trying to get the package included into the Fedora repo proper?

**Comment by thomasfedb** [comment]
@skilion wanted to check, do you have any appetite for merging the RPM spec and copr Makefile into your repo?

**Comment by pipiche38** [comment]
@thomas I had a check to your revised/simplified version of onedrive.spec which looks good. My issue is that the version number is hard coded, while I was expecting something more independent and taking information directly from the git source repository.

**Comment by thomasfedb** [comment]
@pipiche38 That's fairly standard practice as far as I can tell from the Fedora official repos. Probably because the .patch, etc, might need to be updated with different versions of the package.

**Comment by pipiche38** [comment]
@thomas, fine with me. I think that you have most of the work done, so I 
leave it to you make it. So you will have the full ownership of the 
onedrive source code as well as the Fedora/CentOS packaging.

**Comment by thomasfedb** [comment]
@pipiche38 I don't own the onedrive source code.

**Comment by pipiche38** [comment]
@thomas sorry I thought it was. My mistake.

Nevertheless , I understand the approach to work with a tar ball and get 
the version number embedded in the .spec file, but It will prevent to 
have daily build in a kind of automatic way.

For instance, 2 days agos a fix has been produce.

We may consider to have 2 builds, one based on your approach tar and 
hardcoded version number and an other one aligned with the latest 
version of the source code.

**Comment by pipiche38** [comment]
For the daily/realtime build based on github changes, it would be really nice to be able to trigger the build directly from the Github.

This can be done by adding a proper tag into the Settings->Webhooks of github/skilion/onedrive

If this can be done, let me know and I'll provide you the webhooks info.

**Comment by thomasfedb** [comment]
Turns out that there's already a fedora package: https://apps.fedoraproject.org/packages/onedrive

**Comment by thomasfedb** [comment]
And in the next few hours v1.1.1 should be available in the `updates-testing` repo.

https://bodhi.fedoraproject.org/updates/FEDORA-2018-379a1c9699

**Comment by thomasfedb** [comment]
Given that, we can probably close this issue.

**Comment by pipiche38** [comment]
Excellent !

Envoyé de mon iPhone

**Comment by thomasfedb** [comment]
@pipiche38 could you close this?
