### ISSUE TITLE
One-way sync?

### ISSUE THREAD

**Issue by kirbyfan64** [skilion/onedrive#293]
I'm not sure whether or not this is possible, but it would be awesome...

**Comment by Sqvirrel** [comment]
Yes, I would also like a "sync only local -> remote" option. Nice for backup setups.

**Comment by skilion** [comment]
Sync local only is already possible with the `--download` switch

**Comment by thomasfedb** [comment]
@kirbyfan64 which way are you asking for? Download only is already provided, so please close this issue if that's what you're looking for.

**Comment by kirbyfan64** [comment]
Yup!
