### ISSUE TITLE
Synchronization crashed the client

### ISSUE THREAD

**Issue by Sqvirrel** [skilion/onedrive#294]
First, thanks for a very good and nice onedrive client for linux. I use it mainly to upload my backups to the cloud. Initially I had some problems with the client appending my account-name to the end of files, but after I turned of monitoring, and instead cron-tabbed the client to a time in the middle of the night, it works ok.

Now I have a new problem where the client suddenly cashed when trying to upload/synchronize the folder. This is the verbose output when running the command "onedrive --confdir="/home/bareos/.config/onedrive" --verbose" :
```
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /media/bareosdrive/onedrive
Initializing the Synchronization Engine ...
Trying to restore the upload session ...
Continuing the upload session ...
Uploading fragment: 0-10485760/66878760588
onedrive.OneDriveException@src/onedrive.d(401): HTTP request returned status code 400 (Bad Request)
----------------
??:? void onedrive.OneDriveApi.checkHttpCode() [0x3975116b]
??:? std.json.JSONValue onedrive.OneDriveApi.uploadFragment(const(char)[], immutable(char)[], long, long, long) [0x3975028c]
??:? std.json.JSONValue upload.UploadSession.upload() [0x3975bb60]
??:? void sync.SyncEngine.init() [0x39757f59]
??:? _Dmain [0x39748057]
```

This happens in 2 seconds after I run the command. The first time, it actually uploaded for a while before the error occurred , but now its happens instantaneous. Keep in mind that several of the files are 10-50gb large, could that be the problem?

**Comment by Sqvirrel** [comment]
I see my problem is probably a duplicate of this: https://github.com/skilion/onedrive/issues/121
So yes, I guess this problem is related to files over 10gb in size. I use the onedrive client for uploading backup-files, so as soon as I changed the maxfilesize in the backup-software to 10gb, the onedrive-client works as a charm!

**Comment by skilion** [comment]
Thanks for finding the cause of the problem. Keep the issue open, I will see to put a better error message.

**Comment by abraunegg** [comment]
I have pushed a patch in #314 that resolves this issue

**Comment by abraunegg** [comment]
@Sqvirrel 

Any update? Can you retest with #314?

**Comment by abraunegg** [comment]
@Sqvirrel 
Any update?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
