### ISSUE TITLE
Service causes delayed startup

### ISSUE THREAD

**Issue by FlorisRemmen** [skilion/onedrive#295]
Hi

Maybe not entirely related to onedrive v1.0.1. 

I tried using the service, added a time delay to make it start a bit later (this due to the fact that my OneDrive folder is loaded after system boot), but now the service just delays my startup by 1m30s.

```
[Service]
ExecStartPre=/bin/sleep 90
ExecStart=/usr/local/bin/onedrive -m
Restart=no
```

I have erased this line from the service, but it persists. Should I reinstall my OneDrive or can I fix this in an easier way? It shows up as user@1000.service

```
systemd-analyze blame
1min 30.200s user@1000.service
```

Thanks in advance.

**Comment by thomasfedb** [comment]
@FlorisRemmen What do you mean by "it persists"?

You should seek support from your Linux distribution's community. This issue is with your systemd configuration rather than onedrive.

**Comment by abraunegg** [comment]
@FlorisRemmen 

In #314 the service files are updated - can you look at those changes and report back?

**Comment by abraunegg** [comment]
@FlorisRemmen 
Given the changes in #314 - can we close this issue out now?

**Comment by FlorisRemmen** [comment]
yes!

**Comment by abraunegg** [comment]
@FlorisRemmen 

Great - if you can close the issue that would be great
