### ISSUE TITLE
Feature request: Only sync local to remote

### ISSUE THREAD

**Issue by Sqvirrel** [skilion/onedrive#297]
I use this client only for uploading backup archive files to the cloud. I have encountered various bugs that changes the file names, appending the account name to the file name.

I would very much like an argument that forces the client to do a one-way sync from local to remote, making sure that the remote cloud files are an exact replica of the local files, disregarding modified dates or anything. 
How it accomplishes this, by deleting or renaming or syncing the remote files in the process does not matter to me, as long as I can be 100% sure that the client will positively upload my valuable archive files to the cloud.

This would be a perfect addition to the functionality to the client. As before, thank you very much for a very nice onedrive client for linux.

**Comment by thomasfedb** [comment]
@Sqvirrel Would you consider a PR?

**Comment by abraunegg** [comment]
Pull #314 provides this functionality

**Comment by bertin0** [comment]
@abraunegg and how do you do it?

**Comment by abraunegg** [comment]
> and how do you do it?

Unsure what your asking here ..

How do you add the patch to the source code?
How do I sync one way using my patch?

Can you clarify?

**Comment by bertin0** [comment]
Sorry I'm a bit of a newbie with git and all this. How do I use your patch? I have installed it

**Comment by sbocquet** [comment]
Hi,

You need to clone its repository locally, and compil like you've done with this one.
Then you can test the new features.
Run ./onedrive --help to see the new options.

**Comment by abraunegg** [comment]
@bertin0 

Any update? Where you able to test #314?

There are 2 ways to get the latest code:

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
make install
```

Option 2:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

**Comment by abraunegg** [comment]
@Sqvirrel @bertin0 
Can you advise that the changes in #314 resolve your issue? If yes, please can you close this case.

**Comment by abraunegg** [comment]
@Sqvirrel @bertin0 
Any update from your side? If not, please can you close this case.

**Comment by mnpenner** [comment]
So... to upload a single directory once, what would I do?

```sh
onedrive --upload-only --syncdir /data/gopro/100GOPRO --single-directory Bali2018
```

Would that upload the contents of `/data/gopro/100GOPRO` on my machine to my OneDrive account in the `Bali2018` directory? Will `100GOPRO` directory be created, or just its contents?

**Comment by abraunegg** [comment]
@mnpenner 
First you need to use the #314 branch

If your local directory that you want to sync is `/data/gopro/100GOPRO/Bali2018` then you would use:

```
onedrive --synchronize --upload-only --syncdir /data/gopro/100GOPRO --single-directory 'Bali2018'
```

This will create the correct directory structures on your OneDrive account and upload the contents under the OneDrive root in a folder called `Bali2018`

I would also add the `--local-first` flag so that the upload is done first rather than checking OneDrive & downloading changes.

```
onedrive --synchronize --upload-only --syncdir /data/gopro/100GOPRO --single-directory 'Bali2018' --local-first
```

Example:

```
onedrive --synchronize --upload-only --syncdir /data/gopro/100GOPRO --single-directory 'Bali2018' --local-first --verbose
Loading config ...
Using Config Dir: /root/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /data/gopro/100GOPRO
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 1096293813981
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from this selected path: Bali2018
Syncing changes from selected local path only - NOT syncing data changes from OneDrive ...
Uploading differences of Bali2018
Uploading new items of Bali2018
OneDrive Client requested to create remote path: Bali2018
The requested directory to create was not found on OneDrive - creating remote directory: Bali2018
Sucessfully created the remote directory Bali2018 on OneDrive
Uploading file Bali2018/IMG_3011.JPG... done.
Remaining free space: 1096290282834
Uploading file Bali2018/IMG_3016.JPG... done.
Remaining free space: 1096286118486
Uploading file Bali2018/IMG_3006.JPG... done.
Remaining free space: 1096282865249
Uploading file Bali2018/IMG_3014.JPG... done.
Remaining free space: 1096278868508
Uploading file Bali2018/IMG_3008.JPG... done.
Remaining free space: 1096275748896
Uploading file Bali2018/IMG_3007.JPG... done.
Remaining free space: 1096272518585
Uploading file Bali2018/IMG_3017.JPG... done.
Remaining free space: 1096268944352
Uploading file Bali2018/IMG_3002.JPG... done.
Remaining free space: 1096265192428
Uploading file Bali2018/IMG_3013.JPG... done.
Remaining free space: 1096261142515
Uploading file Bali2018/IMG_3015.JPG...
Uploading fragment: 0-4273123/4273123
OneDrive Response: '201 - Created'
Remaining free space: 1096256869392
Uploading file Bali2018/IMG_3001.JPG... done.
Remaining free space: 1096253467280
Uploading file Bali2018/IMG_3000.JPG... done.
Remaining free space: 1096250693984
Uploading file Bali2018/IMG_3009.JPG... done.
Remaining free space: 1096246831492
Uploading file Bali2018/IMG_3005.JPG... done.
Remaining free space: 1096243483647
Uploading file Bali2018/IMG_3004.JPG... done.
Remaining free space: 1096240055279
Uploading file Bali2018/IMG_3010.JPG... done.
Remaining free space: 1096236204131
Uploading file Bali2018/IMG_3018.JPG... done.
Remaining free space: 1096232760058
Uploading file Bali2018/IMG_3003.JPG... done.
Remaining free space: 1096229059833
Uploading file Bali2018/IMG_3012.JPG... done.
Remaining free space: 1096225325206
```

**Comment by abraunegg** [comment]
It would be best to rename the directory locally as the code checks to see if the local directory exists before performing operations in that directory. The way the DB was setup & how the content is tracked - the local folder has to exist.

Yes, `--upload-only` would achieve the same as `--local-first` without downloading anything. Blame being up too early & not having 1st coffee @ 5am!

**Comment by mnpenner** [comment]
I tried leaving off the `--single-directory 'Bali2018'` param because I didn't want create Bali2018/Bali2018... might as well just sync it into the root. And I got this

```
root@home:~# onedrive --synchronize --upload-only --syncdir /data/gopro --verbose
Loading config ...
Using Config Dir: /root/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /data/gopro
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 695243451965
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root
The directory has not changed
Processing Arq Backup Data
The directory has been deleted
Deleting item from OneDrive: Arq Backup Data <--- !!!!!!
```

I really hope it didn't just try to delete my backup. Because that's kind of the opposite of "upload only".

**Comment by abraunegg** [comment]
Yep - that is because when you specify `--syncdir` parameter - the client sets that as the root for this operation.

Now what SHOULD be happening when using --upload-only is only uploading files from that specified path and not doing any deletion.

I think what you have hit is a corner / edge case here - where changing the local onedrive client root to something other than ~/OneDrive and syncing ... Will look into it as what you saw happen should not have happened.

**Comment by abraunegg** [comment]
@mnpenner

Can you help provide some additional information - when you normally run the client, what is your 'normal' sync dir?

Reading through the code - it actually makes sense what happened with the deletion.

If the path in the database (in this case `~/OneDrive/Arq Backup Data/`) is missing from the `--syncdir` path of `/data/gopro` then the client will treat this as 'locally deleted' thus upload this 'change'

If you now got back to using the onedrive client to perform a normal sync via `onedrive --synchronize --verbose` it will use ~/OneDrive as the local source. It will then see the gopro / bali2018 data as 'new' or 'moved' and will then proceed to download it.

I think a better solution to the whole problem would have been to create applicable symbolic links locally in ~/OneDrive and then sync as per normal, pulling in the files from across the file system as needed which would have then been replicated without issue.

The enhancements I can think of here at this point is as follows:

1. Introduce a `--dry-run` flag so you can see what 'would' be done by running the command without actually downloading / uploading / deleting / committing any change to any database or anything like that.
2. Introduce a `--no-delete` flag so when used with `--upload-only` the client does not try an delete data that is on OneDrive itself

Thoughts?

**Comment by mnpenner** [comment]
> If the path in the database (in this case ~/OneDrive/Arq Backup Data/) is missing from the --syncdir path of /data/gopro then the client will treat this as 'locally deleted' thus upload this 'change'

That makes sense, but *not* in conjunction with `--upload-only` IMO. I would think `--upload-only` only uploads, never deletes. Overwriting is up for debate -- ~~I'd personally like a non-destructive option that'd bail out instead of overwriting, but perhaps as a separate flag (`--no-overwrite` or somesuch).~~ Just read the rest of your post. Yeah, those two options would be fantastic!

> Can you help provide some additional information - when you normally run the client, what is your 'normal' sync dir?

I just started using this tool. I think I left the default of `~/OneDrive`. I just wanted to do a one-off upload, which I thought I could do via the CLI args. I've never done a full two-way sync.

In any case, I think `rclone` is more aligned with my use-case. I think it would be fine to keep this tool to its intended usage of two-way syncing. I had about 200 GB of data that I wanted to upload one-off, which I didn't trust a browser to handle.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
