### ISSUE TITLE
Does the client support multi-factor authorization?

### ISSUE THREAD

**Issue by sbunse** [skilion/onedrive#298]
Hello,
my company uses mult-factor authorization. Is there any support for this and how can this be configured?

**Comment by thomasfedb** [comment]
Have you tried @sbunse? This client authenticates through the standard Microsoft workflow, so if that works, this will to.

**Comment by sbunse** [comment]
Yes, I tried. I visited the requested page, logged in. Only my user name and password was demanded. There was no request for the second factor (typically a sms with a PIN, and I did not receive such an SMS). This is probably due to the fact, that I tried it within our intranet, where we don't need multi-factor authorization. Then I entered the uri and it failed. Probably the process works, if I try it from outside the intranet. I will try that later from home.

See my commands:
$> onedrive -m
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=OAQABAAIAAABHh4kmS_aKT........
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "743d2a09-2136-4d53-a5aa-57128abf4007",
    "error": "invalid_grant",
    "error_codes": [
        50076
    ],
    "error_description": "AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use **multi-factor authentication** to access '00000003-0000-0000-c000-000000000000'.\r\nTrace ID: ca074afd-cd01-42da-bb4b-e1ebf3182d00\r\nCorrelation ID: 743d2a09-2136-4d53-a5aa-57128abf4007\r\nTimestamp: 2018-02-20 07:58:56Z",
    "suberror": "basic_action",
    "timestamp": "2018-02-20 07:58:56Z",
    "trace_id": "ca074afd-cd01-42da-bb4b-e1ebf3182d00"
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x571fe8]
src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x57217a]
src/onedrive.d:252 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x571376]
src/onedrive.d:237 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x571263]
src/onedrive.d:84 bool onedrive.OneDriveApi.authorize() [0x5701da]
src/onedrive.d:64 bool onedrive.OneDriveApi.init() [0x56fffe]
src/main.d:100 _Dmain [0x568c34]
$>

**Comment by thomasfedb** [comment]
Is this with a corporate OneDrive account?

**Comment by sbunse** [comment]
Yes, its a corporate account.

**Comment by thomasfedb** [comment]
@sbunse this project doesn't support OneDrive for Business (yet), see #244. This issue can be closed until #244 is resolved.

**Comment by abraunegg** [comment]
@sbunse 
Can you validate with #314 ? I have been testing with OneDrive Business accounts and have no issue.

**Comment by sbunse** [comment]
Sorry, but it doesn’t work. I get the error message:

{
    "correlation_id": "7631f24e-d1b3-4fd1-b5d3-8cf9b4890d4f",
    "error": "interaction_required",
    "error_codes": [
        50005
    ],
    "error_description": "AADSTS50005: Device platform Unknown used by the user is an unsupported device platform. Supported device platforms are: iOS, Android, Mac, and Windows flavors.\r\nTrace ID: 04015d38-9406-4c01-abef-4adae0f30000\r\nCorrelation ID: 7631f24e-d1b3-4fd1-b5d3-8cf9b4890d4f\r\nTimestamp: 2018-05-18 05:37:52Z",
    "timestamp": "2018-05-18 05:37:52Z",
    "trace_id": "04015d38-9406-4c01-abef-4adae0f30000"
}

Trying to do some magic, I installed the firefox add-on “user agent switcher” and faked to be a firefox browser on a windows system. The resulting error message was then:

{
    "correlation_id": "4a4b607b-f018-4280-bc33-04dd42f8a888",
    "error": "invalid_grant",
    "error_codes": [
        50076
    ],
    "error_description": "AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.\r\nTrace ID: 089bbac3-80cf-44a9-8db7-d0e0fbae0000\r\nCorrelation ID: 4a4b607b-f018-4280-bc33-04dd42f8a888\r\nTimestamp: 2018-05-18 05:35:51Z",
    "suberror": "basic_action",
    "timestamp": "2018-05-18 05:35:51Z",
    "trace_id": "089bbac3-80cf-44a9-8db7-d0e0fbae0000"
}

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
