### ISSUE TITLE
Deleted files are re-uploaded

### ISSUE THREAD

**Issue by agrigorev** [skilion/onedrive#300]
Hello,

I have 2 laptops: one runs Windows 7 with official MS client, another one runs Ubuntu with this Linux client. When I delete files under Windows, and then start Linux-laptop, those deleted files will be re-uploaded and appear again on the server.

This issue was already discussed in "Feature Request: Ability to forfeit local state and update local mirror based on server state (#223)", and proposed way - use switch "-d" - will disable upload generally. I hope, it is possible to resolve the issue in a standard way, with keeping upload running.

Cheers,
Andrey

**Comment by agrigorev** [comment]
Hello,
just now it happened again - I started my Linux laptop and it uploaded deleted files again.
I use version from October 2017.

Rgeards,
Andrey

**Comment by agrigorev** [comment]
I updated client to the version "onedrive v1.1.1-2-gc231b13" - same story. But I noticed two things:
1) I ran logging with "journalctl --user-unit onedrive -f" and saw following error message (among all UPLOAD-messages): 
HTTP request returned status code 412 (Precondition Failed)
Feb 25 21:14:00 DellD420 onedrive[1424]: {
Feb 25 21:14:00 DellD420 onedrive[1424]:     "error": {
Feb 25 21:14:00 DellD420 onedrive[1424]:         "code": "resourceModified",
Feb 25 21:14:00 DellD420 onedrive[1424]:         "innerError": {
Feb 25 21:14:00 DellD420 onedrive[1424]:             "date": "2018-02-25T20:14:01",
Feb 25 21:14:00 DellD420 onedrive[1424]:             "request-id": "7529e8bf-44a0-4966-b25c-0b7d4f6a5a72"
Feb 25 21:14:00 DellD420 onedrive[1424]:         },
Feb 25 21:14:00 DellD420 onedrive[1424]:         "message": "ETag does not match current item's value"
Feb 25 21:14:00 DellD420 onedrive[1424]:     }
Feb 25 21:14:00 DellD420 onedrive[1424]: }

2) I have a feeling, that this automatic re-upload from laptop to the server started immediately after I enabled and started "onedrive"-service. Not sure, if disabling the service will resolve the issue.

Any hints from others?

Regards,
Andrey

**Comment by abraunegg** [comment]
Generally as the local database keeps the state of what is uploaded / not uploaded - if the file is not being added to the database or recorded correctly, it will constantly be re-tried for upload - and uploaded.

In #314 I added a check to see if the file already exists on OneDrive before attempting the upload, and only re-upload the file if the file has actually changed (based on mtime).

In the case of being deleted on OneDrive and then still being uploaded (and you dont want that to happen) essentially what needs to happen is that before local uploads are performed getting a list of current changes (deletions only) on OneDrive and applying that to the database needs to happen - almost like a pre-sync upload state.

**Comment by abraunegg** [comment]
@agrigorev 

Any update ?

**Comment by agrigorev** [comment]
Hello,
sorry for replying late - was busy with my job.
Last time I ran my Linux laptop, it hasn't uploaded anything. But what I noticed - the time before it started to uploaded again  and aftersome time it stopped, as it would hava recognized (with delay) that some files are deleted and they shouldn't be uploaded anymore. A kind of "delayed meta-data sync".

I can try to do some experiments on the week-end, if necessary. I do not travel a lot at the present, so I don't use my "travel laptop" with Linux intensively, therefore I cannot prvide you with "real-life"-examples.

Regards,
Andrey

**Comment by abraunegg** [comment]
Hi,

Can you try with the latest codebase when you do your testing?

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
make install
```

Option 2:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

Best regards,

Alex

**Comment by ELadner** [comment]
I have tested this with the latest patch (314) and get similar results.

From what I can tell, deletes are not ordered properly.  I've seen several cases where, when I delete a directory that contains sub-directories and files at multiple levels, the onedrive client attempts to delete them in the wrong order, and can't remove a directory because it still has contents on the Linux side.  Then, the delete process is aborted and it sees the remaining files as out of sync (i.e. delete on the OneDrive side, but present on the Linux side) so they are re-uploaded.

I've found that searching for all the files in the sub-directory and deleting those first helps, but in cases where you have multiple nested sub-dirs, trying to delete them all at once will invoke this behavior again (tries to delete a parent level dir that still has sub-dirs, fails, re-uploads "out of sync" directories that were deleted from OD.

Prioritizing batch deletes by the length of the file/path getting deleted would fix this, I think.

**Comment by abraunegg** [comment]
> From what I can tell, deletes are not ordered properly. I've seen several cases where, when I delete a directory that contains sub-directories and files at multiple levels, the onedrive client attempts to delete them in the wrong order, and can't remove a directory because it still has contents on the Linux side. 

The ordering of the change values is processed in the order that the client receives them from OneDrive.

Can you capture a log using `--debug-https` so that this can be used to open a case with the OneDrive API team?

**Comment by abraunegg** [comment]
If you are up for locally modifying your code - you can also add the following into sync.d:
```
// Is a root item, has no id in parentReference or is a OneDrive deleted item
+ if (isItemDeleted(item)){
+ 	log.vlog("Found Deletion Change: ", item);
+ }
```
This will add to the verbose log any change that is a deletion item request from OneDrive

**Comment by abraunegg** [comment]
> Also, that debug line did not show up in the output anywhere.

You would have to add those 3 lines of code into your source code locally then rebuild - that would then also negate the need potentially doing `--debug-https` output.

You can email to my gmail account - alex.braunegg@gmail.com

**Comment by abraunegg** [comment]
I can also do a webex with you if your more comfortable with that.

**Comment by abraunegg** [comment]
Working on updating the deleteItem function at the moment to check for child items before attempting delete.

Also - when deleting a large number of items - the following error is thrown by OneDrive:

```
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-04-25T14:59:26",
            "request-id": "40b29587-36f8-467b-bc04-782277bc2e00"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
```
This is logged as a bug here: https://github.com/OneDrive/onedrive-api-docs/issues/844

**Comment by abraunegg** [comment]
This should be fixed through: https://github.com/skilion/onedrive/pull/314/commits/6fe06d03ac8add41abe8d23bfa7dfc34e53b1ac0 

Essentially it checks each directory that it is going to delete locally for any children before actually attempting to delete the local directory.

Whilst it solves the issue of 'deleted files being re-uploaded', it doesnt solve the Internal Server Error received from OneDrive when a large volume of changes have occurred.

**Comment by ELadner** [comment]
The patch behaved as expected.  Thanks for your help!

**Comment by abraunegg** [comment]
@ELadner 
Thanks for the confirmation of the fix

@agrigorev 
Can you help by testing the latest code in your situation / scenario & reporting back?

**Comment by agrigorev** [comment]
@abraunegg: I will try to test coming week.. Which scenario should I try?

As I understand, first I have to update the installation, is it correct?
Cheers,
Andrey

**Comment by abraunegg** [comment]
@agrigorev
Any update from your side?

**Comment by agrigorev** [comment]
@abraunegg : hello, sorry, I was busy last week, and had no time for testing.
Just now I tried to update the client using your Option 1 (see message above), and it says "fatal error: target folder "onedrive" exists already and is not empty". I suppose, I have to reinstall it completely, isn't it?

I promise, I will test it tonight.

Regards,
Andrey

**Comment by agrigorev** [comment]
Update: I installed version 314 successfully. Now I will remove one large folder (containing subfolders and files) using Windows Client, and then switch the Linux-laptop on, in order to check, if it reuploads files, or not.
Regards,
Andrey

**Comment by agrigorev** [comment]
@abraunegg: here is my test scenario: 
as shown in Nautilus on Linux-Laptop:
- <Folder>: 444 objects, 240,3 MB
- <Folder>/ebay: 363 objects, 198,3 MB

as shown in "Windows Explorer"
- <Folder>: 364 files, 92 folders (456 objects in total), 229 MB
- <Folder>/ebay: 287 files, 88 folders (375 objects in total), 188 MB.

So, I deleted <Folder>/ebay in Windows. I start Linux-laptop. No re-upload, but also no sync on the Linux side - subfolder "ebay" is still there. I hope, this can help you.

Regards,
A.

**Comment by abraunegg** [comment]
@agrigorev 

Can you post a `--verbose` log please using the latest #314 code changes please?

**Comment by agrigorev** [comment]
@abraunegg : I run your client as service. Is "--verbose" still relevant?

As far as I remember, in the previous versions it started to re-upload immediately after I log in on Linux laptop. But I will check it for you.

**Comment by agrigorev** [comment]
[20180507_OneDrive_client_Verbose.log](https://github.com/skilion/onedrive/files/1979737/20180507_OneDrive_client_Verbose.log)
here is my Verbose-log. I removed my OneDrive-ID, the rest is not critical.

Hope, it helps.
Regards,
Andrey

**Comment by agrigorev** [comment]
P.S. [privat/ebay] is a folder I removed via Windows client.

**Comment by abraunegg** [comment]
Can you try and not use monitor mode? As in perform your delete then manually run the client?

From your log file it appears that the database is locked - thus no changes can be made & the client crashes. This means that either there is still another onedrive process running or some other process has the file locked.

Please can you test again with out `--monitor` as this mode is not as robust as it should be at present.

**Comment by agrigorev** [comment]
What should I do? I suppose, lock of the DB is caused by the service, running in background. Can it be? Could you please just tell me, what you expect from me, which steps.

**Comment by abraunegg** [comment]
I would to the following:

1. Stop any onedrive service
2. Make sure your running the latest #314 code
3. Make your changes on OneDrive
4. Run the client manually without the `--monitor` flag

After step 4, any files / folders deleted on OneDrive should be removed locally and not re-uploaded.

Once that is confirmed, then we can dig into running it in monitor mode and determine what is happening when running like that.

**Comment by agrigorev** [comment]
OK, I will try it tomorrow morning.. it's quite late alraedy in Europe... I will post tomorrow..

**Comment by agrigorev** [comment]
Hello,
here is my VERBOSE-log:
[20180508_OneDrive_client_Verbose.log](https://github.com/skilion/onedrive/files/1982314/20180508_OneDrive_client_Verbose.log)
Now it looks better. It really downloaded new files which were added yesterday from my smartphone and removed subfolder "ebay", which I removed earlier using Windows client. I suppose, I could even be happy with manual sync, without service.  Main thing is that everything gets synchronised properly.

If you need further support, please, be patient - I'm going for vacations for a couple of days and be back on the week-end.

Regards,
Andrey

**Comment by abraunegg** [comment]
OK - so the client is doing what it is supposed to be doing now which is the main thing.

You should be able to enable the service again and it should behave as expected.

The log file for the application is also in /var/log/onedrive or in your home directory so you can track what it has been doing.

**Comment by agrigorev** [comment]
@abraunegg : hello, I saw your previous message, but I'm on the business trip now and have no access to my private laptop. You get my response as soon as I have my private laptop in my hands.

Cheers,
Andrey

**Comment by agrigorev** [comment]
Hello, I could test the behavior of the client. On the 8th of May I deleted several files via Windows client, today I started Linux-client for the first time since that. Service was not running. Result: new files were added properly, deleted (on the server) files were deleted locally. So, for me it looks well. I will close the issue. Thanks for the resolution.
