### ISSUE TITLE
Broken link of Ubuntu Dependencies

### ISSUE THREAD

**Issue by kamilmaj** [skilion/onedrive#305]
Dependencies: unavailable execution of command below because of broken link (mint kde)

sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list

**Comment by MortimerCat** [comment]
Sourceforge has been out of action for the last few days, See their [twitter feed](https://twitter.com/sfnet_ops) for updates.

**Comment by kamilmaj** [comment]
I've tried to download from another source:
https://sourceforge.net/projects/d-apt/files/files/
but it doesn't help.
Yes, any workaround or wait with patience for sourceforge restoration?

**Comment by kamilmaj** [comment]
Ok, it helped to download d-apt manually and put it in /etc/apt/sources.list.d/ on root

But another, problem appears:
![image](https://user-images.githubusercontent.com/33999337/36940112-4cbad50a-1f3d-11e8-97d2-d49d0a28aa6b.png)

further line generates infinite waiting for response :/

**Comment by MortimerCat** [comment]
Sourceforge back online
