### ISSUE TITLE
systemd[2297]: onedrive.service: Unit entered failed state.

### ISSUE THREAD

**Issue by GhostInTheMachines** [skilion/onedrive#309]
After following setup instructions 
1. Loaded the recommended dependencies
2. Ran application and setup access on Microsoft site
3. Pasted url back into application.
***All steps ran without errors. I setup sync_files to test application with one directory.

RESULT: No files or directories are pulled down from the specified OneDrive folder.

NOTE: "sync_file" has one entry which I tried with and without the slash and wildcard
DU_Classes/*

Log output was:

-- Logs begin at Sun 2018-03-04 12:34:13 CST. --
 onedrive[2370]: src/sqlite.d:117 ref sqlite.Statement.Result sqlite.Statement.Result.__ctor(etc.c.sqlite3.sqlite3_stmt*) [0x581c3f]
 onedrive[2370]: src/sqlite.d:173 sqlite.Statement.Result sqlite.Statement.exec() [0x581f11]
 onedrive[2370]: src/itemdb.d:331 void itemdb.ItemDatabase.setDeltaLink(const(char)[], const(char)[], const(char)[]) [0x570b10]
 onedrive[2370]: src/sync.d:182 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x58300e]
 onedrive[2370]: src/sync.d:146 void sync.SyncEngine.applyDifferences() [0x582c41]
 onedrive[2370]: src/main.d:193 void main.performSync(sync.SyncEngine) [0x571be3]
 onedrive[2370]: src/main.d:169 _Dmain [0x57187f]
 systemd[2297]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
 systemd[2297]: onedrive.service: Unit entered failed state.
 systemd[2297]: onedrive.service: Failed with result 'exit-code'.

**Comment by thomasfedb** [comment]
Can you provide a longer log extract? Is this reproducible? Does it occur consistently?

**Comment by GhostInTheMachines** [comment]
Created a couple of new tester files to get output to share here as these files were not synced to cloud.  Output from the full log will be at the end.
~$ onedrive
$ onedrive --version
onedrive v1.1.1-2-gc231b13
~$ onedrive --verbose
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/ghost/OneDrive
Initializing the Synchronization Engine ...
Applying changes of E6214116B91328F7!125
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of E6214116B91328F7!125
~$ onedrive
~$ onedrive --verbose
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/ghost/OneDrive
Initializing the Synchronization Engine ...
Applying changes of E6214116B91328F7!125
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of E6214116B91328F7!125

Trying to print the log but it only seems to print one line and then freeze: (output below with command run)
journalctl --user-unit onedrive -f
-- Logs begin at Fri 2018-03-09 07:31:02 CST. --
Mar 09 07:31:11 spooky2 systemd[2086]: Started OneDrive Free Client.

**Comment by GhostInTheMachines** [comment]
I waited a few hours, deleted some files in the synced folder and re-ran the log command.  Yes, it is consistent because it has never synced either way up or down.

journalctl --user-unit onedrive -f
-- Logs begin at Fri 2018-03-09 07:31:02 CST. --
Mar 09 07:31:11 spooky2 systemd[2086]: Started OneDrive Free Client.

**Comment by GhostInTheMachines** [comment]
Here is the output from running onedrive in verbose mode:
journalctl --user-unit onedrive -f
-- Logs begin at Fri 2018-03-09 07:31:02 CST. --
Mar 09 07:31:11 spooky2 systemd[2086]: Started OneDrive Free Client.

**Comment by GhostInTheMachines** [comment]
Here is the output from running onedrive in verbose mode:
onedrive --verbose
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/ghost/OneDrive
Initializing the Synchronization Engine ...
Applying changes of E6214116B91328F7!125
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of E6214116B91328F7!125

**Comment by GhostInTheMachines** [comment]
I had to uninstall this because I found another application that seems to work out of the box for me.
https://www.addictivetips.com/ubuntu-linux-tips/access-microsoft-onedrive-on-linux/

Thanks
