### ISSUE TITLE
403 Forbidden when downloading a zip file that I can access online just fine

### ISSUE THREAD

**Issue by lagerspetz** [skilion/onedrive#31]
Hi,
I just moved my data from Copy.com to OneDrive, and I'm on Linux. I use your onedrive tool to sync.
The sync has been doing fine, but now it found an old saved game file from "And Yet It Moves" which is a zip file called ghost.gst. The OneDrive online interface actually asks my confirmation about zips being able to contain viruses before it allows me to download it. Perhaps this software needs to do something special for files like this to be allowed to download them?

The error I got is below:

Timeout was reached on handle 262BEF0
Downloading: ./CopyBackup/Personal/game-saves/Broken Rules/And Yet It Moves/ghosts/loaded/ghost.gst
HTTP request returned status code 403 (Forbidden)
Downloading: ./CopyBackup/Personal/game-saves/Broken Rules/And Yet It Moves/ghosts/loaded/ghost.gst
sync.SyncException@src/sync.d(106): HTTP request returned status code 403 (Forbidden)
----------------
??:? void sync.SyncEngine.applyDifferences() [0x5cc437]
??:? void main.performSync(sync.SyncEngine) [0x5be16f]
??:? _Dmain [0x5bda12]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d908a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d8fc8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d9046]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d8fc8]
??:? _d_run_main [0x5d8f25]
??:? main [0x5bfe6d]
??:? __libc_start_main [0x2d664b44]
onedrive.OneDriveException@src/onedrive.d(337): HTTP request returned status code 403 (Forbidden)
----------------
??:? void onedrive.OneDriveApi.checkHttpCode() [0x5c5420]
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5c474c]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x5c24b4]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5cd619]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5cd150]
??:? void sync.SyncEngine.applyDifferences() [0x5cc2b9]
??:? void main.performSync(sync.SyncEngine) [0x5be16f]
??:? _Dmain [0x5bda12]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d908a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d8fc8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d9046]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d8fc8]
??:? _d_run_main [0x5d8f25]
??:? main [0x5bfe6d]
??:? __libc_start_main [0x2d664b44]

**Comment by telmer6** [comment]
Same issue:
```
E77905114842FC72!24557 SolarWinds-IPAddressTracker-v1.zip
Downloading: ./Work/SolarWinds-IPAddressTracker-v1.zip
sync.SyncException@src/sync.d(106): HTTP request returned status code 403 (Forbidden)
----------------
??:? void sync.SyncEngine.applyDifferences() [0x5cc487]
??:? void main.performSync(sync.SyncEngine) [0x5be1bf]
??:? _Dmain [0x5bda62]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d912a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d9068]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d90e6]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d9068]
??:? _d_run_main [0x5d8fc5]
??:? main [0x5bfebd]
??:? __libc_start_main [0x75d67b44]
onedrive.OneDriveException@src/onedrive.d(337): HTTP request returned status code 403 (Forbidden)
----------------
??:? void onedrive.OneDriveApi.checkHttpCode() [0x5c5470]
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5c479c]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x5c2504]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x5cd6b9]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x5cd1ec]
??:? void sync.SyncEngine.applyDifferences() [0x5cc309]
??:? void main.performSync(sync.SyncEngine) [0x5be1bf]
??:? _Dmain [0x5bda62]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5d912a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d9068]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5d90e6]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5d9068]
??:? _d_run_main [0x5d8fc5]
??:? main [0x5bfebd]
??:? __libc_start_main [0x75d67b44]
```

**Comment by telmer6** [comment]
That appears to have fixed it. Thanks!

**Comment by igno2k** [comment]
Am I right that this is not yet merged to Master?

https://github.com/skilion/onedrive/blob/master/src/onedrive.d
line 102

**Comment by skilion** [comment]
I removed `AVOverride=1` because of [this](https://github.com/OneDrive/onedrive-api-docs/issues/178#issuecomment-204501557).Do you get the error ?

**Comment by igno2k** [comment]
Download of ZIP files or office docs is only working when adding AVOverride=1 in that file es done here:
https://github.com/JonathonMA/onedrive/commit/8b68adf8ddeaed18b74de0133fafddc473f30811

I'm not getting any error with that setting.

I think you should add it to the Master branch.

**Comment by skilion** [comment]
Restored

**Comment by igno2k** [comment]
Perfect - thank you!
