### ISSUE TITLE
undefined reference to `sqlite3_errstr' while installing

### ISSUE THREAD

**Issue by keheliya** [skilion/onedrive#310]
I'm trying to install this in CentOS and getting the following error when I run `make`.

```
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
onedrive.o: In function `_D6sqlite8Database4openMFAxaZv':
/home/keheliya/dev/onedrive/src/sqlite.d:53: undefined reference to `sqlite3_errstr'
onedrive.o: In function `_D6sqlite8Database5closeMFZv':
/home/keheliya/dev/onedrive/src/sqlite.d:102: undefined reference to `sqlite3_close_v2'
collect2: ld returned 1 exit status
Error: linker exited with status 1
make: *** [onedrive] Error 1
``` 

Versions of the dependencies:
-  `dmd-2.079.0`
- `libcurl-devel-7.19.7-53.el6_9.x86_64`
- `sqlite-devel-3.6.20-1.el6_7.2.x86_64`

 What can be the problem here?

**Comment by thomasfedb** [comment]
@keheliya What version of CentOS? You might need a more recent SQLite, in particular 3.7.15 or newer, which I think is available in CentOS 7.

**Comment by keheliya** [comment]
My OS version is `CentOS release 6.9 (Final)`. I guess I won't have any luck directly updating SQLite because 3.7 is not available for that OS version according to [this](https://rpmfind.net/linux/rpm2html/search.php?query=sqlite-devel(x86-64)). :-( Is there any other workaround for me to update SQLite without updating the OS?

**Comment by thomasfedb** [comment]
I'd try asking on IRC (https://wiki.centos.org/irc) to see if the community can assist. You could also compile SQLite 3.7.15+ yourself, which shouldn't be particularly difficult.

Regardless, this is not an issue with this project, so please close this issue.

**Comment by keheliya** [comment]
Thanks. I'll check it out.
