### ISSUE TITLE
Issues on filename with leading, or trailing, spaces 

### ISSUE THREAD

**Issue by tahder** [skilion/onedrive#315]
Mar 15 16:21:58 GUAPO onedrive[5018]: Creating folder ./KSP-Related/prior2018/Flyers/KAGAW2017/ (Whitespace Conflict)
Mar 15 16:21:59 GUAPO onedrive[5018]: HTTP request returned status code 400 (Bad Request)
Mar 15 16:21:59 GUAPO onedrive[5018]: {
Mar 15 16:21:59 GUAPO onedrive[5018]:     "error": {
Mar 15 16:21:59 GUAPO onedrive[5018]:         "code": "invalidRequest",
Mar 15 16:21:59 GUAPO onedrive[5018]:         "innerError": {
Mar 15 16:21:59 GUAPO onedrive[5018]:             "date": "2018-03-15T03:21:59",
Mar 15 16:21:59 GUAPO onedrive[5018]:             "request-id": "2f6beabb-1d4e-4ecc-b0b7-6b8c5ee8dx72"
Mar 15 16:21:59 GUAPO onedrive[5018]:         },
Mar 15 16:21:59 GUAPO onedrive[5018]:         "message": "The provided name cannot contain leading, or trailing, spaces."
Mar 15 16:21:59 GUAPO onedrive[5018]:     }
Mar 15 16:21:59 GUAPO onedrive[5018]: }
Mar 15 16:22:14 GUAPO onedrive[5018]: Creating folder ./KSP-Related/prior2018/Flyers/KAGAW2017/ (Whitespace Conflict)
Mar 15 16:22:14 GUAPO onedrive[5018]: HTTP request returned status code 400 (Bad Request)
Mar 15 16:22:14 GUAPO onedrive[5018]: {
Mar 15 16:22:14 GUAPO onedrive[5018]:     "error": {
Mar 15 16:22:14 GUAPO onedrive[5018]:         "code": "invalidRequest",
Mar 15 16:22:14 GUAPO onedrive[5018]:         "innerError": {
Mar 15 16:22:14 GUAPO onedrive[5018]:             "date": "2018-03-15T03:22:14",
Mar 15 16:22:14 GUAPO onedrive[5018]:             "request-id": "8a79fa90-7d66-4370-81d-40f748a4996b"
Mar 15 16:22:14 GUAPO onedrive[5018]:         },
Mar 15 16:22:14 GUAPO onedrive[5018]:         "message": "The provided name cannot contain leading, or trailing, spaces."
Mar 15 16:22:14 GUAPO onedrive[5018]:     }
Mar 15 16:22:14 GUAPO onedrive[5018]: }
Mar 15 16:22:15 GUAPO onedrive[5018]: Creating folder ./KSP-Related/prior2018/Flyers/KAGAW2017/ (Whitespace Conflict)
Mar 15 16:22:16 GUAPO onedrive[5018]: onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
Mar 15 16:22:16 GUAPO onedrive[5018]: {
Mar 15 16:22:16 GUAPO onedrive[5018]:     "error": {
Mar 15 16:22:16 GUAPO onedrive[5018]:         "code": "invalidRequest",
Mar 15 16:22:16 GUAPO onedrive[5018]:         "innerError": {
Mar 15 16:22:16 GUAPO onedrive[5018]:             "date": "2018-03-15T03:22:16",
Mar 15 16:22:16 GUAPO onedrive[5018]:             "request-id": "d474521b-f547-45c7-bd45-11e24a8ace64"
Mar 15 16:22:16 GUAPO onedrive[5018]:         },
Mar 15 16:22:16 GUAPO onedrive[5018]:         "message": "The provided name cannot contain leading, or trailing, spaces."
Mar 15 16:22:16 GUAPO onedrive[5018]:     }
Mar 15 16:22:16 GUAPO onedrive[5018]: }
Mar 15 16:22:16 GUAPO onedrive[5018]: ----------------
Mar 15 16:22:16 GUAPO onedrive[5018]: src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x57ae94]
Mar 15 16:22:16 GUAPO onedrive[5018]: src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x57b026]
Mar 15 16:22:16 GUAPO onedrive[5018]: src/onedrive.d:185 std.json.JSONValue onedrive.OneDriveApi.createById(const(char)[], const(char)[], std.json.JSONValue) [0x579b68]
Mar 15 16:22:16 GUAPO systemd[3392]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Mar 15 16:22:16 GUAPO systemd[3392]: onedrive.service: Unit entered failed state.
Mar 15 16:22:16 GUAPO systemd[3392]: onedrive.service: Failed with result 'exit-code'.

**Comment by tahder** [comment]
As the folder contains parenthesis () which has this name "(Whitespace Conflict)". The workaround I rename it without parenthesis and restart service and works well.

**Comment by tahder** [comment]
I think, it is related too with a folder with dot name "Imahen.." as it works on dr0pb0x.

> Mar 15 16:39:41 GUAPO onedrive[6727]: Creating folder ./KSP-Related/prior2018/Flyers/Invitations/Imahen..
> Mar 15 16:39:42 GUAPO onedrive[6727]: HTTP request returned status code 400 (Bad Request)
> Mar 15 16:39:42 GUAPO onedrive[6727]: {
> Mar 15 16:39:42 GUAPO onedrive[6727]:     "error": {
> Mar 15 16:39:42 GUAPO onedrive[6727]:         "code": "invalidRequest",
> Mar 15 16:39:42 GUAPO onedrive[6727]:         "innerError": {
> Mar 15 16:39:42 GUAPO onedrive[6727]:             "date": "2018-03-15T03:39:42",
> Mar 15 16:39:42 GUAPO onedrive[6727]:             "request-id": "7b6b0e97-8233-4c20-a57e-094fcb83fd0e"
> Mar 15 16:39:42 GUAPO onedrive[6727]:         },
> Mar 15 16:39:42 GUAPO onedrive[6727]:         "message": "The provided name cannot contain any illegal characters."
> Mar 15 16:39:42 GUAPO onedrive[6727]:     }
> Mar 15 16:39:42 GUAPO onedrive[6727]: }
> Mar 15 16:40:07 GUAPO onedrive[6727]: Creating folder ./KSP-Related/prior2018/Flyers/Invitations/Imahen..
> Mar 15 16:40:07 GUAPO onedrive[6727]: HTTP request returned status code 400 (Bad Request)
> Mar 15 16:40:07 GUAPO onedrive[6727]: {
> Mar 15 16:40:07 GUAPO onedrive[6727]:     "error": {
> Mar 15 16:40:07 GUAPO onedrive[6727]:         "code": "invalidRequest",
> Mar 15 16:40:07 GUAPO onedrive[6727]:         "innerError": {
> Mar 15 16:40:07 GUAPO onedrive[6727]:             "date": "2018-03-15T03:40:07",
> Mar 15 16:40:07 GUAPO onedrive[6727]:             "request-id": "83eb8517-19f2-4a7b-a506-8ab397fe23d6"
> Mar 15 16:40:07 GUAPO onedrive[6727]:         },
> Mar 15 16:40:07 GUAPO onedrive[6727]:         "message": "The provided name cannot contain any illegal characters."
> Mar 15 16:40:07 GUAPO onedrive[6727]:     }
> Mar 15 16:40:07 GUAPO onedrive[6727]: }
> Mar 15 16:40:09 GUAPO onedrive[6727]: Creating folder ./KSP-Related/prior2018/Flyers/Invitations/Imahen..
> Mar 15 16:40:09 GUAPO onedrive[6727]: onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
> Mar 15 16:40:09 GUAPO onedrive[6727]: {
> Mar 15 16:40:09 GUAPO onedrive[6727]:     "error": {
> Mar 15 16:40:09 GUAPO onedrive[6727]:         "code": "invalidRequest",
> Mar 15 16:40:09 GUAPO onedrive[6727]:         "innerError": {
> Mar 15 16:40:09 GUAPO onedrive[6727]:             "date": "2018-03-15T03:40:09",
> Mar 15 16:40:09 GUAPO onedrive[6727]:             "request-id": "2563f3b2-ae97-4f47-83b6-8dca639385e1"
> Mar 15 16:40:09 GUAPO onedrive[6727]:         },
> Mar 15 16:40:09 GUAPO onedrive[6727]:         "message": "The provided name cannot contain any illegal characters."
> Mar 15 16:40:09 GUAPO onedrive[6727]:     }
> Mar 15 16:40:09 GUAPO onedrive[6727]: }
> Mar 15 16:40:09 GUAPO onedrive[6727]: ----------------
> Mar 15 16:40:09 GUAPO onedrive[6727]: src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x57ae94]
> Mar 15 16:40:09 GUAPO onedrive[6727]: src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x57b026]
> Mar 15 16:40:09 GUAPO onedrive[6727]: src/onedrive.d:185 std.json.JSONValue onedrive.OneDriveApi.createById(const(char)[], const(char)[], std.json.JSONValue) [0x579b68]
> Mar 15 16:40:09 GUAPO onedrive[6727]: src/sync.d:606 void sync.SyncEngine.uploadCreateDir(const(char)[]) [0x585806]
> Mar 15 16:40:09 GUAPO onedrive[6727]: src/sync.d:582 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x58549c]
> Mar 15 16:40:09 GUAPO onedrive[6727]: src/sync.d:587 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x585513]
> Mar 15 16:40:09 GUAPO onedrive[6727]: src/sync.d:443 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x584955]
> Mar 15 16:40:09 GUAPO onedrive[6727]: src/main.d:195 void main.performSync(sync.SyncEngine) [0x57222f]
> Mar 15 16:40:09 GUAPO onedrive[6727]: src/main.d:121 _Dmain [0x571d5f]
> Mar 15 16:40:09 GUAPO systemd[3392]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
> Mar 15 16:40:09 GUAPO systemd[3392]: onedrive.service: Unit entered failed state.
> Mar 15 16:40:09 GUAPO systemd[3392]: onedrive.service: Failed with result 'exit-code'.

**Comment by thomasfedb** [comment]
Renaming the file or directory is your best option at this point @tahder.

**Comment by abraunegg** [comment]
With #314 the client will gracefully skip files and folders that do not match the MS Naming Conventions

```
Skipping item - invalid name (Microsoft Naming Convention): ./KSP-Related/prior2018/Flyers/KAGAW2017/ (Whitespace Conflict)
Skipping item - invalid name (Microsoft Naming Convention): ./KSP-Related/prior2018/Flyers/Invitations/Imahen..
```
This is a better approach than causing the application to crash & there is a log of why it was skipped.

**Comment by abraunegg** [comment]
@tahder 

Any update?

**Comment by abraunegg** [comment]
@tahder

Any update?

**Comment by abraunegg** [comment]
@tahder

Any update? If not, please can you close this issue.

**Comment by abraunegg** [comment]
@tahder


Any update? If not, please can you close this issue.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by tahder** [comment]
Apology takes time to respond to this issue and close this as busy and overlooked the notification. Thanks as sorted out.
