### ISSUE TITLE
centos enable and start the systemd service failed....

### ISSUE THREAD

**Issue by luckfu** [skilion/onedrive#316]
**uname -a**
Linux VM_49_119_centos 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**systemctl --user enable onedrive**
Failed to get D-Bus connection: Connection refused

**Comment by thomasfedb** [comment]
@luckfu this appears to be an issue with `systemctl` on your machine rather with `onedrive` itself. You should get in touch with your distro's community. It seems that `--user` is not supported in Centos 7, see [this bug report](https://bugs.centos.org/view.php?id=8767#c28611). You can always invoke `onedrive -m` manually or via login script.

**Comment by toledoroy** [comment]
Any way to get this to autostart on CentOS?

**Comment by abraunegg** [comment]
@toledoroy 
Refer to https://github.com/abraunegg/onedrive/blob/master/README.md#onedrive-service-running-as-root-user

Also, the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
