### ISSUE TITLE
Detect when sync-folder is missing

### ISSUE THREAD

**Issue by droberg** [skilion/onedrive#317]
I have and issue where my computer sometimes fails to mount an external drive. Today onedrive will wipe the entire directory if I'm not careful and tries to sync before making sure the drive actually exists. 

Is there any chance that some simple heuristics could be implemented to get around this? Perhaps check if the root of the sync-folder actually exists before starting to sync?

**Comment by thomasfedb** [comment]
@droberg how does the directory get wiped by onedrive?

**Comment by droberg** [comment]
Perhaps I was a bit brief, sorry about that. I'll try to clarify what is actually happening.

I have my  onedrive root directory on an external drive. Sometimes I forget to mount my external drive and start onedrive by mistake. From what I have seen, onedrive will then detect that all files in the root directory are missing and will remove them from the online storage. 

If I had removed everything from my storage, excluding the onedrive root dir I agree that this would be the correct way to act. However, because in my case the folder that act as the root is also missing I think it would be better to assume that something is horribly wrong and warn the user.

**Comment by thomasfedb** [comment]
Thanks for the explanation @droberg. Seems to be a reasonable suggestion.

In the meantime, you could add a `ExecStartPre` directing to your systemd config to check for the directory before the service starts.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by droberg** [comment]
I don't get it. I was hardly expected to answer anything, or was I?

I had a feature request, it was commented that I might use another approach, but the feature has neither been rejected, implemented, or considered.

**Comment by abraunegg** [comment]
Nope - but the original author has abandoned this code - so if you want to see something like this, close this issue and open it against my branch.

**Comment by droberg** [comment]
Ok, good to know. Thanks
