### ISSUE TITLE
OneDrive Daemon Power Consumption

### ISSUE THREAD

**Issue by blue995** [skilion/onedrive#318]
The monitoring feature of this onedrive client consumes a lot of battery life. I enabled and started the onedrive.service and my cpu usage was often at 100 % just because of the onedrive monitoring service. There was nothing that the client had to pull or push and this behaviour didn't change. I deactivated the service now until this behaviour gets fixed. Besides its enormous power consumption the feature works great though.

(Also posted in AUR: [https://aur.archlinux.org/packages/onedrive/](url))

**Comment by abraunegg** [comment]
This is most likely due to how the 'monitor' mode operates. Rather than utilise inotify, it is running through a full push/pull execution every 45 seconds.

A better method of handling a 'monitor' mode sync is to use a cronjob and have that run every X minutes until inotify support can be introduced.

**Comment by bnysten** [comment]
I've the same problem and the only solution I found was to stop onedrive.service.
Is there any other solution that allow onedrive to continue monitoring modifications without without using so much ressources ?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by skilion** [comment]
Fixed in c2cdb24131ad3b1c9f62562561510a931db2b72a

**Comment by blue995** [comment]
That‘s Great, Thank you very much :)
