### ISSUE TITLE
Resync issue

### ISSUE THREAD

**Issue by Joe-Schmo** [skilion/onedrive#322]
Getting the error message, similar to issue  #262, although user said it was not an issue

joe@joe-X751NA:~$ onedrive --verbose
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
object.Exception@src/itemdb.d(70): The item database is incompatible, please resync manually
----------------
src/itemdb.d:70 itemdb.ItemDatabase itemdb.ItemDatabase.__ctor(const(char)[]) [0x56ee13]
src/main.d:108 _Dmain [0x5715c5]

**Comment by abraunegg** [comment]
I think the right way to solve this one is:

```onedrive --resync```

Have you tried that?

**Comment by abraunegg** [comment]
@Joe-Schmo 

Any update?

**Comment by Joe-Schmo** [comment]
I originally tried  ondrive --resync and it did not work.  It is working now and I don't know why.

Sorry for the delay updating.

**Comment by abraunegg** [comment]
If its resolved, please can you close this case.

**Comment by Joe-Schmo** [comment]
done

________________________________

**Comment by matihost** [comment]
Any reason why the app does not do that automatically upon first attempt of the issue?
