### ISSUE TITLE
NTFS drives

### ISSUE THREAD

**Issue by casperdcl** [skilion/onedrive#324]
When downloading files into an NTFS directory (ubuntu 16.04 LTS), errors with "Operation not Permitted," renames the downloaded file, and then re-downloads ad infinitum. Probably related to file permission errors?

**Comment by sibero80** [comment]
it happened to me, what I ended up doing is mounting the drive as the default user.
Here's an example of my FSTAB (it's a samba share).

`//m.y.i.p/volume9 /media/pi/USB500 cifs uid=pi,gid=pi,username=myusername,password=mypassword 0 0`

Adding the `uid=pi,gid=pi` (Pi bein my user and user group) did the trick for me. It was either that or running the binary as root.

**Comment by casperdcl** [comment]
Thanks @sibero80 - I added just my `uid` (`uid=1000`), and left `gid=plugdev` as it was before (making sure I was part of `plugdev`). Seems to work fine.
