### ISSUE TITLE
Authorization O365 business

### ISSUE THREAD

**Issue by kruoff** [skilion/onedrive#327]
I installed onedrive successfully. But when the authorization of my O365-Account is asked, ther's no going on for me.
My Account is "login.microsoftonline.de" and not "login.microsoftonline.com". So I can't get a successfull Authorization.
Can I change the Authorization-Server-Adress in any way?

**Comment by elhennig** [comment]
I already had the client working but since today I get:
```
src/sync.d:102 void sync.SyncEngine.applyDifferences() [0x5ad2b5]
src/main.d:184 void main.performSync(sync.SyncEngine) [0x596b4b]
src/main.d:114 _Dmain [0x59632a]
onedrive.OneDriveException@src/onedrive.d(403): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "6fc5d05b-c2bf-44fd-bc30-e55e54fb38a1",
    "error": "invalid_request",
    "error_codes": [
        90130
    ],
    "error_description": "AADSTS90130: Application '22c49a0d-d21c-4792-aed1-8f163c982546' (OneDrive Free Client) is not supported over the \/common or \/consumers endpoints. Please use the \/organizations or tenant-specific endpoint.\r\nTrace ID: 42c8c828-19be-4289-888f-778c92470e00\r\nCorrelation ID: 6fc5d05b-c2bf-44fd-bc30-e55e54fb38a1\r\nTimestamp: 2018-04-06 09:00:07Z",
    "timestamp": "2018-04-06 09:00:07Z",
    "trace_id": "42c8c828-19be-4289-888f-778c92470e00"
}
Refresh token invalid, use --logout to authorize the client again
```

**Comment by kolya-ay** [comment]
@elhennig. Me to. It's stopped working since today. Ver. 20170919 from Debian testing repository. Trying to compile from source.

What version are you guys using?

**Comment by elhennig** [comment]
I rebuilt the client today with actual github sources. It did not help

**Comment by Kkeller83** [comment]
Same here.. I actually logged out and no I can not log in anymore.. also a German account: I get tenant not found all of sudden.. happend since today

**Comment by kolya-ay** [comment]
Quick googling and glancing [through the docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-code) gave me *temporary* solution that works for me. Just replace `common` to `organizations` while copying authorization url to browser.

![auth](https://user-images.githubusercontent.com/238048/38421490-04054920-39b0-11e8-86a8-9d313917fe71.png)

**Comment by elhennig** [comment]
Thanks for the hint! it works....

**Comment by abraunegg** [comment]
@kruoff @kolya-ay 

Can you test with the latest version of #314?

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
make install
```

Option 2:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

I have been testing against 'business' / O365 accounts without issue.

**Comment by abraunegg** [comment]
@kruoff @kolya-ay 
Any update?

**Comment by possiblybhavin** [comment]
Version #314 does NOT work with O365 Business.

After integrating the changes from [PR302](https://github.com/skilion/onedrive/pull/302/commits/541307bfa4535e165842d7b123891d10e2e17dd1?diff=split), I was able to O365 business to work.

The differences between Personal and O365 API is with the [DriveItem API](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get) (which PR302 implements):

Personal:
GET /me/drive/items/{item-id}
GET /me/drive/root:/{item-path}

For O365 business:
GET /drives/{drive-id}/items/{item-id}
GET /drives/{drive-id}/root:/{item-path}

_I did however have one issue after integrating PR302 on top of PR314. The remaining free space for my O365 drive was turning up as empty, even though I have loads of storage space (I suspect it has to do with the locked down permission for the drive I have been given access to by our IT). For now, I stubbed out the check for file size (in sync.d) and two-way syncing now works._

**Comment by abraunegg** [comment]
@possiblybhavin 
RE: O365
I am using an MS Developer O365 account and I have zero issues using the Personal API path's. Given the changes in how 'defaultDriveId' and 'defaultRootId' are now set during sync.init() it should be possible to present the 'drive-id' to all of the URL requests without having to set an additional config parameter.

RE: Storage Space Counter
Can you help check the response of "https://graph.microsoft.com/v1.0/me/drive" when using MS Graph Explorer & your account credentials?

MS Graph Explorer: https://developer.microsoft.com/en-us/graph/graph-explorer# 

That should return a JSON array with the details, of this one of them should be 'quota' with a 'remaining' field.

If you can post your response here that would be great

**Comment by BarnyXX** [comment]
Hi, 

I also having problems to login to onedrive in a german datacenter. I need to login with login.microsoftonline.de. Changing common to organizations don't work for me.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
