### ISSUE TITLE
monitor mode enter infinite loop and not stopping check folder

### ISSUE THREAD

**Issue by priv** [skilion/onedrive#328]
After the folder is 100% sync, I run onedrive -m -v

It keeps a strange loop and not stabilizes at monitoring mode.
--
Applying changes of 3D9D041A324CB7A5!621
Applying changes of 3D9D041A324CB7A5!621
Uploading differences of .
Processing root
(And then Processing/has not changed for several thousands of files)
Uploading new items of .
--

And the checking is eating full CPU usage.

How can I enable more debug message or how I can check to know why it keeps thinking root dir is change?(3D9D041A324CB7A5!621 is root)

Thanks,
Alvin

**Comment by abraunegg** [comment]
In the short term, dont use the monitor mode - perhaps set a cronjob to run a sync every hour?

The longer term fix would be to compare the JSON changes timestamp with local timestamps or something along those lines - then if there is a mis match (ie something changed) process to sync those changes

**Comment by abraunegg** [comment]
@priv 

Any update?

**Comment by abraunegg** [comment]
@priv

Any update?

**Comment by abraunegg** [comment]
@priv

Any update? If no - please can you close this case.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by priv** [comment]
No idea why it is not really closed.  Closing this issue.
