### ISSUE TITLE
Error sync large files

### ISSUE THREAD

**Issue by DanielTravi** [skilion/onedrive#329]
This error only happens to me with large files, this file Travis.rar has 43GB. With smaller files it works fine. I use debian 9

Error Log:

root@ns3010239:/home/onedrive# onedrive --resync
Uploading file ./Travis.rar...
HTTP request returned status code 400 (Bad Request)
Uploading file ./Travis.rar...
HTTP request returned status code 400 (Bad Request)
Uploading file ./Travis.rar...
onedrive.OneDriveException@src/onedrive.d(401): HTTP request returned status code 400 (Bad Request)
----------------
??:? void onedrive.OneDriveApi.checkHttpCode() [0xe56347d3]
??:? std.json.JSONValue onedrive.OneDriveApi.uploadFragment(const(char)[], immutable(char)[], long, long, long) [0xe5633904]
??:? std.json.JSONValue upload.UploadSession.upload() [0xe5640764]
??:? std.json.JSONValue upload.UploadSession.upload(immutable(char)[], const(char)[], const(char)[], const(char)[], const(char)[]) [0xe564027a]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0xe563f47f]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xe563eff8]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xe563ef1b]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xe563e35d]
??:? void main.performSync(sync.SyncEngine) [0xe562bc37]
??:? _Dmain [0xe562b767]

**Comment by sibero80** [comment]
This issue might shed some light to your scenario #294 it seems the API is limited to 10GB.

**Comment by abraunegg** [comment]
I have pushed a patch in #314 that resolves this issue

**Comment by abraunegg** [comment]
@DanielTravi @sibero80 

Any update?

**Comment by abraunegg** [comment]
@DanielTravi @sibero80 
Any update?

**Comment by abraunegg** [comment]
@DanielTravi @sibero80
Any update? If not, please can you close this issue.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
