### ISSUE TITLE
error building under opensuse-tumbleweed

### ISSUE THREAD

**Issue by jaraudea** [skilion/onedrive#331]
Error building on opensuse tumbleweed with following deps:
libcurl-devel: 7.59.0-1.1 
sqlite3-devel: 3.23.0-207.1 
dmd: 2.079.0-2.1 
phobos-devel: 2.079.0-2.1
phobos-devel-static: 2.079.0-2.1  

`/usr/lib64/libphobos2.a(uri.o):(.data.rel.ro+0x10): undefined reference to '_D3std3uri12URIException7__ClassZ'
/usr/lib64/libphobos2.a(interval.o):(.data.rel.ro+0x10): undefined reference to '_D4core4time12__ModuleInfoZ'
/usr/lib64/libphobos2.a(bitop.o):(.data.rel.ro+0x10): undefined reference to '_D4core5cpuid12__ModuleInfoZ'
/usr/lib64/libphobos2.a(bitop.o):(.data.rel.ro+0x18): undefined reference to '_D4core5cpuid12__ModuleInfoZ'
/usr/lib64/libphobos2.a(spinlock.o):(.data.rel.ro+0x10): undefined reference to '_D4core6thread12__ModuleInfoZ'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
make: *** [Makefile:29: onedrive] Error 1
`

**Comment by cbcoutinho** [comment]
I just tried to rebuild onedrive on Tumbleweed after the latest snapshot (distribution update this morning)

```shell
$ dmd --version
DMD64 D Compiler v2.079.1
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

Here's the output of `make clean && make > output.txt 2>&1` on the latest clone of master: https://pastebin.com/CVAceFGB

**Comment by abraunegg** [comment]
OK - it is defiantly a localized build environment issue.

What is the contents of your `dmd.conf`?

```
# cat /etc/dmd.conf
;
; dmd.conf file for dmd
;
; dmd will look for dmd.conf in the following sequence of directories:
;   - current working directory
;   - directory specified by the HOME environment variable
;   - directory dmd resides in
;   - /etc directory
;
; Names enclosed by %% are searched for in the existing environment and inserted
;
; The special name %@P% is replaced with the path to this file
;

[Environment32]
DFLAGS=-I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/i386-linux-gnu -L--export-dynamic

[Environment64]
DFLAGS=-I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/x86_64-linux-gnu -L--export-dynamic -fPIC
```

You may need to manually add the include paths below to your build command

**Comment by jaraudea** [comment]
`dmd --version
DMD64 D Compiler v2.079.1
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright
ajaramillo@localhost:~> cat /etc/dmd.conf 
;
; dmd.conf file for dmd
;
; dmd will look for dmd.conf in the following sequence of directories:
;   - current working directory
;   - directory specified by the HOME environment variable
;   - directory dmd resides in
;   - /etc directory
;
; Names enclosed by %% are searched for in the existing environment and inserted
;
; The special name %@P% is replaced with the path to this file
;

[Environment32]
DFLAGS=-I/usr/include/dlang/dmd -L-L/usr/lib -L--export-dynamic -fPIC

[Environment64]
DFLAGS=-I/usr/include/dlang/dmd -L-L/usr/lib64 -L--export-dynamic -fPIC`

**Comment by abraunegg** [comment]
The search path's for DMD in your dmd.conf look incorrect. You need to know where these two items are on your system:

```
I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import
```

Then ensure that your build command is including them by ensuring your dmd.conf file replicates at least something like below using the actual paths where phobos & druntime/import are located:

```
[Environment32]
DFLAGS=-I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/i386-linux-gnu -L--export-dynamic

[Environment64]
DFLAGS=-I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/x86_64-linux-gnu -L--export-dynamic -fPIC
```

**Comment by cbcoutinho** [comment]
As far as I can tell Tumbleweed has a different `phobos-devel` setup than expected. Here's a copy of my `dmd.conf`:

```conf
;
; dmd.conf file for dmd
;
; dmd will look for dmd.conf in the following sequence of directories:
;   - current working directory
;   - directory specified by the HOME environment variable
;   - directory dmd resides in
;   - /etc directory
;
; Names enclosed by %% are searched for in the existing environment and inserted
;
; The special name %@P% is replaced with the path to this file
;

[Environment32]
DFLAGS=-I/usr/include/dlang/dmd -L-L/usr/lib -L--export-dynamic -fPIC

[Environment64]
DFLAGS=-I/usr/include/dlang/dmd -L-L/usr/lib64 -L--export-dynamic -fPIC
```

Which doesn't contain an include statement to `/usr/include/dmd/phobos`. On my system, here's the directory layout of `/usr/include/dlang/dmd`:

```shell
$ tree /usr/include/dlang/dmd -d
/usr/include/dlang/dmd
├── core
│   ├── internal
│   ├── stdc
│   ├── stdcpp
│   ├── sync
│   └── sys
│       ├── darwin
│       │   ├── mach
│       │   ├── netinet
│       │   └── sys
│       ├── dragonflybsd
│       │   ├── netinet
│       │   └── sys
│       ├── freebsd
│       │   ├── netinet
│       │   └── sys
│       ├── linux
│       │   ├── netinet
│       │   └── sys
│       │       └── netinet
│       ├── openbsd
│       ├── osx
│       │   ├── mach
│       │   └── sys
│       ├── posix
│       │   ├── arpa
│       │   ├── net
│       │   ├── netinet
│       │   └── sys
│       ├── solaris
│       │   └── sys
│       └── windows
├── etc
│   ├── c
│   │   ├── odbc
│   │   └── zlib
│   └── linux
└── std
    ├── algorithm
    ├── c
    │   ├── freebsd
    │   ├── linux
    │   ├── osx
    │   └── windows
    ├── container
    ├── datetime
    ├── digest
    ├── experimental
    │   ├── allocator
    │   │   └── building_blocks
    │   └── logger
    ├── internal
    │   ├── digest
    │   ├── math
    │   ├── test
    │   └── windows
    ├── net
    ├── range
    ├── regex
    │   └── internal
    └── windows

61 directories
```

**Comment by abraunegg** [comment]
To build (OK - under admittedly CentOS 7) - the only things that needed to be installed where:
```
yum -y install libcurl-devel
yum -y install sqlite-devel
```
Then, downloaded DMD from the applicable site:
```
wget http://downloads.dlang.org/releases/2.x/2.079.1/dmd-2.079.1-0.fedora.x86_64.rpm
```
Then installed that via yum:
```
yum -y install ./dmd-2.079.1-0.fedora.x86_64.rpm
```
Any dependencies needed by dmd get pulled in correctly.

If you can clean your build system up & perhaps follow similar process to above under OpenSuSE and then see what your outcome is.

**Comment by cbcoutinho** [comment]
Just to add to this issue, I just tested my OpenSUSE Leap 42.3 machine, and `onedrive` seems to build just fine. When I get some more time later this week I'm going to start looking at the build scripts of those two packages.

I also noticed that `dmd` _et al_ are included in the main repository on Tumbleweed, but not on Leap - for Leap I had to add the `devel:languages:D` repository, which works. I don't know where Tumbleweed is getting it's version of `dmd` from, possibly Factory or devel:languages:D?

@jaraudea: which repository is your version of `dmd` coming from?

For reference:
1. `devel:languages:D/dmd`: https://build.opensuse.org/package/show/devel:languages:D/dmd
2. `openSUSE:Factory/dmd`: https://build.opensuse.org/package/show/openSUSE:Factory/dmd

**Comment by abraunegg** [comment]
OK - so this is platform issue & not a bug with onedrive.

**Comment by jaraudea** [comment]
@cbcoutinho Information for package dmd:
----------------------------
Repository     : devel:languages:D                         
Name           : dmd                                       
Version        : 2.079.1-35.2                              
Arch           : x86_64                                    
Vendor         : obs://build.opensuse.org/devel:languages:D
Installed Size : 6.5 MiB                                   
Installed      : Yes

**Comment by mfzha** [comment]
Leaving a comment to say I'm running into the same issue on Tumbleweed, kernel version 4.16.3. dmd.conf looks exactly the same as above users, and have tried installing through yast directly, the .rpm from the DMD site (https://dlang.org/download.html#dmd), 1 click installs from https://software.opensuse.org/package/dmd and https://software.opensuse.org/download.html?project=devel%3Alanguages%3AD&package=dmd . Unfortunately it doesn't seem to be playing nice.

**Comment by cbcoutinho** [comment]
@abraunegg yes I agree that this is an OpenSUSE Tumbleweed issue and not a Onedrive issue, but I'm also not a D programmer so I'm not really sure what the issue could be or where to start.

I find it strange that @jaraudea had success with the devel:languages:D repo, whereas @mfzha didn't.

I'm going to try again with the various repos later this weekend and report back. Maybe getting in touch with the OpenSUSE `dmd` maintainers is an idea. Will report back.

**Comment by abraunegg** [comment]
@cbcoutinho 

What happens if you manually change your dmd.conf to replicate this - obviously with the include paths tweaked so that match where those items are actually found on OpenSUSE Tumbleweed ?

```
# cat /etc/dmd.conf
;
; dmd.conf file for dmd
;
; dmd will look for dmd.conf in the following sequence of directories:
;   - current working directory
;   - directory specified by the HOME environment variable
;   - directory dmd resides in
;   - /etc directory
;
; Names enclosed by %% are searched for in the existing environment and inserted
;
; The special name %@P% is replaced with the path to this file
;

[Environment32]
DFLAGS=-I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/i386-linux-gnu -L--export-dynamic

[Environment64]
DFLAGS=-I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/x86_64-linux-gnu -L--export-dynamic -fPIC
```

**Comment by mfzha** [comment]
@cbcoutinho I don't think @jaraudea has actually had success with the `devel:languages:D` repo - correct me if I'm wrong.

I built dmd and phobos manually using instructions from the wiki here - https://wiki.dlang.org/Building_under_Posix

and then using the suggestion by @abraunegg, changed `dmd.conf` to specify the generated files from the build. Still not working - perhaps someone else can give that a shot and look into it?

**Comment by abraunegg** [comment]
What if you remove all dmd / phobos installation files as installed by the SuSE repositories and install the SuSE package from here:

https://dlang.org/download.html

Is there any difference?

**Comment by mfzha** [comment]
@abraunegg Interesting. So I've tried that before, installing the openSUSE x86-64 version which didn't work, even after removing all dmd and phobos installation files through YaST (that is, `dmd`, `libphobos2-0_79`, and `phobos-devel`). Trying that again, and installing using the given script `curl -fsS https://dlang.org/install.sh | bash -s dmd` has allowed `make` and `sudo make install` to run fine. Then `journalctl --user-unit onedrive -f` confirms the service is running fine. 

Testing with my laptop, upload and downloads are working as intended.

**Comment by abraunegg** [comment]
Glad you have a successful build going now.

What is the contents of your dmd.conf & any relevant local system variables?

It sounds like the SuSE packages are broken, however I am also unsure why your installing phobos parts as well via YaST - unless dmd is pulling these in as a dependancy.

**Comment by mfzha** [comment]
`dmd.conf` has exact same outline as before:

```
[Environment32]
DFLAGS=-I/usr/include/dlang/dmd -L-L/usr/lib -L--export-dynamic -fPIC

[Environment64]
DFLAGS=-I/usr/include/dlang/dmd -L-L/usr/lib64 -L--export-dynamic -fPIC
```

**Comment by abraunegg** [comment]
OK .. very weird .. I suspect some sort of local system variable / path is not being set when using the YaST packages but the curl install fixes that ..

**Comment by jaraudea** [comment]
Works for me with install script, just have in mind that you have to activate dmd before to install onedrive. going to close the issue

**Comment by abraunegg** [comment]
@cbcoutinho 
Unsure if you switched over to my client version yet, however SuSE now includes my version of the client in the official SuSE repositories - refer to: https://software.opensuse.org/package/onedrive for details
