### ISSUE TITLE
Authorisation problem

### ISSUE THREAD

**Issue by jamiedow** [skilion/onedrive#333]
Hi, I don't know how to solve this authorisation problem.
I scarcely understand it. Here's what I'm doing and what I'm getting:

================
`onedrive -v
Loading config ...
No config file found, using defaults
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: 
`
================

I then paste in what I get when I use the link given above and log into my account. The uri returned is this, which doesn't look good:

================
`https://login.microsoftonline.com/common/oauth2/nativeclient?error=invalid_request&error_description=AADSTS90130%3a+Application+%2722c49a0d-d21c-4792-aed1-8f163c982546%27+(OneDrive+Free+Client)+is+not+supported+over+the+%2fcommon+or+%2fconsumers+endpoints.+Please+use+the+%2forganizations+or+tenant-specific+endpoint.%0d%0aTrace+ID%3a+6411e14d-fb8a-4570-81dd-5af8149e0e00%0d%0aCorrelation+ID%3a+bfa12c2b-01aa-40dc-9599-fb4cd9b594a0%0d%0aTimestamp%3a+2018-04-06+10%3a02%3a40Z`
================

I confess I'm beyond my own understanding here.

If I am signing in to Office365 to use its web interface, MS's standard login page redirects to an institution-specific login page with a URL something like this:

================
`https://adfs.leeds.ac.uk/adfs/ls/?client-request-id=a57a0956-b3a9-41dc-b911-7bd15cb8d836&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAXWSz2vTYBjHl3YrbMjmRPC6gyAISZ83v9oUBmZt1_VH2s61yxqEkiZv2yRN0jVvmzZe_BMqeNpREHEXQS_TP2Gn7SbDk6ehF_Hk0ewPkAeew8Pn8OX5fJ8mEYNyj3mOF_RMT6IlXeRoXkJA6zwr0pzAiRwLyBSAmzzYuH-8Hr378Pm7_GX75fWLi2_iOfVoSMg4yKXTYRgyfr9vGZgxfDd9QVFXFHVLUWeJNezRpb3zRCByopAVIR4WJAA-yzP1yAm11r6tRGXSsQ1BOwLQ7OKi1nJQPb4pbIfVWnVXYcvzmBvV1TKq2x1ecWM-ckDJAyh2EdXUYqiUFFK3KyNNPRQ0tb1Q1EPuJrHVkKdkyN4tf2JF-E9ive9P3O7YD8hZ8j3VGGOvbOZ9z8MGYe4w7BHL0Inle82JP8YTYuFgFxuckNfzlYVrKbMZbveqB4VoNm3MxwHdA-dUqg6G--rJgj9omjQHcrWSn1eRPusMjm0PiVYUyIYchZJePAa3DANUZOmSkC3Q2J42JbkbSAUAvcbOWyNMD0LbMezuETSrQ-uk4pLm4lMyFb_V9b3L5GYcyrPMnfHE71sj_CO5bWHdNp-NMDYDRjeYqXO1Sv1cTcDm31Xq7Vrs7eMT5fXi3i_51e3p9fLN1srlWroxCHizIXACmape73Q20tDzfHPWy8B8T9-XD1RTd5SSRpDd3s3m0DJFLVOp36mVr-v_U36z8TCuSpYGngZxB0EOMjle1P4B0&cbcxt=&username=XXXXX%40leeds.ac.uk&mkt=en-GB&lc=`
================

Apologies for ignorance. Can anyone help / shed light?

**Comment by Kkeller83** [comment]
I have a similiar problmen I think.. onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "c9901829-210c-4ab8-be49-4244c05b8d79",
    "error": "invalid_request",
    "error_codes": [
        90002
    ],
    "error_description": "AADSTS90002: Tenant 9188040d-6c67-4c5b-b112-36a304b66dad not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: a9ddcb17-be12-4be5-a209-425ed5d61f00\r\nCorrelation ID: c9901829-210c-4ab8-be49-4244c05b8d79\r\nTimestamp: 2018-04-06 10:29:30Z",
    "timestamp": "2018-04-06 10:29:30Z",
    "trace_id": "a9ddcb17-be12-4be5-a209-425ed5d61f00"
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x57ade4]
src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x57af76]
src/onedrive.d:252 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x57a182]
src/onedrive.d:237 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x57a06f]
src/onedrive.d:84 bool onedrive.OneDriveApi.authorize() [0x578fe6]
src/onedrive.d:64 bool onedrive.OneDriveApi.init() [0x578e17]
src/main.d:100 _Dmain [0x571ac8]

**Comment by cbcoutinho** [comment]
Same problem for me as well, I'm able to sign into office365, but trying to get a response uri for onedrive results in the following error:

```
Sign in

Sorry, but we’re having trouble signing you in.
AADSTS70001: Application with identifier '<some long alphanumeric string>' was not found in the directory <some long alphanumeric string>
```

Looks indeed like an authorization problem

**Comment by cbcoutinho** [comment]
I was just able to create my own app in the [microsoft dev portal](https://apps.dev.microsoft.com) and a redirect url to the one onedrive uses for authorization `authUrl`: https://login.microsoftonline.com/common/oauth2/nativeclient.

I'm not sure what the settings are of the `onedrive` app, maybe it's authorization expired or it needs to update its endpoints?

**Comment by kolya-ay** [comment]
Seems that something changed today on Microsoft side. See similar problem for business auth: #327

**Comment by jamiedow** [comment]
Just tried again, and authorisation seems to have worked ..... ??? What was going on there?
Or has someone sorted out the issues that @cbcoutinho mentioned?

**Comment by Kkeller83** [comment]
yep works again

**Comment by obrobertsen** [comment]
Depends on where you have your microsoft account, business use {tendant} or private use "common" ?

"The {tenant} value in the path of the request can be used to control who can sign into the application. The allowed values are tenant identifiers, for example, 8eaef023-2b34-4da1-9baa-8bc8c9d6a490 or contoso.onmicrosoft.com or common for tenant-independent tokens."

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code

**Comment by obrobertsen** [comment]
Check status here: https://mobile.twitter.com/office365status/status/982191898902212615
