### ISSUE TITLE
Key not found: lastModifiedDateTime

### ISSUE THREAD

**Issue by lorenzosu** [skilion/onedrive#334]
I changed a file locally and now the command keeps crashing with the following error:

```
Key not found: lastModifiedDateTime
Key not found: lastModifiedDateTime
std.json.JSONException@std/json.d(494): Key not found: lastModifiedDateTime

??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x493b0397]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException, inout(std.json.JzSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x493b0402]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x493694f5]
??:? itemdb.Item sync.makeItem(ref const(std.json.JSONValue)) [0x4933ee51]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x4933fd2e]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x4933fb73]
??:? void sync.SyncEngine.applyDifferences() [0x4933f851]
??:? void main.performSync(sync.SyncEngine) [0x4932fcf3]
??:? _Dmain [0x4932f850]
```

Also if I do:
`onedrive --resync`

Everything seems ok, but if I modify the "offending file" (e.g. change name) and re-run

`onedrive`

```
Deleting [path_to_modified_file]
Uploading file .[path_to_renamed_file]... done.
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "generalException",
        "innerError": {
            "date": "2018-04-13T10:56:08",
            "request-id": "77b60c55-8a61-4e60-ad07-ffcf29fe1bb2"
        },
        "message": "An unspecified error has occurred."
    }
}
Key not found: lastModifiedDateTime
std.json.JSONException@std/json.d(494): Key not found: lastModifiedDateTime

??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x12d38397]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException, inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x12d38402]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x12cf14f5]
??:? itemdb.Item sync.makeItem(ref const(std.json.JSONValue)) [0x12cc6e51]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x12cc7d2e]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x12cc7b73]
??:? void sync.SyncEngine.applyDifferences() [0x12cc7851]
??:? void main.performSync(sync.SyncEngine) [0x12cb7cf3]
??:? _Dmain [0x12cb7850]
```

**Comment by lorenzosu** [comment]
v1.1.1

**Comment by abraunegg** [comment]
Can you try with #314 ?

**Comment by lorenzosu** [comment]
$ ./onedrive -v
std.file.FileException@std/file.d(2506): /var/log/onedrive/: Permission denied
----------------
??:? @safe bool std.file.cenforce!(bool).cenforce(bool, lazy const(char)[], immutable(char)[], ulong) [0xc120dbc7]
??:? @safe bool std.file.ensureDirExists!().ensureDirExists(const(char[])) [0xc125c635]
??:? @safe void std.file.mk

**Comment by lorenzosu** [comment]
Ok I manually fixed that in /var/log.

But I get the same original problem: the initial 'offending' file is recreated both locally and remotely several times each time creating a new file, but appending some sort of tag to the filename (before extension) like this pattern (assume name is my first name in office365 and org is my company domain name):
```
filename-name-org.xlsx
filename-name-org-name-org.xlsx
filename-name-org-name-org-name-org.xlsx
```
And so on until it crashes with the following error:
```
onedrive.OneDriveException@src/onedrive.d(535): HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "generalException",
        "innerError": {
            "date": "2018-04-13T13:53:13",
            "request-id": "869acfb9-f147-489f-9e60-7880e1986871"
        },
        "message": "An unspecified error has occurred."
    }
}
----------------
??:? void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x70ca77a4]
??:? std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0x70ca786a]
??:? std.json.JSONValue onedrive.OneDriveApi.updateById(const(char)[], const(char)[], std.json.JSONValue, const(char)[]) [0x70ca5e9b]
??:? void sync.SyncEngine.uploadLastModifiedTime(const(char)[], const(char)[], const(char)[], std.datetime.systime.SysTime) [0x70cb3cff]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x70cb34e0]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x70cb29b6]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x70cb28d5]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x70cb28d5]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x70cb28d5]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x70cb1b11]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x70c989d7]
??:? _Dmain [0x70c983a8]
```

**Comment by abraunegg** [comment]
Sounds similar to #171 .. 

Can you do a WebEx (happy to host it) so that I can see what is going on - full logging & http process debugging? That way you wont need to post your log file & redact it the way you have been.

What sort of OneDrive account is this?

**Comment by abraunegg** [comment]
@niknah - are you free to do webex?

Whilst the issue still remains with #314 patches, it provides additional logging under verbose mode & enables https debugging as well.

**Comment by abraunegg** [comment]
This appears to also be a OneDrive regression maybe - details here:

https://github.com/OneDrive/onedrive-api-docs/issues/834

**Comment by niknah** [comment]
How do I use webex?  I registered but it just says that it's setting up the trial account.

I applied #314  , but now it doesn't do anything at all...

Loading config ...
Using Config Dir: /home/hankin/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/hankin/OneDrive
Initializing the Synchronization Engine ...

**Comment by abraunegg** [comment]
I will sent you a webex meeting invite - what's an email address to send to?

in #314 - the code changes - to sync you need to use `onedrive --synchronize` so that the application does not blindly sync.

`onedrive --synchronize --verbose` gives you verbose
`onedrive --synchronize --verbose --debug-http` gives you httpd debugging as well

**Comment by abraunegg** [comment]
I have posted an update in #314 to help debug the return JSON responses from OneDrive. If you can apply that & provide the debug log that would be great.

**Comment by abraunegg** [comment]
With #341, and using a Developers Office 365 Account, I get the following myself:

```
OneDrive Response: 
{
	"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#Collection(driveItem)",
	"@odata.deltaLink":"https:\/\/graph.microsoft.com\/v1.0\/drives('<redacted>')\/items('<redacted>')\/microsoft.graph.delta(token='<redacted>')?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference",
	"value":[{
		"@odata.type":"#microsoft.graph.driveItem",
		"fileSystemInfo":{"createdDateTime":"2018-04-04T03:32:04Z","lastModifiedDateTime":"2018-04-16T03:39:25Z"},
		"folder":{"childCount":0},
		"id":"<redacted>",
		"name":"root",
		"parentReference":{"driveId":"<redacted>","driveType":"business"},
		"root":{}},
		{
			"@odata.type":"#microsoft.graph.driveItem",
			"deleted":{"state":"deleted"},
			"fileSystemInfo":{},
			"folder":{"childCount":0},
			"id":"<redacted>",
			"parentReference":{"driveId":"<redacted>",
			"driveType":"business","id":"<redacted>"}},
			{"@odata.type":"#microsoft.graph.driveItem","deleted":{"state":"deleted"},
				"file":{},
				"fileSystemInfo":{},
				"id":"<redacted>",
				"parentReference":{"driveId":"<redacted>","driveType":"business","id":"<redacted>"}
			}
		]
}
Adding OneDrive Root to the local database
std.json.JSONException@std/json.d(494): Key not found: name
```

When I remove `items.sqlite3` for the user running `onedrive` everything successfully sync's.

@niknah - Thanks for the debug logs as well. Can you remove the `items.sqlite3` for your user and retry?
@lorenzosu - Can you upgrade to the latest #314 branch, remove `items.sqlite3` and retry?

**Comment by niknah** [comment]
I removed it.  A different problem has appeared, it's not skipping .* files.

In my config I have...
skip_dir = ".*|node_modules|.git|.ssh"


./Backup/git/.ssh: Permission denied
./Backup/git/.ssh: Permission denied
std.file.FileException@std/file.d(3818): ./Backup/git/.ssh: Permission denied
----------------
??:? @safe core.sys.posix.dirent.DIR* std.file.cenforce!(core.sys.posix.dirent.DIR*).cenforce(core.sys.posix.dirent.DIR*, lazy const(char)[], immutable(char)[], ulong) [0x5b04bb]
??:? @safe bool std.file.DirIteratorImpl.stepIn(immutable(char)[]) [0x5af655]
??:? ref @safe std.file.DirIteratorImpl std.file.DirIteratorImpl.__ctor!(immutable(char)[]).__ctor(immutable(char)[], std.file.SpanMode, bool) [0x601660]
??:? ref @safe std.conv.emplaceRef!(std.file.DirIteratorImpl, std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplaceRef(ref std.file.DirIteratorImpl, ref immutable(char)[], ref std.file.SpanMode, ref bool).S std.conv.emplaceRef!(std.file.DirIteratorImpl, std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplaceRef(ref std.file.DirIteratorImpl, ref immutable(char)[], ref std.file.SpanMode, ref bool).S.__ctor(ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x5f7492]
??:? @safe void std.conv.emplaceRef!(std.file.DirIteratorImpl, std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplaceRef(ref std.file.DirIteratorImpl, ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x5f743a]
??:? @safe std.file.DirIteratorImpl* std.conv.emplace!(std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplace(std.file.DirIteratorImpl*, ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x5f73ec]
??:? void std.typecons.RefCounted!(std.file.DirIteratorImpl, 0).RefCounted.RefCountedStore.initialize!(immutable(char)[], std.file.SpanMode, bool).initialize(ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x5bf74b]
??:? ref std.typecons.RefCounted!(std.file.DirIteratorImpl, 0).RefCounted std.typecons.RefCounted!(std.file.DirIteratorImpl, 0).RefCounted.__ctor!(immutable(char)[], std.file.SpanMode, bool).__ctor(ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x5bf6e0]
??:? ref @trusted std.file.DirIterator std.file.DirIterator.__ctor(immutable(char)[], std.file.SpanMode, bool) [0x5afdb5]
??:? std.file.DirIterator std.file.dirEntries(immutable(char)[], std.file.SpanMode, bool) [0x5affd0]
src/sync.d:752 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x590bf8]
src/sync.d:754 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x590c51]
src/sync.d:754 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x590c51]
src/sync.d:754 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x590c51]
src/sync.d:583 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x58fea7]
src/main.d:315 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x578833]
src/main.d:206 _Dmain [0x578204]

**Comment by lorenzosu** [comment]
Hi @abraunegg,
Sorry I catched up only now.
I'm using an office365 account. And yes we can set up a screenshare if you like. Feel free to private message me to set-up.
What should I remove from where in #314?

**Comment by abraunegg** [comment]
> In my config I have...
skip_dir = ".*|node_modules|.git|.ssh"

The `~/.config/onedrive/config` should be configured like this:
```
skip_file = ".*|node_modules|.git|.ssh"
```

You have seem to have substituted `skip_file` for `skip_dir` for your configuration.

**Comment by lorenzosu** [comment]
I have updated to #314 and deleted the items.sqlite3 in ~/.config/onedrive, did a --syncronise and it seemed to work. Now I am testing in --monitor mode (which is what I would prefer to emulate a sync client).

I'm wondering in the new version what the difference between the --local-first and --synchronize flags is in the new version.

**Comment by lorenzosu** [comment]
Also for the benefit of someone landing here and wanting to try #314 the commans would be of the kind:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
```

**Comment by lorenzosu** [comment]
Unfortunatelly after adding a few files locally and running the command again it crashes with:
```
Initializing the Synchronization Engine ...
Applying changes of Path ID: [the_id_number_is_displayed_here]
Adding OneDrive Root to the local database
Key not found: name
Applying changes of Path ID: [the_id_number_is_displayed_here]
Adding OneDrive Root to the local database
Key not found: name
Applying changes of Path ID: [the_id_number_is_displayed_here]
Adding OneDrive Root to the local database
std.json.JSONException@std/json.d(494): Key not found: name
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x1cc2e633]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x1ccd0a7a]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x1cc7fe75]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x1cc4f420]
??:? void sync.SyncEngine.applyDifferences() [0x1cc4eab5]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x1cc37692]
??:? _Dmain [0x1cc3707c]
```

**Comment by niknah** [comment]
It's not skipping any files, even when I put...
skip_file = "*"

I found skip_dir from the instructions...
https://github.com/skilion/onedrive/wiki/Configuring-onedrive

**Comment by abraunegg** [comment]
> It's not skipping any files, even when I put...
skip_file = "*"
I found skip_dir from the instructions...
https://github.com/skilion/onedrive/wiki/Configuring-onedrive

Did you rebuild your client after change 835806f0eb634b1c4531a2c2a1f5c3ff6d79868f was posted?

**Comment by abraunegg** [comment]
> Unfortunatelly after adding a few files locally and running the command again it crashes with:
```
Initializing the Synchronization Engine ...
Applying changes of Path ID: [the_id_number_is_displayed_here]
Adding OneDrive Root to the local database
Key not found: name
Applying changes of Path ID: [the_id_number_is_displayed_here]
Adding OneDrive Root to the local database
Key not found: name
Applying changes of Path ID: [the_id_number_is_displayed_here]
Adding OneDrive Root to the local database
std.json.JSONException@std/json.d(494): Key not found: name
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x1cc2e633]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x1ccd0a7a]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x1cc7fe75]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x1cc4f420]
??:? void sync.SyncEngine.applyDifferences() [0x1cc4eab5]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x1cc37692]
??:? _Dmain [0x1cc3707c]
```

Can you send me via email the verbose debug log & http debug when this is happening?

`onedrive --synchronize --verbose -- --debug-https`

**Comment by abraunegg** [comment]
Hi all, 
I have posted a fix for `Key not found: lastModifiedDateTime` in #314.

There are 2 ways you can use #314:

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
```

Option 2:
```
git clone https://github.com/abraunegg/onedrive.git
make
```

I think the original author has abandoned this work.

Best regards,

Alex

**Comment by abraunegg** [comment]
When using #314 and a local DB that has items which are deleted, the resulting log is as follows: 
```
Loading config ...
Using Config Dir: /root/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Applying changes of Path ID: <redacted>
Adding OneDrive Root to the local database
This remote item is in a deleted state
Skipping item: 01D6JQORTO66SOHIVQNZHZ5SI3ECOKQXRK
This remote item is in a deleted state
Skipping item: 01D6JQORXMCNNJ2NQUJRBIK5T2HWS77ZJE
This remote item is in a deleted state
Skipping item: 01D6JQORRXJ7WLBMT44RHI3XEUVAFEFZEK
This remote item is in a deleted state
Skipping item: 01D6JQORRCXCVRB3VQSRGJFCCWH2IO7YBB
This remote item is in a deleted state
Skipping item: 01D6JQORXA4VNQVEOUSVBY5HLNRHYL2BYP
This remote item is in a deleted state
Skipping item: 01D6JQORSR2NVSL7QAWVE3FBW3GUWQSOTV
This remote item is in a deleted state
Skipping item: 01D6JQORTBWXMO7Y7KTZGLRE75LNTQOICG
This remote item is in a deleted state
Skipping item: 01D6JQORQB3JYV7IKVSNFJQPSMXFGLWAFH
This remote item is in a deleted state
Skipping item: 01D6JQORQZF6247BNGKNGZXB23KZERJQ3Q
This remote item is in a deleted state
Skipping item: 01D6JQORR6QRC5QMD54VBYVO25IO22GVSK
This remote item is in a deleted state
Skipping item: 01D6JQORSA2KI2GWKRGRH23LLRQXSYRLH3
This remote item is in a deleted state
Skipping item: 01D6JQORV7FWBGRGBTZ5AY6ZEDNQCOOJ3J
This remote item is in a deleted state
Skipping item: 01D6JQORRQGF3JUJSK75FKVMEMHSSPKGIE
This remote item is in a deleted state
Skipping item: 01D6JQORSE6RUPNRROXJC24NE57MTXNFZJ
This remote item is in a deleted state
Skipping item: 01D6JQORXKIQIAG4VJTZE2YA7GHSQFPLZJ
This remote item is in a deleted state
Skipping item: 01D6JQORTV7UBDP4GJ7JEK54IMGSWL5RVJ
This remote item is in a deleted state
Skipping item: 01D6JQORV5XF35YPTH3ZGJZ5YYYXFQJTRS
This remote item is in a deleted state
Skipping item: 01D6JQORQJVSGT3BJH6JALC6ZVA5N3DCW5
This remote item is in a deleted state
Skipping item: 01D6JQORWZZ3FX2STRE5EIWDSEEDQ5ADHA
This remote item is in a deleted state
Skipping item: 01D6JQORSMHVFCQYZQERF22VKXRGYD4Q4O
This remote item is in a deleted state
Skipping item: 01D6JQORXVZBHOGL4OHVBY3CC6X3QZLFIW
This remote item is in a deleted state
Skipping item: 01D6JQORUATHOBKD2HIFBJT4LPIYUB6HZW
This remote item is in a deleted state
Skipping item: 01D6JQORTFJFOJSIXQ3FC2E434G5YWIJHN
This remote item is in a deleted state
Skipping item: 01D6JQORWH3MRZ2B5ZN5EZFZ5NQLY7XHQO
This remote item is in a deleted state
Skipping item: 01D6JQORUCFD4UBA7S35EYG36FM7WQWWBZ
This remote item is in a deleted state
Skipping item: 01D6JQORWORO5VZC5FAZD3DDGNQUN5RA7H
This remote item is in a deleted state
Skipping item: 01D6JQORT3YGRHJYJJ2ZGYWAOPGH2DKKTE
This remote item is in a deleted state
Skipping item: 01D6JQORXLEBLWXRN2L5FIB36WDWCRFQO5
This remote item is in a deleted state
Skipping item: 01D6JQORVBXATDFHIT4RFYBHXNU3WZVKZP
This remote item is in a deleted state
Skipping item: 01D6JQORVKHNVG4GPBJFCJ6DT5KHW3NVJV
This remote item is in a deleted state
Skipping item: 01D6JQORSM3UR4EIUMABGYD2ZHM7Z6HDGB
This remote item is in a deleted state
Skipping item: 01D6JQORSZ6O64KXBS6FE34ISH3G6YAOAJ
This remote item is in a deleted state
Skipping item: 01D6JQORW7J7WF7X2VKZHZHLU3MD2QMI3D
Fetching details for OneDrive Root
OneDrive Root exists in the database
Uploading differences of .
Processing root
The directory has not changed
Processing asdf
The directory has been deleted
Deleting item from OneDrive: asdf
OneDrive reported: The resource could not be found.
Processing next
The directory has been deleted
Deleting item from OneDrive: next
OneDrive reported: The resource could not be found.
Uploading new items of .
OneDrive Client requested to create remote path: ./new_dir
Fetching details for OneDrive Root
OneDrive Root exists in the database
The requested directory to create was not found on OneDrive - creating remote directory: ./new_dir
Sucessfully created the remote directory ./new_dir on OneDrive
Uploading file ./new_dir/1.txt... done.
Uploading file ./new_dir/1.txt... done.
Applying changes of Path ID: <redacted>
Adding OneDrive Root to the local database
```

**Comment by jamiedow** [comment]
Thank you! This is brilliant ... I think ...

However, I can't get the daemon to work. I've done:
`systemctl --user start onedrive`
and I get the following error:
`Failed to start onedrive.service: Unit network-online.target not found.`

I've no idea what this means. Help?!!!

**Comment by abraunegg** [comment]
What OS are you running it under?

The service systemd file is configures so that it should start only after
the network is available. Maybe your OS needs a tweak of the service file.

**Comment by jamiedow** [comment]
Slightly weirdly, I've noticed the daemon is actually running, despite that error.
I'm running Linux Mint 18.1 (with xfce desktop).

**Comment by jamiedow** [comment]
Btw, really appreciate all the above help in getting this working again. Hopefully it won't be broken when I come back to it tomorrow! Cheers, Jamie

**Comment by sbocquet** [comment]
Linux Mint is based on Ubuntu or Debian (LMDE), so it should be there.

**Comment by jamiedow** [comment]
Thanks, y'all. No idea what the network-online.target problem was. It seemed to go away, and hasn't returned. All working well, at this point. Thanks again.

**Comment by lorenzosu** [comment]
Hi update on this. I've been running the latest #314 in monitor mode for a couple of days and everything seems good. As specified above this can also be obtained directly from @abraunegg fork:
```
git clone https://github.com/abraunegg/onedrive.git
```

**Comment by ekim8587** [comment]
Hello! I've been lurking on this thread to wait for some fixes. Applying the patch #314 fixed the syncing issues, but I found that I was only able to run the new version using sudo because I would get a permission denied error when running onedrive, which wasn't the case with the previous version:

std.file.FileException@std/file.d(816): /home/michael/.config/onedrive/refresh_token: Permission denied

I'm also having the "Failed to start onedrive.service: Unit network-online.target not found." issue and it doesn't seem that the service is running so I've been manually synchronizing in the terminal when I make changes.

**Comment by speedster-pta** [comment]
I have upgraded to #314 after encountering the lastModifiedDateTime error.

I now get this error:shofar@server:~/onedrive$ onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/shofar/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /mnt
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!2FMzqS7WOEGZ6xlJd3bkJqaetgEmNDFOuFPSvfnbENufj_Lg54EOTovKnvnO8hW2
Default Root ID: 016ALCZWV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1080919220115
Fetching details for OneDrive Root
OneDrive Root exists in the database
Applying changes of Path ID: 016ALCZWV6Y2GOVW7725BZO354PWSELRRZ
attempt to write a readonly database
Applying changes of Path ID: 016ALCZWV6Y2GOVW7725BZO354PWSELRRZ
attempt to write a readonly database
Applying changes of Path ID: 016ALCZWV6Y2GOVW7725BZO354PWSELRRZ
sqlite.SqliteException@src/sqlite.d(147): attempt to write a readonly database
----------------
src/sqlite.d:22 void sqlite.Statement.Result.step() [0x599ac9]
src/sqlite.d:117 ref sqlite.Statement.Result sqlite.Statement.Result.__ctor(etc.c.sqlite3.sqlite3_stmt*) [0x599993]
src/sqlite.d:173 sqlite.Statement.Result sqlite.Statement.exec() [0x599c65]
src/itemdb.d:114 void itemdb.ItemDatabase.upsert(ref const(itemdb.Item)) [0x57df21]
src/sync.d:388 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x59b7af]
src/sync.d:360 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x59b5b8]
src/sync.d:184 void sync.SyncEngine.applyDifferences() [0x59aacd]
src/main.d:326 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x58361e]
src/main.d:219 _Dmain [0x583007]

**Comment by abraunegg** [comment]
Check your folder and file permissions in:

/home/shofar/.config/onedrive

Potentially remove the items database file and re-create

**Comment by speedster-pta** [comment]
Thanks. It was a permissions error. I deleted my original post once I realised my mistake, but obviously not before you'd seen it. 

I'm using onedrive as a backup for our office server files - so I don't need realtime update all the time. What would be the best way to sync - should I setup a cronjob to run after the office closes each day, or is it easiest to just keep an instance of --monitor running?

**Comment by abraunegg** [comment]
I would set it up as a cronjob so that all the daily changes locally are
finished for the business day and can be commited to OneDrive.

I would tho also ensure your local file system has internal integrity
checking (zfs) otherwise your local files - whist appearing healthy - may
not actually be healthy.

**Comment by speedster-pta** [comment]
Thanks. I've set the cronjob up now - looks like it's all working. In case anyone else wants to do this, note that in order to get the cronjob to work I had to copy the config and sync_list files from the user I had set onedrive up on to the equivalent folder in root.

I had to use root's crontab as some of the files and folders in that drive have restrictions (manually I can run sudo opendrive --synchronise, but sudo doesn't play nice in crontab).

**Comment by reinierpost** [comment]
I got this same error after removing a directory tree and resyncing (by typing `onedrive`).
Switching to abraunegg's fork fixed the problem. Thank you!

**Comment by MeneerDoktoor** [comment]
One thing i tend to notice when doing the --resync is that it downloads and overwrites files i adjusted.. Which gave me rather big headache last time I did this haha.

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
