### ISSUE TITLE
I need a simple example manual

### ISSUE THREAD

**Issue by seandex** [skilion/onedrive#335]
Hello

I have three substantial onedrive folders already that I don't want to be synced after skilion installation.

I created the 4th folder called "next" and I want only "next" to be synced between onedrive server and skilion linux_cli.

how can I achieve this?

**Comment by abraunegg** [comment]
Hi,

Are you using a 'personal' or 'business' account?

If you are using a 'personal' account, you can use #314 to give you the solution your looking for:

`onedrive --synchronize --verbose --single-directory 'blah'`

If you use the same command with a 'business' account, it fails as the query I use to support that capability has not been implemented in OneDrive Business.

```
HTTP request returned status code 501 (Not Implemented)
{
    "error": {
        "code": "notSupported",
        "innerError": {
            "date": "2018-04-18T21:33:37",
            "request-id": "4014f2a9-aa82-4f77-aefc-b9d6db069469"
        },
        "message": "view.delta can only be called on the root."
    }
}
```

I am working on a 'workaround' at present to make this work for 'business' accounts.

Best regards,

Alex

**Comment by abraunegg** [comment]
Updated #314 so that syncing a single directory works under 'personal' or 'business' accounts.

Use the command: `onedrive --synchronize --verbose --single-directory 'blah'` to sync just a single directory.

**Comment by seandex** [comment]
My client that I installed on Apr 16th is missing some of command options. 

onedrive v1.1.1-2-gc231b13

Usage: onedrive [OPTION]...

no option        Sync and exit
       --confdir Set the directory used to store the configuration files
-d    --download Only download remote changes
        --logout Logout the current user
-m     --monitor Keep monitoring for local and remote changes
   --print-token Print the access token, useful for debugging
        --resync Forget the last saved state, perform a full sync
       --syncdir Set the directory used to sync the files that are synced
-v     --verbose Print more details, useful for debugging
       --version Print the version and exit
-h        --help This help information.

**Comment by abraunegg** [comment]
You need to be using the code as per #314 - the base version you have does
not offer the functionality you need

**Comment by seandex** [comment]
#314 installation, i get this error on both option 1 and option 2 
Makefile:35: recipe for target 'onedrive' failed
make: *** [onedrive] Killed
----------------------------
also tried make DC=ldmd2, more errors..

reverted back to echo v1.1.1-2-gc231b13 to test again, re-installed it flawlessly and operational.

Debian 8 btw, I'm in the openvz. 042stab if this matters with #314

**Comment by abraunegg** [comment]
What version of dmd are you using?

**Comment by seandex** [comment]
DMD64 D Compiler v2.079.1

**Comment by sbocquet** [comment]
Strange... I have no error with the latest commit on a Debian 9 x64 with the same version of the DMD compiler

```
root@home-server:/opt/onedrive# uname -a
Linux home-server 4.14.0-0.bpo.3-amd64 #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64 GNU/Linux

root@home-server:/opt/onedrive# dmd --version
DMD64 D Compiler v2.079.1
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

root@home-server:/opt# git clone https://github.com/abraunegg/onedrive.git
Clonage dans 'onedrive'...
remote: Counting objects: 1071, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 1071 (delta 70), reused 79 (delta 33), pack-reused 951
Réception d'objets: 100% (1071/1071), 324.28 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (732/732), fait.

root@home-server:/opt# cd onedrive/

root@home-server:/opt/onedrive# make
echo v1.1.1-26-g648c1ef >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
sed "s|@PREFIX@|/usr/local|g" systemd.units/onedrive.service.in > onedrive.service
sed "s|@PREFIX@|/usr/local|g" systemd.units/onedrive@.service.in > onedrive@.service
```

**Comment by seandex** [comment]
make --debug
GNU Make 4.0
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating goal targets....
 File 'all' does not exist.
   Prerequisite 'version' is newer than target 'onedrive'.
   Prerequisite 'src/config.d' is newer than target 'onedrive'.
   Prerequisite 'src/log.d' is newer than target 'onedrive'.
   Prerequisite 'src/main.d' is newer than target 'onedrive'.
   Prerequisite 'src/onedrive.d' is newer than target 'onedrive'.
   Prerequisite 'src/selective.d' is newer than target 'onedrive'.
   Prerequisite 'src/sync.d' is newer than target 'onedrive'.
   Prerequisite 'src/util.d' is newer than target 'onedrive'.
  Must remake target 'onedrive'.
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
Makefile:35: recipe for target 'onedrive' failed
make: *** [onedrive] Killed

**Comment by abraunegg** [comment]
@seandex 

Any update?

**Comment by seandex** [comment]
$ uname -a
Linux 2.6.32-042stab120.20 #1 SMP Fri Mar 10 16:52:50 MSK 2017 x86_64 GNU/Linux

$ dmd --version
DMD64 D Compiler v2.079.1
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

$ git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Counting objects: 1120, done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 1120 (delta 102), reused 126 (delta 63), pack-reused 951
Receiving objects: 100% (1120/1120), 332.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (762/762), done.
Checking connectivity... done.

$ make
echo v1.1.1-42-gdff245d >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
Makefile:34: recipe for target 'onedrive' failed
make: *** [onedrive] Killed

**Comment by abraunegg** [comment]
What is the contents of your dmd.conf file?

**Comment by abraunegg** [comment]
Are you still having issues building? in #331 it appears the SuSE packages are broken - so perhaps things are broken for your DMD install.

Can you try to install DMD via this mechanism:
```
curl -fsS https://dlang.org/install.sh | bash -s dmd
```

There is no reason why the build is breaking on your OS unless there is an issue with the DMD install itself.

**Comment by seandex** [comment]
@abraunegg 
$ cat /etc/dmd.conf 
;
; dmd.conf file for dmd
;
; dmd will look for dmd.conf in the following sequence of directories:
;   - current working directory
;   - directory specified by the HOME environment variable
;   - directory dmd resides in
;   - /etc directory
;
; Names enclosed by %% are searched for in the existing environment and inserted
;
; The special name %@P% is replaced with the path to this file
;

[Environment32]
DFLAGS=-I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/i386-linux-gnu -L--export-dynamic

[Environment64]
DFLAGS=-I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/x86_64-linux-gnu -L--export-dynamic -fPIC

**Comment by seandex** [comment]
@abraunegg 
$ curl -fsS https://dlang.org/install.sh | bash -s dmd
Downloading https://dlang.org/d-keyring.gpg
######################################################################## 100.0%
Downloading https://dlang.org/install.sh
######################################################################## 100.0%
The latest version of this script was installed as ~/dlang/install.sh.
It can be used it to install further D compilers.
Run `~/dlang/install.sh --help` for usage information.

Downloading and unpacking http://downloads.dlang.org/releases/2.x/2.079.1/dmd.2.079.1.linux.tar.xz
######################################################################## 100.0%
Using dub 1.8.1 shipped with dmd-2.079.1

Run `source ~/dlang/dmd-2.079.1/activate` in your shell to use dmd-2.079.1.
This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
Run `deactivate` later on to restore your environment.

$ source ~/dlang/dmd-2.079.1/activate
(dmd-2.079.1)sean@sean:~$ 
(dmd-2.079.1)sean@sean:~$ dmd --version
DMD64 D Compiler v2.079.1
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

(dmd-2.079.1)sean@sean:~$ git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Counting objects: 1141, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 1141 (delta 9), reused 13 (delta 5), pack-reused 1120
Receiving objects: 100% (1141/1141), 352.93 KiB | 0 bytes/s, done.
Resolving deltas: 100% (777/777), done.
Checking connectivity... done.
(dmd-2.079.1)sean@sean:~$ cd onedrive/
(dmd-2.079.1)sean@sean:~/onedrive$ make
echo v1.1.1-47-gccd4dfb >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/util.d(111): Deprecation: std.file.dur is not visible from module util
Makefile:34: recipe for target 'onedrive' failed
make: *** [onedrive] Killed

(dmd-2.079.1)sean@sean:~/onedrive$ uname -a
Linux sean.ovh 2.6.32-042stab120.20 #1 SMP Fri Mar 10 16:52:50 MSK 2017 x86_64 GNU/Linux

$ cat /etc/debian_version 
8.10


well.. since echo v1.1.1-2-gc231b13  works without a single errors. I think it is just a couple of lines from Makefile. have you checked on it?

**Comment by abraunegg** [comment]
Ok .. it looks like your build is failing on the depreciation warning maybe - as from a Makefile perspective there are no issues, and builds correctly on Debian 9.x

**Comment by abraunegg** [comment]
Posted 90dec8d6f1fbae6ffdca42c918f16ed13dffbd59 which resolves the following build warning:

```
src/util.d(111): Deprecation: `std.net.curl.dur` is not visible from module `util`
```

Can you try the build again ensuring a clean build:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

If you can try with that, that would be greatly appreciated.

**Comment by abraunegg** [comment]
@seandex 
Any update?

**Comment by seandex** [comment]
@abraunegg 
Thank you very much for keep reminding me of this issue.
and here is the result.
> sean@sean:~$ git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Counting objects: 1159, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 1159 (delta 22), reused 27 (delta 12), pack-reused 1120
Receiving objects: 100% (1159/1159), 359.20 KiB | 0 bytes/s, done.
Resolving deltas: 100% (790/790), done.
Checking connectivity... done.
sean@sean:~$ cd onedrive/
sean@sean:~/onedrive$ make
echo v1.1.1-51-g0c4def8 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
Makefile:34: recipe for target 'onedrive' failed
make: *** [onedrive] Killed
sean@sean:~/onedrive$ make install
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
Makefile:34: recipe for target 'onedrive' failed
make: *** [onedrive] Killed
sean@sean:~/onedrive$ 

I will try to upgrade to Debian 9 and let you know.
Thanks again.

**Comment by seandex** [comment]
git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Counting objects: 1159, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 1159 (delta 22), reused 27 (delta 12), pack-reused 1120
Receiving objects: 100% (1159/1159), 359.20 KiB | 0 bytes/s, done.
Resolving deltas: 100% (790/790), done.

sean@153757:~/onedrive$ make
echo v1.1.1-51-g0c4def8 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
Makefile:34: recipe for target 'onedrive' failed
make: *** [onedrive] Killed
sean@153757:~/onedrive$ cat /etc/debian_version 
9.4
sean@153757:~/onedrive$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by seandex** [comment]
I think its the openvz kernel problem as containers cant update the kernel itself.

**Comment by abraunegg** [comment]
OK - so building #314 is breaking for you with openvz kernel  .. unsure how or why that would cause a problem when the 'master' code builds fine for you. I am unsure as to resolve this as the build process completes without issue on other systems and the build failure seems to be entirely related to your environment.

**Comment by seandex** [comment]
Thank you for your support though,
so, there any workarounds to bypass the whole disk sync? Or one-way upload option from the master version?

**Comment by abraunegg** [comment]
No there isnt - I wish I knew what is actually breaking for you with the build process - as there is nothing unique at all in those changes in #314 

Can you build on a non openvz kernel and see what happens?

**Comment by abraunegg** [comment]
Can you 'manually' call dmd to build rather than using 'make' ?

`dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d`

**Comment by seandex** [comment]
sean@153757:~/onedrive$ dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
Killed
sean@153757:~/onedrive$ dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d -vvv
Error: unrecognized switch '-vvv'
       run 'dmd -man' to open browser on manual
sean@153757:~/onedrive$ dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d -v
predefs   DigitalMars Posix linux ELFv1 LittleEndian D_Version2 all D_SIMD D_InlineAsm_X86_64 X86_64 CRuntime_Glibc D_LP64 D_PIC assert D_HardFloat
binary    dmd
version   v2.080.0
config    /etc/dmd.conf
DFLAGS    -I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/x86_64-linux-gnu -L--export-dynamic -fPIC
parse     config
parse     itemdb
parse     log
parse     main
parse     monitor
parse     onedrive
parse     qxor
parse     selective
parse     sqlite
parse     sync
parse     upload
parse     util
importall config
import    object	(/usr/include/dmd/druntime/import/object.d)
import    std.file	(/usr/include/dmd/phobos/std/file.d)
import    core.time	(/usr/include/dmd/druntime/import/core/time.d)
import    core.internal.traits	(/usr/include/dmd/druntime/import/core/internal/traits.d)
import    core.exception	(/usr/include/dmd/druntime/import/core/exception.d)
import    core.stdc.time	(/usr/include/dmd/druntime/import/core/stdc/time.d)
import    core.sys.posix.sys.types	(/usr/include/dmd/druntime/import/core/sys/posix/sys/types.d)
import    core.sys.posix.config	(/usr/include/dmd/druntime/import/core/sys/posix/config.d)
import    core.stdc.config	(/usr/include/dmd/druntime/import/core/stdc/config.d)
import    core.stdc.stdint	(/usr/include/dmd/druntime/import/core/stdc/stdint.d)
import    core.stdc.stddef	(/usr/include/dmd/druntime/import/core/stdc/stddef.d)
import    core.stdc.signal	(/usr/include/dmd/druntime/import/core/stdc/signal.d)
import    core.stdc.wchar_	(/usr/include/dmd/druntime/import/core/stdc/wchar_.d)
import    core.stdc.stdarg	(/usr/include/dmd/druntime/import/core/stdc/stdarg.d)
import    core.stdc.stdlib	(/usr/include/dmd/druntime/import/core/stdc/stdlib.d)
import    core.stdc.stdio	(/usr/include/dmd/druntime/import/core/stdc/stdio.d)
import    core.internal.string	(/usr/include/dmd/druntime/import/core/internal/string.d)
import    core.sys.posix.time	(/usr/include/dmd/druntime/import/core/sys/posix/time.d)
import    core.sys.posix.signal	(/usr/include/dmd/druntime/import/core/sys/posix/signal.d)
import    core.sys.linux.time	(/usr/include/dmd/druntime/import/core/sys/linux/time.d)
import    core.sys.posix.sys.time	(/usr/include/dmd/druntime/import/core/sys/posix/sys/time.d)
import    core.sys.posix.sys.select	(/usr/include/dmd/druntime/import/core/sys/posix/sys/select.d)
import    core.sys.linux.sys.time	(/usr/include/dmd/druntime/import/core/sys/linux/sys/time.d)
import    core.sys.linux.config	(/usr/include/dmd/druntime/import/core/sys/linux/config.d)
import    std.datetime.date	(/usr/include/dmd/phobos/std/datetime/date.d)
import    std.traits	(/usr/include/dmd/phobos/std/traits.d)
import    std.meta	(/usr/include/dmd/phobos/std/meta.d)
import    std.functional	(/usr/include/dmd/phobos/std/functional.d)
import    std.typecons	(/usr/include/dmd/phobos/std/typecons.d)
import    std.format	(/usr/include/dmd/phobos/std/format.d)
import    core.vararg	(/usr/include/dmd/druntime/import/core/vararg.d)
import    std.exception	(/usr/include/dmd/phobos/std/exception.d)
import    std.range.primitives	(/usr/include/dmd/phobos/std/range/primitives.d)
import    std.datetime.systime	(/usr/include/dmd/phobos/std/datetime/systime.d)
import    std.datetime.timezone	(/usr/include/dmd/phobos/std/datetime/timezone.d)
import    core.stdc.errno	(/usr/include/dmd/druntime/import/core/stdc/errno.d)
import    core.stdc.string	(/usr/include/dmd/druntime/import/core/stdc/string.d)
import    std.internal.cstring	(/usr/include/dmd/phobos/std/internal/cstring.d)
import    std.range	(/usr/include/dmd/phobos/std/range/package.d)
import    std.array	(/usr/include/dmd/phobos/std/array.d)
import    std.range.interfaces	(/usr/include/dmd/phobos/std/range/interfaces.d)
import    core.sys.posix.dirent	(/usr/include/dmd/druntime/import/core/sys/posix/dirent.d)
import    core.sys.posix.fcntl	(/usr/include/dmd/druntime/import/core/sys/posix/fcntl.d)
import    core.sys.posix.sys.stat	(/usr/include/dmd/druntime/import/core/sys/posix/sys/stat.d)
import    core.sys.posix.unistd	(/usr/include/dmd/druntime/import/core/sys/posix/unistd.d)
import    core.sys.posix.inttypes	(/usr/include/dmd/druntime/import/core/sys/posix/inttypes.d)
import    core.stdc.inttypes	(/usr/include/dmd/druntime/import/core/stdc/inttypes.d)
import    core.sys.posix.utime	(/usr/include/dmd/druntime/import/core/sys/posix/utime.d)
import    std.string	(/usr/include/dmd/phobos/std/string.d)
import    std.uni	(/usr/include/dmd/phobos/std/uni.d)
import    std.internal.unicode_tables	(/usr/include/dmd/phobos/std/internal/unicode_tables.d)
import    std.algorithm.comparison	(/usr/include/dmd/phobos/std/algorithm/comparison.d)
import    std.algorithm.searching	(/usr/include/dmd/phobos/std/algorithm/searching.d)
import    std.regex	(/usr/include/dmd/phobos/std/regex/package.d)
import    std.regex.internal.ir	(/usr/include/dmd/phobos/std/regex/internal/ir.d)
import    std.stdio	(/usr/include/dmd/phobos/std/stdio.d)
import    std.algorithm.mutation	(/usr/include/dmd/phobos/std/algorithm/mutation.d)
import    std.algorithm	(/usr/include/dmd/phobos/std/algorithm/package.d)
import    std.algorithm.iteration	(/usr/include/dmd/phobos/std/algorithm/iteration.d)
import    std.algorithm.setops	(/usr/include/dmd/phobos/std/algorithm/setops.d)
import    std.algorithm.sorting	(/usr/include/dmd/phobos/std/algorithm/sorting.d)
import    std.path	(/usr/include/dmd/phobos/std/path.d)
import    std.base64	(/usr/include/dmd/phobos/std/base64.d)
import    std.conv	(/usr/include/dmd/phobos/std/conv.d)
import    std.ascii	(/usr/include/dmd/phobos/std/ascii.d)
import    std.digest.crc	(/usr/include/dmd/phobos/std/digest/crc.d)
import    std.digest	(/usr/include/dmd/phobos/std/digest/package.d)
import    std.digest.sha	(/usr/include/dmd/phobos/std/digest/sha.d)
import    core.bitop	(/usr/include/dmd/druntime/import/core/bitop.d)
import    std.net.curl	(/usr/include/dmd/phobos/std/net/curl.d)
import    etc.c.curl	(/usr/include/dmd/phobos/etc/c/curl.d)
import    std.socket	(/usr/include/dmd/phobos/std/socket.d)
import    core.sys.posix.sys.un	(/usr/include/dmd/druntime/import/core/sys/posix/sys/un.d)
import    core.sys.posix.sys.socket	(/usr/include/dmd/druntime/import/core/sys/posix/sys/socket.d)
import    core.sys.posix.sys.uio	(/usr/include/dmd/druntime/import/core/sys/posix/sys/uio.d)
import    core.sys.posix.netinet.in_	(/usr/include/dmd/druntime/import/core/sys/posix/netinet/in_.d)
import    core.sys.posix.arpa.inet	(/usr/include/dmd/druntime/import/core/sys/posix/arpa/inet.d)
import    core.sys.posix.netdb	(/usr/include/dmd/druntime/import/core/sys/posix/netdb.d)
import    core.sys.posix.netinet.tcp	(/usr/include/dmd/druntime/import/core/sys/posix/netinet/tcp.d)
import    std.encoding	(/usr/include/dmd/phobos/std/encoding.d)
import    std.datetime	(/usr/include/dmd/phobos/std/datetime/package.d)
import    std.datetime.interval	(/usr/include/dmd/phobos/std/datetime/interval.d)
import    std.digest.digest	(/usr/include/dmd/phobos/std/digest/digest.d)
import    std.process	(/usr/include/dmd/phobos/std/process.d)
import    core.sys.posix.sys.wait	(/usr/include/dmd/druntime/import/core/sys/posix/sys/wait.d)
import    core.thread	(/usr/include/dmd/druntime/import/core/thread.d)
import    core.atomic	(/usr/include/dmd/druntime/import/core/atomic.d)
import    core.memory	(/usr/include/dmd/druntime/import/core/memory.d)
import    core.sync.mutex	(/usr/include/dmd/druntime/import/core/sync/mutex.di)
import    core.sync.exception	(/usr/include/dmd/druntime/import/core/sync/exception.di)
import    core.sys.posix.pthread	(/usr/include/dmd/druntime/import/core/sys/posix/pthread.d)
import    core.sys.posix.sched	(/usr/include/dmd/druntime/import/core/sys/posix/sched.d)
import    core.sys.posix.semaphore	(/usr/include/dmd/druntime/import/core/sys/posix/semaphore.d)
import    core.sys.posix.stdlib	(/usr/include/dmd/druntime/import/core/sys/posix/stdlib.d)
import    core.sys.posix.pwd	(/usr/include/dmd/druntime/import/core/sys/posix/pwd.d)
importall itemdb
import    etc.c.sqlite3	(/usr/include/dmd/phobos/etc/c/sqlite3.d)
importall log
importall main
import    std.getopt	(/usr/include/dmd/phobos/std/getopt.d)
import    core.sys.linux.sys.inotify	(/usr/include/dmd/druntime/import/core/sys/linux/sys/inotify.d)
import    core.sys.posix.poll	(/usr/include/dmd/druntime/import/core/sys/posix/poll.d)
import    std.json	(/usr/include/dmd/phobos/std/json.d)
import    std.uri	(/usr/include/dmd/phobos/std/uri.d)
importall monitor
importall onedrive
importall qxor
importall selective
importall sqlite
importall sync
importall upload
importall util
semantic  config
import    std.math	(/usr/include/dmd/phobos/std/math.d)
import    core.math	(/usr/include/dmd/druntime/import/core/math.d)
import    core.stdc.math	(/usr/include/dmd/druntime/import/core/stdc/math.d)
import    core.stdc.fenv	(/usr/include/dmd/druntime/import/core/stdc/fenv.d)
import    std.regex.internal.kickstart	(/usr/include/dmd/phobos/std/regex/internal/kickstart.d)
import    std.utf	(/usr/include/dmd/phobos/std/utf.d)
semantic  itemdb
semantic  log
semantic  main
import    std.bitmanip	(/usr/include/dmd/phobos/std/bitmanip.d)
import    std.system	(/usr/include/dmd/phobos/std/system.d)
entry     main      	src/main.d
semantic  monitor
semantic  onedrive
semantic  qxor
semantic  selective
semantic  sqlite
semantic  sync
semantic  upload
semantic  util
semantic2 config
semantic2 itemdb
semantic2 log
semantic2 main
semantic2 monitor
semantic2 onedrive
semantic2 qxor
semantic2 selective
semantic2 sqlite
semantic2 sync
semantic2 upload
semantic2 util
semantic3 config
import    std.algorithm.internal	(/usr/include/dmd/phobos/std/algorithm/internal.d)
import    core.checkedint	(/usr/include/dmd/druntime/import/core/checkedint.d)
import    std.regex.internal.parser	(/usr/include/dmd/phobos/std/regex/internal/parser.d)
import    std.internal.unicode_grapheme	(/usr/include/dmd/phobos/std/internal/unicode_grapheme.d)
import    std.regex.internal.backtracking	(/usr/include/dmd/phobos/std/regex/internal/backtracking.d)
import    std.regex.internal.thompson	(/usr/include/dmd/phobos/std/regex/internal/thompson.d)
import    core.internal.hash	(/usr/include/dmd/druntime/import/core/internal/hash.d)
import    core.internal.convert	(/usr/include/dmd/druntime/import/core/internal/convert.d)
semantic3 itemdb
semantic3 log
semantic3 main
file      version	(/home/sean/onedrive/version)
import    core.internal.abort	(/usr/include/dmd/druntime/import/core/internal/abort.d)
semantic3 monitor
semantic3 onedrive
semantic3 qxor
semantic3 selective
semantic3 sqlite
import    std.c.stdlib	(/usr/include/dmd/phobos/std/c/stdlib.d)
semantic3 sync
semantic3 upload
semantic3 util
import    core.cpuid	(/usr/include/dmd/druntime/import/core/cpuid.d)
import    std.internal.digest.sha_SSSE3	(/usr/include/dmd/phobos/std/internal/digest/sha_SSSE3.d)
Killed
sean@153757:~/onedrive$

**Comment by abraunegg** [comment]
Is there any way to fix up all your posts so that they don't have the strike through - and where it is command output use the code ticks ` 3 times to open & close the code / output sections?

On that build - it looks like it is failing to import an internal function - something with your DMD install certainly is not right ...

**Comment by seandex** [comment]
I just created VZ Ubuntu container from another machine on the east coast. It produced same error messages. Well, OpenVZ can't support it. I will test this on my computer here later using VirtualBox, but I'm pretty sure it will work straightforwardly like XEN and KVM.

**Comment by seandex** [comment]
If you want to debug this issue, I just reproduced the problem,
I just duplicated the problem so you can log-in if you're going to take a look at it.

root@158.69.69.1 -p22222
password is onedrive

Ubuntu jessie clean install and then
> sudo apt install libcurl4-openssl-dev
sudo apt install libsqlite3-dev
sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
sudo apt-get update && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
sudo apt-get update && sudo apt-get install dmd-compiler dub
git clone https://github.com/abraunegg/onedrive.git
make

and then error.

git cloned at the root this time, /onedrive

I will leave that container on for a while; I can delete it later so no big deal to test whatever you want.

**Comment by abraunegg** [comment]
OK .. so does it compile correctly on your own system now as well ?

**Comment by abraunegg** [comment]
@seandex 
any update now that the compile is working on 1G of RAM ?

**Comment by seandex** [comment]
@abraunegg 
It just works on Debian Jessie 8.6 without an error (the 1GB container) But here is an update, I thought I had the container setup as 1G RAM, and I did not realize until now,  it was 256MB but 2GB Swap RAM. So that swap ram did the trick.

Now, I'm not sure if your script required minimum 1G RAM because I was on 512MB/256MB Swap but failed whole time on this topic. 

so the 3rd VirtualBox in my MacBook, it is the clean installation of Fedora 28, the latest one.
It just works too. But I had to install gcc when the instruction didn't mention about it. No big deal, dnf install gcc will fit all other dependencies like cpp binutils, etc. at once.

Anyways, I will try the 512MB/256MB VPS once more time by increasing swap, since that VZ node isn't mine, I gotta do some little hacks to increase swap ram. I will try at 512/512 and see that is successful, and I hope this works so maybe we could find the minimum RAM requirements.

Thanks for your great support.

**Comment by abraunegg** [comment]
@seandex 
> It looks like the program relies on privmpages

Is that the dmd compiler here or 'onedrive' (the program reference)

**Comment by abraunegg** [comment]
@seandex 
Any update?

**Comment by seandex** [comment]
@abraunegg 
last time I tested was Centos 7 and dmd was 
curl -fsS https://dlang.org/install.sh | bash -s dmd

**Comment by abraunegg** [comment]
@seandex 
But in terms of the original issue - and syncing a single folder:

```
onedrive --synchronize --verbose --single-directory 'blah'
```

Are you able to do that now  by compiling the #314 code and using it?

**Comment by seandex** [comment]
@abraunegg 
Yes, it is working great as long as the dmd generate no errors on low-end servers.

**Comment by seandex** [comment]
@abraunegg 
Yes, thank you very much for the most exceptional support.

**Comment by abraunegg** [comment]
If you can close it then that would be great
