### ISSUE TITLE
Often create new file such as <filename>-<hostname>

### ISSUE THREAD

**Issue by Honghe** [skilion/onedrive#338]
Environment:
* Ubuntu 16.04.4 GNOME
* onedrive v1.1.1-2-gc231b13

I have two Onedrive client, one is https://github.com/skilion/onedrive, one is Official Onedrive on Windows 10. And I didn't edit/open files on Windows Onedrive, only edit files on Ubuntu.
But https://github.com/skilion/onedrive often create file such as `<filename>-<hostname>.md` or `<filename>-<hostname>-1.md` from my original file `<filename>-<hostname>.md` when I edit some file.

**Comment by abraunegg** [comment]
Hi,

Can you provide a debug log when the issue is occurring using the latest available code?

`onedrive --synchronize --verbose`

There are 2 ways to get the latest code:

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
make install
```

Option 2:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

The original author appears to have abandoned this project.

Best regards,

Alex

**Comment by abraunegg** [comment]
This is the same issue as #171, #265, #343

There appears to be an issue in the local conflict handling routine in the original codebase. This will be the next item I look at.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
