### ISSUE TITLE
Syncing shared objects

### ISSUE THREAD

**Issue by frispete** [skilion/onedrive#339]
Hi,

sorry for my ignorance, but I don't grok the "Shared folders" paragraph of your documentation:
there's no "Add to my OneDrive" kind of function:

![screenshot_20180418](https://user-images.githubusercontent.com/1009685/38942553-67bab116-432f-11e8-9dcb-3b68729b94d7.png)

The native Windows 10 client interface looks similar!
Any idea, what's wrong here?

**Comment by abraunegg** [comment]
Hi,

The original author appears to have abandoned this project.

On reading the 'Shared Folders' section, it certainly if not clear what the direction is. My understanding is:

1. Another OneDrive user share's out a folder or document with you. This action is performed via the OneDrive web interface
2. This shared item will be then visible under the 'Shared' menu, where you can add it to be sync'd to your OneDrive account.

All of this functionality / capability is with the OneDrive web interface and not this onedrive client.

What the onedrive client will do is - when you have configured the web interface to sync a shared folder to your account, it will sync those shared changes locally to your local system.

Note: I have not tested this, I am simply reading through the lines of how this may work. Yes the documentation is unclear and needs to be updated. Will look at updating the documentation for this after I test and see what is going on.

**Comment by sbocquet** [comment]
From what I know about OneDrive, that the way it works.
If someone shares some dir/files with you (via web UI), they are duplicated/synch to your OneDrive. The space is used on both accounts.

**Comment by abraunegg** [comment]
> I haven't found a way to add the shared items to the sync set of onedrive directly.

You cant - you can only add / remove shared set's from the OneDrive web interface - it is not a function of the onedrive client to manage shared objects.

**Comment by frispete** [comment]
> You cant - you can only add / remove shared set's from the OneDrive web interface - it is not a function of the onedrive client to manage shared objects.

I fully understand the operation/purpose of the involved parts here. `onedrive` is a background job, syncing the content of ones `OneDrive` storage space back and forth, controlled by a configuration file. All other UI tasks have to be made in the web interface, or the native windows client UI.

Anyway, I misunderstood the referenced paragraph. I was under the impression, that shared objects can be handled more directly, but it's like @sbocquet said, there is no other way than making a copy by now.

Copying shared objects to the "private" storage space has the additional side effect of loosing the shared state, consequently changes from other parties to the shared object aren't tracked in the copied objects. In this respect, shared objects are second class members in `OneDrive` only.

Probably, it's possible to extend `onedrive` to handle shared items in a more sensible way. As additional benefit, this would be a **USP** since even the native windows sync client does handle non shared objects only.

Or am I still miss something here?
