### ISSUE TITLE
network-online.target not found & have to run client as root.

### ISSUE THREAD

**Issue by ekim8587** [skilion/onedrive#342]
Applying the patch #314 fixed the syncing issues, but I found that I was only able to run the new version using sudo because I would get a permission denied error when running onedrive, which wasn't the case with the previous version:

std.file.FileException@std/file.d(816): /home/michael/.config/onedrive/refresh_token: Permission denied

I'm also having the "Failed to start onedrive.service: Unit network-online.target not found." issue and it doesn't seem that the service is running so I've been manually synchronizing in the terminal when I make changes.

`
ls -la /home/michael/.config/onedrive
total 20
drwxrwxr-x  2 michael michael 4096 Apr 21 17:27 .
drwxr-xr-x 24 michael michael 4096 Apr 21 17:26 ..
-rw-r--r--  1 root    root    5120 Apr 21 17:27 items.sqlite3
-rw-r--r--  1 root    root     932 Apr 21 17:27 refresh_token
`

I built the client by cloning the abraunegg version directly, installing the dependencies and running
`make
sudo make install`

Install as regular user gives permission denied.

Currently running Elementary OS 0.4.1, based on Ubuntu. I found the network-online.target where it should be since Elementary is based on Ubuntu.

**Comment by abraunegg** [comment]
OK .. that makes sense as to the permission's issue.

Can you also edit your post above and format it using the ` quotes - 3 before CLI output and 3 after CLI output for readability? For inline items use the quote once before & after.

The `onedrive.service` file is geared for a `root` user, where as the `onedrive@.service` is geared to a non-root user running `onedrive` as a service.

Can you do the following:

1. Remove the /home/michael/.config/ directory using sudo
2. Run, without sudo, simple `onedrive`. It should then prompt for authorisation. Authorise the application.
3. List the permissions of `/home/michael/.config/onedrive`

**Comment by ekim8587** [comment]
Removed the directory /home/michael/.config/
Ran onedrive.

`Authorize this app visiting:

std.exception.ErrnoException@std/stdio.d(423): Cannot open file `/var/log/onedrive/Michael Pietrasiewicz.onedrive.log' in mode `a' (Permission denied)
----------------
??:? @safe shared(core.stdc.stdio._IO_FILE)* std.exception.errnoEnforce!(shared(core.stdc.stdio._IO_FILE)*, "std/stdio.d", 423uL).errnoEnforce(shared(core.stdc.stdio._IO_FILE)*, lazy immutable(char)[]) [0x614cc1]
??:? ref @safe std.stdio.File std.stdio.File.__ctor(immutable(char)[], const(char[])) [0x5ccd34]
src/log.d:45 @safe void log.logfileWriteLine!(immutable(char)[]).logfileWriteLine(immutable(char)[]) [0x57f59b]
src/log.d:20 @safe void log.log!(immutable(char)[]).log(immutable(char)[]) [0x57fa3b]
src/onedrive.d:77 bool onedrive.OneDriveApi.authorize() [0x58e8ab]
src/onedrive.d:67 bool onedrive.OneDriveApi.init() [0x58e7a7]
src/main.d:144 _Dmain [0x5812ed]`

**Comment by ekim8587** [comment]
After updating permissions, I still get the same output that I pasted above.

**Comment by abraunegg** [comment]
Are you free to do a WebEx?

**Comment by ekim8587** [comment]
Sure I can do that.

**Comment by abraunegg** [comment]
What email address to send invite to?

**Comment by ekim8587** [comment]
ekim8587@me.com

**Comment by abraunegg** [comment]
invite is sent - waiting for you to join

**Comment by abraunegg** [comment]
Resolution:
* Fixed Makefile ordering (d3f406459c13b2a786c7b216553b035a7779623c, da9cc628cb3f58efbd627378519ee9ba398bf030)
* Local user account was not in local `users` group (GID 100) thus had no permission to write to `/var/log/onedrive`

Action Items:
* Update README.md to highlight differences for systemd service files
