### ISSUE TITLE
Unit network-online.target not found

### ISSUE THREAD

**Issue by jamiedow** [skilion/onedrive#344]
Hi, folks,
Can anyone help? I'm getting the following issue, when I try to use the onedrive service.

`jamie@jamie-samsung ~ $ systemctl --user start onedrive
Failed to start onedrive.service: Unit network-online.target not found.`

I had this before, and it somehow went away after some time (I don't know why), but now it's back.
It isn't plausible to think that this is simply missing in my distro (Mint 18.1 xfce). Network seems to be working otherwise ..... what can this be - I'm really beyond my tech abilities here?

All help very much appreciated.
Oh, I'm already running #314.

Thanks, Jamie

**Comment by abraunegg** [comment]
A tweak was made to the service file in recent commit. Can you post the contents of your service file? You may have the older version.

**Comment by jamiedow** [comment]
Sorry ... I'm not certain which file you mean. But I'm guessing it might be ~/onedrive/onedrive@.service
If so (I also have a file called onedrive.service in the same directory, but I think that's a different service, to be run as root), here it is:

~/onedrive/onedrive@.service
`[Unit]
Description=OneDrive Free Client for %i
Documentation=https://github.com/skilion/onedrive
Requires=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/local/bin/onedrive --monitor --confdir=/home/%i/.config/onedrive
User=%i
Group=users
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target`

**Comment by abraunegg** [comment]
So thats the older version of the file.

If you rebuild onedrive from git & install you will get the newer version of the file.

**Comment by jamiedow** [comment]
Thanks. 
Which version, and where from? ..... I'm sorry to be asking such basic questions.

When I've updated versions in the past, I've deleted everything from my ~/onedrive directory, including hidden files/folders, and then redone the installation there.
Is that the correct way to do this? It somehow seems a bit of a crude way to do it (although it worked).

Thanks,
Jamie

**Comment by jamiedow** [comment]
Also, is this going to land me back with the problems I had before I moved to #314 ?

**Comment by abraunegg** [comment]
~~There are 2 ways to get the latest code:~~

~~Option 1:~~

~~git clone https://github.com/skilion/onedrive.git~~
~~git fetch origin pull/314/head:pr314~~
~~git checkout pr314~~
~~make~~
~~make install~~

Option 2:

git clone https://github.com/abraunegg/onedrive.git
make
make install


**Update 2023:** All the latest code is here: https://github.com/abraunegg/onedrive. PR-314 was removed in favour of a dedicated repository

**Comment by jamiedow** [comment]
OK. Many thanks! That's seemed to sort it. Very much appreciated.

**Comment by Shekelme** [comment]
@jamiedow What does your onedrive@.service file look like now?

**Comment by abraunegg** [comment]
@Shekelme 
> @jamiedow What does your [onedrive@.service](mailto:onedrive@.service) file look like now?

This issue is over 5 years old, all current work and development is located here: https://github.com/abraunegg/onedrive
