### ISSUE TITLE
Speed up sqlite with Write-Ahead Logging (WAL)

### ISSUE THREAD

**Issue by tweek-dk** [skilion/onedrive#346]
Hi

You can speed up sqlite a bit by activating WAL:
`PRAGMA journal_mode=WAL;`

Resyncing a 25G drive with 79000 files is now way faster.

It's persistant, so you only need to do it once.

Have a look at https://www.sqlite.org/wal.html for more info.

Regards,
-Martin

**Comment by sworah** [comment]
This works really well, thanks!

I did it by using the following command in a Linux terminal:

`sqlite3 ~/.config/onedrive/items.sqlite3`

When in the sqlite console, run `PRAGMA journal_mode=WAL;` and then `.quit` and you are done! Everything persists from that point, so no need to redo this.

**Comment by abraunegg** [comment]
@tweek-dk 
Thanks for the suggestion - I have added in as a default for any new builds / clones of #314

**Comment by abraunegg** [comment]
@tweek-dk 
Can you close this case out as this is now included by default in #314
