### ISSUE TITLE
App authorization URL No such file or directory

### ISSUE THREAD

**Issue by LordRahl007** [skilion/onedrive#349]
Made it through the install, it presents the link to authorize the app.  When I authorize it and then copy the URL of the blank page back into the terminal, I get this and it does not create a OneDrive folder or sync anything. (Note I substituted the actual URL here for security purposes, but I just copied and pasted the whole thing in the terminal)

`onedrive -m &`
then it gives me
`[1] 27184`
`Authorize this app visiting:`
`https://[authorization request link here]`
`https://[pasted authorization link here]`
`bash: https://login.microsoftonline.com/common/oauth2/nativeclient?code=[authorization code here]: No such file or directory`
`[1]+    Stopped                                             onedrive -m`

**Comment by LordRahl007** [comment]
Wow, it really was that simple!  Thanks!

**Comment by abraunegg** [comment]
If this is resolved - can you close this issue?
