### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by cmddroid** [skilion/onedrive#35]
Install al dependencies but make dosen't work.
Ubuntu 14.04.4

`make 
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl patch/etc_c_curl.d patch/std_net_curl.d src/config.d src/itemdb.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
/usr/bin/ld: cannot find -lcurl
/usr/bin/ld: cannot find -lsqlite3
collect2: error: ld returned 1 exit status
--- errorlevel 1
make: *** [onedrive] Fehler 1
`

**Comment by mirage8** [comment]
Hi, try this:

`sudo apt-get install libsqlite3-dev libcurl3-dev`

**Comment by dcrystalj** [comment]
this worked for me. 
Should be put in readme. I would say like this:

```
sudo apt-get install libsqlite3-dev libcurl3-dev
sudo apt-get install libsqlite3-dev libcurl3-dev
curl -fsS https://dlang.org/install.sh | bash -s dmd
```

for faster jump in to project

**Comment by alvaromartins** [comment]
Hello,

In Centos 7,
Im having similar issue, but the solution hasnt work, as I already have the libsqlite3 libs installed:

`[root@centos onedrive-master]# yum install libsqlite3-dev libcurl3-dev
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ptisp.pt
 * epel: mirror.uv.es
 * extras: centos.mirror.ptisp.pt
 * nux-dextop: mirror.li.nux.ro
 * rpmforge: mirror.ate.info
 * trinity-r14: ftp.fau.de
 * trinity-r14-noarch: ftp.fau.de
 * updates: centos.mirror.ptisp.pt
No package libsqlite3-dev available.
No package libcurl3-dev available.
Error: Nothing to do
[root@centos onedrive-master]# make
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
/bin/ld: cannot find -lsqlite3
collect2: error: ld returned 1 exit status
--- errorlevel 1
make: *** [onedrive] Error 1
[root@centos onedrive-master]# 
`

**Comment by jlcs-es** [comment]
@alvaromartins I've not used yum in a while, but it seems that you **have not** installed sqlite3, nor curl, as it says:
```No package libsqlite3-dev available.
No package libcurl3-dev available.```
That may mean that there isn't packages with those names in CentOS repos, try to find out alternative names or what repos to add to your system.

**Comment by alvaromartins** [comment]
Yes it true.
Were in the earth are those libs for centos?
Those libs arent updated im guessing, so for CENTOS and RHEL this very usefulll tool wont work.
This note should be addedd to the project.

**Comment by jlcs-es** [comment]
@alvaromartins maybe the libraries aren't supported in CentOS repositories, but I doubt they are not compatible. You could try the hard way, download the curl and sqlite developer packages and install manually, if your centos installation supports rpm it should be easy.
Sadly, making a one wonderfull script that supports every distro is impossible, and if we have to start listing the distros not directly supported, the list would go on and on.

**Comment by alvaromartins** [comment]
unfortunately its not my effort to this that is on the top of the table, but the fact the thoose 2 libs arent available for deploy. Fedora, Centos and Rhel are used not like ubuntu, so its normal to have this issues.

```
`[root@centos ~]# yum list | grep -i curl
curl.x86_64                              7.29.0-25.el7.centos     @anaconda     
libcurl.i686                             7.29.0-25.el7.centos     @base         
libcurl.x86_64                           7.29.0-25.el7.centos     @anaconda     
libcurl-devel.x86_64                     7.29.0-25.el7.centos     @anaconda     
python-pycurl.x86_64                     7.19.0-17.el7            @anaconda     
collectd-curl.x86_64                     5.5.1-2.el7              epel          
collectd-curl_json.x86_64                5.5.1-2.el7              epel          
collectd-curl_xml.x86_64                 5.5.1-2.el7              epel          
curlftpfs.x86_64                         0.9.2-14.el7             epel          
flickcurl.x86_64                         1.25-2.el7.nux           nux-dextop    
flickcurl-debuginfo.x86_64               1.25-2.el7.nux           nux-dextop    
flickcurl-devel.x86_64                   1.25-2.el7.nux           nux-dextop    
fuse-curlftpfs.x86_64                    0.9.1-1.el7.rf           rpmforge      
libcurl-devel.i686                       7.29.0-25.el7.centos     base          
mingw32-curl.noarch                      7.47.0-1.el7             epel          
mingw32-curl-static.noarch               7.47.0-1.el7             epel          
mingw64-curl.noarch                      7.47.0-1.el7             epel          
mingw64-curl-static.noarch               7.47.0-1.el7             epel          
ocaml-curl.x86_64                        0.7.5-2.el7              epel          
ocaml-curl-devel.x86_64                  0.7.5-2.el7              epel          
perl-WWW-Curl.x86_64                     4.15-12.el7              base          
php-pear-Net-Curl.noarch                 1.2.5-10.el7             epel          
uwsgi-alarm-curl.x86_64                  2.0.12-2.el7             epel          
uwsgi-plugin-curl-cron.x86_64            2.0.12-2.el7             epel          
[root@centos ~]# ``
```

Here the list of installed sqlite name related packages:

```

[root@centos ~]# yum list | grep -i sqlite
perl-DBD-SQLite.x86_64                   1.39-3.el7               @anaconda     
sqlite.i686                              3.7.17-8.el7             @base         
sqlite.x86_64                            3.7.17-8.el7             @anaconda     
sqlite-devel.x86_64                      3.7.17-8.el7             @base         
apr-util-sqlite.x86_64                   1.5.2-6.el7              base          
dspam-sqlite3.x86_64                     3.10.2-11.el7            epel          
freeradius-sqlite.x86_64                 3.0.4-6.el7              base          
gnokii-smsd-sqlite.x86_64                0.6.31-12.el7            epel          
golang-googlecode-sqlite-devel.i686      0-0.9.hg74691fb6f837.el7 base          
golang-googlecode-sqlite-devel.x86_64    0-0.9.hg74691fb6f837.el7.centos
libdbi-dbd-sqlite.x86_64                 0.8.3-16.el7             base          
libgda-sqlite.x86_64                     1:5.2.2-7.el7            epel          
libodb-sqlite.x86_64                     2.3.0-1.el7              epel          
libodb-sqlite-devel.x86_64               2.3.0-1.el7              epel          
libsqlite3x.x86_64                       20071018-14.el7.nux      nux-dextop    
libsqlite3x-debuginfo.x86_64             20071018-14.el7.nux      nux-dextop    
libsqlite3x-devel.x86_64                 20071018-14.el7.nux      nux-dextop    
libtqt3-mt-sqlite.x86_64                 3.5.0-14.0.3_1.el7       trinity-r14   
libtqt3-mt-sqlite3.x86_64                3.5.0-14.0.3_1.el7       trinity-r14   
mingw32-sqlite.noarch                    3.8.4.3-1.el7            epel          
mingw32-sqlite-static.noarch             3.8.4.3-1.el7            epel          
mingw64-sqlite.noarch                    3.8.4.3-1.el7            epel          
mingw64-sqlite-static.noarch             3.8.4.3-1.el7            epel          
mono-data-sqlite.x86_64                  2.10.8-9.el7             epel          
opendbx-sqlite.x86_64                    1.4.6-6.el7              epel          
opendbx-sqlite2.x86_64                   1.4.6-6.el7              epel          
owncloud-sqlite.noarch                   8.0.10-1.el7             epel          
pdns-backend-sqlite.x86_64               3.4.8-1.el7              epel          
perl516-perl-DBD-SQLite.x86_64           1.40-2.el7               centos-sclo-rh
poco-sqlite.x86_64                       1.6.1-2.el7              epel          
python-sqlite3dbm.noarch                 0.1.4-6.el7              epel          
rh-perl520-perl-DBD-SQLite.x86_64        1.37-2.el7               centos-sclo-rh
rh-ror41-rubygem-sqlite3.x86_64          1.3.10-1.el7             centos-sclo-rh
rh-ror41-rubygem-sqlite3-doc.noarch      1.3.10-1.el7             centos-sclo-rh
root-sql-sqlite.x86_64                   5.34.32-5.el7            epel          
ror40-rubygem-sqlite3.x86_64             1.3.6-5.el7              centos-sclo-rh
ror40-rubygem-sqlite3-doc.noarch         1.3.6-5.el7              centos-sclo-rh
ruby193-rubygem-sqlite3.x86_64           1.3.6-3.el7              centos-sclo-rh
ruby193-rubygem-sqlite3-doc.noarch       1.3.6-3.el7              centos-sclo-rh
rubygem-sqlite3.x86_64                   1.3.5-4.el7              epel          
rubygem-sqlite3-doc.noarch               1.3.5-4.el7              epel          
soci-sqlite3.x86_64                      3.2.3-1.el7              epel          
soci-sqlite3-devel.x86_64                3.2.3-1.el7              epel          
sqlite-devel.i686                        3.7.17-8.el7             base          
sqlite-doc.noarch                        3.7.17-8.el7             base          
sqlite-tcl.x86_64                        3.7.17-8.el7             base          
sqlite2.x86_64                           2.8.17-17.el7            epel          
sqlite2-devel.x86_64                     2.8.17-17.el7            epel          
sqlite2-tcl.x86_64                       2.8.17-17.el7            epel          
sqlite3-dbf.x86_64                       2011.01.24-3.el7         epel          
uwsgi-plugin-sqlite3.x86_64              2.0.12-2.el7             epel          
vsqlite++.x86_64                         0.3.13-3.el7             epel          
vsqlite++-devel.x86_64                   0.3.13-3.el7             epel          
vsqlite++-doc.noarch                     0.3.13-3.el7             epel          
zabbix20-proxy-sqlite3.x86_64            2.0.16-1.el7             epel          
zabbix22-dbfiles-sqlite3.noarch          2.2.11-1.el7             epel          
zabbix22-proxy-sqlite3.x86_64            2.2.11-1.el7             epel          
[root@centos ~]# yum list | grep -i libsqlite3
libsqlite3x.x86_64                       20071018-14.el7.nux      nux-dextop    
libsqlite3x-debuginfo.x86_64             20071018-14.el7.nux      nux-dextop    
libsqlite3x-devel.x86_64                 20071018-14.el7.nux      nux-dextop    
[root@centos ~]# 

```

**Comment by jlcs-es** [comment]
@alvaromartins if those libraries are compatible or the same with different names, you can download sourcecode of this project, change the references and try to install, or any method that aliases the libraries in your system with the ones used by the project.
If you change the source-code by checking the system available libraries, you can pull-request a fix, so other people don't have that problem.
Or you can wait or add more info untill skillion fixes it. I myself fixed a Makefile issue, but opened an issue for a json bug, until I have time to debug it myself, or skillion fixes it.

**Comment by alvaromartins** [comment]
Im goin to investigate a little more. I dont think I can edit the source code with success, but I can try.
Thanks for your help. 
We will wait for @skilion  for an update.

**Comment by JPtheJP** [comment]
OK, I figured it out.
I am working on Fedora 23, solution should apply to CentOS, please report.
The failure comes from the library being searched. Digging around the error gave me this link: http://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary and look for solution #2 (161 or above rating).
Here, if we do a: ld -lcurl -verbose or a ld -lsqlite3 -verbose we see that it parses the /usr/lib64/ then /usr/lib/ folders and don't find a match for libcurl.so and libsqlite3.so. Because they don't exist in /usr/lib64 (assuming you use x64 arch as I do).

Fix from there becomes easy:

'sudo ln -s /usr/lib64/libcurl.so.4.3.0 /usr/lib64/libcurl.so
'sudo ln -s /usr/lib64/libsqlite3.so.0.8.6 /usr/lib64/libsqlite3.so

Then you can do a make.

**Comment by Scimmia22** [comment]
Those symlinks should be present in the -devel package.

**Comment by karlney** [comment]
Hi, in the readme says  to install

`sudo apt-get install libcurl-dev`

but for Linux mint 18 (based on ubuntu 16.04) you need to install

`sudo apt-get install libcurl3-dev`

then I could run make successfully.

**Comment by skilion** [comment]
The README has been improved

**Comment by zakir8** [comment]
I was getting an Error 127 when trying to run the command make. We have to be sure to do "source ~/dlang/dmd-2.075.0/activate" before doing make or sudo make install.

I think this will be really helpful to have in ReadMe for someone who doesn't know D language.
