### ISSUE TITLE
Ubuntu dmd dependency installation was failing

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [skilion/onedrive#350]
`jigao@jigao-CW35S:~$ cd onedrive/
jigao@jigao-CW35S:~/onedrive$ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127
jigao@jigao-CW35S:~/onedrive$ sudo make install
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127
`

**Comment by cakebytheoceanLuo** [comment]
jigao@jigao-CW35S:~$ cd onedrive/
jigao@jigao-CW35S:~/onedrive$ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127
jigao@jigao-CW35S:~/onedrive$ sudo make install
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127

**Comment by cakebytheoceanLuo** [comment]
I am using Ubuntu 17.10.
But i can't install the dmd.


jigao@jigao-CW35S:~$ sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
--2018-05-08 12:24:57--  http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list
Resolving master.dl.sourceforge.net (master.dl.sourceforge.net)... 216.105.38.12
Connecting to master.dl.sourceforge.net (master.dl.sourceforge.net)|216.105.38.12|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 85 [application/octet-stream]
Saving to: ‘/etc/apt/sources.list.d/d-apt.list’

/etc/apt/sources.li 100%[===================>]      85  --.-KB/s    in 0s      

2018-05-08 12:24:58 (14,7 MB/s) - ‘/etc/apt/sources.list.d/d-apt.list’ saved [85/85]

jigao@jigao-CW35S:~$ sudo apt-get update && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
Hit:1 http://de.archive.ubuntu.com/ubuntu artful InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu artful-updates InRelease             
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                   
Ign:4 https://ftp.fau.de/cran/bin/linux/ubuntu artful/ InRelease               
Hit:5 http://de.archive.ubuntu.com/ubuntu artful-backports InRelease           
Hit:6 https://ftp.fau.de/cran/bin/linux/ubuntu artful/ Release                 
Ign:7 http://ppa.launchpad.net/fsqcds/goldendict/ubuntu artful InRelease       
Hit:8 http://security.ubuntu.com/ubuntu artful-security InRelease              
Hit:9 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:10 http://ppa.launchpad.net/git-core/ppa/ubuntu artful InRelease           
Hit:11 http://ppa.launchpad.net/webupd8team/java/ubuntu artful InRelease       
0% [1 InRelease gpgv 237 kB] [Waiting for headers] [Connecting to archive.ubunt^Err:12 http://ppa.launchpad.net/fsqcds/goldendict/ubuntu artful Release        
  404  Not Found
Hit:14 http://archive.ubuntukylin.com:10006/ubuntukylin xenial InRelease       
0% [Connecting to downloads.sourceforge.net (216.105.38.13)] [Release.gpg gpgv ^Get:13 http://master.dl.sourceforge.net/project/d-apt d-apt InRelease [1.027 B]
Err:13 http://master.dl.sourceforge.net/project/d-apt d-apt InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done                                    
E: The repository 'http://ppa.launchpad.net/fsqcds/goldendict/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
jigao@jigao-CW35S:~$ sudo apt-get update && sudo apt-get install dmd-compiler dub
Hit:1 http://de.archive.ubuntu.com/ubuntu artful InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu artful-updates InRelease             
Hit:3 http://de.archive.ubuntu.com/ubuntu artful-backports InRelease           
Ign:4 https://ftp.fau.de/cran/bin/linux/ubuntu artful/ InRelease               
Ign:5 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:6 http://security.ubuntu.com/ubuntu artful-security InRelease              
Ign:7 http://ppa.launchpad.net/fsqcds/goldendict/ubuntu artful InRelease       
Hit:8 https://ftp.fau.de/cran/bin/linux/ubuntu artful/ Release                 
Hit:9 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:10 http://ppa.launchpad.net/git-core/ppa/ubuntu artful InRelease           
Hit:11 http://ppa.launchpad.net/webupd8team/java/ubuntu artful InRelease       
Err:12 http://ppa.launchpad.net/fsqcds/goldendict/ubuntu artful Release        
  404  Not Found
Get:13 http://master.dl.sourceforge.net/project/d-apt d-apt InRelease [4.878 B]
Hit:14 http://archive.ubuntukylin.com:10006/ubuntukylin xenial InRelease       
Err:13 http://master.dl.sourceforge.net/project/d-apt d-apt InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBCF975E5BA24D5E
Reading package lists... Done 
E: The repository 'http://ppa.launchpad.net/fsqcds/goldendict/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://master.dl.sourceforge.net/project/d-apt d-apt InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBCF975E5BA24D5E
E: The repository 'http://master.dl.sourceforge.net/project/d-apt d-apt InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.


How can i fix it?

**Comment by abraunegg** [comment]
Go here - https://dlang.org/download.html or speak to your distribution maintainers.

**Comment by cakebytheoceanLuo** [comment]
THX
