### ISSUE TITLE
386 violacion de segmento segment fault when command onedrive

### ISSUE THREAD

**Issue by mikevt** [skilion/onedrive#353]
I have installed free onedirive in Debian x64 adnd it works fine, but in Lubunti 386 after installation when you call onedrive command it gives a segment fault error 'core'. I am not able to fix it. Anybody can helpme?

**Comment by abraunegg** [comment]
@mikevt 

I have not tested anything in i386 platforms at all. I would say at the moment that is is unsupported / untested.

Did you compile this yourself on the platform or did you use a package?

**Comment by mikevt** [comment]
I used the package built but I wonder if I could modify the make using the
instruction dmd -n32.

Regards

**Comment by abraunegg** [comment]
Feel free to clone the repository and try to build for a 32bit platform and provide feedback as to your success.

**Comment by abraunegg** [comment]
@mikevt 
Any Update?

**Comment by mikevt** [comment]
I have not had tone so far. I ll keep you posted.

**Comment by abraunegg** [comment]
@mikevt 
Any update?

**Comment by abraunegg** [comment]
@mikevt 
Any update?

**Comment by abraunegg** [comment]
Potentially same issue as #336 

@mikevt 
What is the reason for running a 32Bit / x86_64 platform?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by abraunegg** [comment]
This is the fix for Debian i386 / i686 systems:
```
mkdir ldc && cd ldc
wget http://ftp.us.debian.org/debian/pool/main/l/ldc/ldc_1.8.0-3_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/l/ldc/libphobos2-ldc-shared-dev_1.8.0-3_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/l/ldc/libphobos2-ldc-shared78_1.8.0-3_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/l/llvm-toolchain-5.0/libllvm5.0_5.0.1-2~bpo9+1_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/n/ncurses/libtinfo6_6.1+20180714-1_i386.deb
sudo dpkg -i ./*.deb
```
then to build:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
make make DC=/usr/bin/ldmd2
sudo make install
```
