### ISSUE TITLE
Ubuntu 18.04  E: Unable to locate package d-apt-keyring

### ISSUE THREAD

**Issue by Erurainon** [skilion/onedrive#354]
sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package d-apt-keyring

**Comment by abraunegg** [comment]
To resolve your issue, please try the following:
```
sudo apt install libcurl4-openssl-dev
sudo apt install libsqlite3-dev
curl -fsS https://dlang.org/install.sh | bash -s dmd
```

The original author appears to have also abandoned this code, all new work & bugfixes is being done here:
```
https://github.com/abraunegg/onedrive
```

Once you have DMD installed, there are 2 ways to get the latest code:

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
make install
```

Option 2:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

**Comment by abraunegg** [comment]
@Erurainon 
Any update?

**Comment by abraunegg** [comment]
@Erurainon 
Any update?

**Comment by abraunegg** [comment]
@Erurainon 
Any update?

**Comment by RubenMaier** [comment]
@abraunegg when i use "sudo make" the console show:

make: *** No target was specified and no makefile was found. High.

**Comment by abraunegg** [comment]
@RubenMaier 
That sounds to me more like a local build problem or that you did not cd into the onedrive directory that was created from the git process.

**Comment by abraunegg** [comment]
@Erurainon
Any update?

**Comment by mcintyrechris** [comment]
You don't want to use `sudo` for `make`, just `sudo make install`. Try just `make` then `make install` after cloning. You may also have to activate the D compiler environment using `source [your d compliler location]` if you installed the D compiler to a user directory.

**Comment by EnduranceCode** [comment]
To solve the "*E: Unable to locate package d-apt-keyring*", I've download the Debina/Ubuntu package from the [D Programming Language](https://dlang.org/download.html#dmd) and I've installed it with the GDebi Package Installer.
I was then able to install Skilion Onedrive from this repo.

**Comment by abraunegg** [comment]
@EnduranceCode 
Please note that the code from this repo is not maintained. You need to use #314 or my branch to get a whole lot of fixes and enhancements.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by skilion** [comment]
Follow https://dlang.org/download.html to install DMD on Ubuntu 18

**Comment by castigohd** [comment]
I was getting the same error while trying to install Onedrive client on Ubuntu 19.10 (the one from [this website](https://www.maketecheasier.com/sync-onedrive-linux/) ). After some time I wen't back to the website to read everythig again and I noticed that after all I didn't even need to run that command because I am using a Ubuntu version 18.04+. So I didnt' need to run that command after all. all I really needed was `sudo snap install --classic dmd && sudo snap install --classic dub` for the afore mentioned reason.

ftr I comment this just in case someone else got the error while trying to do the same thing as I was

**Comment by abraunegg** [comment]
@castigohd
The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

Specifically, refer to this to install - https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md
