### ISSUE TITLE
OneDrive for Business authorisation problem

### ISSUE THREAD

**Issue by Eddles999** [skilion/onedrive#358]
Hi all,

Am using OneDrive for Business and in issue number 244, someone recommended following the instructions here:

`git clone https://github.com/abraunegg/onedrive.git
make
make install`

Seems to be working better than before, however when I try to authorise OneDrive, I take the URL that was given and put it in a web browser - entered my username and password which got in OK, however after the username and password part, the web server doesn't give me anything - it's just a blank screen, no response uri shown?

Many thanks for help!

**Comment by abraunegg** [comment]
Can you post an image of the issue your seeing?

The browser should have a URI and that is what you use to return to the application

**Comment by abraunegg** [comment]
@Eddles999 
Any update?

**Comment by mccarthyryanc** [comment]
I'm having the same issue. Trying to sync with OneDrive for Business and getting a blank page after following the link during the first run. Checking the javascript console I did see this:
![selection_137](https://user-images.githubusercontent.com/997120/40447620-0d3bac3a-5e88-11e8-87fd-22a2c7c2e621.png)

**System Specs:**
Ubuntu 16.04
link opened in Firefox 60.0

**Comment by mccarthyryanc** [comment]
Oh! That worked for me. Thanks!

**Comment by abraunegg** [comment]
@Eddles999 
Any update?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
