### ISSUE TITLE
[Ubuntu 18.04] std.net.curl.CurlException@std/net/curl.d(4392): SSL connect error on handle

### ISSUE THREAD

**Issue by Djacomo** [skilion/onedrive#359]
Checkout latest git repository, installed dependencies and get the following errors:

$ /usr/local/bin/onedrive -v -m
Loading config ...
No config file found, using defaults
Initializing the OneDrive API ...
Authorize this app visiting:
.. REMOVED ...
Enter the response uri: https://login... REVOVED....

**std.net.curl.CurlException@std/net/curl.d(4392): SSL connect error on handle** 
----------------
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x8cfe77ec]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x8d03fd16]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x8d03fb11]

**Comment by abraunegg** [comment]
> Checkout latest git repository, installed dependencies and get the following errors

This codebase is not maintained by the original author - it's not the latest code.

To get the latest code:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
make
sudo make install
```

Regarding the libcurl error - what development versions of curl and ssl packages are installed?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
