### ISSUE TITLE
Tray icon and status/configuration using a GUI

### ISSUE THREAD

**Issue by andrebrait** [skilion/onedrive#36]
Hi there,

First of all, sorry if this is not the place to post a feature request/idea. I tried to find one. Failed at that, but thought this would be a nice place, if people want to contribute. 

I really, _really_ like your client. It has worked very well (except for one or two errors). The only thing that's kinda missing is a GUI for it, both for configuration and as status indicator. A simples GUI for the former and a tray icon for the latter (much like it is in Windows, or Dropbox for Linux) would make it friendlier to the user and simpler to know what's happening just by glancing at the system tray. 

Do you think it's doable? I don't know D or how to build a GUI using it.

**Comment by telmer6** [comment]
This would be fantastic. Eschewing a GUI, at least having a tray icon for status would be great.

**Comment by Modelmat** [comment]
I agree! A tray icon would be lovely.
@telmer6 I can help you make up a basic Electron-based interface, that runs the commands. Electron also supports tray icon. [This](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) can be used to run the commands - we only really need something basic.

**Comment by Scimmia22** [comment]
Something basic, but you want to use a full blown web browser (chromium/electron) to do it?

**Comment by Modelmat** [comment]
@Scimmia22 Why not? If we really needed the GUI, @skilion would make one, however, it is not really required. Running electron is not that much of a resource hog - Discord is far much bigger than this would ever be, and it uses so little CPU & RAM.

**Comment by thomasfedb** [comment]
@Modelmat have you considered making a GUI as a separate project to this? Seems fairly simple to have a little app that spits out the required config files and runs `systemctl --user` commands to start/stop and `journalctl --user` to display logs. I don't see why it would be need to be directly part of this project however.

**Comment by Modelmat** [comment]
Maybe. I might try one day! (I will have to learn a lot - I can just barely write HTML & JS)

**Comment by coxackie** [comment]
This would be really awesome - at least notifications to be sent so that one can know when uploads/downloads have finished. I do not suppose it would be an immense amount of work - unfortunately, I cannot do it, but I am sure this will increase the popularity of the package by volumes.

**Comment by thomasfedb** [comment]
This is actually rather a lot of work.

**Comment by Modelmat** [comment]
It probably will be a lot of work; something I am unable to spent lots of time on due to learning commitments.

**Comment by coxackie** [comment]
oh... I did not realise pushing notifications was complicated. Pardon my ignorance. Well, too bad, it would have lead to a really positive user experience. At any rate, it is awesome and many thanks to the developer for the amazing work!

**Comment by erenoglu** [comment]
I agree on this. I just noticed when I switched to Windows that my files were not actually syncing, as I had filenames which didn't conform to Windows standards (thanks Evolution for saving attachments like this), which eventually crashed and kept crashing Onedrive, without me knowing about it.
I wish there was an indicator at least to show Onedrive is running or not.

**Comment by abraunegg** [comment]
There is an attempt here (https://github.com/zachbr/onedrive-z/commit/68c4851e93c37bbb597e471c63700ae964a69c92) that looks like it sends a notification to the desktop. I am unsure how complete this is.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by benoitlavorata** [comment]
Hello everyone, I just started working on a (very) simple interface built on electron (using node-red dashboard), and based on skilion/onedrive. 

It uses the commands described in the readme. I will likely add the possibility to edit the config (selective sync) and a system tray icon to start/stop/latest action/up-down bandwith.

https://gitlab.com/benoit.lavorata/onedrive-electron-gui

**Comment by coxackie** [comment]
@benoitlavorata you may also want to check
https://github.com/abraunegg/onedrive/

**Comment by benoitlavorata** [comment]
Thanks @coxackie I will take a look.
