### ISSUE TITLE
Feature request: webhook for OneDrive updates

### ISSUE THREAD

**Issue by Lyncredible** [skilion/onedrive#360]
OneDrive allows apps to register webhooks to listen for updates: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/subscription_post_subscriptions.

It would be nice to leverage this to enable faster pull when running as a daemon.

To implement this, I think the changes are:
- Register webhook with a configurable endpoint (user may want to run this behind nginx, for example)
- Configurable `client_id` so that webhooks don't cross fire.
- Listen to incoming webhooks and trigger pull.

**Comment by abraunegg** [comment]
This codebase appears to have been abandoned by the original author. Feel free to submit this as a FR against my branch.

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by Lyncredible** [comment]
Will do when I get some free cycles.
