### ISSUE TITLE
How to initially setup multiple accounts

### ISSUE THREAD

**Issue by andrewproctor** [skilion/onedrive#361]
Hi!  I would like to use my OneDrive for Business and Personal OneDrive accounts.  I see in the instructions this can be accomodated by using `--confdir=`, but this appears to refer to the stage at which you specify which OneDrive accounts to monitor for resyncing.

So far, I haven't been able to perform an initial sync of the two directories.  I tried to create two config directories first by initially setup them up as individual directories (using `onedrive` to get the refresh token and setup a config folder,  then setting up my selective sync and sync directories), then editing these directory names to be `OneDrive-Work` and `OneDrive-Personal`.  

At this point though, I can't get it to perform a sync correctly.  If I use `onedrive --resync`, it asks me to authorize the app (ie ignoring the config folders I created).  If I try to adlib a little and say e.g.  `onedrive --resync  --confdir="~/.config/OneDrive-Personal"`, it doesn't do anything.

How do I initially create and sync multiple accounts?

**Comment by abraunegg** [comment]
Hi Andrew,

This code source is not the latest as it appears to have been abandoned by the original author. To get the latest code:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
make
sudo make install
```
To see all the fixes that the different version fixes see #314.

So to tackle your original question - keeping the terminal window open when using '-m' for monitor mode. This is correct if your testing / trying the application out. For a more persistent method use the service files to start / stop the applicable onedrive daemon which will run the application in monitor mode until the service is stopped.

In regards to using 2 different accounts you need to authorise each OneDrive Account separately. Typically, the account information is stored in `~/.config/onedrive`, however when you use the `--confdir=` directive this places that configuration data in that specified location. When running onedrive for each account you need to specify which `confdir` you want to use. 

Steps I would try are the following (assuming here using the latest code base):

1. `onedrive --synchronize --verbose --confdir="~/.config/OneDrive-Personal"`
2. `onedrive --synchronize --verbose --confdir="~/.config/OneDrive-Business"`

Both these commands will sync data from `~/OneDrive` to the account when authorised.

If there is any issue or error - the verbose output will help assist and identify where things are going wrong.

**Comment by andrewproctor** [comment]
That solved it for me, thanks!

**Comment by abraunegg** [comment]
Great - if you can close this case then that would be awesome
