### ISSUE TITLE
Multiple versions of file shown on website after single upload

### ISSUE THREAD

**Issue by jlarkin-oxford** [skilion/onedrive#362]
Hi, 

I'm not sure if this is a bug or me being an idiot. With that out of the way, the problem is that the OneDrive web interface shows multiple versions for every file that I upload, meaning that each file consumes multiples of its own size from my storage allocation. 

Some background:
onedrive --version:  onedrive v1.1.2-1-ge8d3a26
OS: Debian 9.4 (Stretch)
For testing, I deleted all files from my account on the OneDrive servers, emptied the recycle bin and the second recycle bin. Storage Metrics page shows 0 bytes usage. I deleted my local items.sqlite3* files. 

Command ran: onedrive --verbose --local-first --monitor --synchronize

Sequence of events:
1) A file is recognised as absent from the OneDrive account and is uploaded. 
2) The storage metrics page shows the file size for this file steadily increasing during the upload (to 100MB, the actual file size). The file has a "~tmp" prefix as expected.
3) During the upload, the Version History for the file shows one version with a timestamp of the time of the upload.
3) The file finishes uploading, the filename changes to remove the "~tmp" prefix.
4) The file storage metrics summary size continues to increase, eventually stopping at 200MB. 
5) The Version History for the file now shows two versions, one with a timestamp of upload and one with a timestamp when the file was first created. 

The upshot of this is that even if my files total, say 1GB, my storage allocation is reduced by 2GB. If I manually download and check each "version", they are identical (md5sum). I suppose the intended outcome is that there is one version, which has a modification date equal to when the file was last modified, not when it was uploaded. 

A short section of the log file is shown here: 
[Onedrive_log.txt](https://github.com/skilion/onedrive/files/2031215/Onedrive_log.txt)

I have also screen-grabbed a short video showing the problem. Keep looking at the file 'duplicati-b167be4f012754240b8679b9b81a9f6fa.dblock.zip.aes' which I highlight at various points. 
[video_example.zip](https://github.com/skilion/onedrive/files/2031216/video_example.zip)

Many thanks in advance, 
James

**Comment by abraunegg** [comment]
Thanks for the great detail behind this issue - any chance you can submit this against my branch rather than this branch so I track and handle better?

It sounds like what is happening is that when the current code base updates the timestamps, that 'change' is causing a version of the file .. will have to do some testing on that.

**Comment by abraunegg** [comment]
https://github.com/abraunegg/onedrive

**Comment by jlarkin-oxford** [comment]
Thanks, found that earlier but no place to submit issues that I can see. 

![noissues](https://user-images.githubusercontent.com/33656664/40441007-9b5090ec-5eb7-11e8-9665-40e98b091476.png)

**Comment by abraunegg** [comment]
Try now - I had to enable the issues function

**Comment by jlarkin-oxford** [comment]
Perfect, thanks! I've duplicated the issue there (https://github.com/abraunegg/onedrive/issues/2).

**Comment by abraunegg** [comment]
thanks - best close the issue here as the entire skilion codebase has been abandoned
