### ISSUE TITLE
Feauture request: Sync file from sharepoint?

### ISSUE THREAD

**Issue by lorenzosu** [skilion/onedrive#363]
So now our team is using Teams, which in turn uses files form Sharepoint, where you can ask to share files and this would open the OneDrive Windows or Mac client. I'm wondering if/how similar funcionality could be obtained, e.g. by creating (locally) a new subdirectory with that share?

**Comment by abraunegg** [comment]
Can you submit this against my branch rather than here for better tracking ?

**Comment by lorenzosu** [comment]
How? This is really a bit confusing as your fork doesn't allow to post issues...

**Comment by abraunegg** [comment]
you may want to double check that :)

**Comment by lorenzosu** [comment]
It is now

**Comment by abraunegg** [comment]
if you can close this case that would be great
