### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by MS047** [skilion/onedrive#364]
A "database is locked" issue keeps happening to me, which suggests that there is an external soft trying to access my database. Though no obvious browser has OneDrive online open. Even if it did, this behavior would deserve a fix as well. Could be an app on a smartphone syncing in the background, maybe.

Here is my log for the command `onedrive -m --debug-https --verbose`, from the point when I add a new directory to the ~/onedrive directory (see[ this text file](https://drive.google.com/open?id=1ev5G7o-28SRkueq1s-cVDqGBEhiTICSg), the log is too long).

**Comment by abraunegg** [comment]
Can you close this case and open it here:

https://github.com/abraunegg/onedrive
