### ISSUE TITLE
HTTP request returned status code 412 (Precondition Failed)

### ISSUE THREAD

**Issue by MrJinx2015** [skilion/onedrive#366]
While uploading a large amount of files, I get this message:

`HTTP request returned status code 412 (Precondition Failed)
{
    "error": {
        "code": "resourceModified",
        "innerError": {
            "date": "2018-05-29T16:26:07",
            "request-id": "xxxxxx"
        },
        "message": "ETag does not match current item's value"
    }
}
`

Sometimes it continues syncing and sometimes it just crashes with this message:
`src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x57a874]
src/onedrive.d:322 std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0x57a93a]
src/onedrive.d:166 std.json.JSONValue onedrive.OneDriveApi.updateById(const(char)[], const(char)[], std.json.JSONValue, const(char)[]) [0x579363]
src/sync.d:652 void sync.SyncEngine.uploadLastModifiedTime(const(char)[], const(char)[], const(char)[], std.datetime.systime.SysTime) [0x58581b]
src/sync.d:627 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x585554]
src/sync.d:592 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x584fd0]
src/sync.d:587 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x584ef3]
src/sync.d:587 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x584ef3]
src/sync.d:587 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x584ef3]
src/sync.d:587 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x584ef3]
src/sync.d:587 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x584ef3]
src/sync.d:587 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x584ef3]
src/sync.d:443 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x584335]
src/main.d:195 void main.performSync(sync.SyncEngine) [0x571c0f]
src/main.d:121 _Dmain [0x57173f]
`

Any idea what could be wrong?

**Comment by MrJinx2015** [comment]
Many thanks! I installed your branch and everything seems to be working fine now.

**Comment by abraunegg** [comment]
Great - thanks for the feedback.

Please can you close this case given your issue is resolved.
