### ISSUE TITLE
Configure with environment variables

### ISSUE THREAD

**Issue by davidbarratt** [skilion/onedrive#367]
It would be really helpful (when used in a docker container especially) to be able to configure this program with environment variables rather than a config file.

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed.

If you wish to use the latest code you need to use the code from here: https://github.com/abraunegg/onedrive

If you have any issues submit your issue against my branch.
