### ISSUE TITLE
Create an official Docker image

### ISSUE THREAD

**Issue by davidbarratt** [skilion/onedrive#368]
There seems to be several docker images for this program that are severaly out of date. It would be awesome if there was an official `Dockerfile` and and docker image on docker hub.

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed.

If you wish yo use the latest code you need to use the code from here: https://github.com/abraunegg/onedrive

If you have any issues submit your issue against my branch.
