### ISSUE TITLE
Add support for ARM processors

### ISSUE THREAD

**Issue by Boia11** [skilion/onedrive#369]
It's possible to convert from DMD to GDC (or LDC) for support:

- armhf
- arm64 (aarch64)

[https://wiki.dlang.org/Compilers#Comparison](https://wiki.dlang.org/Compilers#Comparison)

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by Boia11** [comment]
@abraunegg Thanks for info!

**Comment by skilion** [comment]
If you have LDC installed just set the compiler to `ldmd2` (ex: `make DC=ldmd2`)
