### ISSUE TITLE
HTTP request returned status code 400 (Bad Request)

### ISSUE THREAD

**Issue by lifestronaut** [skilion/onedrive#37]
When running onedrive for the first time, I get the following error.  I'm using the onedrive package from the AUR in Archlinux.

[lifestronaut@pepper ~]$ onedrive
## std.net.curl.CurlException@patch/std_net_curl.d(1006): HTTP request returned status code 400 (Bad Request)

??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x57e452]
??:? char[] std.net.curl._basicHTTP!(char)._basicHTTP(const(char)[], const(void)[], std.net.curl.HTTP) [0x5bc812]
??:? char[] std.net.curl.post!(char, char).post(const(char)[], const(char)[], std.net.curl.HTTP) [0x5bdbdc]
??:? void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x5cb4c2]
??:? _Dmain [0x5c4b67]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5df826]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5df764]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5df7e2]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5df764]
??:? _d_run_main [0x5df6c1]
??:? main [0x5c71d5]
??:? __libc_start_main [0x75b6970f]

**Comment by skilion** [comment]
Looks like the app was not authorized to access your onedrive. Since ad4e910 it will ask to be authorized again.
