### ISSUE TITLE
OneDrive for business - Admin Consent

### ISSUE THREAD

**Issue by phillip-from-oz** [skilion/onedrive#370]
Hi,
Can you please tell me if you support "Admin Consent" as described:
https://docs.microsoft.com/en-au/azure/active-directory/develop/active-directory-devhowto-multi-tenant-overview#understanding-user-and-admin-consent
The reason that I need this is that I have thousands of accounts under our OneDrive for business, so the administrator will  give admin consen to a set of users

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
