### ISSUE TITLE
cannot delete files on onedrive?

### ISSUE THREAD

**Issue by starriddle** [skilion/onedrive#371]
I deleted local directories and files at noon, but they were still exist on remote several hours later

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
