### ISSUE TITLE
I/O problems using cron command

### ISSUE THREAD

**Issue by shughesphotons** [skilion/onedrive#374]
Hi,

Are there any known issues with using cron to execute onedrive, and can anyone help with the issue below?

Namely, onedrive --resync seems to have problem under cron, returning:

sqlite.SqliteException@src/sqlite.d(6attempt to write a readonly database
sqlite.SqliteException@src/sqlite.d(181): attempt to write a readonly database
----------------
src/sqlite.d:22 void sqlite.Statement.reset() [0x5948e1]
src/sqlite.d:162 void sqlite.Statement.bind(int, const(char)[]) [0x594797]
src/itemdb.d:196 void itemdb.ItemDatabase.bindItem(ref const(itemdb.Item), ref sqlite.Statement) [0x58243b]
src/itemdb.d:113 void itemdb.ItemDatabase.upsert(ref const(itemdb.Item)) [0x5819e1]
src/sync.d:204 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x595b14]
src/sync.d:177 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x5958af]
src/sync.d:146 void sync.SyncEngine.applyDifferences() [0x59558d]
src/main.d:193 void main.performSync(sync.SyncEngine) [0x5845a3]
src/main.d:121 _Dmain [0x5840ff]

the cron command is (for testing):

* * * * *  /usr/local/bin/onedrive --resync > onedrive3.log 2>&1

Tested same problem on Ubuntu 14 and 16 (16.04)

Again, outside of cron, it works perfectly, so is installed correctly and works fine otherwise.

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by shughesphotons** [comment]
Great thanks,  this newer version seems to work no problem with cron - sorry for not noticing this earlier
