### ISSUE TITLE
Log in with business account

### ISSUE THREAD

**Issue by matilarab** [skilion/onedrive#375]
Hi, I'm trying to log in using a business account. I can log in with the account with the provided link, but i just get redirected to a blank page of microsoft, with and invalid uri.

I looked around in the other questions and also changed the authorization address from:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

to:
https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/organizations/oauth2/nativeclient

and when i log in here this error message appears:
"Message: AADSTS50001: The application named https://graph.microsoft.com was not found in the tenant named 62e7947c-180e-41e4-84c3-46f162be4dcb. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant."

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
