### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by liger1978** [skilion/onedrive#376]
Hi

Has this project been abandoned? Thanks.

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by liger1978** [comment]
@abraunegg Great news that someone has adopted this project.  Many thanks!  I will use your fork for the CentOS 7 RPM that I maintain.
