### ISSUE TITLE
skip_dir not working

### ISSUE THREAD

**Issue by age6racer** [skilion/onedrive#377]
Hi, 

I've read a handful of other pages on this and most people seem able to get it working eventually but I have tried all the suggested methods and still cannot get skip_dir to work. At first I thought it was due to having spaces in the directory names but I am also having the problem with directories with no spaces.

I have added the following to my config file.

skip_dir = ".*|Attachments|Archive"

But the directories Attachments and Archive are still downloading.

I have tried creating multiple skip_dir lines with individual directories in them but this doesn't help.

What am I doing wrong?

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by skilion** [comment]
skip_dir is not a working configuration option. You should be using [selective sync](https://github.com/skilion/onedrive#selective-sync) instead.

**Comment by abraunegg** [comment]
@age6racer 
This feature is now available in my fork. Refer to https://github.com/abraunegg/onedrive/issues/123#issuecomment-466696653 for further details
