### ISSUE TITLE
Command make encounters error 127

### ISSUE THREAD

**Issue by nahmias22** [skilion/onedrive#378]
Hi,
I'm trying to install your software on ubuntu 18.07. I have tried installing some of the dependencies but I receive some peculiar responses for the last two seen below (but I am not sure if this is the cause):

:~$ sudo apt-get update && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
Hit:1 http://il.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://il.archive.ubuntu.com/ubuntu bionic-updates InRelease                                  
Hit:3 http://il.archive.ubuntu.com/ubuntu bionic-backports InRelease                                
Hit:4 http://ppa.launchpad.net/maateen/battery-monitor/ubuntu bionic InRelease                      
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease                                   
Hit:6 http://archive.canonical.com bionic InRelease                                                 
Get:7 http://master.dl.sourceforge.net/project/d-apt d-apt InRelease [4,879 B]                      
Err:7 http://master.dl.sourceforge.net/project/d-apt d-apt InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBCF975E5BA24D5E
Reading package lists... Done
W: GPG error: http://master.dl.sourceforge.net/project/d-apt d-apt InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBCF975E5BA24D5E
E: The repository 'http://master.dl.sourceforge.net/project/d-apt d-apt InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
:~$ sudo apt-get update && sudo apt-get install dmd-compiler dub
Hit:1 http://il.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://il.archive.ubuntu.com/ubuntu bionic-updates InRelease                                  
Hit:3 http://il.archive.ubuntu.com/ubuntu bionic-backports InRelease                                
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                   
Hit:5 http://ppa.launchpad.net/maateen/battery-monitor/ubuntu bionic InRelease                      
Hit:6 http://archive.canonical.com bionic InRelease                                                 
Get:7 http://master.dl.sourceforge.net/project/d-apt d-apt InRelease [1,027 B]         
Err:7 http://master.dl.sourceforge.net/project/d-apt d-apt InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done        
E: Failed to fetch http://master.dl.sourceforge.net/project/d-apt/dists/d-apt/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://master.dl.sourceforge.net/project/d-apt d-apt InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

So after I have copied your github repository using git and cd into the directory I try running the make command and receive the following error:
:~/onedrive$ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127

Do you have any advice on how to resolve these issues?

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by skilion** [comment]
The dmd command is not installed on your system. Follow the instructions at https://dlang.org/download.html to install it

**Comment by arnold237worker** [comment]
f
