### ISSUE TITLE
onedrive synching too much (invisible folders)

### ISSUE THREAD

**Issue by hgrebler** [skilion/onedrive#379]
I have been allocated 5 TB on MOfB (MS OneDrive for Business). I have decided to use some of that for backup (in a directory (folder) called, imaginatively, BACKUPS). I don't have anywhere near that much space on any of my PCs, so I mark the BACKUPS folder (and possibly others) not "visible":

![mofb_choose_folders](https://user-images.githubusercontent.com/22044134/41890280-379e93ea-7952-11e8-9f88-49ccd8256dee.png)

However, the last time I invoked _onedrive_, it started downloading the BACKUPS folder and its contents.

Am I doing something wrong? Or can _onedrive_ be taught to honour the visibility of folders?

Thanks.

**Comment by abraunegg** [comment]
Essentially what you want to look at using is skip_dir, however this option appears to not work as intended - see #377 

Additionally, the 'skilion' code appears to have been abandoned (though skilion closed 377 ..) by the original author and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by Rondom** [comment]
> Additionally, the 'skilion' code appears to have been abandoned (though skilion closed 377 ..) by the original author and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

Sorry to hijack this issue, but have you two (@skilion, @abraunegg) tried to contact each other? I think it would be nice to have some official blessing and make @abraunegg's fork "official" -- maybe by creating a GitHub-organization for the project with @abraunegg (and @skilion if they are still interested) as owners.

**Comment by abraunegg** [comment]
I have attempted contact by responding to most things - as the github account has no visible email address associated with it I would have dropped an email to them .. certainly if I read in an issue that people think the project has been abandoned I would respond with either yes, sorry or no - let's work on this or something else ..

**Comment by skilion** [comment]
Through [selective sync](https://github.com/skilion/onedrive#selective-sync) you can sync only the folders you are interested in.
