### ISSUE TITLE
How to upload specific directory/file 

### ISSUE THREAD

**Issue by ttpro1995** [skilion/onedrive#381]
I don't want to sync everything, I just want to upload (or Backup) 
How should I do that 
Is there a command to upload specific directory/file ?

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by skilion** [comment]
You can use [selective sync](https://github.com/skilion/onedrive#selective-sync).
