### ISSUE TITLE
Can I choose difference directory for local vs Onedrive

### ISSUE THREAD

**Issue by ttpro1995** [skilion/onedrive#382]
For example, on One drive, I have 2 folder:  PC,  Laptop
I want to sync Home  of my PC to PC folder on Onedrive, and sync Home of my Laptop to Laptop folder on Onedrive.

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by skilion** [comment]
This specific functionality of mapping remote directories to different local directories is not supported
