### ISSUE TITLE
cannot find uri

### ISSUE THREAD

**Issue by achimbenoit** [skilion/onedrive#383]
anything did work well during installation, 
but after stating ./onedrive  
and of course copying the URL (which works well, when i just copy it to e browser manually)
which was shown 
I've got the messages
1. Invalid uri
2. Could not initialize the OneDrive API

What did i do wrong?

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by skilion** [comment]
Not enough info about the issue
