### ISSUE TITLE
Makefile Error

### ISSUE THREAD

**Issue by TheKingOfCats** [skilion/onedrive#384]
I am trying to install the onedrive client. When I do `make` inside of onedrive_code, I get:
`dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127`
I get this on Ubuntu 18.04 LTS (Bionic Beaver)

**Comment by abraunegg** [comment]
You have not activated DMD - refer to https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions

Additionally, the 'skilion' code appears to have been abandoned by the original author and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
