### ISSUE TITLE
Crash with `lastModifiedDateTime`

### ISSUE THREAD

**Issue by wagh** [skilion/onedrive#388]
I am having trouble with the sync when the remote files are removed / updated. A folder was deleted from the cloud (tested with web interface as well as through a OneDrive app on another windows system). The `onedrive` was in monitor mode ($ onedrive -m).  The error is as follows:

``
Key not found: lastModifiedDateTime
Key not found: lastModifiedDateTime
std.json.JSONException@std/json.d(494): Key not found:
lastModifiedDateTime
----------------
/usr/include/dmd/phobos/std/exception.d:515 pure @safe void
std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[],
ulong, scope const(char)[]) [0xd6d21aaf]
??:? pure @safe inout(std.json.JSONValue)*
std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*,
lazy const(char)[], immutable(char)[], ulong) [0xd6da84f6]
??:? inout pure ref @safe inout(std.json.JSONValue)
std.json.JSONValue.opIndex(immutable(char)[]) [0xd6d623f1]
src/sync.d:47 itemdb.Item sync.makeItem(ref const(std.json.JSONValue))
[0xd6d39361]
src/sync.d:197 void sync.SyncEngine.applyDifference(std.json.JSONValue,
immutable(char)[], bool) [0xd6d3a212]
src/sync.d:177 void sync.SyncEngine.applyDifferences(immutable(char)[],
const(char)[]) [0xd6d3a083]
src/sync.d:146 void sync.SyncEngine.applyDifferences() [0xd6d39d61]
src/main.d:193 void main.performSync(sync.SyncEngine) [0xd6d28d1f]
src/main.d:169 _Dmain [0xd6d289bb]
``

To get onedrive back to work, I have only one option (after which everything works smooth): 
``rm -f ~/.config/onedrive/*``

This is repeatable as mentioned above. I am using Ubuntu 18.04. I have compiled onedrive with latest commit (SHA: c231b13ad4b64e35a1205135fd6ee0b01fb95edc)

Does anyone have any idea about the cause / solution (not the workaround I mentioned)?

**Comment by abraunegg** [comment]
Hi,

This is fixed by PR #314, but also detailed in #388  #380, #372, #351, #337

Additionally, the 'skilion' code appears to have been abandoned by the original author and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by wagh** [comment]
Thanks for the redirect to the latest code. 

About this version, as I have mentioned I am using the latest commit, so that is expected to have taken care of #314 (and other issues). The point of my post was precisely the same!

Will try the other code.

**Comment by abraunegg** [comment]
> About this version, as I have mentioned I am using the latest commit

The commit you have mentioned you are running:

> This is repeatable as mentioned above. I am using Ubuntu 18.04. I have compiled onedrive with latest commit (SHA: c231b13)

Does not include any of the fixes provided in PR #314 as the original author has not made any changes to the source code since 19th Feb 2018 (https://github.com/skilion/onedrive/commit/c231b13ad4b64e35a1205135fd6ee0b01fb95edc)

**Comment by wagh** [comment]
Oh! Thanks for pointing out... I was under the impression that if I `git pull` the latest update, then I will get everything... In other words, I didnt realize that the issue was not closed in that commit. In any case I am using the **other** branch onedrive. Its still syncing. Will post there if I face any issue!

Thanks once again!

**Comment by wagh** [comment]
Closing the issue as I have moved to the [other](https://github.com/abraunegg/onedrive) branch.
