### ISSUE TITLE
'std/c/stdlib.d' which cannot be read

### ISSUE THREAD

**Issue by FilipeSantana** [skilion/onedrive#389]
Dear all,

Could you tell me how can I solve such an issue?

```
(dmd-2.081.0)root@filipe:/home/filipe/onedrive# make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/sqlite.d(71): Error: module `stdlib` is in file 'std/c/stdlib.d' which cannot be read
import path[0] = /root/dlang/dmd-2.081.0/linux/bin64/../../src/phobos
import path[1] = /root/dlang/dmd-2.081.0/linux/bin64/../../src/druntime/import
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
```

It seems the path is pointing to the wrong location.
Tried it several times (all with a fresh install DMD and all additional dependencies), but the error persists.

By the way... Trying to make it work with Mint 19.

**Comment by abraunegg** [comment]
Hi,

Your specific issue has been resolved in my branch / repository. The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by FilipeSantana** [comment]
Cool!

Seems to be working.

Thank you @abraunegg. 

If I identify something which is not working properly, I'll let you know.

Best regards!
