### ISSUE TITLE
Makefile:29: Onedrive Error 1

### ISSUE THREAD

**Issue by n1marc** [skilion/onedrive#394]
Hi,
I just tried installing this on my Kali Linux and I always get
`(dmd-2.081.1)root@kali:~/onedrive# make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/sqlite.d(71): Error: module `stdlib` is in file 'std/c/stdlib.d' which cannot be read
import path[0] = /root/dlang/dmd-2.081.1/linux/bin64/../../src/phobos
import path[1] = /root/dlang/dmd-2.081.1/linux/bin64/../../src/druntime/import
make: *** [Makefile:29: onedrive] Error 1
`

Anyone know what error I made along the way?
Not the best on Linux, so be mindful of that

**Comment by skilion** [comment]
Fixed in 19793c854d9dd97eb5accf94d21406f825c75fb5
