### ISSUE TITLE
The parent item is not in the local database

### ISSUE THREAD

**Issue by cyberblitz** [skilion/onedrive#395]
I am repeatedly seeing this error in the logs. I have tried various methods to rectify it based on these forums to no avail. Any advice?

Here is the log:

> Aug 04 15:44:37 server  onedrive[16163]: src/sync.d:723 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5943c31]
Aug 04 15:44:37 server  onedrive[16163]: src/main.d:392 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x5927f33]
Aug 04 15:44:37 server  onedrive[16163]: src/main.d:308 _Dmain [0x59279a9]
Aug 04 15:44:37 server  systemd[1272]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Aug 04 15:44:37 server  systemd[1272]: onedrive.service: Failed with result 'exit-code'.
Aug 04 15:44:40 server  systemd[1272]: onedrive.service: Service hold-off time over, scheduling restart.
Aug 04 15:44:40 server systemd[1272]: onedrive.service: Scheduled restart job, restart counter is at 823.
Aug 04 15:44:40 server  systemd[1272]: Stopped OneDrive Free Client.
Aug 04 15:44:40 server systemd[1272]: Started OneDrive Free Client.
Aug 04 15:44:40 server  onedrive[16169]: Initializing the Synchronization Engine ...
Aug 04 15:45:33 server onedrive[16169]: Syncing changes from OneDrive ...
Aug 04 15:45:41 server  onedrive[16169]: The parent item is not in the local database

**Comment by abraunegg** [comment]
Hi,

Your specific issue has been resolved in my branch / repository. The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
