### ISSUE TITLE
No network connection

### ISSUE THREAD

**Issue by fgauvrit** [skilion/onedrive#400]
Hi,

since my last update of my Leap 42.3, onedrive is not working anymore.

When I launch onedrive, I always have "No network connection".

Any clue how to fix that issue ?

Thanks in advance for your help.

Regards.

**Comment by fgauvrit** [comment]
# rpm -qi onedrive
Name        : onedrive
Version     : 1.1.1
Release     : 2.4
Architecture: x86_64
Install Date: Thu Aug  9 18:45:58 2018
Group       : BLAH
Size        : 3237812
License     : GPL-3.0
Signature   : RSA/SHA256, Mon Jun 18 02:02:39 2018, Key ID 44fa29e1ada4be92
Source RPM  : onedrive-1.1.1-2.4.src.rpm
Build Date  : Mon Jun 18 02:02:05 2018
Build Host  : lamb62
Relocations : (not relocatable)
Vendor      : obs://build.opensuse.org/home:bmanojlovic
URL         : https://github.com/skilion/onedrive/
Summary     : Client for One Drive Service for Linux
Description :
OneDrive is a client for Microsoft file serving service
Distribution: home:bmanojlovic:onedrive / openSUSE_Leap_42.3

> onedrive -v
Loading config ...
No config file found, using defaults
Initializing the OneDrive API ...
No network connection

**Comment by abraunegg** [comment]
Hi,

No network connection is indicative of just that - the client cannot get to the applicable services. See if you can reach https://login.microsoftonline.com from a browser, perform a dns lookup as well:

```
nslookup login.microsoftonline.com
```

Additionally the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by fgauvrit** [comment]
Thanks a lot for your answer.

Yes, no dns problem. My internet connection is working perfectly.

I will give a try to the other github.

Regards.

**Comment by abraunegg** [comment]
For any future visitors here - issue is related to local SSL certificates on host system giving issues. See https://github.com/abraunegg/onedrive/issues/111 for further details.
