### ISSUE TITLE
Makefile:29: recipe for target 'onedrive' failed#Error 127

### ISSUE THREAD

**Issue by aavishek** [skilion/onedrive#401]
I am unable to make and am receiving the below error.
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127

I tried https://github.com/abraunegg/onedrive.git as well but received the following error
Makefile:38: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127

please help
Linuxmint 19

**Comment by abraunegg** [comment]
Hi,

Please refer to the readme file - https://github.com/abraunegg/onedrive/blob/master/README.md - especially the sections titled 'Build Requirements' and 'Compilation & Installation'. Also refer to the wiki entry here: https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions

Essentially the error you have encountered is that you have either not installed 'dmd' or you have not activated the compiler for your operating system.

**Comment by aavishek** [comment]
Thanks.
