### ISSUE TITLE
Crash when local file deleted or renamed

### ISSUE THREAD

**Issue by Mjolinir** [skilion/onedrive#402]
Fedora 28
OneDrive 1.1.1

Whenever I delete or rename a file on my local machine that is synced to OneDrive, the app crashes. It will not start until I do a --resync, which then re-downloads the files I wanted to delete in the first place.

onedrive.service - OneDrive Free Client
   Loaded: loaded (/usr/lib/systemd/user/onedrive.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-08-13 09:33:57 EDT; 4min 44s ago
     Docs: https://github.com/skilion/onedrive
  Process: 27220 ExecStart=/usr/bin/onedrive -m (code=exited, status=1/FAILURE)
 Main PID: 27220 (code=exited, status=1/FAILURE)

Aug 13 09:33:57 hostname onedrive[27220]: std.json.JSONException@std/json.d(494): Key not found: lastModifiedDateTime
Aug 13 09:33:57 hostname onedrive[27220]: ----------------
Aug 13 09:33:57 hostname onedrive[27220]: ??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException, inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x4f623076]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x4f671be6]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? [0x45c6b9]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? [0x45d523]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? [0x45d030]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? [0x45cdb5]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? [0x46c5d7]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? [0x46bcbe]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x4f1671cf]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? _d_run_main [0x4f1670a1]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? __libc_start_main [0x4e55f24a]
Aug 13 09:33:57 hostname onedrive[27220]: ??:? [0x451509]
Aug 13 09:33:57 hostname onedrive[q]: Key not found: lastModifiedDateTime
Aug 13 09:33:57 hostname systemd[30700]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Aug 13 09:33:57 hostname systemd[30700]: onedrive.service: Failed with result 'exit-code'.

**Comment by abraunegg** [comment]
Hi,

Your specific issue has been resolved in my branch / repository. The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by Mjolinir** [comment]
Thanks @abraunegg I will try your branch

**Comment by skilion** [comment]
Fixed in 3d6262b3ee7f371d6ee99ea16037f41b8b00dc71
