### ISSUE TITLE
Remote items are not supported yet

### ISSUE THREAD

**Issue by roldengarm** [skilion/onedrive#404]
I've added a Shared Folder to my OneDrive, and I would like to only share a certain item in that share. Folder name is "Work Folder"

I've added the line to my sync_list:

`Work Folder/Documents/template.docx`

Then, running `onedrive --resync --verbose` returns for this particular item:
Remote items are not supported yet

Isn't this supported?

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by roldengarm** [comment]
woot @abraunegg you're the man! It works in your version :)
If you can make the installation a bit easier that would be awesome :dancer:
