### ISSUE TITLE
onedrive keeps crashing after some time

### ISSUE THREAD

**Issue by arbasel** [skilion/onedrive#406]
I have just installed onedrive on Fedora 28. It runs fine for a few minutes but then crashes returning [https://pastebin.com/AwGYAxa1](https://pastebin.com/AwGYAxa1).

I am not sure what all this means

**Comment by abraunegg** [comment]
Hi,

Your specific issue has been resolved in my branch / repository. The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by arbasel** [comment]
Thanks for that. Unfortunately I am new with GIT. I installed using 

> sudo yum install libcurl-devel
sudo yum install sqlite-devel
curl -fsS https://dlang.org/install.sh | bash -s dmd

How do I remove/upgrade the old install?

**Comment by abraunegg** [comment]
It depends on how you did the install. Best to follow the uninstall guidelines in the readme, or if you installed via package uninstall the package.

Lastly remove the 'onedrive' directory that git creates so you get a clean git clone.

**Comment by arbasel** [comment]
Ok, I think very last question. I now need to reauthorize the install. Googling tells me to use
 `onedrive-perf`
but I get a command not found error when I do this.

**Comment by arbasel** [comment]
Awesome.... all done and dusted. Busy syncing with the other fork. Thanks again

**Comment by abraunegg** [comment]
No problem. If all working, best close this case
