### ISSUE TITLE
Synchronization of a deleted item generate a JSON Exception

### ISSUE THREAD

**Issue by lbarbierato** [skilion/onedrive#408]
Dear skilion,

during some test on synchronization with my MAC laptop, I experienced in Ubuntu 18.04 this error in the log once I eliminated from my MAC a file:

`systemd[1]: Started OneDrive Free Client.
onedrive[6735]: Loading config ...
onedrive[6735]: Initializing the OneDrive API ...
onedrive[6735]: Opening the item database ...
onedrive[6735]: All operations will be performed in: /mnt/2C12-AD8D/OneDrive - Politecnico di Torino
onedrive[6735]: Initializing the Synchronization Engine ...
onedrive[6735]: Applying differences ...
onedrive[6735]: 015MW27RF6Y2GOVW7725BZO354PWSELRRZ root
onedrive[6735]: The item has not changed
onedrive[6735]: 015MW27REQBT2IHRGJ4RGJIADRSFHALFY5
onedrive[6735]: std.json.JSONException@../../../../src/libphobos/src/std/json.d(442): Key not found: lastModifiedDateTime
onedrive[6735]: ----------------
onedrive[6735]: 0x5558551f70b6 ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x55585525f9ae ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x55585525ea5b ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x5558551944fa ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x555855195a7a ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x55585519546c ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x55585518b002 ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x55585518aa72 ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x5558552de8be ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x5558552dea2e ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x5558552dedea ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x5558552dea2e ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x5558552debc0 ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x555855189ea3 ???
onedrive[6735]:         ???:0
onedrive[6735]: 0x7fc0fcf7eb96 __libc_start_main
onedrive[6735]:         ???:0
onedrive[6735]: 0x555855181c99 ???
onedrive[6735]:         ???:0
onedrive[6735]: 0xffffffffffffffff ???
onedrive[6735]:         ???:0
systemd[1]: onedrive.service: Main process exited, code=dumped, status=11/SEGV
systemd[1]: onedrive.service: Failed with result 'core-dump'.
`
My onedrive version is **1.0.1**. Any way to fix this?

Kind regards,
Luca

**Comment by abraunegg** [comment]
Hi,

Your specific issue has been resolved in my branch / repository. The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by skilion** [comment]
Fixed in 3d6262b3ee7f371d6ee99ea16037f41b8b00dc71
