### ISSUE TITLE
Forbidden error?

### ISSUE THREAD

**Issue by glicatap** [skilion/onedrive#410]
sudo onedrive --logout
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

"response url here"
HTTP request returned status code 403 (Forbidden)
{
    "error": {
        "code": "accessDenied",
        "innerError": {
            "date": "2018-09-12T03:02:29",
            "request-id": "4dfd4fe8-03bd-4e03-aed1-1a1297942e26"
        },
        "message": "The caller does not have permission to perform the action."
    }
}
HTTP request returned status code 403 (Forbidden)
{
    "error": {
        "code": "accessDenied",
        "innerError": {
            "date": "2018-09-12T03:02:31",
            "request-id": "e763c5c0-8d59-44c7-96a6-11cdefd4e5a1"
        },
        "message": "The caller does not have permission to perform the action."
    }
}
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 403 (Forbidden)
{
    "error": {
        "code": "accessDenied",
        "innerError": {
            "date": "2018-09-12T03:02:34",
            "request-id": "377bbf20-e648-4580-976f-bc1dee8fa410"
        },
        "message": "The caller does not have permission to perform the action."
    }
}
this is giving me a forbidden error, i logged out and attempted to log back in but to no avail. Has microsoft changed something?

**Comment by abraunegg** [comment]
By doing this:
```
sudo onedrive --logout
```
Your logging out the onedrive application as the 'root' user - not your user account. Also, you do not indicate what application version your running. I have tested auth / logout using test Personal / Business accounts and there is no issue I can see. Further to this, The 'skilion' code contains a significant number of defects. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
