### ISSUE TITLE
Syncs hiden files

### ISSUE THREAD

**Issue by Tasty213** [skilion/onedrive#411]
### The program syncs hidden files in the directory

onedrive v1.1.3

https://pastebin.com/S5aZFSA5 (verbose version of resync)
https://pastebin.com/vdqpD3M0 (config file)
https://pastebin.com/19UTu9X2 (verbose version of confdir)

I am connecting to a business office 365 account.

### Situation
I am attempting to set my files to sync from my home directory to both my account at school and my laptop. I am doing this in the ~/ directory to emulate window's implementation of the same system (although all actual files will be in subfolders). However, my hidden files are also syncing, this is not going to work as it will override my hidden files on the other computers.

**Comment by abraunegg** [comment]
@Tasty213 
Unsure if you have already migrated to my fork, however this is supported in my fork:

https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#skip_dotfiles
