### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by chenxuuu** [skilion/onedrive#413]
```Bash
pi@raspberrypi:~/onedrive $ sudo make DC=ldmd2
ldmd2 -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/onedrive.d(37): Error: function std.json.toJSON (const(JSONValue*) root, const(bool) pretty = false, const(JSONOptions) options = cast(JSONOptions)0) is not callable using argument types (const(JSONValue), bool)
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
```

Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux

compiler : LDC

**Comment by abraunegg** [comment]
> Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux

Make sure you have the right dependencies:

```
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libsqlite3-dev
wget https://github.com/ldc-developers/ldc/releases/download/v1.10.0/ldc2-1.10.0-linux-armhf.tar.xz
tar -xvf ldc2-1.10.0-linux-armhf.tar.xz
```

Then build correctly:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
make DC=~/ldc2-1.10.0-linux-armhf/bin/ldmd2
sudo make install
```
Refer ro https://github.com/abraunegg/onedrive/blob/master/README.md for further dedails

Also, the 'skilion' code contains a significant number of issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by chenxuuu** [comment]
thanks, it works!
(I used `sudo apt install ldc` yesterday)
