### ISSUE TITLE
Problem with libphobos2

### ISSUE THREAD

**Issue by toniozz** [skilion/onedrive#418]
Hi,

I have an issue when i execute Onedrive. The error message is 
`onedrive: error while loading shared libraries: libphobos2-ldc-shared.so.79: cannot open shared object file: No such file or directory`
I'm on Archlinux (up to date). The packages ldc, libphobos2 are up to date.
I don't understand. Can you help me ?

Antoine

**Comment by abraunegg** [comment]
Hi,

Your missing runtime dependencies. Try these instructions and see if you get further:

https://github.com/abraunegg/onedrive/blob/master/README.md

**Comment by toniozz** [comment]
Hi,

OK now onedrive works. But when i execute onedrive -m i have this message 
`Initializing monitor ...
OneDrive monitor interval (seconds): 45
./takeout-20180609T175120Z-002-tonio-server.zip: No such file or directory
The item to delete is not in the local database
./takeout-20180609T175120Z-002-tonio-server.zip: No such file or directory
The item to delete is not in the local database
Syncing changes from OneDrive ...

A database statement execution error occurred: database is locked`
Any ideas ?

Antoine

**Comment by abraunegg** [comment]
> A database statement execution error occurred: database is locked

You have multiple instances of the application running somehow - either by systemd services or other.

Suggest you uninstall everything, uninstall 'skilion' version & start from scratch. Also ensure you find and delete any  `items.sqlite3` files from your `~/.config/onedrive` folder

**Comment by toniozz** [comment]
Hi,

It works. thanks

Antoine
