### ISSUE TITLE
Cannot even build

### ISSUE THREAD

**Issue by sanastasiou** [skilion/onedrive#419]
echo v1.1.3 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
cc: No such file or directory
Error: linker exited with status 255
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1

Following instructions on documentation.

**Comment by abraunegg** [comment]
Hi,

Try these instructions and see if you get further:

https://github.com/abraunegg/onedrive/blob/master/README.md

Essentially, your missing additional build capabilities - as your are not detailing what OS your running, refer to the above readme to assist.

**Comment by abraunegg** [comment]
@sanastasiou 
Did you resolve your issue? If yes, please close this case.

**Comment by sanastasiou** [comment]
Yeah I could then build. Thanks!
