### ISSUE TITLE
Crash while creating folder, due to invalid trailing character

### ISSUE THREAD

**Issue by vrischmann** [skilion/onedrive#420]
Hello,

I've just set up onedrive and it crashed while trying to create a folder:

    Sep 30 17:11:45 thor onedrive[14556]: Creating folder ./Images/Pellicule/Google Photos/Hangout_ foobar ● barbaz R.
    Sep 30 17:11:46 thor onedrive[14556]: HTTP request returned status code 400 (Bad Request)
    Sep 30 17:11:46 thor onedrive[14556]: {
    Sep 30 17:11:46 thor onedrive[14556]:     "error": {
    Sep 30 17:11:46 thor onedrive[14556]:         "code": "invalidRequest",
    Sep 30 17:11:46 thor onedrive[14556]:         "innerError": {
    Sep 30 17:11:46 thor onedrive[14556]:             "date": "2018-09-30T15:11:46",
    Sep 30 17:11:46 thor onedrive[14556]:             "request-id": "17d20551-9958-4195-8184-ccd45c1b5e31"
    Sep 30 17:11:46 thor onedrive[14556]:         },
    Sep 30 17:11:46 thor onedrive[14556]:         "message": "Path (\/Hangout_ foobar ● barbaz R.) contains invalid trailing character."
    Sep 30 17:11:46 thor onedrive[14556]:     }
    Sep 30 17:11:46 thor onedrive[14556]: }
    Sep 30 17:12:49 thor onedrive[14556]: Creating folder ./Images/Pellicule/Google Photos/Hangout_ foobar ● barbaz R.
    Sep 30 17:12:50 thor onedrive[14556]: HTTP request returned status code 400 (Bad Request)
    Sep 30 17:12:50 thor onedrive[14556]: {
    Sep 30 17:12:50 thor onedrive[14556]:     "error": {
    Sep 30 17:12:50 thor onedrive[14556]:         "code": "invalidRequest",
    Sep 30 17:12:50 thor onedrive[14556]:         "innerError": {
    Sep 30 17:12:50 thor onedrive[14556]:             "date": "2018-09-30T15:12:50",
    Sep 30 17:12:50 thor onedrive[14556]:             "request-id": "1e17b039-71af-4a59-9914-9c46108c11bf"
    Sep 30 17:12:50 thor onedrive[14556]:         },
    Sep 30 17:12:50 thor onedrive[14556]:         "message": "Path (\/Hangout_ foobar ● barbaz R.) contains invalid trailing character."
    Sep 30 17:12:50 thor onedrive[14556]:     }
    Sep 30 17:12:50 thor onedrive[14556]: }
    Sep 30 17:12:51 thor onedrive[14556]: Creating folder ./Images/Pellicule/Google Photos/Hangout_ foobar ● barbaz R.
    Sep 30 17:12:51 thor onedrive[14556]: onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
    Sep 30 17:12:51 thor onedrive[14556]: {
    Sep 30 17:12:51 thor onedrive[14556]:     "error": {
    Sep 30 17:12:51 thor onedrive[14556]:         "code": "invalidRequest",
    Sep 30 17:12:51 thor onedrive[14556]:         "innerError": {
    Sep 30 17:12:51 thor onedrive[14556]:             "date": "2018-09-30T15:12:51",
    Sep 30 17:12:51 thor onedrive[14556]:             "request-id": "6cd4c1b2-1d3d-4414-b0cd-7c8761d82708"
    Sep 30 17:12:51 thor onedrive[14556]:         },
    Sep 30 17:12:51 thor onedrive[14556]:         "message": "Path (\/Hangout_ foobar ● barbaz R.) contains invalid trailing character."
    Sep 30 17:12:51 thor onedrive[14556]:     }
    Sep 30 17:12:51 thor onedrive[14556]: }
    Sep 30 17:12:51 thor onedrive[14556]: ----------------
    Sep 30 17:12:51 thor onedrive[14556]: src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x58d470]
    Sep 30 17:12:51 thor onedrive[14556]: src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x58d602]
    Sep 30 17:12:51 thor onedrive[14556]: src/onedrive.d:185 std.json.JSONValue onedrive.OneDriveApi.createById(const(char)[], const(char)[], std.json.JSONValue) [0x58c195]
    Sep 30 17:12:51 thor onedrive[14556]: src/sync.d:608 void sync.SyncEngine.uploadCreateDir(const(char)[]) [0x5984ee]
    Sep 30 17:12:51 thor onedrive[14556]: src/sync.d:584 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x598184]
    Sep 30 17:12:51 thor onedrive[14556]: src/sync.d:589 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5981fb]
    Sep 30 17:12:51 thor onedrive[14556]: src/sync.d:445 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x59763d]
    Sep 30 17:12:51 thor onedrive[14556]: src/main.d:194 void main.performSync(sync.SyncEngine) [0x584a6f]
    Sep 30 17:12:51 thor onedrive[14556]: src/main.d:121 _Dmain [0x5845a7]

I probably can workaround by renaming the folder, however I don't think this should make the app crash.

**Comment by abraunegg** [comment]
@vrischmann 
Apart from 2 defect fixes recently - there has been zero updates from skilion on any issue, PR's or anything in a long time. I have been maintaining my brach for >12 months with many of all the defects listed as issues here resolved. Have a read through all the issues & PR's and you will get an idea of what I am talking about.

It's your choice as to which branch you wish to use - I know your specific issue is resolved in my branch.

**Comment by vrischmann** [comment]
I have no beef in this game :) was just curious.

Anyway, thanks for the advice, I'll try your fork. I'll keep this issue open in the meantime.
