### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by Unixware** [skilion/onedrive#422]
make returns

make: *** No rule to make target '.git/HEAD', needed by 'version'. Stop.

system Ubuntu 18.04 (yes onedrive exists on repos, but is an old (see: buggy) version)

**Comment by Unixware** [comment]
oh darn... src corrupted file , sry

**Comment by abraunegg** [comment]
@Unixware 
Just as an FYI - the 'skilion' code contains significant issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
