### ISSUE TITLE
Occasional auth issues - invalid_grant

### ISSUE THREAD

**Issue by sweharris** [skilion/onedrive#424]
I just compiled from source
```
% cat version 
v1.1.3
```

I sometimes see errors such as:

```
HTTP request returned status code 400 (Bad Request)
{
"correlation_id": "<an ID number>",
"error": "invalid_grant",
"error_codes": [
70000
],
"error_description": "AADSTS70000: The user could not be authenticated or the grant is expired. The user must first sign in and if needed grant the client application access to the requested scope.\r\nTrace ID: <another_id_number>\r\nCorrelation ID: <an ID number>\r\nTimestamp: 2018-10-08 11:49:36Z",
"timestamp": "2018-10-08 11:49:36Z",
"trace_id": "<another_id_number>"
}
Refresh token invalid, use --logout to authorize the client again
```

I run this under systemd.  I see the error repeated 3 times with different correlation IDs, and the onedrive aborts

```
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x58d4a8]
src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x58d63a]
src/onedrive.d:252 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x58c85a]
src/onedrive.d:247 void onedrive.OneDriveApi.newToken() [0x58c80f]
src/onedrive.d:264 void onedrive.OneDriveApi.checkAccessTokenExpired() [0x58c9b9]
src/onedrive.d:91 std.json.JSONValue onedrive.OneDriveApi.getDefaultDrive() [0x58b85c]
src/sync.d:147 void sync.SyncEngine.applyDifferences() [0x595ec7]
src/main.d:192 void main.performSync(sync.SyncEngine) [0x584a7b]
src/main.d:169 _Dmain [0x58471d]
```

systemd restarts the service 1 second later...

```
systemd[1]: onedrive.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit onedrive.service entered failed state.
systemd[1]: onedrive.service failed.
systemd[1]: onedrive.service holdoff time over, scheduling restart.
systemd[1]: Started OneDrive Free Client.
systemd[1]: Starting OneDrive Free Client...
```

And then it works.

So I don't know if this was a temporary API outage at Microsoft and the code misinterpreted it, or if onedrive just failed to renew the token, but worked on restart.

I wouldn't have noticed, except I was reviewing logs; I was on a train at the time, so the system was idle and no files were being edited.

**Comment by abraunegg** [comment]
@sweharris 
Just as an FYI, application exception handling - such as this - has been greatly improved under my branch - so instances where a 4xx response code from OneDrive does not cause an application crash.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by abraunegg** [comment]
@sweharris 
Despite a couple of commits in the last month to fix issues which were raised a long time ago - there has been historically no response to many of the issues raised or pull requests to fix problems (not just mine) for quite a long time. You can choose what 'version' you run - just be forewarned that there are significant issues with this codebase which have not been resolved - so if / when you run into issues - like the one you've raised - the defect has probably been fixed in my branch.

You might want to browse through all the open issues & so on to make up your own mind - its your choice after all - not mine and I am not here to sway you either way.
