### ISSUE TITLE
Iterates all my One Terabyte!!!

### ISSUE THREAD

**Issue by jradxl** [skilion/onedrive#427]
Ubuntu 18.10, OneDrive v1.1.3 from Ubuntu APT repository.

Having created a sync_list file with the Dir I want, ie u1810a, and creating same on my OneDrive, with some contents, when running onedrive -v --resync, the same Dir is created locally and the files downloaded in an instant!! Thanks, great....

But, OneDrive then starts to iterate all the other files with the messages like,
Processing 123EAE145FB79F50!279911 20180809_151239.jpg
Filtered out
which are outside the u1810a Dir. In fact, I think it is iterating the whole of my big OneDrive, which is going to take years!

I can then use Cntl-C to stop it, and I do get the effect I want - ie just those files I have in my Dir u1810a have been downloaded. (Alas no upload of new contents)

Is there anyway to get OneDrive to limit itself to only contents of the Dir(s) I create in sync_list?

**Comment by abraunegg** [comment]
What you need is the `--single-directory` functionality which is available in my branch - https://github.com/abraunegg/onedrive

**example:**
```
onedrive --synchronize --single-directory '<dir_name>'
```

This will only scan and process the given directory.
