### ISSUE TITLE
Files are downloaded multiple time until error

### ISSUE THREAD

**Issue by virtualflyer** [skilion/onedrive#429]
I am trying to resync my onedrive after a new setup, but the first file is downloaded three times before onedrive throws an error. I have deleted the first file downloaded from the cloud to see if the error was due to the specific file, but without any luck.
Version is 1.1.3
Output https://pastebin.com/Wt22pb9r

**Comment by GalaxyCurse** [comment]
I have the same problem, it just started suddenly yesterday. Perhaps Microsoft have change something? I've tried to re-install, also tried the fork by abraunegg and got the same problem.
If I have a file manager window open, I can see the file coming, then disappearing before onedrive crashes. The terminal says "No such file or directory"
`$ onedrive --synchronize
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Downloading file ASG/Dreams 11-03-2017 23-20.zip ... done.
ASG/Dreams 11-03-2017 23-20.zip: No such file or directory
Syncing changes from OneDrive ...
Downloading file ASG/Dreams 11-03-2017 23-20.zip ... done.
ASG/Dreams 11-03-2017 23-20.zip: No such file or directory
Syncing changes from OneDrive ...
Downloading file ASG/Dreams 11-03-2017 23-20.zip ... done.
std.file.FileException@/usr/include/dlang/dmd/std/file.d(1556): ASG/Dreams 11-03-2017 23-20.zip: No such file or directory
----------------
??:? @trusted bool std.file.cenforce!(bool).cenforce(bool, scope const(char)[], scope const(char)*, immutable(char)[], ulong) [0x16d3368c]
??:? @safe void std.file.setTimes!(immutable(char)[]).setTimes(immutable(char)[], std.datetime.systime.SysTime, std.datetime.systime.SysTime) [0x16d43e76]
??:? void sync.SyncEngine.downloadFileItem(itemdb.Item, immutable(char)[]) [0x16d7753f]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x16d76eab]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x16d76d41]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x16d7622f]
??:? void sync.SyncEngine.applyDifferences() [0x16d75261]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x16d5a5ea]
??:? _Dmain [0x16d59e80]
[curse@curzed ~]$ 
`

**Comment by arek199602** [comment]
I also have the same problem

**Comment by virtualflyer** [comment]
That is the case, thank you. 
I will wait for an update, here or on your fork.
