### ISSUE TITLE
Feature Request: only sync certain folders/files from remote

### ISSUE THREAD

**Issue by niulin** [skilion/onedrive#43]
While it supports to skip certain files/patterns, can we also support the inverted case: only sync selected folders?

**Comment by abraunegg** [comment]
Would love this functionality as well - being able to specify what local directory(s) get's synced is better than syncing down the entire contents of the OneDrive folder as there maybe content there (on OneDrive) that I do not want to sync back down

**Comment by skilion** [comment]
Feature added in 9dd944286f381b30b0fe656e66d69900782732a2
