### ISSUE TITLE
HTTP request returned status code 302 (Found)

### ISSUE THREAD

**Issue by diegoortizmatajira** [skilion/onedrive#430]
I've been doing my first upload of documents to OneDrive service. I have a lot of images and the process is being interrupted whe it gets to a file:

```
Downloading Imágenes/Por Organizar/Celular/20171123_214715a.jpg...
onedrive.OneDriveException@src/onedrive.d(401): HTTP request returned status code 302 (Found)
----------------
??:? void onedrive.OneDriveApi.checkHttpCode() [0x35ea806b]
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x35ea7936]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], const(char)[], immutable(char)[]) [0x35ea68bb]
??:? void sync.SyncEngine.downloadFileItem(itemdb.Item, immutable(char)[]) [0x35eb1d49]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x35eb18f0]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x35eb1785]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x35eb0f2f]
??:? void sync.SyncEngine.applyDifferences() [0x35eb0c0d]
??:? void main.performSync(sync.SyncEngine) [0x35e9f707]
??:? _Dmain [0x35e9f26b]
```
After this the application stops and doesn't sync anymore.

I've renamed the file and it doesn't affect the behavior.

**DETAILS**

I have Office 365 suscription which provides me with 1 TB on OneDrive.
I've installed onedrive on my computer (Arch Linux) using AUR

**OS**: Arch Linux x86_64 
**Model**: X442UA 1.0 
**Kernel**: 4.18.16-arch1-1-ARCH 
**Shell**: zsh 5.6.2 
**DE**: GNOME 3.30.1 
**WM**: GNOME Shell 
**Terminal**: gnome-terminal 
**CPU**: Intel i7-7500U (4) @ 3.500GHz 
**GPU**: Intel HD Graphics 620 
**Memory**: 2905MiB / 11890MiB 

**LOG**: [https://pastebin.com/L0vAEr8S](https://pastebin.com/L0vAEr8S)

[Log in Pastebin](https://pastebin.com/L0vAEr8S)

**Comment by abraunegg** [comment]
What is the version of curl you are currently running?

**Comment by tithrimimi** [comment]
I've been having the same issue as well suddenly.

Downloading Documents/TV Episodes.xlsx...onedrive.OneDriveException@src/onedrive.d(401): HTTP request returned status code 302 (Found)
----------------
src/onedrive.d:25 void onedrive.OneDriveApi.checkHttpCode() [0x76f761f3]
src/onedrive.d:312 void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x76f75abe]
src/onedrive.d:136 void onedrive.OneDriveApi.downloadById(const(char)[], const(char)[], immutable(char)[]) [0x76f74a43]
src/sync.d:361 void sync.SyncEngine.downloadFileItem(itemdb.Item, immutable(char)[]) [0x76f7fed1]
src/sync.d:309 void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x76f7fa78]
src/sync.d:276 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x76f7f90d]
src/sync.d:179 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x76f7f0b7]
src/sync.d:148 void sync.SyncEngine.applyDifferences() [0x76f7ed95]
src/main.d:192 void main.performSync(sync.SyncEngine) [0x76f6d88f]
src/main.d:121 _Dmain [0x76f6d3f3]

curl --version
curl 7.62.0 (x86_64-pc-linux-gnu) libcurl/7.62.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.34.0
Release-Date: 2018-10-31
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile

OS: Manjaro 18.0.0 w/KDE 5.51
Kernel: .18.16-2-MANJARO #1 SMP PREEMPT

**Comment by tithrimimi** [comment]
Seeing as you asked about curl, I noticed my version was just updated on 31 Oct so I downgraded back to 7.61 and it is now working.

**Comment by diegoortizmatajira** [comment]
> What is the version of curl you are currently running?

curl 7.62.0 (the same as @tithrimimi initially) I've downgraded too and the sync is in progress.

Thanks @abraunegg and @tithrimimi!!

**Comment by tiscal404** [comment]
Same here with curl 7.62.0 in Arch. I downgraded curl to the previous version with downgrader from AUR and the sync is in progress

**Comment by LorenzoAstengo** [comment]
I had the same problem, resolved downgrading curl.

**Comment by abraunegg** [comment]
@diegoortizmatajira, @tiscal404, @tithrimimi, @LorenzoAstengo  
Your specific issue has been resolved in my branch / repository, negating the need / requirement to downgrade your version of Curl. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive rather than the skilion repository.

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by LorenzoAstengo** [comment]
Thank you I will do!
Can you please tell me what enhancements have you done? Thank you!
Il giorno dom 11 nov 2018, 20:04 abraunegg <notifications@github.com (https://link.getmailspring.com/link/CAFSu2HNp6Biqe-XdNYUovacn+T30sDpg5uYAfsUyHh0-wck8GQ@mail.gmail.com/0?redirect=mailto%3Anotifications%40github.com&recipient=cmVwbHkrMDFlZWU0MGU3MmVlYWNmNDE2NWUyMDMxZDA1ZGJiNjhmYTk2MmYwMTMzMzFiZDJiOTJjZjAwMDAwMDAxMTgwMDNmMjQ5MmExNjljZTE2OWM5MzRkQHJlcGx5LmdpdGh1Yi5jb20%3D)> ha scritto:

**Comment by abraunegg** [comment]
https://github.com/abraunegg/onedrive/releases

**Comment by abraunegg** [comment]
https://github.com/abraunegg/onedrive/blob/master/CHANGELOG.md

**Comment by tithrimimi** [comment]
Worked like a charm with cURL 7.62, thank you.

Another thing I noticed about your branch; it doesn't pegged one of my CPUs all the time like the skilion build did. Not to mention it seems to have much more options/functionality.

I like to give some coin to projects that I have a great use for, so if you can let me know how to send a small donation it would be appreciated.

**Comment by tiscal404** [comment]
> Worked like a charm with cURL 7.62, thank you.
> 
> Another thing I noticed about your branch; it doesn't pegged one of my CPUs all the time like the skilion build did. Not to mention it seems to have much more options/functionality.
> 
> I like to give some coin to projects that I have a great use for, so if you can let me know how to send a small donation it would be appreciated.

Also here. Sync in progress with curl 7.62. Tks

**Comment by tiscal404** [comment]
> > Worked like a charm with cURL 7.62, thank you.
> > Another thing I noticed about your branch; it doesn't pegged one of my CPUs all the time like the skilion build did. Not to mention it seems to have much more options/functionality.
> > I like to give some coin to projects that I have a great use for, so if you can let me know how to send a small donation it would be appreciated.
> 
> Also here. Sync in progress with curl 7.62. Tks

Somehow it seems that it is not working again with curl 7.62.
