### ISSUE TITLE
Unable to start service at startup - permission denied

### ISSUE THREAD

**Issue by playgamemy** [skilion/onedrive#432]
```
Nov 12 22:45:43 nick-Lenovo-ideapad-100S-11IBY systemd[981]: Started OneDrive Free Client.
Nov 12 22:45:43 nick-Lenovo-ideapad-100S-11IBY onedrive[997]: std.file.FileException@std/file.d(2954): /media/nick/disk: Permission denied
Nov 12 22:45:43 nick-Lenovo-ideapad-100S-11IBY onedrive[997]: ----------------
Nov 12 22:45:43 nick-Lenovo-ideapad-100S-11IBY onedrive[997]: ??:? @safe bool std.file.cenforce!(bool).cenforce(bool, lazy const(char)[], immutable(char)[], ulong) [0xda0d7a13]
Nov 12 22:45:43 nick-Lenovo-ideapad-100S-11IBY onedrive[997]: ??:? @safe bool std.file.ensureDirExists!().ensureDirExists(const(char[])) [0xda117971]
Nov 12 22:45:43 nick-Lenovo-ideapad-100S-11IBY onedrive[997]: ??:? @safe void std.file.mkdirRecurse(const(char[])) [0xda1162f4]
Nov 12 22:45:43 nick-Lenovo-ideapad-100S-11IBY onedrive[997]: ??:? @safe void std.file.mkdirRecurse(const(char[])) [0xda1162c7]
Nov 12 22:45:43 nick-Lenovo-ideapad-100S-11IBY onedrive[997]: ??:? _Dmain [0xda0deb08]
Nov 12 22:45:43 nick-Lenovo-ideapad-100S-11IBY systemd[981]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Nov 12 22:45:43 nick-Lenovo-ideapad-100S-11IBY systemd[981]: onedrive.service: Failed with result 'exit-code'.
```
I configured to sync to a folder on my sd card to save some limited storage on my ideapad 100s. starting the service manually through `systemctl --user start onedrive` will resume with no issue. Maybe that's because the media is not mounted properly yet when the service start? any ways to delay the service start?

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
