### ISSUE TITLE
Installing and running on CentOS 7

### ISSUE THREAD

**Issue by ctyeong** [skilion/onedrive#434]
I've just found some things I needed to do during installation and running with automatic synchronization on CentOS7.

Before `$ make`, I had to run `$ source ~/dlang/dmd-2.083.0/activate`. 

Also, to sync files automatically, I ran
`$ systemctl enable onedrive` due to the absence of `--user` option on CentOS.

Then, I used 
`$ sudo vim /usr/lib/systemd/system/onedrive.service` 

to add 

`User=my_account` under `[Service]`.

Lastly, I executed
`$ systemctl start onedrive`

Now, it works without any issue!

**Comment by jackxujh** [comment]
I got a strange behavior working with CentOS 7. 

    $ source ~/dlang/dmd-2.083.0/activate
    (dmd-2.083.0)[centos@vm onedrive]$ make
    dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
    make: *** [onedrive] Killed
    (dmd-2.083.0)[centos@vm onedrive]$

Did you get `make: *** [onedrive] Killed` as well?

**Comment by abraunegg** [comment]
The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

I also specifically build and test under CentOS as well, and I do not get this issue your describing. If you have any issues when using my branch submit your issue against my branch for resolution & management.
