### ISSUE TITLE
problem with uploading not nice files ...eg "5.4.2.54_???.xml"

### ISSUE THREAD

**Issue by turekm** [skilion/onedrive#439]
Uploading new items of .
Uploading file ./projects/tde/vIMS/UAG/mt1/uag-xml/Yang_Confdxmls_mt1/hmr-raw/NOT_NEEDED/5.4.2.54_???.xml...onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 401 (Unauthorized)
{
    "error": {
        "code": "UnknownError",
        "innerError": {
            "date": "2018-12-13T15:15:39",
            "request-id": "8713d4e4-3b66-4ee7-b775-667300a8605a"
        },
        "message": ""
    }
}
----------------

**Comment by turekm** [comment]
i have version 1.1.3

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by turekm** [comment]
thank you, let me try it

**Comment by Mart-Bogdan** [comment]
Same problem here

I have Cyrillic letters in file name and spaces.
```

Creating folder ./АУТС/Курсова 1 
HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "innerError": {
            "date": "2019-03-22T19:19:58",
            "request-id": "ae81013b-e653-4cfa-9573-e0af27a66864"
        },
        "message": "Path (\/Курсова 1 ) contains invalid trailing character."
    }
}

src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0xc833574c]
src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0xc83358de]
src/onedrive.d:185 std.json.JSONValue onedrive.OneDriveApi.createById(const(char)[], const(char)[], std.json.JSONValue) [0xc833445d]                                                                                             
src/sync.d:608 void sync.SyncEngine.uploadCreateDir(const(char)[]) [0xc83408aa]                                                                                                                                                  
src/sync.d:584 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xc8340540]                                                                                                                                               
src/sync.d:589 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xc83405b7]                                                                                                                                               
src/sync.d:589 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xc83405b7]                                                                                                                                               
src/sync.d:445 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xc833f9f9]                                                                                                                                           
src/main.d:194 void main.performSync(sync.SyncEngine) [0xc832cf87]                                                                                                                                                               
src/main.d:121 _Dmain [0xc832cabf] 
```
Checking out such files is no problem.

**Comment by Mart-Bogdan** [comment]
upd. I've got " " space as the last character of a directory name. Removing it fixed an issue.

**Comment by abraunegg** [comment]
@Mart-Bogdan 
Whilst you have solved your issue - that is also a bug which is solved in my fork. The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
