### ISSUE TITLE
problem with sync when i deleted directory with files 

### ISSUE THREAD

**Issue by turekm** [skilion/onedrive#440]
hello

i have 1.1.3 version

somehow when i deleted directory with files  on hdd i get this, and i have to fix it manually that i created the directory on hdd and then onedrive works fine (would be possible when there this error it will try to create directory on hdd automaticaly?

----------------
Deleting item from OneDrive: 1can_be_deleted/delete
onedrive.OneDriveException@src/onedrive.d(544): HTTP request returned status code 403 (Forbidden)
{
    "error": {
        "code": "accessDenied",
        "innerError": {
            "date": "2018-12-13T14:46:36",
            "request-id": "3433860d-5253-49a6-b65a-1a0966ea2e75"
        },
        "message": "Request was cancelled by event received. If attempting to delete a non-empty folder, it's possible that it's on hold"
    }
}
----------------
thanks in advance

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
