### ISSUE TITLE
Problem with onedrive -m

### ISSUE THREAD

**Issue by toniozz** [skilion/onedrive#441]
Hello,

I have an issue with onedrive -m since a couple of weeks. Infortunately i don't have the return code (not in the alert message by mail) :

```
`onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 0 () {
    "expirationDateTime": "2018-12-17T22:08:02.707Z",
    "nextExpectedRanges": [
        "10485760-3061789718"
    ]
}
----------------
??:? void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x6535d2] ??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x652b4e] ??:? std.json.JSONValue onedrive.OneDriveApi.requestUploadStatus(const(char)[]) [0x652670] ??:? bool upload.UploadSession.restore() [0x65fbc3] ??:? void sync.SyncEngine.init() [0x65c877] ??:? _Dmain [0x64b46c]
`
```
An idea of the problem ?

Regards
Tonio

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
