### ISSUE TITLE
config is not used

### ISSUE THREAD

**Issue by rednag** [skilion/onedrive#443]
Hi,

I'm trying to set the confdir, but it is ignored and system-wide is no config file found. I've created my own config-file in ~/.config/onedrive/ which is called onedrive.conf. I've installed onedrive with aptitude.

What's the matter? Thank you for your help.

**Comment by rednag** [comment]
I've seen the file needs to be named "config" instead of "onedrive.conf"

**Comment by abraunegg** [comment]
@rednag 
Glad you got your issue sorted

FYI the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository. Unsure which version you installed via 'aptitude' as well - as for Debian / Ubuntu it has been repackaged for v2.2.x

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by rednag** [comment]
Thank you, just updated.
