### ISSUE TITLE
Use skip_file to Skip Specific Directories

### ISSUE THREAD

**Issue by minmossi** [skilion/onedrive#445]
`skip_file = "./Directory1/*|./Directory2/*"`

Above setting doesn't skip the sync in Directory1 and Directory2 on the root directory of Onedrive Business. I don't want to use Selective Sync since I want to sync the upcoming directories in the root directory.

**Comment by abraunegg** [comment]
Hi,

`skip_file` only looks at objects which are files - so it will not skip directories. What you need is this FR added - https://github.com/abraunegg/onedrive/issues/123

Also, the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
