### ISSUE TITLE
every run: The user could not be authenticated or user interaction is required

### ISSUE THREAD

**Issue by etalot** [skilion/onedrive#446]
Every run get:
`"error_description": "AADSTS70000: The user could not be authenticated or user interaction is re                                                                                    quired. The user must sign in again and if needed grant the client application access to the request                                                                                    ed scope`

**Comment by abraunegg** [comment]
@etalot 
You need to potentially use `--logout` and re-authenticate the client.

Also, the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests may not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by etalot** [comment]
> You need to potentially use --logout and re-authenticate the client.

I tried. Authentication procedure works only once for one run. Next run error about authentication.
I tried your version and got:
```
$ onedrive --synchronize
Initializing the Synchronization Engine ...

ERROR: OneDrive returned a 'HTTP 401 Unauthorized' - Cannot Initialize Sync Engine
ERROR: Check your configuration as your access token may be empty or invalid
```

Of course I did authentication procedure before.
It works only once. Next time run get error. 

What is wrong?

**Comment by abraunegg** [comment]
Potentially your permissions for your config directory are incorrect

If you have issues with my fork, submit an issue against my fork not here

**Comment by abraunegg** [comment]
The error is indicative of:
* cannot create refresh_token
* contents of refresh token invalid

**Comment by abraunegg** [comment]
@etalot 
> > cannot create refresh_token
> 
> it is excluded. I remove refresh_token, and app creates new with content.
> 
> > contents of refresh token invalid
> 
> possible, but app wrote invalid token on previous run.
> it's true for you version and for original.

What do you mean by: 'it is excluded' ?

If the application is writing an invalid token, the token being received by the application is either being modified by some sort of man-in-the-middle attack or you have some sort of SSL / HTTPS inspection going on that is mangling the data.

If there was an issue with the creation of this file, this issue would be more widespread.

I suggest that if you want to look at this further, please open a case against my branch rather than the skilion code.

**Comment by castigohd** [comment]
So I was getting the same error today when I tried to sync my OneDrive on Ubuntu, after 7 days without logging into Ubuntu.
While I was about to read the comments here I remembered that within those 7days I didn't logon to Ubuntu I changed my OneDrive passowrd.
I decided then to loggout ( `onedrive --logout` ) and log back in. and that's what I did.

ps: when I had to paste the url on the browser I didn't have to allow anything (just like the very first time you set up the client) I only copied the url that was on the address bar when I was presented with the white screen

**Comment by abraunegg** [comment]
@castigohd 
The 'skilion' code appears to have been abandoned and contains many issues that have not been fixed. It contains defects that put you at risk of data loss and corruption. If you wish to use the latest code which contains numerous fixes and enhancements you need clone & build from here: https://github.com/abraunegg/onedrive
