### ISSUE TITLE
Add option to view online

### ISSUE THREAD

**Issue by huntantr** [skilion/onedrive#447]
Just like with the windows onedrive client, it would be extremely useful if a context menu entry could be added so that Word/Excel/etc files could be viewed online.

**Comment by huntantr** [comment]
@abraunegg 
Thanks for the info.
I'm wondering if something like this be possible through a script. Is there a way to get the url to a particular file in onedrive?

**Comment by abraunegg** [comment]
@huntantr
It would be worth reviewing the OneDrive API - https://docs.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online

**Comment by huntantr** [comment]
@abraunegg 
I wasn't sure if you had a property or something within your service that would have that information. I'll look into the API though.

**Comment by abraunegg** [comment]
@huntantr 
> I'm wondering if something like this be possible through a script. Is there a way to get the url to a particular file in onedrive?

FYI - this is now implemented in my fork of this client - refer to 
https://github.com/abraunegg/onedrive/releases/tag/v2.3.8

Use `--get-file-link` to obtain the URL of a file
