### ISSUE TITLE
Multiple folder sync

### ISSUE THREAD

**Issue by moritz31** [skilion/onedrive#448]
Is it possible to sync multiple folders, like with nextcloud client?

**Comment by shgo** [comment]
This feature is almost mandatory for many use cases. Do you guys intend to implement it? Or it already supports multiple folder sync?

**Comment by abraunegg** [comment]
@moritz31 , @shgo 

The 'skilion' repo appears to have been abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
