### ISSUE TITLE
jsonexception jsonvalue is not an object

### ISSUE THREAD

**Issue by webe3** [skilion/onedrive#449]
I have onedrive --synchronize working the other day.  Now I am getting a failure:
onedrive --synchronize
Initializing the Synchronization Engine ...
std.json.JSONException@std/json.d(274): JSONValue is not an object
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x557d78fd0309]
??:? pure @safe bool std.exception.enforce!(std.json.JSONException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x557d78f64981]
??:? inout pure @property @trusted inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.objectNoRef() [0x7f952ee55cdd]
??:? [0x557d78f47a10]
??:? [0x557d78f49b0c]
??:? [0x557d78f68f72]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x7f952eb6a12f]
??:? _d_run_main [0x7f952eb69f45]
??:? __libc_start_main [0x7f952e74909a]
??:? [0x557d78f36bf9]

**Comment by abraunegg** [comment]
@webe3 
Please close this issue as this is irrelevant if not running the 'skilion' version

**Comment by webe3** [comment]
I am not running skilion and I fixed the problem.
