### ISSUE TITLE
out of sync - renames local more recent file and replaces with remote

### ISSUE THREAD

**Issue by ghost** [skilion/onedrive#45]
EEFFEFC3B64745EA!160937 classnotes.txt
The local item has a different modified time 2016-Apr-14 07:57:16 remote is 2016-Apr-07 21:43:51Z
The local item has a different hash
The local item is out of sync, renaming ...
Downloading: ./work/classnotes.txt

should instead upload more recent version, perhaps back up remote one. could be download remote and rename. then upload both

**Comment by nightah** [comment]
Also experiencing this issue, despite the fact that local item has a more recent modified time it's replacing it with the remote file.

**Comment by skilion** [comment]
It seems logically that the most recent file should always replace the old one but I can think at least of one situation where it could lead to data loss: when you are sharing a file. If a file is edited by 2 people at the same time, one edit will permanently overwrite the other. Also computers are far from perfect and time glitches can happen with destructive consequences. I prefer to be on the safe side and duplicate the files when in doubt. A few copies are better than lost data.
