### ISSUE TITLE
No service for onedrive in Ubuntu 18.04

### ISSUE THREAD

**Issue by mahmoodn** [skilion/onedrive#451]
I have built and put the config file and by running onedrive command for the first time, all files were fetched.
```
$ ls OneDrive/Public/
test.docx
$ cat .config/onedrive/config 
# Directory where the files will be synced
sync_dir = "~/OneDrive"
# Skip files and directories that match this pattern
skip_file = ".*|~*"
```

However, there is no related service for that.

```
$ sudo systemctl --user enable onedrive
Failed to connect to bus: No such file or directory
$ sudo systemctl restart onedrive
Failed to restart onedrive.service: Unit onedrive.service not found.
```

What should I do?

**Comment by abraunegg** [comment]
@mahmoodn 
How did you build and install the client? The makefile should install the service files to the correct location when you run `make install`

Also, the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
