### ISSUE TITLE
error while make

### ISSUE THREAD

**Issue by pedrosmmc** [skilion/onedrive#454]
~/onedrive$ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/sqlite.d(142): Deprecation: foreach: loop index implicitly converted from size_t to int
/usr/bin/ld: cannot find -lsqlite3
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
make: *** [Makefile:29: onedrive] Error 1

~/onedrive$ sqlite3 --version
3.26.0 2018-12-01 12:34:55 bf8c1b2b7a5960c282e543b9c293686dccff272512d08865f4600fb58238b4f9

**Comment by abraunegg** [comment]
@pedrosmmc 
It appears you have not installed the development libraries required. Refer to https://github.com/abraunegg/onedrive/blob/master/README.md#build-requirements for assistance.

Also, the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by LeonMac** [comment]
I meet the same issue under the ubuntu18.04..
`$make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/sqlite.d(142): Deprecation: foreach: loop index implicitly converted from size_t to int
/usr/bin/ld: cannot find -lsqlite3
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
$cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
`

**Comment by abraunegg** [comment]
@LeonMac 
The 'skilion' github site is defunct. The code in this repository appears to have been abandoned and contains many other issues that have not been fixed. It contains defects that put you at risk of data loss and corruption. 

If you wish to use the latest code which contains numerous fixes and enhancements you need clone & build from here: https://github.com/abraunegg/onedrive

Please refer to these build instructions: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md

**Comment by LeonMac** [comment]
@abraunegg Got it, tks for reminder..

**Comment by georgette-femerling** [comment]
Got a similar issue plus cannot find -lcurl:

$ make
if [ -f .git/HEAD ] ; then \
	git describe --tags > version ; \
else \
	echo v2.4.1-dev > version ; \
fi
dmd -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
/home/gfemer/anaconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lcurl
/home/gfemer/anaconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lsqlite3
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
make: *** [Makefile:100: onedrive] Error 1

$ sqlite3 --version
3.30.1 2019-10-10 20:19:45 18db032d058f1436ce3dea84081f4ee5a0f2259ad97301d43c426bc7f3df1b0b

$ curl --version
curl 7.68.0 (x86_64-conda_cos6-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.11 libssh2/1.8.2
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets

I cloned the latest update so far. 
Running on Ubuntu 18.04.4 LTS

**Comment by abraunegg** [comment]
@georgette-femerling 
The 'skilion' repo appears to have been abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change

Refer to https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md to install the client.

Again - this repo is **dead** and **broken**

**Comment by georgette-femerling** [comment]
@abraunegg Thank you for your help. I have cloned and tried to build from your repo, following the install instructions you refer to. Nonetheless, the same error continues to appear. Any idea of what could be happening?

**Comment by abraunegg** [comment]
Raise a new issue on my repo please - this repo is dead.
