### ISSUE TITLE
I am not a robot: Google blocks IP

### ISSUE THREAD

**Issue by maxiwelian** [skilion/onedrive#457]
My IP was blocked from Google scholar ~2min after setting the app running.

Will update when it is finished syncing. I understand if this is an issue with the high # calls to the server to fetch all the files initially.

**Comment by Rondom** [comment]
How is Google Scholar related to *Microsoft* OneDrive?

**Comment by abraunegg** [comment]
@maxiwelian 
I agree with @Rondom - there can be no correlation between the two. There is no way the way the app operates a different company and service detected a violation of TOC for Google Scholar.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
