### ISSUE TITLE
White screen after authroizing app

### ISSUE THREAD

**Issue by Sp3ctreSec** [skilion/onedrive#459]
Gives me white screen after logging into overdrive account for authorization

**Comment by Sp3ctreSec** [comment]
Get the same result on Chrome and Firefox.

**Comment by abraunegg** [comment]
@Sp3ctreSec 
That is normal operation. The resulting 'URL' is what you copy / paste back into the client.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
