### ISSUE TITLE
Invalid client when I first run authorization

### ISSUE THREAD

**Issue by guikarist** [skilion/onedrive#463]
This is the url I get:
```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
```

Then I get a login page, after I logged in, I get this url:
```
https://login.microsoftonline.com/common/oauth2/nativeclient?error=invalid_client&error_description=AADSTS650051%3a+Using+application+%27OneDrive+Free+Client%27+is+currently+not+supported+for+your+organization+stu.hit.edu.cn+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+stu.hit.edu.cn+before+the+application+OneDrive+Free+Client+can+be+provisioned.%0d%0aTrace+ID%3a+8983736c-f363-4388-8338-2c62b6e63700%0d%0aCorrelation+ID%3a+8f224716-cead-4850-bbf6-690ad19ee82e%0d%0aTimestamp%3a+2019-04-15+02%3a49%3a19Z
```
which tells me *a invalid client*.

**Comment by guikarist** [comment]
Ubuntu version: `18.10`
Kernel version: `4.18.0-17-generic`

**Comment by abraunegg** [comment]
@guikarist 
Your OneDrive API response tells you the reason for this:

```
OneDrive Free Client is currently not supported for your organization stu.hit.edu.cn because it is in an unmanaged state. 
An administrator needs to claim ownership of the company by DNS validation of stu.hit.edu.cn before the application OneDrive Free Client can be provisioned.
```

This is not an issue with the client, but with your organisation / Active Directory instance & so on.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

Regardless of what client you choose to run, unless you fix the issues with 'stu.hit.edu.cn' then neither client will be able to authorise correctly.

**Comment by guikarist** [comment]
Got it!
Thanks for your reply!

**Comment by yjcn** [comment]
@guikarist  hello  I meet the same problem?Is there other onedrive client in linux?

**Comment by guikarist** [comment]
@yjcn There is one which is not free.

**Comment by yjcn** [comment]
> @yjcn There is one which is not free.

Could you please tell me? Thanks.

**Comment by guikarist** [comment]
> > @yjcn There is one which is not free.
> 
> Could you please tell me? Thanks.

https://www.insynchq.com/i/onedrive
