### ISSUE TITLE
Duplicates file with computer name until core dump.

### ISSUE THREAD

**Issue by ITCMD** [skilion/onedrive#464]
This program has done this before and I fixed it by deleting all of the duplicated file, but now it is happening again with a different file So I figured I'd bring it to your attention. It seems to only happen with PDFs; it copies it over and over and over until it crashes with `(Core dumped)`., however that may just be a coincidence as it has happened only twice. Here's the log with `onedrive -m -v` (the `-m` should mean it stays open constantly checking for changes, the `-v` means it prints more info).

    lukaka@SetLucas-PC:~$ onedrive -m -v
    Loading config ...
    No config file found, using defaults
    Initializing the OneDrive API ...
    Opening the item database ...
    All operations will be performed in: /home/lukaka/OneDrive
    Initializing the Synchronization Engine ...
    Applying differences ...
    823D77D17D574B54!103 root
    The item has not changed
    823D77D17D574B54!43816 na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf
    Moving: na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf -> ./na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf
    The destination is occupied, renaming the conflicting file...
    ./na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf: File name too long
    Applying differences ...
    823D77D17D574B54!103 root
    The item has not changed
    823D77D17D574B54!43816 na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf
    Moving: na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf -> ./na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf
    The destination is occupied, renaming the conflicting file...
    ./na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf: File name too long
    Applying differences ...
    823D77D17D574B54!103 root
    The item has not changed
    823D77D17D574B54!43816 na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf
    Moving: na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf -> ./na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf
    The destination is occupied, renaming the conflicting file...
    sync.SyncException@src/sync.d(178): ./na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf: File name too long
    ----------------
    0x5636eda14836 ???
    	???:0
    0x5636eda0a002 ???
    	???:0
    0x5636eda09a72 ???
    	???:0
    0x5636edb5d8be ???
    	???:0
    0x5636edb5da2e ???
    	???:0
    0x5636edb5ddea ???
    	???:0
    0x5636edb5da2e ???
    	???:0
    0x5636edb5dbc0 ???
    	???:0
    0x5636eda08ea3 ???
    	???:0
    0x7feadcf69b96 __libc_start_main
    	???:0
    0x5636eda00c99 ???
    	???:0
    0xffffffffffffffff ???
    	???:0
    std.file.FileException@../../../../src/libphobos/src/std/file.d(658): ./na4a website-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC-SetLucas-PC.pdf: File name too long
    ----------------
    0x5636eda6a3e6 ???
    	???:0
    0x5636edac8911 ???
    	???:0
    0x5636eda7d98a ???
    	???:0
    0x5636eda19613 ???
    	???:0
    0x5636eda158fa ???
    	???:0
    0x5636eda1531d ???
    	???:0
    0x5636eda1446c ???
    	???:0
    0x5636eda0a002 ???
    	???:0
    0x5636eda09a72 ???
    	???:0
    0x5636edb5d8be ???
    	???:0
    0x5636edb5da2e ???
    	???:0
    0x5636edb5ddea ???
    	???:0
    0x5636edb5da2e ???
    	???:0
    0x5636edb5dbc0 ???
    	???:0
    0x5636eda08ea3 ???
    	???:0
    0x7feadcf69b96 __libc_start_main
    	???:0
    0x5636eda00c99 ???
    	???:0
    0xffffffffffffffff ???
    	???:0
    Segmentation fault (core dumped)

Here's a picture of the folder:
[![Onedrive Folder][1]][1]

  [1]: https://i.stack.imgur.com/kXKNs.png

**Comment by abraunegg** [comment]
@ITCMD 
This is a 'known' issue due to bugs in the 'skilion' code that calculate the hash of files being incorrect + if you are using an Office 365 account (given you are seeing this issue with PDF's) then you are most likely also hitting this OneDrive bug: https://github.com/OneDrive/onedrive-api-docs/issues/935 where Microsoft modifies your files by 'enriching them' - thus the file hash is different, has a name clash and you get the result your seeing.

The good news is that both of these bug's are fixed in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
