### ISSUE TITLE
Issue after kernel update

### ISSUE THREAD

**Issue by dexMilano** [skilion/onedrive#465]
I'm facing an issue since 1 month using the client
I already tried to reinstall from repository but...
Everything was fine till that moment.
Look on the web some solution but I canìt find anything related

Ubuntu 18.04 LTS
onedrive v1.0.1

Here the output on the screen

`
dex@dex-6330-ux:~$ onedrive -v
Loading config ...
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/dex/OneDrive
Initializing the Synchronization Engine ...
Applying differences ...
Delta link expired, resyncing
std.json.JSONException@/usr/lib/gcc/x86_64-linux-gnu/7/include/d/std/json.d(551): JSONValue is not an object
----------------
0x556df11530b6 ???
	???:0
0x556df1153004 ???
	???:0
0x556df1164b45 ???
	???:0
0x556df10f1608 ???
	???:0
0x556df10e7002 ???
	???:0
0x556df10e6a72 ???
	???:0
0x556df123a8be ???
	???:0
0x556df123aa2e ???
	???:0
0x556df123adea ???
	???:0
0x556df123aa2e ???
	???:0
0x556df123abc0 ???
	???:0
0x556df10e5ea3 ???
	???:0
0x7f6fb6a4db96 __libc_start_main
	???:0
0x556df10ddc99 ???
	???:0
0xffffffffffffffff ???
	???:0
Errore di segmentazione (core dump creato)

`

**Comment by abraunegg** [comment]
@dexMilano 
This sounds like the resync bug which is fixed in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by dexMilano** [comment]
Thanks abraunegg.
Have you a deb package for that?

Thanks
dexMilano

Il giorno gio 2 mag 2019 alle ore 08:54 abraunegg <notifications@github.com>
ha scritto:

**Comment by abraunegg** [comment]
@dexMilano 
It would be worth refering to https://packages.debian.org/search?keywords=onedrive&searchon=names&suite=all&section=all

However you are better off building directly from source as per https://github.com/abraunegg/onedrive/blob/master/README.md
