### ISSUE TITLE
syncing sharepoint document librarys - I don't get it ...

### ISSUE THREAD

**Issue by HansAchterbahn** [skilion/onedrive#467]
Hi,

I used the Graph Explorer and the Sharepoint API:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/sharepoint

There you can see, how to build the required URL in order to geht the drive ID:
GET https://graph.microsoft.com/v1.0/sites/[hostname]:/[PATH]:/drives

So what you need to know is the Hostname and the Path to the sharepoint website collection. Example:
GET https://graph.microsoft.com/v1.0/sites/contoso.sharepoint.com:/teams/hr:/drives

I created a Sharepoint website collection called "Backup" in the Sharepoint Admin Center. So the URL is:
GET https://graph.microsoft.com/v1.0/sites/myname.sharepoint.com:/sites/Backup:/drives

Unfortunately this URL cant be direclty used as "driveURL" in the sync client. But in the answer there is an entry called "id". Using this ID you can create the "driveURL":
https://graph.microsoft.com/v1.0/drives/[id]

Inserting this into driveUrl, itemByIdUrl and itemByPathUrl in the source code allows the sharepoint drives to be synced using this client.

_Originally posted by @riversource in https://github.com/skilion/onedrive/issues/283#issuecomment-366899361_

**Comment by HansAchterbahn** [comment]
Hi guys, I tried realy hard to get this to work, but i didn't get it. Can you may help me on this?

Syncing on my private documents is still working, but i don't get the drive_id.

**Comment by HansAchterbahn** [comment]
Relocated issue to:
https://github.com/abraunegg/onedrive/issues/503

**Comment by abraunegg** [comment]
@HansAchterbahn
Syncing sharepoint sites requires a lot of other changes not implemented. The good news is that all works in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
