### ISSUE TITLE
Russian letters long names crach

### ISSUE THREAD

**Issue by Leonid1969** [skilion/onedrive#469]
BDAD7AFBC00EE64C!52753 Справка о состоянии расчетов по налогам, сборам, страховым взносам, пеням, штрафам, процентам.pdf
Downloading: Метизы/Тендеры ТМЗ/Документы ТМЗ/Справка о состоянии расчетов по налогам, сборам, страховым взносам, пеням, штрафам, процентам.pdf
sync.SyncException@src/sync.d(176): Cannot open file `Метизы/Тендеры ТМЗ/Документы ТМЗ/Справка о состоянии расчетов по налогам, сборам, страховым взносам, пеням, штрафам, процентам.pdf' in mode `wb' (File name too long)
----------------
0x55e54ffeb7c4 ???
	???:0
0x55e54ffe1002 ???
	???:0
0x55e54ffe0a72 ???
	???:0
0x55e5501348be ???
	???:0
0x55e550134a2e ???
	???:0
0x55e550134dea ???
	???:0
0x55e550134a2e ???
	???:0
0x55e550134bc0 ???
	???:0
0x55e54ffdfea3 ???
	???:0
0x7f1fc818bb96 __libc_start_main
	???:0
0x55e54ffd7c99 ???
	???:0
0xffffffffffffffff ???
	???:0
std.exception.ErrnoException@../../../../src/libphobos/src/std/stdio.d(401): Cannot open file `Метизы/Тендеры ТМЗ/Документы ТМЗ/Справка о состоянии расчетов по налогам, сборам, страховым взносам, пеням, штрафам, процентам.pdf' in mode `wb' (File name too long)
----------------
0x55e5500ebe1c ???
	???:0
0x55e5500ea101 ???
	???:0
0x55e54ffe4eef ???
	???:0
0x55e54ffe3829 ???
	???:0
0x55e54ffec56d ???
	???:0
0x55e54ffec1d8 ???
	???:0
0x55e54ffeb46c ???
	???:0
0x55e54ffe1002 ???
	???:0
0x55e54ffe0a72 ???
	???:0
0x55e5501348be ???
	???:0
0x55e550134a2e ???
	???:0
0x55e550134dea ???
	???:0
0x55e550134a2e ???
	???:0
0x55e550134bc0 ???
	???:0
0x55e54ffdfea3 ???
	???:0
0x7f1fc818bb96 __libc_start_main
	???:0
0x55e54ffd7c99 ???
	???:0
0xffffffffffffffff ???
	???:0
Ошибка сегментирования (стек памяти сброшен на диск)

**Comment by abraunegg** [comment]
@Leonid1969 
This is a known bug and is fixed in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
