### ISSUE TITLE
compilation error or make error

### ISSUE THREAD

**Issue by ukreddy-erwin** [skilion/onedrive#470]
uday@jenkins-server:~/onedrive$ make
echo v1.1.3 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127

uday@jenkins-server:~/onedrive$ make DC=ldmd2
ldmd2 -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: ldmd2: Command not found
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127
uday@jenkins-server:~/onedrive$

**Comment by yepw** [comment]
I had the same problem and solved it by installing [DMD](https://dlang.org/download.html).  More info can be found [here](https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions#make-command-during-installation-encounters-error-127https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions#make-command-during-installation-encounters-error-127).

**Comment by ukreddy-erwin** [comment]
How to connect or sync shared folders?
