### ISSUE TITLE
Synchronization Error - Etag does not match current item's value

### ISSUE THREAD

**Issue by jeffrussell37** [skilion/onedrive#473]
Version: onedrive v2.3.3-15-g8d4a35e
OS: Fedora 30
uname -a:  Linux <HOSTNAME> 5.1.15-300.fc30.x86_64 #1 SMP Tue Jun 25 14:07:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Many times when a file changes, I receive the following error messages:
Uploading modified file Documents/Blood Sugar Checks-1-jeff-7579.russellingupfun.com.xlsx ... done.
ERROR: OneDrive response missing required 'id' element
ERROR: {"error":{"code":"notAllowed","innerError":{"date":"2019-07-08T18:03:40","request-id":"2ac7080f-407e-4bd9-be8b-f4b9e0b2c1a7"},"message":"ETag does not match current item's value"}}

This error repeats constantly for the same filename.  Initial sync works, subsequent syncs sometimes work, but when a failure occurs, it will not sync the file until it is removed from the OneDrive webpage and resynced.  When the error occurs, the file on OneDrive cloud no longer updates.

**Comment by abraunegg** [comment]
@jeffrussell37 
A couple of issues here:
1. Your running v2.x.x - which is not the 'skilion' version. Please close this case and open an issue ticket here: https://github.com/abraunegg/onedrive
2. Your running v2.3.3 which is many versions old - latest is `onedrive v2.3.7-7-g705f78b`

Please:
1. Close this case
2. Clone from the latest master

**Comment by jeffrussell37** [comment]
My apologies.  I'll follow your recommendations.  Thank you!
