### ISSUE TITLE
error on delete file

### ISSUE THREAD

**Issue by buster95** [skilion/onedrive#474]
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0xae6d94b9]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException, inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0xae6d951e]
??:? std.json.JSONValue.opIndexinout(pure ref @safe inout(std.json.JSONValue) function(immutable(char)[])) [0xae68be99]
??:? itemdb.Item sync.makeItem(ref const(std.json.JSONValue)) [0xae65fb37]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0xae660c74]
??:? void sync.SyncEngine.applyDifferences() [0xae66079d]
??:? void main.performSync(sync.SyncEngine) [0xae64c84f]
??:? _Dmain [0xae64c077]
std.json.JSONException@std/json.d(493): Key not found: lastModifiedDateTime

**Comment by abraunegg** [comment]
@buster95 
This is a known bug with the 'skilion' code and it looks like from above you are running some version < 1.1.3. You need to upgrade your client to the latest available version.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by buster95** [comment]
> @buster95
> This is a known bug with the 'skilion' code and it looks like from above you are running some version < 1.1.3. You need to upgrade your client to the latest available version.
> 
> Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

thanks abraunegg, i'm working to run onedrive in a docker container, we need make information backup from virtual folder

**Comment by abraunegg** [comment]
@buster95 
Suggest you read the following for Docker: https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md
