### ISSUE TITLE
Random files uploads after first sync

### ISSUE THREAD

**Issue by taokann** [skilion/onedrive#475]
Hello,
I installed onedrive just now.
I made my first sync, but at the end, it uploaded completely random files that I never edit.
I did not edit nothing, and a dozen of files are uploaded.
Seems it's just a bug.

**Comment by abraunegg** [comment]
@taokann 
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by taokann** [comment]
Ok I read that in other issues but is this bug fixed in your fork ? @abraunegg


De : abraunegg
Envoyé : jeudi 18 juillet à 00:36
Objet : Re: [skilion/onedrive] Random files uploads after first sync (#475)
À : skilion/onedrive
Cc : taokann.one, Mention


@taokann<https://github.com/taokann>
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by abraunegg** [comment]
@taokann 
Without you providing any debug log or what version or anything - I cannot tell.

All I can say is this - the issue sounds very weird, and there are many many many bugs in the 'skilion' code that have been fixed in my fork. This 'may' be one of them but without any data or evidence I cannot 100% advise yes or no

**Comment by taokann** [comment]
Alright, I'll try your fork and come back if I find issues again. Thanks @abraunegg

Tao-Kann

________________________________

**Comment by abraunegg** [comment]
@taokann 
Please close this issue if resolved, if you have issues with my fork, open a case there .. not here.

**Comment by taokann** [comment]
@abraunegg
Don't worry about that I know well how GitHub works

Tao-Kann

________________________________

**Comment by taokann** [comment]
This weird thing does not happen in @abraunegg 's fork
