### ISSUE TITLE
files in my onedrive service can't sync to the local

### ISSUE THREAD

**Issue by yongqianxiao** [skilion/onedrive#476]
Ubuntu 18.04
onedrive version: 1.1.3
I  installed the onedrive successful, and after I run the commander "onedrive",  there were 3 folders added in the path, ~/OneDrive/Picture, ~/OneDrive/Document and another folder. However, my files in my onedrive can sync in my windows10, but they were not downloaded in the ubuntu 18.04. How to sync files and folders in onedrive to the ubuntu system?

**Comment by abraunegg** [comment]
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by yongqianxiao** [comment]
> The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

I will try, thanks

**Comment by yongqianxiao** [comment]
@abraunegg thanks for the former help. I can synchronize all the files and folders from OneDrive. But there are so many files and folders on OneDrive, can I choose some folders not to synchronize to the local? I tried to modify the config file ~/.config/onedrive/config, and the contents as follows:
```bash
skip_file = "~*|.~*|*.tmp"
sync_dir = "~/OneDrive"
skip_dir = "~/OneDrive/cart_pole|~/OneDrive/文档"
```
where `~/OneDrive` is the folder to synchronize all files of OneDrive. `cart_pole/`  and `文档/` are 2 folders of my OneDrive account.
Could you tell me how to design the `config` file to ignore some folders and files of my OneDrive account to synchronize to the local? Thanks a lot.

**Comment by yongqianxiao** [comment]
`skip_dir` is relative to `sync_dir` so:
```
skip_dir = "~/OneDrive/cart_pole|~/OneDrive/文档"
```
should be:
```
skip_dir = "cart_pole|文档"
```
it works, thanks to @abraunegg
