### ISSUE TITLE
small suggestion for documentation

### ISSUE THREAD

**Issue by michaeldchristopher** [skilion/onedrive#477]
First: Thank you! I love your work and it helps me a lot. 

I had updated some things on my Manjaro and something caused my One Drive to stop syncing. 

So i uninstalled/reinstalled but that did not fix it. So I tried the command to force a resync in a terminal window. That took me to the part where it gave me the authorization and waited for a response. I copied that to a browser, logged into Microsoft one drive account and got a blank page. 

I thought something was wrong. So I read the fine manual and then saw that getting a blank page was right and I took that URL and pasted it in the terminal. The problem is that part of your (great) documentation that tells you that you get a blank page was in a different area than the resync command.

My humble suggestion:

* Make the resync command section be its own little topic.
* Make the docs that say you will get a blank page be "bolder" or maybe show a screenshot. It does work perfectly, but it is a little bit unique in the way it works.
* Recommend that if your syncing stop, to use resync to get it going again
* Mention that if something stops working, re-read the fine manual :)

This is just an idea.

**Comment by abraunegg** [comment]
@michaeldchristopher 
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
