### ISSUE TITLE
Not syncing files in root folder

### ISSUE THREAD

**Issue by pavarinodu** [skilion/onedrive#478]
Hello! I've already installed and configured OneDrive, and it's working flawlessly, except on this issue: **files created in the root folder (~/OneDrive) are not synced**, although files created inside folders described on ~/.config/onedrive/sync_list are synced.
I tried modifying the config files, but nothing worked... what can be done for solving this issue?

**Comment by abraunegg** [comment]
@pavarinodu 
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

Specifically for your issue:

As per https://github.com/abraunegg/onedrive/issues/491 this feature is implemented and works as per design.

**Comment by pavarinodu** [comment]
@abraunegg 
Thank you for your feedback! I didn't know about this new repo and the design of not syncing root folder by default. Sure I'm switching to this new repo.
