### ISSUE TITLE
std.json.JSONException@../../../../src/libphobos/src/std/json.d(442): Key not found: 

### ISSUE THREAD

**Issue by surapuramakhil** [skilion/onedrive#479]
Hie I am receiving this. it seems error is common but stack seems a bit different.

running on ubuntu 18.04

`onedrive --verbose`

Loading config ...
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/*****-***/OneDrive
Initializing the Synchronization Engine ...
Applying differences ...
0166GTOS56Y2GOVW7725BZO354PWSELRRZ root
The item has not changed
0166GTOSZ7OGZ4XQZMEBDJMW6DNPBA3P2X 
std.json.JSONException@../../../../src/libphobos/src/std/json.d(442): Key not found: lastModifiedDateTime
----------------
0x55b81a7d60b6 ???
	???:0
0x55b81a83e9ae ???
	???:0
0x55b81a83da5b ???
	???:0
0x55b81a7734fa ???
	???:0
0x55b81a774a7a ???
	???:0
0x55b81a77446c ???
	???:0
0x55b81a76a002 ???
	???:0
0x55b81a769a72 ???
	???:0
0x55b81a8bd8be ???
	???:0
0x55b81a8bda2e ???
	???:0
0x55b81a8bddea ???
	???:0
0x55b81a8bda2e ???
	???:0
0x55b81a8bdbc0 ???
	???:0
0x55b81a768ea3 ???
	???:0
0x7f61ea2b7b96 __libc_start_main
	???:0
0x55b81a760c99 ???
	???:0
0xffffffffffffffff ???
	???:0
Segmentation fault (core dumped)

**Comment by abraunegg** [comment]
This is a known issue and is fixed in my fork.

The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by surapuramakhil** [comment]
hey Buddy @abraunegg, go ahead and raise a pull request mentioning as the fix for this issue.
