### ISSUE TITLE
Trying to install on Ubuntu 16.04

### ISSUE THREAD

**Issue by GrouchyGaijin** [skilion/onedrive#48]
I am trying to install on Ubuntu 16.04 and when I run make I get this error:

`~/onedrive $ make
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
--- errorlevel 1
Makefile:18: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
`
I have curl installed.  What am I missing?

When I try to install libcurl3 I get this:

`sudo apt-get install libcurl3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcurl3 is already the newest version (7.47.0-1ubuntu2)`

Thank you

**Comment by telmer6** [comment]
You need libcurl3-dev.

**Comment by Enkouyami** [comment]
On Ubuntu 16.04 I have 'libcurl4-openssl-dev' (7.47.0-1ubuntu2) which provides 'libcurl3-dev' and I got the same error.

**Comment by GrouchyGaijin** [comment]
@Enkouyami Try searching for  libcurl3-dev jn Synaptic.  I am on 16.04 and once I installed  libcurl3-dev everything worked.  Ubuntu now uses systemctl so even running onedrive as a service works.

**Comment by Enkouyami** [comment]
@GrouchyGaijin searching for libcurl3-dev in synaptic shows zero results.

**Comment by GrouchyGaijin** [comment]
@Enkouyami Odd - it showed up when I searched for it.

**Comment by GrouchyGaijin** [comment]
@Enkouyami hmmmm I _thought__that is what I looked for._

**Comment by Enkouyami** [comment]
@GrouchyGaijin Have you tried doing this on a fresh install of Ubuntu 16.04?

**Comment by GrouchyGaijin** [comment]
@Enkouyami Yes I was able to install this on a fresh install of 16.04.  It is currently working flawlessly.

**Comment by Scimmia22** [comment]
@Enkouyami Y The error seems pretty clear. It's failing to find the sqlite3 dev files.

**Comment by GrouchyGaijin** [comment]
@Enkouyami Why so it does.  It says /usr/bin/ld: cannot find -lsqlite3
Say, have you installed the sqlite3-dev files?

**Comment by Enkouyami** [comment]
@GrouchyGaijin after installing libsqlite3-dev on Ubuntu it compiled successfully.

**Comment by skilion** [comment]
Added the commands to install the dependencies to the README in bfb2419
