### ISSUE TITLE
generalException: An error occurred in the data store.

### ISSUE THREAD

**Issue by 366Cobra** [skilion/onedrive#482]
Hi,
am having a little bit of an issue trying to sync.
i was syncing an existing repo and it was downloading files to my linux box.
i was not able to delete the files via the web interface, as M$ was saying that it timed out because of there being too many files (~2M small files)
then i started deleting files via the web site, as well as the downloaded ones on the linux box and now it fails doing anything.
the install was done about a week ago.

i have removed the token and redone the initial steps and all.
is there a way to increase the debug level, as the error message does not give me clue?
i can upload files via the web, so it is working.
an idea on where to look would be great.

#:~/.config/onedrive# onedrive -v
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /mnt/data/
Initializing the Synchronization Engine ...
Applying differences ...
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "generalException",
        "innerError": {
            "date": "2019-08-09T08:46:47",
            "request-id": "f8f897a6-8e6d-41e3-a59a-xxxxxx"
        },
        "message": "An error occurred in the data store."
    }
}
Applying differences ...
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "generalException",
        "innerError": {
            "date": "2019-08-09T08:47:04",
            "request-id": "76f2ca78-945a-479d-aa82-xxxxxxx"
        },
        "message": "An error occurred in the data store."
    }
}
Applying differences ...
sync.SyncException@src/sync.d(182): HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "generalException",
        "innerError": {
            "date": "2019-08-09T08:47:23",
            "request-id": "6e640e19-54ea-470f-9731-xxxxxxx"
        },
        "message": "An error occurred in the data store."
    }
}
----------------
0x560ac8cf191a ???
	???:0
0x560ac8ce7002 ???
	???:0
0x560ac8ce6a72 ???
	???:0
0x560ac8e3a8be ???
	???:0
0x560ac8e3aa2e ???
	???:0
0x560ac8e3adea ???
	???:0
0x560ac8e3aa2e ???
	???:0
0x560ac8e3abc0 ???
	???:0
0x560ac8ce5ea3 ???
	???:0
0x7ff781d44b96 __libc_start_main
	???:0
0x560ac8cddc99 ???
	???:0
0xffffffffffffffff ???
	???:0
`

**Comment by abraunegg** [comment]
@366Cobra
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by 366Cobra** [comment]
thanks, that worked.
strange that this old one was the most prominent and latest version i could find using search engines......

**Comment by abraunegg** [comment]
@366Cobra 
Glad you now have a working client. Suggest that if you found the old client via googling etc and the details on a website - advise that site to update their information :) I cant do too much about google / bing / duckduckgo search entries atm
