### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by spectrumcomputing** [skilion/onedrive#483]
Hi,

Can I make a small suggestion for the documentation:

First run

After installing the application you must run it at least once from the terminal to authorize it.

I know it sounds obvious, but nowhere does it say that the command to run is 'onedrive'

Thanks

**Comment by abraunegg** [comment]
@spectrumcomputing 
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
