### ISSUE TITLE
Crash on 400 (Bad Request) - illegal characters

### ISSUE THREAD

**Issue by elpamyelhsa** [skilion/onedrive#484]
Version 1.1.3 will crash instead of ignore

HTTP request returned status code 400 (Bad Request)
 "message": "The provided name cannot contain any illegal characters."

_Creating folder ./aaaaa_data/aaaaa/data/aaaaa/files_trashbin/files/Recovered Files – 11 Aug 2019 at 9:29:59 am.d1565493327
HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "innerError": {
            "date": "2019-08-27T02:34:10",
            "request-id": "29a17067-750a-4fbc-844d-b2556267d4d7"
        },
        "message": "The provided name cannot contain any illegal characters."
    }
}
Creating folder ./aaaaa_data/aaaaa/data/aaaaa/files_trashbin/files/Recovered Files – 11 Aug 2019 at 9:29:59 am.d1565493327
HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "innerError": {
            "date": "2019-08-27T02:34:13",
            "request-id": "b21ca5ee-eb93-4adf-90fd-39f2e7ee50ba"
        },
        "message": "The provided name cannot contain any illegal characters."
    }
}
Creating folder ./aaaaa_data/aaaaa/data/aaaaa/files_trashbin/files/Recovered Files – 11 Aug 2019 at 9:29:59 am.d1565493327
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "innerError": {
            "date": "2019-08-27T02:34:16",
            "request-id": "f7201c31-7859-4a0c-9b92-b633f1b419a7"
        },
        "message": "The provided name cannot contain any illegal characters."
    }
}
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x55ef631625e4]
src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x55ef63162786]
src/onedrive.d:185 std.json.JSONValue onedrive.OneDriveApi.createById(const(char)[], const(char)[], std.json.JSONValue) [0x55ef63161211]
src/sync.d:608 void sync.SyncEngine.uploadCreateDir(const(char)[]) [0x55ef6316df0a]
src/sync.d:584 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55ef6316dba0]
src/sync.d:589 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55ef6316dc17]
src/sync.d:589 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55ef6316dc17]
src/sync.d:589 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55ef6316dc17]
src/sync.d:589 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55ef6316dc17]
src/sync.d:589 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55ef6316dc17]
src/sync.d:589 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55ef6316dc17]
src/sync.d:589 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55ef6316dc17]
src/sync.d:445 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x55ef6316d05d]
src/main.d:194 void main.performSync(sync.SyncEngine) [0x55ef63159717]
src/main.d:121 _Dmain [0x55ef63159244]_

**Comment by abraunegg** [comment]
@elpamyelhsa 
This is a known bug and is fixed in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by elpamyelhsa** [comment]
> @elpamyelhsa
> This is a known bug and is fixed in my fork.
> 
> Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

Awesome, thanks

**Comment by abraunegg** [comment]
validation just to close this out:
```
The file has not changed
Uploading new items of .
Skipping item - invalid character sequences: ./Recovered Files – 11 Aug 2019 at 9:29:59 am.d1565493327
Applying changes of Path ID: 66D53BE8A5056ECA!101
```
