### ISSUE TITLE
make error 127

### ISSUE THREAD

**Issue by omaidb** [skilion/onedrive#485]
OS:Ubuntu16.04
allride@allride2705:~/onedrive$ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd：命令未找到
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127

**Comment by omaidb** [comment]
Find a solution
找到解决办法 https://dlang.org/download.html

**Comment by abraunegg** [comment]
@omaidb 
This is the same issue as #470 and many others - refer to https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions#make-command-during-installation-encounters-error-127

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
