### ISSUE TITLE
Onedrive for business is not supported

### ISSUE THREAD

**Issue by omaidb** [skilion/onedrive#486]
Onedrive for business is not supported

**Comment by Rondom** [comment]
Please look at https://github.com/abraunegg/onedrive/

This repo seems unmaintained.

**Comment by tim1mw** [comment]
I'm using this with OneDrive for Business, it does work, but you can't sync shared folders because the business version lacks the "Add to my onedrive function". Which sadly is what I needed this for.

**Comment by abraunegg** [comment]
@tim1mw 
As per @Rondom , the 'skilion' repo appears to have been abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change

Specifically for OneDrive for Business:
* It is supported

Specifically for OneDrive for Business Shared Folders:
* https://github.com/abraunegg/onedrive/issues/459
* https://github.com/abraunegg/onedrive/pull/473

I have flagged it as on-hold as there is not enough people testing it or providing feedback.
