### ISSUE TITLE
Add Proxy

### ISSUE THREAD

**Issue by TonySue2000** [skilion/onedrive#487]
For Some reason,The web version of Onedrive is banned in China(For domain name live.com is blocked),so unless use VPN,or the speed of syncing is just 20KB/s,too slow for most users.Also ,Proxy is more flexible than VPN,so I hope SOCK5 proxy feature could be added in next version

**Comment by TonySue2000** [comment]
PS:It can run a fast speed without VPN or proxy if using official apps (in iOS,Android and Windows)rather than website .

**Comment by abraunegg** [comment]
@TonySue2000 
Proxy support has already been added as per: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#access-onedrive-service-through-a-proxy

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. It contains defects that put you at risk of data loss and corruption. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
