### ISSUE TITLE
build on ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by sir-rave-alot** [skilion/onedrive#488]
Hi, I'm trying to build the software on a Raspberry Pi 3 with latest Raspbian Buster Lite as an operating system.
As I am unable to install DMD/DUB (because they are not available for ARM platform) I tried to proceed using gdc and set in the Makefile DC = gdc.

I got errors like below when executing make: 
/usr/bin/ld: /home/pi/onedrive/src/sqlite.d:157: undefined reference to `sqlite3_finalize'

libsqlite3-dev is installed.

It is maybe possible to crosscompile it using cmake (?)... I would prefer to compile on target in this particular usecase.

Does anyone has an idea how to get the job done?

Thank you very much,
sir-rave-alot

**Comment by abraunegg** [comment]
@sir-rave-alot 
It is best that you follow these directions for Raspberry Pi: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md

Also, the 'skilion' repo appears to have been abandoned and contains many other issues that have not been fixed. It contains functional defects that put you at risk of data loss and corruption. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by sir-rave-alot** [comment]
@abraunegg 
thank you very much for providing me the link.
I will close this issue as soon as I manged to compile.

Best regards,
sir-rave-alot

**Comment by abraunegg** [comment]
@sir-rave-alot 
Any update as to success ?

**Comment by joecool1029** [comment]
@abraunegg I'm gonna guess he raved too hard. This can be closed, I will explain:

GDC uses a dmd frontend that's too old (gcc bundles 2.076, you could use a newer with some voodoo, but I didn't have success on 2.081). abraunegg's page calls for 2.083.1 as a minimum DMD version. So what this means is you have to use LDC2 for compiling this on the pi (or any arm/arm64 target).

For reference: I just successfully compiled LDC2 1.19 (which uses DMD 2.089 as frontend) with the GDC from GCC 9.2.0. With this I was able to successfully run and build abraunegg's fork. It works fine.

**Comment by sir-rave-alot** [comment]
@abraunegg sorry, I missed your comment from Sep 5.
I was not able to try out by myself yet.
Thanks @abraunegg again  and @joecool1029 for contribution.
