### ISSUE TITLE
Gui Notifikation

### ISSUE THREAD

**Issue by marrog86** [skilion/onedrive#489]
I made a script for notifying changes made from onedrive on de X-Server. 

journalctl --user-unit onedrive -f | ./onedriveNot.sh working on Linux Mint. 

------------------------- start script ----------------------------
#! /bin/bash

#a='/gasg/string'

while [ 1 ]
do
    start=`date +%s`
#echo start + $start;
    read a;
    end=`date +%s`;
#echo end + $end;
    runtime=$((end-start));
#echo diffe+ $runtime;
    if [ $runtime -gt 5 ]
    then
        runtime=5000;
    else
       runtime=$((runtime * 1000));
    fi
    
    if [ $runtime  != 0 ] 
    then    
        #notify-send "OneDrive" "$filename" -u low -a OneDrive -i arrow-down-double -t $runtime;
        echo $a;
        filename=${a##*/};    
        echo $filename;
        if [[ $a = *Uploading* ]]; then
            notify-send "OneDrive" "UP: $filename hochgeladen" -u low -a OneDrive -i arrow-up-double -t $runtime;
        elif [[ $a = *Downloading* ]]; then
            notify-send "OneDrive" "$filename heruntergeladen" -u low -a OneDrive -i arrow-down-double -t $runtime;
        elif [[ $a = *Deleting* ]]; then
            notify-send "OneDrive" "$filename gelöscht" -u low -a OneDrive -i dialog-cancel -t $runtime;
        else
            notify-send "OneDrive" "$filename" -u low -a OneDrive -t $runtime;
        fi
    fi
done

 
----------------------------- end Scipt ----------------------
 

Can somebody help my getting startet this script automatically on startup for the right user? Starting in the Console works, automatic start not.

**Comment by abraunegg** [comment]
@marrog86 
Desktop GUI notifications is supported natively in my fork: https://github.com/abraunegg/onedrive/blob/master/README.md

Also, the 'skilion' repo appears to have been abandoned and contains many other issues that have not been fixed. It contains functional defects that put you at risk of data loss and corruption if you use this repo. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
