### ISSUE TITLE
Config doesn't update

### ISSUE THREAD

**Issue by StijnvanWijk98** [skilion/onedrive#490]
I have a problem that the config doesn't update to the given parameters in the config file. I have followed the steps given in the README for creating a custom config.

The screenshot shows the current config file and what the output is of the onedrive --display-config command.
![image](https://user-images.githubusercontent.com/43369474/64731126-da324080-d4e0-11e9-8f19-bef5658c2e53.png)

After saving the config file I run the onedrive  --resync command but this doesn't change the config file.
Add the moment my drive is not yet synced fully, because I want my drive to be on a HDD, not the SSD. Can this cause the problem?

**Comment by abraunegg** [comment]
@StijnvanWijk98 
Please close this issue as this has nothing to do with the 'skilion' code as you are running my fork.

Please close this case and open / create here: https://github.com/abraunegg/onedrive

**Comment by StijnvanWijk98** [comment]
I will post a more extensive bug report on your repo tomorrow.
