### ISSUE TITLE
moving directories into synched folder (using sync_list)

### ISSUE THREAD

**Issue by OneLineTwoBugs** [skilion/onedrive#491]
When moving a directory (using the onedrive web gui) that is currently not part of the sync (because it's parent folder is not listed in sync_list) into a folder that is part of the sync, that folder and all it's subfolders are created, but the files are not downloaded.

**Comment by abraunegg** [comment]
@OneLineTwoBugs

The 'skilion' repo appears to have been abandoned and contains many other issues that have not been fixed. It contains functional defects that put you at risk of data loss and corruption if you use this repo. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by OneLineTwoBugs** [comment]
thanks, I'll try the version you've linked and will report this bug over there if it still applies.
