### ISSUE TITLE
No network connnection

### ISSUE THREAD

**Issue by ladychili** [skilion/onedrive#492]
First run of `onedrive`, always got `No network connection`.
Uninstalled and reinstalled, still not working.

P.S. I'm using a proxy, do I need to configure the connection somewhere?

**Comment by abraunegg** [comment]
@ladychili 
Proxy support has already been added as per: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#access-onedrive-service-through-a-proxy

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. It contains defects that put you at risk of data loss and corruption. If you wish to use the latest code which contains numerous fixes and enhancements you need clone & build from here: https://github.com/abraunegg/onedrive
