### ISSUE TITLE
Sync to second drive in my laptop

### ISSUE THREAD

**Issue by Desperatus** [skilion/onedrive#493]
Hi I have 2 drives in my laptop. First is SSD 120GB and second is 1TB HDD.
I was not able to find out how to set it for the bigger one. Otherwise I dont have enough space for my files. Did I missed something or its not possible. 
Thank you very much for your time. 
running ubuntu 19.04
D.

**Comment by Lime-Parallelogram** [comment]
Hi, I had this exact issue this morning. If you copy the config file included in the repo to /home/**name**/.config/onedrive, you can then edit the sync directory to the disk mount point (e.g. /media/**name**/Disk/OneDrive)

**Comment by abraunegg** [comment]
@Desperatus , @Lime-Parallelogram 
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. It contains defects that put you at risk of data loss and corruption. If you wish to use the latest code which contains numerous fixes and enhancements you need clone & build from here: https://github.com/abraunegg/onedrive

**Comment by Desperatus** [comment]
Thank you a lot I was trying to change it with comand in the terminal but config.save was created and I saw no change in in the path. you helped me a lot thank you very much for your advice.
D.
