### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by tonimelisma** [skilion/onedrive#494]
I've been syncing several hundred GBs of material to OneDrive. The client randomly aborts with no clear error to console when running with `onedrive --upload-only --synchronize --no-remote-delete`. Rerunning the same console picks up where the previous left.

Running an strace produces:

`write(1, " done.", 6)                   = 6
write(1, "\n", 1)                       = 1
lstat("./Pictures/filename_censored.jpg", {st_mode=S_IFREG|0664, st_size=2478571, ...}) = 0                                                              
stat("./Pictures/filename_censored.jpg", {st_mode=S_IFREG|0664, st_size=2478571, ...}) = 0                                                               
poll([{fd=7, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=13, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=13, revents=POLLIN|POLLERR|POLLHUP|POLLRDNORM}])                                          
recvfrom(13, 0x7fffb641fd87, 1, MSG_PEEK, NULL, NULL) = -1 ECONNRESET (Connection reset by peer)                                                                       
write(13, "\25\3\3\0\32S8\356p\34\340u%\326Y,\326\326\214\220+\222\33s\315;\334Ek\212\265", 31) = -1 EPIPE (Broken pipe)                                               
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=9839, si_uid=1000} ---`

So apparently there isn't proper error handling and if the TCP/IP connection is reset for whatever reason, the whole client crashes..?

**Comment by abraunegg** [comment]
@tonimelisma 
You appear to be running my fork of the client and not the 'skilion' client.

Please close this case as this is invalid for this repo and open a new case here: https://github.com/abraunegg/onedrive 

Makesure that you follow these directions:
https://github.com/abraunegg/onedrive#reporting-issues
