### ISSUE TITLE
--synchronize fails with errors sating "response missing required 'id' element"

### ISSUE THREAD

**Issue by 18goldr** [skilion/onedrive#495]
I have confirmed I'm on the current version (2.3.11)

This is my error paste: https://privatebin.net/?093a98a1ec14e03a#AfPzMsdwGqRN2S4dnvbUro6dCvJvNqZsEASd5waokmfi

To trigger the error, I run `onedrive --synchronize`

I have tried uninstalling the application which did not help

**Comment by abraunegg** [comment]
@18goldr 
The 'skilion' github site is defunct. As your running my fork and not the 'skilion' version please close this issue and open a new issue here: https://github.com/abraunegg/onedrive

When opening a new issue please use the template for submitting issues and follow the directions as per https://github.com/abraunegg/onedrive/blob/master/README.md#reporting-issues

This **critically important** as it helps configure a system in an attempt to replicate the issue or identify quickly what or where the problem may be.

From the error log that you have uploaded however the actual issue stems from you having a `~` in your folder path. This is potentially being incorrectly expanded or interpreted by OneDrive.

Please open a new case ASAP for further handling and potential resolution.

**Comment by 18goldr** [comment]
Oops my mistake. The issue has been solved in the correct repo.
