### ISSUE TITLE
HTTP request status code 504 Gateway Timeout

### ISSUE THREAD

**Issue by alexwiki** [skilion/onedrive#496]
when trying to upload an h5 file it states the following. an h5 file is like a multiple layers image (size 500mb approx.)

**Comment by alexwiki** [comment]
it's ok now... managed to upload everything

**Comment by abraunegg** [comment]
@alexwiki 
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. It contains defects that put you at risk of data loss and corruption. If you wish to use the latest code which contains numerous fixes and enhancements you need clone & build from here: https://github.com/abraunegg/onedrive
