### ISSUE TITLE
Files lost after renaming folder

### ISSUE THREAD

**Issue by alexmir18** [skilion/onedrive#497]
I set up onedrive to selectively sync a folder named "ReFF". Then I modified the content of this folder on the linux machine without re-syncing it. Meanwhile, I changed the name of the folder to "ReAC" on a remote MacOS desktop, also synced to onedrive. However, after I launched onedrive on linux again, I discovered that the folder "ReFF" is completely gone and no folder "ReAC" appeared. Is there a way to restore the original, unsynced "ReFF" folder?

**Comment by abraunegg** [comment]
@alexmir18 
Sorry to hear about your data loss - but this is not surprising.

The 'skilion' repo appears to have been abandoned and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to watch the right repository for updates & releases, please watch this repo: https://github.com/abraunegg/onedrive 

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from that repo as well.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change

**Comment by alexmir18** [comment]
Thank you for the suggestion!
