### ISSUE TITLE
onedrive seg faults from missing OneDrive folder

### ISSUE THREAD

**Issue by Enkouyami** [skilion/onedrive#50]
onedrive, once launched, doesn't check if the OneDrive folder is there nor creates it if it's missing, and immediately segfaults. Installing onedrive also doesn't create the OneDrive folder if it isn't there.

**Comment by telmer6** [comment]
+1
Creating the folder manually solves the issue, but this should not be necessary.

**Comment by Scimmia22** [comment]
There's already a pull request for this.

**Comment by telmer6** [comment]
Oh hey, so there is. I didn't notice that this was included in that.

**Comment by skilion** [comment]
Fixed in 09af80d84313f780d3ea75d33481f7212b505d1e
