### ISSUE TITLE
the wrong onedrive is loading

### ISSUE THREAD

**Issue by sama2689** [skilion/onedrive#500]
I have 2 onedrives, for two different university accounts. But the program is automatically syncing the wrong onedrive into my folder. How can I reset the whole thing, remove the onedrive folder and any previous instructions it has to load onedrive from this account, and switch to a different onedrive account?
Thanks

**Comment by sama2689** [comment]
https://www.fosslinux.com/8835/how-to-sync-microsoft-onedrive-with-linux.htm I was following these instructions on ubuntu.

**Comment by abraunegg** [comment]
@sama2689 

> https://www.fosslinux.com/8835/how-to-sync-microsoft-onedrive-with-linux.htm I was following these instructions on ubuntu.

I have attempted to contact the author of that article to get them to update it, however have had zero response.

The 'skilion' repo appears to have been abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
