### ISSUE TITLE
Most important feature: missing

### ISSUE THREAD

**Issue by damib** [skilion/onedrive#501]
In my opinion one of the most important features, regarding cloud storage in general, is missing: client side encryption. Yes I know it can be difficult or impossible for some collaborative environments, nevertheless it would be a valuable option for many users.

**Comment by abraunegg** [comment]
@damib 

The 'skilion' repo appears to have been abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change

**Comment by Rathna-K** [comment]
@abraunegg I looked at you repo before google point me here, do you have any documentation for installing the new one under Rasbian command line without make install and using apt? Whatever i install default using apt install OneDrive seems to be limited in functionality. For example —display-confit is not available. 
This is what is available in -h
Usage: onedrive [OPTION]...

no option    Sync and exit.
-m --monitor Keep monitoring for local and remote changes.
    --resync Forget the last saved state, perform a full sync.
    --logout Logout the current user.
   --confdir Set the directory to use to store the configuration files.
-v --verbose Print more details, useful for debugging.
-h    --help This help information.


Thanks in advance, 
R

**Comment by abraunegg** [comment]
@Rathna-K 
The skilion repo is dead - do not use this codebase or post here.

> I looked at you repo before google point me here, do you have any documentation for installing the new one under Rasbian command line without make install and using apt?

No - when using 'apt' you get the skilion code. Your only choice is to build as per https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-raspbian-armhf

**Comment by Rathna-K** [comment]
Understood, it takes forever to build on there pi though. :-/
