### ISSUE TITLE
GUI contribution

### ISSUE THREAD

**Issue by martijnmichel** [skilion/onedrive#504]
I might be able to write a little GUI for this which I would do with nodejs/electron (and probably quasar). Any chance we can work together?

**Comment by abraunegg** [comment]
@martijnmichel 

The 'skilion' repo appears to have been abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
