### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xpitrus** [skilion/onedrive#506]
Hello, I get:

$ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/qxor.d(2): Deprecation: module std.digest.digest is deprecated - import std.digest instead of std.digest.digest. std.digest.digest will be removed in 2.101
src/qxor.d(88): Error: template instance WrapperDigest!QuickXor template WrapperDigest is not defined
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1

$ dmd --version
DMD64 D Compiler v2.092.0
Copyright (C) 1999-2020 by The D Language Foundation, All Rights Reserved written by Walter Bright

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

Thanks!

**Comment by abraunegg** [comment]
@xpitrus 

The 'skilion' repo appears to have been abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change

**Comment by xpitrus** [comment]
@abraunegg many thanks, I'm going to try...

**Comment by xpitrus** [comment]
@abraunegg it works, thanks a lot!
