### ISSUE TITLE
sync but do not download already uploaded data

### ISSUE THREAD

**Issue by John2397** [skilion/onedrive#509]
I have just installed onedrive in ubuntu. I have already several files in onedrive

Is it possible to activate onedrive but NOT download the data that already exist in the cloud? (Just sync the newly created files from that point)

**Comment by abraunegg** [comment]
@Georger2323 

The 'skilion' repo appears to have been abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change

Regarding your issue, refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md for assistance.

**Comment by Georger2323** [comment]
Thank you a lot!
