### ISSUE TITLE
Setup onedrive under Ubuntu 20.04.01: The provided value for the 'code' parameter is not valid.

### ISSUE THREAD

**Issue by Martin-Guenther** [skilion/onedrive#512]
Hi, I tried to setup onedrive under Ubuntu 20.04.01 LTS Focal Fossa. I've cloned the repository and checked out tag v1.1.3. Then did `sudo make install`and executed the command `onedrive`. After visiting the shown URL I copied and pasted the response URL and hit enter. Then I got this response: 
```
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "b2e445b7-b108-4671-beb3-2e5222c60848",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid.\r\nTrace ID: f31bdef3-43da-47d3-98f6-badbe8794000\r\nCorrelation ID: b2e445b7-b108-4671-beb3-2e5222c60848\r\nTimestamp: 2020-08-20 16:49:40Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=70000",
    "timestamp": "2020-08-20 16:49:40Z",
    "trace_id": "f31bdef3-43da-47d3-98f6-badbe8794000"
}
----------------
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x55d6be9ea420]
src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x55d6be9ea5c2]
src/onedrive.d:252 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x55d6be9e96f5]
src/onedrive.d:237 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x55d6be9e95da]
src/onedrive.d:84 bool onedrive.OneDriveApi.authorize() [0x55d6be9e8636]
src/onedrive.d:64 bool onedrive.OneDriveApi.init() [0x55d6be9e8467]
src/main.d:100 _Dmain [0x55d6be9e0da2]
``

**Comment by abraunegg** [comment]
@Martin-Guenther 

The 'skilion' repo was abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others. Do not use this repo. 

The latest and maintained code can be found here: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please 'star' and 'watch' the new repo location.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances

**Comment by yezhengli-Mr9** [comment]
For latest https://github.com/abraunegg/onedrive, I only use `sudo apt install onedrive` on `Ubuntu 20.04` and I still confront following although the browser can login to onedrive smoothly (that is, my password is correct for sure):
```java
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=**&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=**
onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "**",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid. Trace ID: ** Correlation ID: ** Timestamp: 2024-01-01 06:58:24Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=70000",
    "timestamp": "2024-01-01 06:58:24Z",
    "trace_id": "**"
}
----------------
??:? [0x55cf7c6d89d9]
??:? [0x55cf7c6d7cb5]
??:? [0x55cf7c6d8b65]
??:? [0x55cf7c6d6f58]
??:? [0x55cf7c6d68c5]
??:? [0x55cf7c6e47a8]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7fe94e01a9db]
??:? _d_run_main2 [0x7fe94e01a7ee]
??:? _d_run_main [0x7fe94e01a65d]
??:? __libc_start_main [0x7fe94dc03082]
??:? [0x55cf7c6af5ed]
```

**Comment by yezhengli-Mr9** [comment]
Seems better performance by following https://github.com/skilion/onedrive/issues/511

**Comment by abraunegg** [comment]
@yezhengli-Mr9 
> ```
> Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=**
>onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
>{
> ```

You get this error because you are using the Ubuntu Universe package. Do not use the Ubuntu Universe package.

To correctly install on Ubuntu you *must* follow this document: https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md
