### ISSUE TITLE
Timeout starting service after machine restart

### ISSUE THREAD

**Issue by ClimberBear** [skilion/onedrive#515]
Hi

I have installed onedrive and configured the service in standard user mode. But the service fails to start when I restart the machine (here is the systemctl status output).

`onedrive@xxxxxxxx.service - OneDrive Free Client for xxxxxxxx
     Loaded: loaded (/lib/systemd/system/onedrive@.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2020-09-26 07:33:24 CEST; 2h 40min ago
       Docs: https://github.com/abraunegg/onedrive
   Main PID: 1329 (onedrive)
      Tasks: 2 (limit: 14210)
     Memory: 161.6M
     CGroup: /system.slice/system-onedrive.slice/onedrive@jmalbarran.service
             └─1329 /usr/local/bin/onedrive --monitor --confdir=/home/xxxxxxxx/.config/onedrive

sep 26 07:33:24 irulan systemd[1]: Started OneDrive Free Client for xxxxxxxx.
sep 26 07:33:29 irulan onedrive[1329]: Configuration file successfully loaded
sep 26 07:33:40 irulan onedrive[1329]: Configuring Global Azure AD Endpoints
sep 26 07:33:40 irulan onedrive[1329]: Initializing the Synchronization Engine ...
sep 26 07:33:40 irulan onedrive[1329]: Initializing monitor ...
sep 26 07:33:40 irulan onedrive[1329]: OneDrive monitor interval (seconds): 300
sep 26 09:28:26 irulan onedrive[1329]: ERROR: OneDrive returned an error with the following message:
sep 26 09:28:26 irulan onedrive[1329]:   Error Message: Timeout was reached on handle 55CD0AF96220
sep 26 09:34:40 irulan onedrive[1329]: ERROR: OneDrive returned an error with the following message:
sep 26 09:34:40 irulan onedrive[1329]:   Error Message: Timeout was reached on handle 55CD0AF96220
`

After, if I start the service manually with systemctl restart, it starts fine. It seems it has some kind of dependency, but I'm not able to imagine which one.

NOTE: The machine is running connected to wired router permanently to internet

**Comment by abraunegg** [comment]
@ClimberBear 
Please close this issue and open on https://github.com/abraunegg/onedrive

This GitHub site has been abandoned.

**Comment by ClimberBear** [comment]
Closed in this repo and reopened in abraunegg
