### ISSUE TITLE
Excluded folders checking consumes a lot of time

### ISSUE THREAD

**Issue by ClimberBear** [skilion/onedrive#516]
I'm running onedrive synchornizations on Ubuntu 20.04.

Versión: onedrive v2.4.5-16-g19cf656

In my onedrive, I have an internal folder for backup purposes, with a lot of files. I have excluded from syncronizaction using both config and sync_list

My config:
```
jmalbarran@irulan:~/.config/onedrive$ cat config 
# upload_only = "false"
# check_nomount = "false"
check_nosync = "true"
# download_only = "false"
# disable_notifications = "false"
skip_symlinks = "true"
skip_dir = "Backup"
```

My sync_list
```
# Include / Exclude folders to sync
# Include
Dropbox
# Exclude
!Backup
```

But, when I run 
`onedrive --synchronize --verbose`

I takes a very, very long time because it checks the Backup folder (excluded intentionally) a lot of times. This is an extract from output:
```
Processing 303 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by skip_dir config: Backup
Processing 301 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by skip_dir config: Backup
Processing 322 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by skip_dir config: Backup
```

NOTE: I have several hundred thousands files in Backup

**Comment by advaithm** [comment]
@ClimberBear this repo has been more or less abandoned this is the current repo everyone uses https://github.com/abraunegg/onedrive

**Comment by abraunegg** [comment]
@ClimberBear 
Please close this issue and open on https://github.com/abraunegg/onedrive

This GitHub site has been abandoned.

**Comment by ClimberBear** [comment]
Closed and reopened in abraunegg
