### ISSUE TITLE
Collaborate with https://github.com/abraunegg/onedrive

### ISSUE THREAD

**Issue by abraunegg** [skilion/onedrive#518]
@skilion 
Hi - Why not collaborate with the client that I have developed / maintained / enhanced (https://github.com/abraunegg/onedrive) over the last 2 years whilst this client grew stale? Most distributions now include the updated client I maintain as the default & it does not make sense to have 2 clients to confuse users.

#### Major differences / Enhancements:
- Existing bugs with this client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances
- Supports single & multi-tenanted applications

Please reach out to me vial email - I have sent many over the last 2 years to reach out. Please get in touch.

**Comment by skilion** [comment]
Hi, great job by augmenting my client with all these features and congrats for making it into most Linux distributions. That's the beauty of open source, if one thinks he can do better, he can fork/clone the code and modify it as he likes. People will use the best one that fits their needs.

I consider this project an hobby. I made it to fulfill my use cases and nothing else. Therefore I don't want to spend time to implement and maintain features I don't use. Also I do not want to feel obliged to offer support when things stop working. 

Keep up the good work :)

**Comment by abraunegg** [comment]
@skilion 
No problem.

> Also I do not want to feel obliged to offer support when things stop working.

Suggest then that you disable the ability to raise new issues against your code & clearly update your readme / documentation to say this is a hobby, and issues will not be supported / fixed etc ... as - folk need to know where they can get support & where they can ask questions on how to use.

**Comment by K1ngjulien** [comment]
@skilion 

Could you put a link to @abraunegg 's fork on the top of the readme?
Your version is still the first result on google.

**Comment by abraunegg** [comment]
@skilion 
Additionally - I am more than happy to create a GitHub Organisation so that there can be one client where you can contribute & collaborate if you choose to (and who knows - maybe some of the remaining features can be added) - but I am no way saying all support and defect remediation should be on you. This way at least there is a single client where as the current contributors & support folk can continue to provide support to the community. This would fix the current fragmented view of which onedrive client should be used.

Sure it can be overwhelming when things break - and things need fixing - but this is where a collaborative effort works.

If this is something you want to consider - please get in touch.

If this is not something you want to consider, then please, in the interest of the wider community:
* Shut down your GitHub pages site (gh-pages) - as there is no point 'advertising' your client in this manner as it gives many folk the false sense of here is a client I can use & get support if I run into issues
* Update your readme to say this is a hobby, just for you, no support, advise folk to use a supported client and redirect them to https://github.com/abraunegg/onedrive
* Remove the ability for folk to open issues against your code (under Settings | Features - untick the Issues box)

By doing this, this will achieve the following:
* Reduce the noise of folk raising issues when they have a problem with your code - and there are still many including serious ones that cause serious data loss
* Keeps your code as a hobby, if people choose to use it, that is their choice

**Comment by pd5rm** [comment]
@skilion You've done some great work here, but as @abraunegg mentioned in previous comment, it would be great to have a "single" maintained source for OneDrive Linux client. His suggestions above all seem like a good way to transition the project if you're no longer actively maintaining it.

**Comment by ChadBailey** [comment]
A response of any kind would be appreciated.
