### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by jbb0906** [skilion/onedrive#519]
I just installed onedrive verions 1.1.4 from here on Ubuntu 18.04. All seems to go well until I run "sudomake install". The reply is install -D onedrive /usr/local/bin/onedrive and then install -D -m 644 onedrive.service /usr/lib/systemd/user/onedrive.service. 
When I type make DC=ldmd2, I get a response: make: Nothing to be done for 'all'.
If I then try to run onedrive, I get an error saying Segmentation fault (core dumped).

I am extremely rusty with my Linux skills, so I'm stuck. Can someone please help me get this running?
Thanks.

**Comment by abraunegg** [comment]
@jbb0906 
Please read https://github.com/skilion/onedrive/issues/518 very carefully and in full.

**Comment by skilion** [comment]
I need more info to understand why the app is crashing.

Could you follow the instructions at http://www.unknownroad.com/rtfm/gdbtut/gdbsegfault.html and provide a _backtrace_
