### ISSUE TITLE
Problem with managing the onedrive systemd service

### ISSUE THREAD

**Issue by Enkouyami** [skilion/onedrive#52]
Being able to safely stop, and or restart the service via a CLI command would be nice.

**Comment by Scimmia22** [comment]
If you're using the provided systemd service, you stop or restart it just like to do any other user service.

**Comment by Enkouyami** [comment]
I had started the onedrive service using `systemctl --user start onedrive`; I cheched that was running by having `journalctl --user-unit onedrive -f` opened beforehand and it stated that the OneDrive Free Client was started. I attempted to stop it `sudo service onedrive stop`, but it reported that 

>  Failed to stop onedrive.service: Unit onedrive.service not loaded.

I then tried `systemctl status onedrive.service` and it reported:

> ● onedrive.service
>    Loaded: not-found (Reason: No such file or directory)
>    Active: inactive (dead)

**Comment by Scimmia22** [comment]
If you used systemctl --user to start it, why in the world would you use sudo service to try to stop it?

**Comment by Enkouyami** [comment]
I assumed that `service` would work with systemctl service, when I tried `service onedrive stop` without sudo it stated that authentication was required to stop 'onedrive.service', so I put sudo in from it. Also I'm a noob at managing service, so I looked up systemctl command after I tried `service`.

**Comment by Scimmia22** [comment]
Forget that "service" exists. On modern installations, it's just a (marginal) wrapper around systemctl provided for backward compatibility and people who refuse to learn anything new.

**Comment by Enkouyami** [comment]
Is there a problem with how onedrive installed the service or is there a problem with my system?

**Comment by GrouchyGaijin** [comment]
I guess I don't understand the question.
Have you Googled systemctl?
What do the systemctl instructions say about stopping a service?
What happens when you follow those instructions?

**Comment by GrouchyGaijin** [comment]
Say, a **really** quick Google search gave me this:
[https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units](https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units).

**Comment by Enkouyami** [comment]
@GrouchyGaijin you can read above to see what I've already tried with systemctl

**Comment by GrouchyGaijin** [comment]
So you are trying to stop a service that isn't running?

**Comment by Enkouyami** [comment]
On #issuecomment-215206575 I've said I started the service with `systemctl --user start onedrive`. Before I ran that I used `systemctl --user enable onedrive`.

**Comment by Enkouyami** [comment]
I figured at the issue; I wasn't using the option `--user` with `systemctl status onedrive` and `systemctl stop onedrive`. Going to add this to the wiki.
