### ISSUE TITLE
Have an error when install

### ISSUE THREAD

**Issue by duccanh0022** [skilion/onedrive#520]
Hello,
When I install, have an error occurred. Please, help me!
OS: Centos 7
Error when run:
(dmd-2.094.1)[root@static onedrive]# make
echo v1.1.4 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
/bin/ld: /root/dlang/dmd-2.094.1/linux/bin64/../lib64/libphobos2.a(inflate.o): unrecognized relocation (0x2a) in section `.text'
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
make: *** [onedrive] Error 1

<img width="1440" alt="Screen Shot 2020-11-01 at 17 17 19" src="https://user-images.githubusercontent.com/4942484/97800233-3f597000-1c66-11eb-81a7-b000865874b3.png">

Thank you!

**Comment by abraunegg** [comment]
@duccanh0022 
Please read https://github.com/skilion/onedrive/issues/518 very carefully and in full.

**Comment by skilion** [comment]
You have incompatible versions of DMD and your GCC toolchain. You need either to update your GCC version or downgrade DMD.
