### ISSUE TITLE
onedrive.service does not exist.

### ISSUE THREAD

**Issue by NeiBaf79** [skilion/onedrive#524]
Hi,

I'm trying to sync my files automatically. I used the doc : 

systemctl --user enable onedrive

It returns this : 
Failed to enable unit: Unit file onedrive.service does not exist.

Thanks for your work.
Regards.

**Comment by topsbr** [comment]
Same problem here... 

I've altered the initial directory to /etc/onedrive, but I do not believe that this is the cause of the problem because the sync works fine... 

Any ideias? I've using Debian 10 (buster).

**Comment by abraunegg** [comment]
@NeiBaf79 , @topsbr 
The 'skilion' GitHub repository receives zero support. Refer to the following [comment](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726) in https://github.com/skilion/onedrive/issues/518

As you are using Debian 10, I suggest you utilise the Debian packages as per this [list](https://packages.debian.org/search?keywords=onedrive)

For a 'onedrive' client that receives support, please refer to: https://github.com/abraunegg/onedrive
