### ISSUE TITLE
Instant upload stopped working on Linux 20.04

### ISSUE THREAD

**Issue by Rmano** [skilion/onedrive#525]
It seems that, for whatever reason, the instant upload of changes to OneDrive stopped working. I suppose it is the result of some change in the main distro, because nothing changing on the `onedrive` side; but I hope somebody can help me to debug this thing. 

I have the following configuration:

```
[romano:~/software/configs/onedrive] % onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.8-0~202012020750~ubuntu20.04.1
Config path                            = /home/romano/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/romano/OneDrive
Config option 'skip_dir'               = Attic|Notebooks|Backups|Blocs de Notas
Config option 'skip_file'              = ~*|.~*|*.tmp|Romano @ Universidad*
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
#
# después de modificar hacer
# onedrive --resync
# 
# Test por si acaso
IEEC 2020
```

If I do a `--resync`, the documents are correctly uploaded. But if I change a document locally, it is not automatically uploaded (it worked perfectly one month ago --- I do not know what could have changed). If I stop and restart the service with

```
systemctl --user restart onedrive
```

I have the following in `journalctl --user-unit=onedrive -f`:

```
Dec 18 08:56:26 RRyS onedrive[8254]: Got termination signal, shutting down db connection
Dec 18 08:56:26 RRyS systemd[2386]: Stopping OneDrive Free Client...
Dec 18 08:56:27 RRyS systemd[2386]: onedrive.service: Main process exited, code=dumped, status=11/SEGV
Dec 18 08:56:27 RRyS systemd[2386]: onedrive.service: Failed with result 'core-dump'.
Dec 18 08:56:27 RRyS systemd[2386]: Stopped OneDrive Free Client.
Dec 18 09:18:20 RRyS systemd[2386]: Started OneDrive Free Client.
Dec 18 09:18:20 RRyS onedrive[11032]: Configuration file successfully loaded
Dec 18 09:18:20 RRyS onedrive[11032]: Configuring Global Azure AD Endpoints
Dec 18 09:18:22 RRyS onedrive[11032]: Initializing the Synchronization Engine ...
Dec 18 09:18:22 RRyS onedrive[11032]: Initializing monitor ...
Dec 18 09:18:22 RRyS onedrive[11032]: OneDrive monitor interval (seconds): 300
```

Notice that I have one file in 
```
[romano:~/OneDrive/DocumentosPorCompartir] % ls -l 
total 72
-rw-rw-r-- 1 romano romano 34323 Dec 18 09:29 'FB Training backup.xlsx'

[romano:~/OneDrive/DocumentosPorCompartir] % date
Fri 18 Dec 2020 09:39:39 CET
```

and it should have been uploaded... (the core-dump on shutdown was here before, too). Notice also that the timeout seems not to work... the file has changed since 

Just now I have received the message:
```
Dec 18 09:34:04 RRyS onedrive[11032]: ERROR: OneDrive returned an error with the following message:
Dec 18 09:34:04 RRyS onedrive[11032]:   Error Message: Timeout was reached on handle 5565564C6070
```

I tried a `--resync --synchronize`, it works and resynchronize things.

I have another instance on a remote computer (same configuration file, on the same OneDrive disk) that seems to work ok. 
How can I find what happens?

**Comment by abraunegg** [comment]
@Rmano 
> `v2.4.8-0~202012020750~ubuntu20.04.1`

This github repo site is not the correct repo to seek support for this version. Please close this case and open a case here: https://github.com/abraunegg/onedrive 

Do not seek support on the 'skilion' github repo for any client version > 2.x

Specific to your a actual issue. You are using the Ubuntu PPA package. This has *known* issues, specifically caused by Ubuntu itself. It also has a compiler issue - refer to https://bugs.launchpad.net/ubuntu/+source/ldc/+bug/1895969 for details.

Do not use the Ubuntu packages or Ubuntu PPA. Build from source for Ubuntu or Ubuntu derived platforms.

Re this error message: `Timeout was reached on handle`

You have intermittent Internet connection to the OneDrive service, thus the connection timed out.

**Comment by Rmano** [comment]
Ok. I will build  from source and substitute as soon as possible the binary. 
Thanks, and sorry for the wrong repo and the time spent. I will open an issue on the correct repo if the problem still occurs.
