### ISSUE TITLE
Can't query the library

### ISSUE THREAD

**Issue by lanshenghai** [skilion/onedrive#526]
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: TVD
std.json.JSONException@std/json.d(626): Key not found: displayName
----------------
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x7f228674eaf6]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x7f22867a6ef6]
??:? [0x558b98407462]
??:? [0x558b984266a2]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f22864c49db]
??:? _d_run_main2 [0x7f22864c47ee]
??:? _d_run_main [0x7f22864c465d]
??:? __libc_start_main [0x7f22860b00b2]
??:? [0x558b983d503d]
std.net.curl.CurlException@std/net/curl.d(4386): A libcurl function was given a bad argument on handle null
----------------
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x7f228674ed9c]
??:? void std.net.curl.HTTP.clearRequestHeaders() [0x7f22867b38ef]
??:? [0x558b98421242]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f22864c49db]
??:? _d_run_main2 [0x7f22864c47ee]
??:? _d_run_main [0x7f22864c465d]
??:? __libc_start_main [0x7f22860b00b2]
??:? [0x558b983d503d]

**Comment by abraunegg** [comment]
@lanshenghai 
This issue is invalid for the 'skilion' codebase. Please close and follow the correct support proceedure.
