### ISSUE TITLE
Multiples Account

### ISSUE THREAD

**Issue by adelmosilva** [skilion/onedrive#527]
good morning all.

Congratularions for the project. Amazing.

Is possible add multiples accounts on onedrive? in your project?

**Comment by AliasAlucard** [comment]
Yes, it seems like.
https://github.com/skilion/onedrive#using-multiple-accounts

**Comment by abraunegg** [comment]
@adelmosilva , @AliasAlucard 
The 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726)) and contains issues / defects that put you at risk of data loss. Despite a new version release in Oct 2020, these defects remain.

If you wish to use a client which is fully supported please refer to: https://github.com/abraunegg/onedrive 

#### Major differences / Enhancements:
- Existing bugs with this client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Support for Docker
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances
- Supports single & multi-tenanted applications
- Supports rate limiting of traffic

Specifically to answer your question, multiple accounts is possible, refer to https://github.com/abraunegg/onedrive/blob/master/docs/advanced-usage.md for detailed instructions.
