### ISSUE TITLE
Crash on status 429 throttledRequest

### ISSUE THREAD

**Issue by wn2000** [skilion/onedrive#529]
This is a continuation to #164 . 
As of today I'm still having this issue of "throttledRequest".

```
onedrive.OneDriveException@src/onedrive.d(529): HTTP request returned status code 429 ()
{
    "error": {
        "code": "activityLimitReached",
        "innerError": {
            "client-request-id": "...",
            "code": "throttledRequest",
            "date": "2021-03-03T03:29:01",
            "innerError": {
                "code": "quota"
            },
            "request-id": "..."
        },
        "message": "The request has been throttled"
    }
}
```
A restart synced another 3GB of data then failed with the same error.

**Comment by abraunegg** [comment]
@wn2000 
The 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726)) and contains issues / defects that put you at risk of data loss. Despite a new version release in Oct 2020, these defects remain. If you wish to use a client which is fully supported please refer to: https://github.com/abraunegg/onedrive 

Regarding your specific issue, 429 responses are correctly handled in the above supported codebase.

#### Major differences / Enhancements:
- Existing bugs with this client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Support for Docker
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances
- Supports single & multi-tenanted applications
- Supports rate limiting of traffic
