### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by m4chi** [skilion/onedrive#530]
Hi,
I am not very skilled with all this, but it seems that onedrive does not sync any more on my system (Ubuntu 18.4), onedrive version 2.4.0. When I try to synchonize, I get the following output:
```
onedrive --display-sync-status --monitor
Initializing the Synchronization Engine ...
Local directory is out of sync with OneDrive
Approximate data to transfer: 197 KB
Initializing monitor ...
OneDrive monitor interval (seconds): 45
The database is currently locked by another process - cannot sync

```

Trying a resync brings up an even more disturbing message:

```
onedrive --resync --monitor
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...

A database statement execution error occurred: disk I/O error

```
Any comments are highly appreciated!

**Comment by abraunegg** [comment]
@m4chi 
The 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726)) and contains issues / defects that put you at risk of data loss. Despite a new version release in Oct 2020, these defects remain. If you wish to use a client which is fully supported please refer to: https://github.com/abraunegg/onedrive 

Specific to your problem, the 'skilion' client version is v1.1.4 and below, as you are running v2.4.0, this would be my fork.

However, if you are running v2.4.0 you are running a version that is ~13 months old (and also non supported), and *most likely* you installed via `sudo apt install onedrive` which also is *not* supported in any way. Please refer to https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md on how to correctly install the client.

Additionally, this error: `A database statement execution error occurred: disk I/O error` means you have 2 copies of the program running - most likely 1 is via systemd, the other your manual execution.

Lastly, as this issue you have opened up is 100% irrelevant to the 'skilion' code, please close this issue.

**Comment by m4chi** [comment]
@abraunegg 
Oh no, I see I totally messed this one up. My sincere apologies for wasting you time, and my gratitude for your patient and very helpful answer. Now I know where to look and what to look for!!! THANK YOU!
