### ISSUE TITLE
I needed to install these prerequisites when installing in Debian/Mint

### ISSUE THREAD

**Issue by garydavenport73** [skilion/onedrive#531]
sudo apt install git
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libsqlite3-dev

**Comment by abraunegg** [comment]
@garydavenport73 
The 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726)) and contains issues / defects that put you at risk of data loss. Despite a new version release in Oct 2020, these defects remain. If you wish to use a client which is fully supported please refer to: https://github.com/abraunegg/onedrive 

#### Major differences / Enhancements:
- Existing bugs with this client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Support for Docker
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances
- Supports single & multi-tenanted applications
- Supports rate limiting of traffic

Specific to your issue, refer to: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#installing-from-distribution-packages-or-building-the-onedrive-client-for-linux-from-source and utilise the the available Debian packages.
