### ISSUE TITLE
The onedrive process disappears.

### ISSUE THREAD

**Issue by leon-zhang-guoao** [skilion/onedrive#532]
When I found that the file was not synchronized correctly, I found that the onedrive process disappeared, and then this was the log.
```
Remove your '/home/nifi/onedrive_conf/dx_edge//items.sqlite3' file and try to sync again

Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 01FGJLFLN6Y2GOVW7725BZO354PWSELRRZ
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 401 (Unauthorized)
  Error Reason:  Signing key is invalid.

Remove your '/home/nifi/onedrive_conf/dx_edge//items.sqlite3' file and try to sync again

Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 01FGJLFLN6Y2GOVW7725BZO354PWSELRRZ
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 401 (Unauthorized)
  Error Reason:  Signing key is invalid.

Remove your '/home/nifi/onedrive_conf/dx_edge//items.sqlite3' file and try to sync again

Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 01FGJLFLN6Y2GOVW7725BZO354PWSELRRZ
Retry sync count: 1: Key not found: refresh_token
Applying changes of Path ID: 01FGJLFLN6Y2GOVW7725BZO354PWSELRRZ
Retry sync count: 2: Key not found: refresh_token
Applying changes of Path ID: 01FGJLFLN6Y2GOVW7725BZO354PWSELRRZ
Giving up on sync after three attempts: Key not found: refresh_token
std.json.JSONException@std/json.d(626): Key not found: refresh_token
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x61c063]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x6c9175]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x67fa29]
??:? void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x639b09]
??:? void onedrive.OneDriveApi.newToken() [0x6399c4]
??:? void onedrive.OneDriveApi.checkAccessTokenExpired() [0x639c71]
??:? std.json.JSONValue onedrive.OneDriveApi.getPathDetailsById(const(char)[], const(char)[]) [0x638f2e]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[], bool) [0x64acce]
??:? void sync.SyncEngine.applyDifferences(bool) [0x64a210]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool, bool) [0x635f05]
??:? _Dmain [0x6355e1]
```

I don't know why.. Please help me find the reason.

onedrive version is v2.4.0

**Comment by abraunegg** [comment]
@leon-zhang-guoao 
> onedrive version is v2.4.0

A couple of *really* important details here:

1. This version is *not* the 'skilion' code base, you are running / using my fork of this client
2. You are running a version which is obsolete / unsupported - the latest release is v2.4.10. You need to upgrade your client.

The actual issue you have encountered is an Azure AD issue, where Microsoft broke Azure AD for a few hours. See https://github.com/abraunegg/onedrive/issues/1344#

Please can you close this case as it is 100% irrelevant to the 'skilion' code base.

**Comment by leon-zhang-guoao** [comment]
> 
> 
> @leon-zhang-guoao
> 
> > onedrive version is v2.4.0
> 
> A couple of _really_ important details here:
> 
>     1. This version is _not_ the 'skilion' code base, you are running / using my fork of this client
> 
>     2. You are running a version which is obsolete / unsupported - the latest release is v2.4.10. You need to upgrade your client.
> 
> 
> The actual issue you have encountered is an Azure AD issue, where Microsoft broke Azure AD for a few hours. See [abraunegg/onedrive#1344](https://github.com/abraunegg/onedrive/issues/1344)
> 
> Please can you close this case as it is 100% irrelevant to the 'skilion' code base.

Okay, thanks for clearing that up.
