### ISSUE TITLE
Links to Sharepoints documents are not sync'ed

### ISSUE THREAD

**Issue by wid** [skilion/onedrive#534]
I use Office365 with several Sharepoints for various projects.

The sharepoints have this kind of feature:
![Screenshot from 2021-07-09 13-59-14](https://user-images.githubusercontent.com/118246/125074688-e4fa9400-e0bd-11eb-8259-1bdd7b50b457.png)

It appears like that in my OneDrive:
![Screenshot from 2021-07-09 13-57-34](https://user-images.githubusercontent.com/118246/125074726-f348b000-e0bd-11eb-916d-41ff0d16d5b8.png)

On sync with the skilion/onedrive I get the Documents (regular folder) but not the Sharepoint Folder (the one with the little chain)

**Comment by abraunegg** [comment]
@wid 
SharePoint Links are not supported by the OneDrive API - refer to: https://github.com/OneDrive/onedrive-api-docs/issues/1427

Also the 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726)) and contains issues / defects that put you at risk of data loss. Despite a new version release in Oct 2020, these defects remain. If you wish to use a client which is fully supported please refer to: https://github.com/abraunegg/onedrive 

#### Major differences / Enhancements:
- Existing bugs with this client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Support for Docker
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances
- Supports single & multi-tenanted applications
- Supports rate limiting of traffic
