### ISSUE TITLE
Locally deleted folder is not removed from OneDrive

### ISSUE THREAD

**Issue by cdrewing** [skilion/onedrive#535]
I am doing a _onedrive --synchronize --upload-only_ to backup my local data to OneDrive. I created a folder named "test-to_delete" and deleted it on my machine, then I performed _onedrive --synchronize --upload-only_ again:

> cdrewing@cdrewing-desktop:~$ onedrive --synchronize --upload-only
> Configuration file successfully loaded
> Configuring Global Azure AD Endpoints
> Initializing the Synchronization Engine ...
> Syncing changes from local path only - NOT syncing data changes from OneDrive ...
> Uploading differences of ~/OneDrive
> Deleting item from OneDrive: Musik/test-to_delete

So everything should be fine. But it isn't. _Musik/test-to_delete_ is still there, even after +600 seconds.

Can anybody confirm?

**Comment by abraunegg** [comment]
@cdrewing 
A couple of important points:
* The 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726))
* You are not running the 'skilion' client, as evidenced by `onedrive --synchronize --upload-only`
  * As such please follow the correct support process as per https://github.com/abraunegg/onedrive#have-a-question or https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
  * Ensure you include important information such as `onedrive --version` if just asking a question
