### ISSUE TITLE
error during make command

### ISSUE THREAD

**Issue by idanciaes** [skilion/onedrive#536]
src/qxor.d(67): Error: need `this` for `lengthInBytes` of type `immutable(ulong)`

I have this error when running the make command on Debian-based Linux. Any thoughts?

**Comment by abraunegg** [comment]
@idanciaes 
This is the same issue as #533 

The 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726)) and contains issues / defects that put you at risk of data loss. Despite a new version release in Oct 2020, these defects remain. If you wish to use a client which is fully supported please refer to: https://github.com/abraunegg/onedrive

**Comment by skilion** [comment]
Fixed in 8001e1c025ddd6c2532b03305c59e407457d059b
