### ISSUE TITLE
SSL error when trying to download the first file

### ISSUE THREAD

**Issue by doubleparadiddle** [skilion/onedrive#537]
Hi,

something seem not to work when it comes to download the first file:

Processing 1A7840231B9A780C!2012 Reisedokumente
Processing 1A7840231B9A780C!92896 2021 xxxx
Processing 1A7840231B9A780C!92698 DSCF7107.dng
Downloading photo/2021/2021 TEMP/DSCF7107.dng...std.net.curl.CurlException@std/net/curl.d(4386): **SSL peer certificate or SSH remote key was not OK on handle 56071464C2D0**
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x5607133ebeea]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x5607133ebe5b]

Directories are being created, but downloading does not work. What might I have done wrong? I am not aware that I need to use SSH keys somewhere. Do I ?

Ubuntu 20.04
onedrive v1.1.4

Thank you !

Thomas

**Comment by abraunegg** [comment]
@doubleparadiddle 

The 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726)) and contains issues / defects that put you at risk of data loss. Despite a new version release in Oct 2020, these defects remain. If you wish to use a client which is fully supported please refer to: https://github.com/abraunegg/onedrive 

#### Major differences / Enhancements:
- Existing bugs with this client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Support for Docker
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances
- Supports single & multi-tenanted applications
- Supports rate limiting of traffic
