### ISSUE TITLE
SQLlite Database is locked

### ISSUE THREAD

**Issue by Dave-Vallance** [skilion/onedrive#54]
Hello,
 I ran into the following error whilst trying to sync for the first time. I have so far reproduced it three times with 100% repo rate. 

I am running OneNote as a local user simply by launching the onennote binary from the terminal. Note that I am able to download around 5 or so files before I see the error. 

Perhaps somewhere during the sync, a connection in the DB is being left open?

Below is a copy of my config file

> sync_dir = "~/OneDrive"
> skip_file = "._|~_"
> skip_dir = ".*"

And here is the error

```

Downloading: ./Family Memories/2016 - General/20160313_101913_Richtone(HDR).jpg
sqlite.SqliteException@src/sqlite.d(126): database is locked
----------------
??:? ref sqlite.Statement.Result sqlite.Statement.Result.__ctor(etc.c.sqlite3.sqlite3_stmt*) [0x598059]
??:? sqlite.Statement.Result sqlite.Statement.exec() [0x598405]
??:? void itemdb.ItemDatabase.insert(const(char)[], const(char)[], itemdb.ItemType, const(char)[], const(char)[], const(char)[], const(char)[], const(char)[]) [0x57ecf6]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x599c66]
??:? void sync.SyncEngine.applyDifferences() [0x598c51]
??:? void main.performSync(sync.SyncEngine) [0x58aa8b]
??:? _Dmain [0x58a1f7]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a521e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a5168]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a51da]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a5168]
??:? _d_run_main [0x5a50d9]
??:? main [0x58c6f5]
??:? __libc_start_main [0x55a9882f]
```

**Comment by Enkouyami** [comment]
You should keep the `client_id` and `client_secret` a secret.

**Comment by Enkouyami** [comment]
Hopefully this helps someone who understands how onedrive uses sqlite databases and D more than I:
http://www.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked
http://stackoverflow.com/a/17592858

**Comment by skilion** [comment]
Maybe you have enabled the onedrive service? Two instances of the app would trigger this kind of errors.

**Comment by saravanakumar-sr** [comment]
I am also facing similar error.
Following is the error log.
This happened after a restart. Only one instance of the application was running at the time. The exception happened after Downloading few files.
```
==================================================================================
sqlite.SqliteException@src/sqlite.d(147): database is locked
----------------
??:? ref sqlite.Statement.Result sqlite.Statement.Result.__ctor(etc.c.sqlite3.sqlite3_stmt*) [0x81f313f]
??:? sqlite.Statement.Result sqlite.Statement.exec() [0x81f348d]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x81f4cbd]
??:? void sync.SyncEngine.applyDifferences() [0x81f3b30]
??:? void main.performSync(sync.SyncEngine) [0x81e785d]
??:? _Dmain [0x81e7023]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x820532e]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x8205280]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x82052ee]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x8205280]
??:? _d_run_main [0x8205218]
??:? main [0x81e9c32]
??:? __libc_start_main [0xb73db275]
==================================================================================
```

**Comment by saravanakumar-sr** [comment]
I have also faced similar error.
Following is the error log.
This happened after a restart. As a Second instance of application was started.
```
sqlite.SqliteException@src/sqlite.d(147): database is locked
----------------
??:? ref sqlite.Statement.Result sqlite.Statement.Result.__ctor(etc.c.sqlite3.sqlite3_stmt*) [0x81f313f]
??:? sqlite.Statement.Result sqlite.Statement.exec() [0x81f348d]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x81f4cbd]
??:? void sync.SyncEngine.applyDifferences() [0x81f3b30]
??:? void main.performSync(sync.SyncEngine) [0x81e785d]
??:? _Dmain [0x81e7023]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x820532e]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x8205280]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x82052ee]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x8205280]
??:? _d_run_main [0x8205218]
??:? main [0x81e9c32]
??:? __libc_start_main [0xb73db275]
```

**Comment by dephekt** [comment]
Getting the same error occasionally if onedrive is doing things behind the scenes. Should probably add error handling for that exception to stop SegFaulting on database locks. If I knew D at all I'd give a hand, sorry...

**Comment by thomasfedb** [comment]
@Dave-Vallance can you replicate this with the latest commit?

**Comment by Dave-Vallance** [comment]
Hello All, 
  Sorry, I have not tracked this project for a while as I am not running a Linux desktop at the moment. When that changes, I will be sure to revist the repo.

**Comment by thomasfedb** [comment]
Given that @Dave-Vallance, would you mind closing this issue for now and reopening it if/when you can provide a reproduction on the latest revision?

**Comment by Dave-Vallance** [comment]
No problem at all.... Issue closed. Sorry for leaving it open so long.

**Comment by Farrukhw** [comment]
Although this is closed, but I seems to be solved it. I also faced it when I restarted my machine (Mint tina). Then I checked ~/.config/systemd/user/default.target.wants/onedrive.service and found following:

[Service]
ExecStart=/usr/local/bin/onedrive -m
Restart=no

So from System Monitor, I searched for onedrive process and it was already running. I killed it. Then in a terminal issued "onedrive -m -v" and volaa, it worked...

**Comment by abraunegg** [comment]
@Farrukhw 
This issue is actually caused by 2 issues:
* existing process running 
* incorrect permissions for the .config directory

This is all fixed in my fork.

Also - if you are using the 'skilion' codebase you are putting yourself at a significant risk of data loss and corruption due to the bugs / unfixed issues in this codebase - it appears that this repo has been totally abandoned by the original author.  If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by duocang** [comment]
It is not safe to resync everything, be careful.

OK. Run `onedrive --resync`.

I had the sql database locked after changing my sync_list.txt and run `onedrive`.

I simply `onedrive --resync`, it will download all files again.

**Comment by abraunegg** [comment]
@duocang 
The 'skilion' repo appears to have been abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change

**Comment by duocang** [comment]
@abraunegg 
Nice. Thanks.

**Comment by gentleqq** [comment]
> Maybe you have enabled the onedrive service? Two instances of the app would trigger this kind of errors.

I’m configured to "Restore a previous session. Because of this, onedrive has been launched many times. Thanks! :)

**Comment by abraunegg** [comment]
@gentleqq
Do not use the 'skilion' codebase. It is broken and puts you at data loss risk.

**Comment by TrinhDinhPhuc** [comment]
onedrive --resync

**Comment by abraunegg** [comment]
@TrinhDinhPhuc 
The 'skilion' repo was abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive

To be notified of new releases / bug fixes please also watch the above repo.

Major differences / Enhancements:
Existing bugs with 'skilion' client fixed
File upload / download validation to ensure data integrity
SharePoint / Office 365 Shared Libraries added
Desktop notifications via libnotify
Dry-run capability to test configuration changes
Prevent major OneDrive accidental data deletion after configuration change
