### ISSUE TITLE
Seems to no update/download ".git" folders

### ISSUE THREAD

**Issue by ignasiialemany** [skilion/onedrive#540]
It seems to not download/sync `.git` folders.

**Comment by abraunegg** [comment]
@ignasiialemany 

The 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726)) and contains issues / defects that put you at risk of data loss. Despite a new version release in Oct 2020, these defects remain. If you wish to use a client which is fully supported please refer to: https://github.com/abraunegg/onedrive

**Major differences / Enhancements between codebases:**
- Existing bugs with this client are fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries
- Support for OneDrive Business Shared Folders
- Support for Docker
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances
- Supports single & multi-tenanted applications
- Supports rate limiting of traffic
