### ISSUE TITLE
AADSTS900144: The request body must contain the following parameter: 'scope'.

### ISSUE THREAD

**Issue by nofrico** [skilion/onedrive#542]
Hi,
using "onedrive v2.4.13-0~202107190106~ubuntu20.04.1" sorry to say but on the first start of "onedrive" in the terminal I only get this response to the generated link:

Anmelden
Leider können wir Sie nicht anmelden.

AADSTS900144: The request body must contain the following parameter: 'scope'.

Details zur Problembehandlung
Wenn Sie sich an Ihren Administrator wenden, senden Sie ihm diese Informationen.
Informationen in die Zwischenablage kopieren
Request Id: 7b42c524-6cbe-4c5b-8397-862e64194700
Correlation Id: 52a0ffe0-6f3c-4ea0-bccc-7ea3296a1001
Timestamp: 2021-11-07T03:57:11Z
Message: AADSTS900144: The request body must contain the following parameter: 'scope'.
Anmeldefehler für die Überprüfung kennzeichnen: Kennzeichnung aktivieren
Wenn Sie Hilfe zu diesem Problem anfordern möchten, aktivieren Sie die Kennzeichnung, und versuchen Sie, den Fehler innerhalb von 20 Minuten zu reproduzieren. Gekennzeichnete Ereignisse generieren Diagnosedaten und werden an den Administrator gemeldet.**

**Comment by abraunegg** [comment]
@nofrico 
Your issue is 100% not related to the 'skilion' or 'abraunegg' onedrive client. It is web browser cookie related.

Please close this issue and open on the correct github repository: https://github.com/abraunegg/onedrive
