### ISSUE TITLE
How to login to sharepoint with command on linux machine

### ISSUE THREAD

**Issue by maiductuan** [skilion/onedrive#544]
How to login to sharepoint with command on linux machine, I can't remote into virtual machine, can only ssh
-----------------------------------------log-------------------------
Loading config ...
No config file found, using defaults
Initializing the OneDrive API ...
Authorize this app visiting:

Invalid uri
Could not initialize the OneDrive API
[https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient](https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient&fbclid=IwAR3PwBK7xRF7y4_V0DVG47wT8jPUAqXAnJEA5YBOmzE69_AbjTmxcqVi4gQ)

Enter the response uri: 
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by abraunegg** [comment]
@maiductuan 
> How to login to sharepoint with command on linux machine

The 'skilion' onedrive client does not support SharePoint. To sync SharePoint data you need to use https://github.com/abraunegg/onedrive

**Major Differences / Enhancements:**
* Existing bugs with the 'skilion' client fixed
* File upload / download validation to ensure data integrity
* Support Real-Time syncing of remote updates via webhooks
* Supports Shared Folder support for OneDrive Personal and OneDrive Business accounts
* Supports SharePoint / Office365 Shared Libraries
* Supports Desktop notifications via libnotify
* Supports Dry-run capability to test configuration changes
* Prevent major OneDrive accidental data deletion after configuration change
* Supports National cloud deployments (Microsoft Cloud for US Government, Microsoft Cloud Germany, Azure and Office 365 operated by 21Vianet in China)
* Supports single & multi-tenanted applications
* Supports rate limiting of traffic
* Support for Docker
* Support for Podman

> I can't remote into virtual machine, can only ssh

You do not need remote graphical display. The authentication URL you are given, you can use on any other system | browser to obtain the response URI - which you can then paste back into your SSH connection where the application is waiting for your response.

You can also present the authentication response as a key value pair, where the application waits for the file containing your response, then reads that authentication response from that file:
```
--auth-files ARG
      Perform authorization via two files passed in as ARG in the format `authUrl:responseUrl`
      The authorization URL is written to the `authUrl`, then onedrive waits for the file `responseUrl`
      to be present, and reads the response from that file.
```
