### ISSUE TITLE
service floods syslog with the failed initialization message

### ISSUE THREAD

**Issue by treestructure** [skilion/onedrive#546]
The service floods syslog and produces arround 300 GB of log data in the following format:

May 19 20:15:19 onedrive[92024]: ERROR: OneDrive returned an error with the following message:
May 19 20:15:19 onedrive[92024]:   Error Message: Failed initialization on handle 55D88CFA42D0
May 19 20:15:19 onedrive[92024]:   Calling Function: perform()

**Comment by abraunegg** [comment]
@treestructure 
That is not an error messsage associated with the 'skilion' codebase

Please follow the correct support process as detailed here: https://github.com/abraunegg/onedrive
