### ISSUE TITLE
Archive this repo and link to abraunegg/onedrive?

### ISSUE THREAD

**Issue by ChadBailey** [skilion/onedrive#547]
According to [this post](https://github.com/skilion/onedrive/issues/313#issuecomment-1244563607) this repo is no longer maintained, yet there are no clear indicators of that.

Should the repo be archived and the README be updated to link to the suggested successor at https://github.com/abraunegg/onedrive?

**Comment by abraunegg** [comment]
@ChadBailey 
Please read: https://github.com/skilion/onedrive/issues/518#issuecomment-717604726

**Comment by ChadBailey** [comment]
I did read it directly before posting this, but I guess I hadn't realized the author seems to just refuse to acknowledge requests like this. Perhaps if nothing else having this as an open issue will be some kind of cautionary indicator for newcomers to go elsewhere 🤷
