### ISSUE TITLE
Login have already authed but onedrive display the white page and enter shows Could not initialize the OneDrive API

### ISSUE THREAD

**Issue by gabrielpondc** [skilion/onedrive#549]
Enter the response uri: 
Invalid uri
Could not initialize the OneDrive API
<img width="1440" alt="截屏2023-08-10 11 05 10" src="https://github.com/skilion/onedrive/assets/26787778/ad8f11e3-d77d-45ea-99ff-2c9b7c74090e">

**Comment by abraunegg** [comment]
@gabrielpondc 
Please read the following to assist you further:
* https://github.com/skilion/onedrive/issues/547
* https://github.com/skilion/onedrive/issues/518#issuecomment-717604726
* https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md
* https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#authorize-the-application-with-your-onedrive-account
