### ISSUE TITLE
Have some version notation

### ISSUE THREAD

**Issue by lhorace** [skilion/onedrive#55]
Hello,

It would be nice to have a version notation or a revision number listed in README. It would be easier for me to know if I am running an outdated build.

Regards

**Comment by Scimmia22** [comment]
I'm really not sure what the use case is for this.

**Comment by lhorace** [comment]
On Mon, 02 May 2016 06:31:15 -0700
Doug Newgard <notifications@github.com> wrote:

> I'm really not sure what the use case is for this.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/skilion/onedrive/issues/55#issuecomment-216235005

I am not aware of any program that I use that don't have some version
notation. Especially if things do break, one can reference what
revision it broke in.

```
$ binary-foo --version
$ binary-foo 1.2 rev c8bdef
```

In my use case specially: am I on the latest revision, especially for
those who download via master.zip.

For now, a workaround I guess would be to use git, which I am
unfamiliar with.

Regards

-- 
Lutchy Horace
Owner/Operator/Administrator [http://www.lhprojects.net]
Owner/Operator/Administrator [http://www.bombshellz.net]
Owner/Operator/Administrator [http://www.animehouse.club]
About Me [http://about.me/lhprojects]
USA

**Comment by Scimmia22** [comment]
Oh, you're not talking about the readme. I get it now.

**Comment by davegregg** [comment]
Can we revisit this discussion? Proper versioning for this project would be a significant improvement for people to keep track of the app.

I could even look into heading this up if an existing contributor could point me in the right direction or jumpstart me. This would be my first D project, but I have some experience in the C family -- C++, Java, PHP, ECMAScript.

**Comment by skilion** [comment]
Added in 7fae9c1befb618d97e7366fd20de2c04e91b99b0
