### ISSUE TITLE
Crash: UTF-32 code point size too small

### ISSUE THREAD

**Issue by arampp** [skilion/onedrive#551]
I have installed version 2.5.0 of onedrive on a Manjaro Linux.

Since a few days,  onedrive crashes during sync as well as doing a `--resync` with the following error message:

```
std.uri.URIException@/usr/include/dlang/dmd/std/uri.d(246): UTF-32 code point size too small
----------------
??:? pure @safe immutable(dchar)[] std.uri.URI_Decode!(char).URI_Decode(scope const(char)[], uint) [0x55ffa41b66c3]
??:? pure @safe immutable(char)[] std.uri.decodeComponent!(char).decodeComponent(scope const(char)[]) [0x55ffa41b628a]
??:? bool syncEngine.SyncEngine.checkJSONAgainstClientSideFiltering(std.json.JSONValue) [0x55ffa41de499]
??:? void syncEngine.SyncEngine.processDeltaJSONItem(std.json.JSONValue, ulong, int, ulong, bool) [0x55ffa41cded2]
??:? void syncEngine.SyncEngine.fetchOneDriveDeltaAPIResponse(immutable(char)[], immutable(char)[], immutable(char)[]) [0x55ffa41cb943]
??:? void syncEngine.SyncEngine.syncOneDriveAccountToLocalDisk() [0x55ffa41c9644]
??:? void main.performStandardSyncProcess(immutable(char)[], monitor.Monitor) [0x55ffa40850bf]
??:? _Dmain [0x55ffa4083328]
```

Here the whole terminal output of `onedrive --resync`: https://pastebin.com/n9FJ4Gfn

**Comment by abraunegg** [comment]
@arampp 
> I have installed version 2.5.0 of onedrive on a Manjaro Linux.

100% the wrong place to seek support. Please seek support in the *right* location

**Comment by arampp** [comment]
@abraunegg I don't understand. I just wanted to report a crash of your software, the comment on Manjaro is just a little bit of context where I am running your software. The problem is not Manjaro but a crash of onedrive, hence I think this issue tracker should be the right location to report it.

Please let me know if I can provide you additional data (logs, configs, etc.) to track down this error.

**Comment by abraunegg** [comment]
@arampp 
Please read this: https://github.com/skilion/onedrive/tags

That should inform you that this GitHub repo is not providing v2.5.0

The correct GitHub Repo for you to seek support from is:  https://github.com/abraunegg/onedrive

**Comment by arampp** [comment]
@abraunegg a I see, thx for the hint.

I opened that one: https://github.com/abraunegg/onedrive/issues/2842
Closing this issue. Let me know if you need any more information
