### ISSUE TITLE
HTTP request returned status code 400 (Bad Request) when trying to authenticate

### ISSUE THREAD

**Issue by aman207** [skilion/onedrive#59]
Hi

After entering the response URI, I get the following error (similar to the error in issue #26 )

<pre>onedrive.OneDriveException@src/onedrive.d(337):
HTTP request returned status code 400 (Bad Request)
----------------
src/onedrive.d:25 void onedrive.OneDriveApi.checkHttpCode() [0x5c8dbb]
src/onedrive.d:269 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x5cb71a]
src/onedrive.d:200 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x5c8213]
src/onedrive.d:186 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x5c808b]
src/onedrive.d:64 void onedrive.OneDriveApi.authorize() [0x5c6fcd]
src/main.d:66 _Dmain [0x5c3a71]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5da5d6]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5da520]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5da592]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5da520]
??:? _d_run_main [0x5da491]
??:? main [0x5c53cf]
??:? __libc_start_main [0x3efd982f]
Segmentation fault (core dumped)</pre>

I'm not using second factor authentication, if that makes a difference. Any ideas?

**Comment by skilion** [comment]
Should be fixed in 0efc2fe
