### ISSUE TITLE
Service doesn't work, command does

### ISSUE THREAD

**Issue by ChrisLane** [skilion/onedrive#61]
When running OneDrive as a service and viewing journalctl, the system never seems to upload or download new files.

When running the "onedrive" or "onedrive -m" command everything works correctly.

This is the output in journalctl
`-- Reboot --
May 23 09:41:12 chrispc systemd[695]: Started OneDrive Free Client`

**Comment by Scimmia22** [comment]
You are running it as a user service, right?

**Comment by ChrisLane** [comment]
Yes.

**Comment by thomasfedb** [comment]
@ChrisLane does this issue occur with the latest codebase? If not, could you close this issue please.

**Comment by ChrisLane** [comment]
@thomasfedb sorry but I don't use OneDrive or this application anymore.

**Comment by thomasfedb** [comment]
Okay @ChrisLane, could you close this issue then?
