### ISSUE TITLE
Authentication link not working

### ISSUE THREAD

**Issue by InYourHead** [skilion/onedrive#63]
In version 1.0 and 1.1 when i'm opening generated link, i'm getting "Page not exists" informaton from my browser

**Comment by telmer6** [comment]
This is after you log in to OneDrive in the browser, yes? Copy and paste the address you were redirected to into the console @ `Enter the response uri:`

**Comment by seungjin** [comment]
I got redirected to 
https://login.live.com/oauth20_desktop.srf?error=invalid_request&error_description=The provided value for the input parameter 'redirect_uri' is not valid. The client application must be marked as 'mobile'%2c or the value must be an absolute URL which matches the registered redirect URI.&lc=1033

**Comment by seungjin** [comment]
Seems my problem is more like https://dev.onedrive.com/app-registration.htm issue.
I went my app in MS's Application Registration Portal and added a platform (web)
gave my own redirect URIs (my own but must be https).

And change the redirect_url value in request address from this onedrive program.

Now it is working just fine!

**Comment by thomasfedb** [comment]
The default `redirect_uri` works as long as you register your app for the mobile platform.
