### ISSUE TITLE
Multiple user

### ISSUE THREAD

**Issue by pjmichel** [skilion/onedrive#68]
Great program,but i don't find how to sync multiple onedrive account or launch multiple time the program but under user land . 
As root no problem for one onedrive account, segfault because of inotify ( privileges ) for classic users

**Comment by Scimmia22** [comment]
Why would inotify be a problem? Are you trying to sync a dir that the user doesn't have access to?

**Comment by pjmichel** [comment]
hi doug, yes right are fine, a user normaly can't invoke inotify without
privileges,

the more easy things, would be ta allow a conf file with multiple one
drive account to sync to multiple folder ( like fetchmail do for mail )

that allow one daemon, to do the task

**Comment by Scimmia22** [comment]
I have no idea what kind of system you're on, but on a standard GNU/Linux system, that's not true at all. There are some limits on how many instances and watches a user can create, but to say a normal user can't use inotify is simply wrong.

**Comment by pjmichel** [comment]
Thank' for your answer, but i if say something, it's true .
I'm sys admin, it's my work . The problem is real .
so i order to find a easy to do and real world solution, do you plan to
implement a fetchmail like system to allow the use or your program as
one dameon, that sync multiple onedrive account to multiple destination
folder ?

**Comment by Scimmia22** [comment]
Better if you just used a sane system.

**Comment by amaccuish** [comment]
@pjmichel what system only allows root to use inotify? And why not just allow users to use inotify, it's not a security problem. And if you want multiple instances then just copy the onedrive.service file with a new name and invoke the daemon under a different user.
@Scimmia22 On this it would be helpful if you could specify the config directory as an option, so you just set up multiple directories for each instance of the client? This would save having to create new users and .config/onedrive directories for each :)

**Comment by skilion** [comment]
Fixed in 738536736a827957ab24aa66f89dd0d83e17e912. The command line parameter `--confdir=[your dir]` can be used to have multiple concurrent accounts.

**Comment by amaccuish** [comment]
@skilion I've looked into this and the client uses this database storage but it ignores the config file I've put there and uses the one at /usr/local/etc/onedrive.conf. The directory I'm specifying is /etc/onedrive/backups, and within that is .config/onedrive/config, but it's ignored. Different users should be able to have individual skip_dirs etc, is there something I'm missing?
