### ISSUE TITLE
One Drive For Business Support?

### ISSUE THREAD

**Issue by edent** [skilion/onedrive#7]
I appreciate that the README says it's not possible - but I'd really like that functionality. Is there anything I can help with in order to make it work?

**Comment by skilion** [comment]
Sure !
I suggest to begin by reimplementing the `onedrive.d` module using the OneDrive for Business API. Then keep iterating until you get a working client just for the business version.
At that point, we could merge the two clients into one.

**Comment by ilmaisin** [comment]
Using the new API 2.0 that works for both consumer and business OneDrives would seem to be a better course action for me. I am however not a software developer.

**Comment by ilmaisin** [comment]
Started a bountysource entry for this.
https://www.bountysource.com/issues/27728932-one-drive-for-business-support

**Comment by skilion** [comment]
Refer to #143
