### ISSUE TITLE
Is onedrive usable with office 365 cloud version ?

### ISSUE THREAD

**Issue by matteoorefice-it** [skilion/onedrive#70]
Hi

I would know if "Is onedrive usable with office 365 cloud version" or it is only for microsoft live. Thanks

**Comment by echristopherson** [comment]
For me, it currently works partially with my Office 365 cloud OneDrive; I just synched 3.5GB of files, but then it crashed after receiving an HTML 410 (Gone) response code.

**Comment by timbaileyjones** [comment]
By "office 365 cloud version", do you mean like corporate office accounts?  Normally, I have ZERO interest in anything that Microsoft does, except that at my job, each employee supposedly has 1TB of OneDrive storage as part of our corporate Office.com domain.  I use Linux 100%, even at work, but I don't want to run Windows (even in a VM) just to get to this 1TB of storage.

I tried changing the URLs in onedrive.d from login.live.com to login.microsoftonline.com (based on comparing [the authentication sections of the API docs](https://dev.onedrive.com/auth/readme.htm)), but apparently there's more to it than that.

**Comment by skilion** [comment]
As of 1581c6989aff571b694473c3e24e4438db9675e1, OneDrive for Business is supported
