### ISSUE TITLE
Skip folder name or path

### ISSUE THREAD

**Issue by pecigonzalo** [skilion/onedrive#71]
First thanks a lot for the tool, its fantastic. 

Im having some issues with the skip_dir directive, im trying to skip `./Documents` (root of onedrive) but not all folders named Documents.

I tried using `./Documents` and `/Documents` on the skip_dir config but nothing seems to work (only using `Documents`, which skips it from every sub folder)

**Comment by skilion** [comment]
Since 9dd9442, you can use selective sync which is not affected by this problem
