### ISSUE TITLE
Shared directory are not synced

### ISSUE THREAD

**Issue by lepennec** [skilion/onedrive#8]
I have a few shared directory with some colleagues, they are not synced by your program except if I'm the one that created them. It seems that this is a (huge) limitation of the API ...

Otherwise this program works perfectly!

Yours,

   Erwan

**Comment by skilion** [comment]
I asked more details about shared folders on the official repository of the OneDrive Documentation.
https://github.com/OneDrive/onedrive-api-docs/issues/261
Hopefully I can fix this in the next month.

**Comment by simonjamain** [comment]
Hi, amazing work! any updates on this issue?

**Comment by lenisko** [comment]
Hello! any update on this one?

**Comment by merbanan** [comment]
I also need this, any updates on how to get it to work ?

**Comment by mschwarzer** [comment]
+1

**Comment by rubenqba** [comment]
+1

**Comment by Rmulet** [comment]
I would also be interested in this!

**Comment by rubenqba** [comment]
+1

**Comment by keithics** [comment]
+1

**Comment by beffardo** [comment]
+1

**Comment by nickdiego** [comment]
+1

**Comment by RaymiiOrg** [comment]
Is there any progress on this?

**Comment by randahlem** [comment]
This feature would be so important! +1 :)

**Comment by JochenLeppin** [comment]
Having support for shared folders (especially SharePoint document libraries) is a basic requirement for us. +1

**Comment by sander76** [comment]
Using a corporate account, is this a limitation on your personal folder or does it also not work on SharePoint folders?  Which a more or less shared by default? (Meaning multiple people have access)

**Comment by Jacob-Thorne** [comment]
+1

**Comment by skilion** [comment]
Experimental support for shared folders added with ab592f134e63edae8ee3bed64f7ec9351183e431
