### ISSUE TITLE
How to use different live user?

### ISSUE THREAD

**Issue by ictdeloods** [skilion/onedrive#80]
Hi,

I accidentally signed in with the wrong live account.. How do I go back to the first initialization for the app? I tried make uninstall, rm -rf the .conf files, deleting the onedrive folder and after reinstalling I still don't get the first initialization prompt.

**Comment by quirinux** [comment]
Dude, have you seen ~/.config/onedrive/ path?
All the config files are stored there, just take care with config file which holds api token, secret, etc...

**Comment by quirinux** [comment]
Just for curiosity, I think the bast way to have more than 1 instance running with different accounts is using docker and mapping the properly devices.  :-)

**Comment by ictdeloods** [comment]
Hey,

Thanks man, I totally over looked the other files in the directory, I should have looked there. I assumed there only was that one config file that the documentation stated should be copied to the home directory.

I don't really need multiple users (yet), but I do have multiple live accounts so may be in the future I will play a little with docker.

Anyway thanks again! ;-)

**Comment by skilion** [comment]
Starting from c91decaa16758f38942b59eef696741a817f9ce2 you can use `--logout` to perform a new login.
Also starting from 738536736a827957ab24aa66f89dd0d83e17e912 the command line parameter `--confdir=[your dir]` can be used to have multiple concurrent accounts.
