### ISSUE TITLE
HTTP request returned status code 410 (Gone)

### ISSUE THREAD

**Issue by ntrocado** [skilion/onedrive#83]
After the initial sync I'm getting this error and crash... Is re-installing the only solution?

**Comment by abraunegg** [comment]
I have seen this issue when syncing as well - as it was to do with the path attempting to be synced, and the wrong `refresh_token` being passed through

 I did fix this issue I was having up with my code additions in https://github.com/skilion/onedrive/pull/82

**Comment by skilion** [comment]
Solved in 7257c4c9bfb07efe4e333f562868e2ad80b739d3
