### ISSUE TITLE
how to run onedrive as a service if systemctl is not available? 

### ISSUE THREAD

**Issue by chiwhalee** [skilion/onedrive#84]
On e.g. Ubuntu 14.04, systemctl is not available, then I wonder is it still possible to run onedrive as a service? And how?

**Comment by quirinux** [comment]
hi there, just type:
onedrive -r &

to get it running on background

Another option is using supervisor, http://supervisord.org, but i've been using forever, https://github.com/foreverjs/forever, or you can easily find a bunch of processes monitoring tools as you like just googling, is up to you, most of these solution has a startup script to help you.

And for a more specific answer, which I don't use often, is creating a systemv init script, take a look at this article, https://mobiarch.wordpress.com/2014/05/16/creating-an-init-script-in-ubuntu-14-04/ it's a good start

**Comment by chiwhalee** [comment]
Thanks, forever does the job.  
However I still suggest the application support a deamon mode out-of-the-box, not depending on systemctl or other apps. Besides, it should support commands like "ondrive status", etc.

**Comment by quirinux** [comment]
totally agree

**Comment by clauderobi** [comment]
You can also create a configuration in Startup Applications preferences.

**Comment by skilion** [comment]
Ubuntu 14 uses Upstart as default system to manage services. If you want to run onedrive as a service with Upstart you should look up the [documentation](http://upstart.ubuntu.com/getting-started.html) and write a custom job. You can use #148 as starting point.
