### ISSUE TITLE
change one drive acount

### ISSUE THREAD

**Issue by dizs** [skilion/onedrive#85]
Hi!
How to change the oneDrive account?

**Comment by dizs** [comment]
I mean, i have registered one account at the first start and now i cannot change it to an other even after reainstalling....

**Comment by Scimmia22** [comment]
Delete ~/.config/onedrive/

**Comment by dizs** [comment]
So i have removed the directory, and I got the next:
rm -r ~/.config/onedrive
$ mkdir -p ~/.config/onedrive
$ cat ~/.config/onedrive/config
cat: /home/dizso/.config/onedrive/config: No such file or directory

**Comment by dizs** [comment]
Sorry, my mistake...
I did not copy the full command>
mkdir -p ~/.config/onedrive
cp /usr/local/etc/onedrive.conf ~/.config/onedrive/config

Now it request for the registry of the account, the problem, is with the answer of the MS site:

"We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later."

Any idea? I tried it several times...

**Comment by skilion** [comment]
Starting from c91decaa16758f38942b59eef696741a817f9ce2 you can use `--logout` to perform a new login.
