### ISSUE TITLE
make and makefile error

### ISSUE THREAD

**Issue by Seejman** [skilion/onedrive#87]
Hi,

Am trying to sync my OneDrive cloud storage with a linux machine running the Kali distro.
Have installed all the dependencies. As I try and make the file, I am presented with the following error:

root@kali:~/onedrive# make
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
--- errorlevel 1
Makefile:19: recipe for target 'onedrive' failed
make: **\* [onedrive] Error 

make install presents the following:
ake install
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
--- errorlevel 1
Makefile:19: recipe for target 'onedrive' failed
make: **\* [onedrive] Error 1

Is it possible to extent support to the Kali distro?

Thanks and regards,
Seejman.

**Comment by Scimmia22** [comment]
"/usr/bin/ld: cannot find -lcurl" means you haven't installed all deps. Make sure you have all the development files for the necessary libs.

**Comment by Seejman** [comment]
Thanks, Doug. Fixed the issue with Synaptic.
