### ISSUE TITLE
Crash when creating reqursive directories

### ISSUE THREAD

**Issue by krestenks** [skilion/onedrive#9]
Great tool, thank you :-)

My version was built from the latest github sources on the 30/11-2015.

I have seen the client crash three times while trying to create the local directory "./Pictures/Camera Roll"

It seems that multiple attempts to create the directory is made after whict the client exits or crashes.
From my log:
Creating directory: ./Pictures/Camera Roll
./Pictures/Camera Roll: No such file or directory
Creating directory: ./Pictures/Camera Roll
./Pictures/Camera Roll: No such file or directory
Creating directory: ./Pictures/Camera Roll

I think the problem is that the "Pictures" wasn't present and then the mkdir fails. I created the "Pictures" dir manually and the problem went away. 

So it seems that when creating a new dir it is neccessary to check that all parent dirs also exists and create them if they do not.

**Comment by skilion** [comment]
Onedrive should always traverse the folders from the root one by one when reporting differencies, so this should not happen. Maybe the Picures folder is somehow trated differently ?
Can you reproduce the error if you resync your OneDrive folder again (i.e. deleting everything and using `onedrive --resync`) ?

**Comment by krestenks** [comment]
I cannot reproduce the error if I do the resync. The amount of files to be synced initially was very large and I lost power to the machine during the initial sync so maybe this could have caused it? 

Anyway, everything has worked perfectly for a week and i have synced 100+ GB of photos and lots of recursive dirs without any problems so I guess you can close the issue. 

 Again, thank you for this great tool :-)

**Comment by skilion** [comment]
A sudden power interruption during the sync could well have caused your error. Generally when you have the suspect to be in a bad state always launch `onedrive --resync`
