### ISSUE TITLE
Cannot launch onedrive -m due to Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by GrouchyGaijin** [skilion/onedrive#96]
Until today I was happiy sharing files between a PC, a Mac and my Linux machine.  Today I noticed I did not get a file I had uploaded to OneDrive from my Mac.  When I checked the onedrive daemon was not running.
I attempted to start onedrive via the onedrive -m command in the terminal and received this error message:

`HTTP request returned status code 404 (Not Found)
HTTP request returned status code 404 (Not Found)
## sync.SyncException@src/sync.d(106): HTTP request returned status code 404 (Not Found)

??:? void sync.SyncEngine.applyDifferences() [0x598dcf]
??:? void main.performSync(sync.SyncEngine) [0x58aa8b]
??:? _Dmain [0x58a1f7]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a521e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a5168]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5a51da]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5a5168]
??:? _d_run_main [0x5a50d9]
??:? main [0x58c6f5]
??:? __libc_start_main [0xebaec82f]
## onedrive.OneDriveException@src/onedrive.d(337): HTTP request returned status code 404 (Not Found)

??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[]) [0x590692]
??:? void sync.SyncEngine.applyDifferences() [0x598ba8]
??:? void main.performSync(sync.SyncEngine) [0x58aa8b]
??:? _Dmain [0x58a1f7]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a521e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a5168]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5a51da]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5a5168]
??:? _d_run_main [0x5a50d9]
??:? main [0x58c6f5]
??:? __libc_start_main [0xebaec82f]

`
I am not sure what all of this means.  Would someone be so kind as to explain what I can do to fix the problem?

**Comment by quirinux** [comment]
Hi @GrouchyGaijin it sounds like the url api.onedrive.com could not be reached, which is a kind weird, can you ping it?
Have you got the most recent source code version?

**Comment by GrouchyGaijin** [comment]
@quirinux 
Sorry, I should have posted back that when I rebooted my computer the OneDrive daemon worked again.

**Comment by tesslocl** [comment]
I am having this issue at first run. Reboot doesn't work. How can I fix this?
