### ISSUE TITLE
I'm lost - Don't know how to install

### ISSUE THREAD

**Issue by Qwerty-Space** [skilion/onedrive#97]
Hi,

I'm fairly new to Linux, but so far I am running Debian and have done this:

`sudo apt-get install libcurl-dev
sudo apt-get install libsqlite3-dev
sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
wget -qO - http://dlang.org/d-keyring.gpg | sudo apt-key add -
sudo apt-get update && sudo apt-get install dmd-bin`

I'm just not sure what to do next, typing `make` just returns the error `make: *** No targets specified and no makefile found.  Stop.`

What do I do next?

**Comment by skilion** [comment]
Fixed in 91c5ac6f3127dcc74f560eef880fd1188fb5e6d5
