### ISSUE TITLE
403 (Forbidden) when sync'ing JPG 

### ISSUE THREAD

**Issue by onemorepereira** [skilion/onedrive#99]
After sync'ing for a while, `onedrive` will start throwing `HTTP request returned status code 403 (Forbidden)`; I came across issue #24 , #27 & #31 which seemed to have 'some' semblance to my problem; however, according to those three cases, the code fixes were merged long ago and I am working off of a build from master with commit hash `eb8d0fe` which is pretty much the HEAD revision as of today.

Same as with previously mentioned cases, I can access & download this artifact through the OneDrive web UI.
- My first move was to re-authorize the client: no change, still choked on that file.
- Then I tried letting the client rebuild the sync-database by renaming `items.db` to `items.db.bak`: still choking on the same file
- Final attempt was a bit more drastic and removed both token files --`refresh_token` / `access_token`-- reauthorized the client: still choking on the same file.

I am still to try to simply _skip_ sync'ing this file by adding it to my _config_ file. I thought I'd create this issue to start documenting this things and to see if anyone else is also running into anything similar.

There is no entry on the SQLite for that file/object, _but there are other objects under that directory structure that have already been sync'd and retrieved from OneDrive.

```
Downloading: ./Pictures/Phone Photos/2013/12/20131216_221032_0225.jpg
HTTP request returned status code 403 (Forbidden)
Downloading: ./Pictures/Phone Photos/2013/12/20131216_221032_0225.jpg
HTTP request returned status code 403 (Forbidden)
Downloading: ./Pictures/Phone Photos/2013/12/20131216_221032_0225.jpg
sync.SyncException@src/sync.d(106): HTTP request returned status code 403 (Forbidden)
----------------
??:? void sync.SyncEngine.applyDifferences() [0x59c964]
??:? void main.performSync(sync.SyncEngine) [0x58cb0b]
??:? _Dmain [0x58c34e]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a9bee]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a9b38]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a9baa]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a9b38]
??:? _d_run_main [0x5a9aa9]
??:? main [0x58fb55]
??:? __libc_start_main [0x99fa5730]
onedrive.OneDriveException@src/onedrive.d(348): HTTP request returned status code 403 (Forbidden)
----------------
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0x5948f7]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], immutable(char)[]) [0x59265c]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x59dc66]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue) [0x59d610]
??:? void sync.SyncEngine.applyDifferences() [0x59c790]
??:? void main.performSync(sync.SyncEngine) [0x58cb0b]
??:? _Dmain [0x58c34e]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a9bee]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a9b38]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5a9baa]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a9b38]
??:? _d_run_main [0x5a9aa9]
??:? main [0x58fb55]
??:? __libc_start_main [0x99fa5730]
```
### Environment: Fedora 24 x64

```
Linux 4.7.2-201.fc24.x86_64 #1 SMP 
Fri Aug 26 15:58:40 UTC 2016 
x86_64 x86_64 x86_64 GNU/Linux
```
## Update

> I am still to try to simply skip sync'ing this file by adding it to my config file. I thought I'd create this issue to start documenting this things and to see if anyone else is also running into anything similar.

I've excluded the file `20131216_221032_0225.jpg` through my config file, and resumed syncing. Seems to be chugging along now. I'll report back to see if I cam across another instance. In the meantime...what could be odd/off with this file?

**Comment by abraunegg** [comment]
I think this comes down to how the uploads are being stored on one drive. When I added in additional validation checks for valid responses (see my #82 branch) - on random image files it reported 403 / 410 / 412 , then on the re-try OneDrive gives a 415. I gracefully fail at that point, and the image file get's uploaded the next time around.

**Comment by thomasfedb** [comment]
@onemorepereira does this issue occur with the latest codebase? If not, could you close this issue please.

**Comment by abraunegg** [comment]
@onemorepereira 
Please can you provide an update or close this case

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
